scrapy/scrapy

- scrapy/utils/testsite.py
- tests/test_commands.py
I changed the parse command test to use a locally-hosted page instead of http://scrapinghub.com. It's the only test that relied on a external url, so, since scrapinghub.com is currently breaking our travis builds because of an issue already reported, after this PR tests should be safer.
> Don't rely on external urls for tests

- docs/topics/practices.rst
Fixes #398
Used dict comprehension for more pythonic code.
> Updates documentation on dynamic item classes.

- docs/topics/extensions.rst
items_scraped is the counter that needs to be reset each time we have scraped a specific number of items in the code instead of item_count (which represents the specific number of items needed before a message is logged). Updating the source code to reflect this.
Signed-off-by: Sudhanshu Shekhar <sudshekhar02@gmail.com>
> Reset items_scraped instead of item_count

- .gitignore
- conftest.py
Hi, I will work on porting Scrapy to Python3. I saw that all problematic tests for python3 are in py3-ignores.txt.
That's great since I know what should be fixed.
While checking few testcases I notice that sometimes fixing will require to modify or even wait for external project (e.g. Twisted).  It would be very helpful to be able to annotate those tests so I can leave them for later and focus on next problem. Example:
```
tests/test1.py
tests/test2.py
```
This PR skips lines which starts with '#' from py3-ignores.txt
> py3-ignores.txt supports comments

- scrapy/core/downloader/handlers/http11.py
There were a few changes on Twisted's Agent API in 15.0.0 release ([Release Notes](https://twistedmatrix.com/trac/browser/tags/releases/twisted-15.0.0/twisted/web/topfiles/NEWS#L9)) which can be seen here: [changeset/42679](https://twistedmatrix.com/trac/changeset/42679).
Agent's API now supports providing a custom EndpointFactory, which should return an Endpoint for a given URI (this object replaces explicit (scheme, host, port) parameters). With this new API we shouldn't need additional Agents as on [ScrapyAgent._get_agent](https://github.com/scrapy/scrapy/blob/09ba4ff68a7ecb00036d02ffda9ee48f48b69402/scrapy/core/downloader/handlers/http11.py#L166), but we can adopt it later.
This PR fixes bug  #1034.
> Twisted 15.0.0 Support

- docs/index.rst
Users need to scroll http://doc.scrapy.org/en/latest/ each time they want to look up what "response" provides: Request/Response docs are buried in the bottom. In this PR they are moved to "Basic Concepts" section. Other changes:
* duplicate "topics/commands" link is removed;
* settings docs are moved to "Basic Concepts";
* exceptions docs are moved to "Basic Concepts";
* "signals" and "exporters" docs are moved to "Extending Scrapy";
* "Reference" section is dropped because it is empty now.
> DOC reorder topics

- docs/topics/downloader-middleware.rst
- docs/topics/request-response.rst
- scrapy/contrib/downloadermiddleware/httpcache.py
- tests/test_downloadermiddleware_httpcache.py
Implementation of: #19 #689
I think doing it on the middleware is the best, because it handle it for all the policies.
> [MRG+1] httpcache dont_cache meta #19 #689

- docs/topics/link-extractors.rst
- scrapy/contrib/linkextractors/lxmlhtml.py
- scrapy/contrib/linkextractors/sgml.py
- scrapy/linkextractor.py
- tests/test_contrib_linkextractors.py
This adds support for using CSS selectors in link extractors.
> [MRG+1] CSS support in link extractors

- docs/topics/downloader-middleware.rst
- scrapy/contrib/httpcache.py
- scrapy/settings/default_settings.py
- tests/test_downloadermiddleware_httpcache.py
Added optional gzip compression to the http cache Filesystem backend, in order to reduce the amount of disk space consumed by the cached files.
Default behavior is the same as previous releases and compression is enabled setting HTTPCACHE_GZIP to True in the settings.
There were two things I was uncertain about regarding documentation
1. Whether or not to add a *versionadded* number or not. After all I don't control which version the feature would be added to if any, as it depends on when you'd merge.
2. If I should update the News section or not, since that document seems to be the purview of the maintainer (you).
Let me know what you think about the patch.
> [MRG+1] add gzip compression to filesystem http cache backend

- scrapy/xlib/pydispatch/dispatcher.py
- scrapy/xlib/pydispatch/errors.py
- scrapy/xlib/pydispatch/robust.py
- scrapy/xlib/pydispatch/robustapply.py
- scrapy/xlib/pydispatch/saferef.py
Tabs to spaces, proper number of blank lines between imports, classes and methods
> [MRG+1]Pydispatch pep8

- scrapy/utils/spider.py
arg_to_iter handles Items since https://github.com/scrapy/scrapy/commit/2bbd92742b796e1a565d4914a77889c884dd01ac.
I'm not sure about keeping `iter_spider_output` vs removing/deprecating it, but kept it for now because it seems its name can be more clear in some cases.
> remove unnecessary check from scrapy.utils.spider.iter_spider_output

- scrapy/contrib/spiders/feed.py
A similar fix was made for XMLFeedSpider in https://github.com/scrapy/scrapy/commit/95fde0a4987acaa75a6749223c8b7f9bd7081c23
> CSVFeedSpider cleanup: use iterate_spider_output

- docs/topics/loaders.rst
- scrapy/contrib/loader/processor.py
- tests/requirements.txt
- tests/test_contrib_loader.py
Created the first implementation of Json processor, any comments/edits are welcome.
I am currently using the jmespath (https://github.com/boto/jmespath) module to search for paths in the given list of values. I have added some sample test cases too.
The processor will return the list of values unchanged in case the jmespath module isn't installed. 
I wasn't sure how to show a warning message in such a case and thus, have used the python print statement for now.
> [MRG+1] Added JmesSelect

- README.rst
This PR changes the README badges to use [Shields.io](http://shields.io) SVGs, which are more friendly to retina displays and have a standardized appearance (see the comparison below). I also added alt text to the PyPI version and build status badges. I wasn't sure how important the wheel status badge is, but I replicated it anyways using Shields' custom badge functionality.
> Use Shields.io SVGs for README badges

- scrapy/core/downloader/contextfactory.py
implement the SNI fix as given in #981
> handle TLS SNI

- docs/topics/commands.rst
- docs/topics/settings.rst
- scrapy/utils/conf.py
Just a slight enhancement.
I like to keep my `~` cleaner by having config files in `~/.config/`.
> [+1 MRG]look in ~/.config/scrapy.cfg for user config

- docs/intro/overview.rst
- docs/topics/autothrottle.rst
Hey folks!
Here is my proposal for addressing issue #609 (and replaces PR #1023, while keeping some ideas).
Since the overview is "the pitch", I tried my best to make it short and to the point.
Summary of the changes:
* Added example spider showcasing both scraping and crawling (link following)
* Wrote an explanation of what the code does, without delving much into details
* Summarized table of features in the end, and reordered them based on my gut feeling
* Cut some text
* Cut some more
Note: the example spider is also showcasing the features from PRs #1081 and #1086, that I assume will be also in Scrapy 1.0 release.
So, what do you think, does this look good?
Thank you!
> [MRG+1] some improvements to overview page

- docs/topics/request-response.rst
- scrapy/http/response/__init__.py
- scrapy/http/response/text.py
- scrapy/utils/response.py
- tests/test_http_response.py
> Add Response.urljoin() helper

- docs/index.rst
- docs/topics/architecture.rst
- docs/topics/exporters.rst
- docs/topics/images.rst
- docs/topics/item-pipeline.rst
- docs/topics/items.rst
- docs/topics/practices.rst
- docs/topics/signals.rst
- docs/topics/spider-middleware.rst
- docs/topics/spiders.rst
- scrapy/commands/parse.py
- scrapy/contracts/default.py
- scrapy/contrib/exporter/__init__.py
- scrapy/contrib/pipeline/files.py
- scrapy/contrib/pipeline/images.py
- scrapy/core/scraper.py
- tests/spiders.py
- tests/test_commands.py
- tests/test_contracts.py
- tests/test_contrib_exporter.py
- tests/test_engine.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
A PR to fix GH-1064.
Docs are missing.
> Allow spiders to return dicts. 

- scrapy/templates/project/module/settings.py.tmpl
Hi, folks!
Here is a proposal for addressing issue #665.
I changed some wording, and added a few more settings that I felt were important or commonly missed.
So, what do you think? Does this look good?
Thank you,
Elias
> [MRG+1] Adding more settings to project template

- scrapy/core/downloader/webclient.py
- tests/test_webclient.py
Discussed in [#823](https://github.com/scrapy/scrapy/issues/823)
> [MRG+1] Add test for webclient with POST method and no body given

- scrapy/commands/deploy.py
- scrapy/contrib/downloadermiddleware/httpproxy.py
- scrapy/http/request/form.py
- scrapy/utils/url.py
- tests/mockserver.py
These are all the instances I found.
> [MRG+1] more python3 compatibility changes for urllib

- scrapy/crawler.py
- tests/test_crawler.py
This change was discussed in #873
This relocation has some advantages:
* Removes functionality from CrawlerRunner: After this change and moving the logging initialization to Crawler.\__init\__ as well (made in the python logging PR #1060) we can run crawlers without CrawlerRunner intervention.
* Settings given to each Crawler will be frozen after the extensions initialization. This allows the extensions to update the settings. That's something we want to implement for the Simplified Addons Idea for this GSoC (issue #591).
> [MRG+1] Move spider settings population from CrawlerRunner to Crawler.__init__

- docs/index.rst
- docs/topics/deployment.rst
Added a deploymention section to point readers towards scrapyd-deploy and shub documentation. Should we should also update the docs to reflect that ``scrapy deploy`` is now deprecated? I can update the PR if so.
> Added deployment section covering scrapyd-deploy and shub

- scrapy/selector/unified.py
- tests/test_selector.py
The exception quotes an xpath string
which may be unicode.
When an invalid xpath contains wide characters
eg ```sel.xpath(u'//x[@y="з"/]')``` (this is a Cyrilic "z", not a "3")
they end up verbatim in the exception message (which quotes the xpath).
Unicode strings should be encoded http://bugs.python.org/issue2517
Currently a UnicodeEncodeError (eg ``` UnicodeEncodeError('ascii', u'Invalid XPath: //x[@y="\u0437"/]', 23, 24, 'ordinal not in range(128)')```) hides the original exception.
~~In this PR I encode the exception message to utf8 and update the relevant test.~~
In this PR I encode the exception message to unicode_escape in python2 and update the relevant tests.
> [MRG+1] encode unicode selector exception

- docs/topics/shell.rst
The current documentation has references to the deprecated `sel` when interacting with the shell. I've removed them and replaced uses of `sel.xpath` with `response.xpath` instead.
> Remove references to the `sel` object in shell.rst

- tests/test_cmdline/settings.py
This small fix updates the deprecated settings API in `tests/test_cmdline/settings.py`, where `EXTENSIONS` was given as a list instead of a dictionary.
> Fix deprecated settings API in tests

- scrapy/crawler.py
- tests/test_crawler.py
> Verify SPIDER_MANAGER_CLASS interface while loading it in CrawlerRunner

- scrapy/contrib/downloadermiddleware/ajaxcrawl.py
- tests/py3-ignores.txt
Tests for _has_ajaxcrawlable_meta pass in Python 3.
> fix Python 3 syntax errors in ajaxcrawl.py

- scrapy/telnet.py
- tests/py3-ignores.txt
A simple fix to disable telnet in Python 3 until twisted.conch is ported to Python 3.
> disable scrapy.telnet if twisted.conch is not available

- docs/topics/practices.rst
- scrapy/crawler.py
- tests/test_crawler.py
I think that when you use Crawler, CrawlerRunner or CrawlerProcess Settings class is just an unnecessary import line. What about allowing dicts?
> allow Crawler, CrawlerRunner and CrawlerProcess to accept dicts instead of Setting objects

- scrapy/contrib/loader/__init__.py
- tests/test_contrib_loader.py
ItemLoader._values, as a defaultdict(list), has the side-effect of setting non existent values even when they are not assigned. As an outcome, writing a processor that reads from its loader state causes cryptic errors such as the one in the following snippet.
```python
class ImagesItem(Item):
images = Field()
page_url = Field()
class ImagesLoader(ItemLoader):
default_item_class = ImagesItem
page_url_out = TakeFirst()
def images_out(self, values):
return tuple(
urljoin(self.get_output_value('page_url'), url )
for url in values)
imgloader = ImagesLoader(response=response)
imgloader.add_xpath('images', '//img/@src')
imgloader.load_item()
```
The last line will raise a ```RuntimeError: dictionary changed size during iteration``` exception which confuses a lot. If I try ```load_item()``` once …
> [MRG +1]ItemLoader.load_item: iterate over copy of fields

- docs/index.rst
- docs/topics/images.rst
- docs/topics/media-pipeline.rst
- scrapy/contrib/pipeline/files.py
- scrapy/contrib/pipeline/images.py
Hey folks,
So, here is a proposal addressing #599 , documenting both media pipelines together.
Thank you!
> Documenting Files Pipeline together with Images Pipeline

- docs/Makefile
- docs/intro/tutorial.rst
So, here are some improvements for Scrapy tutorial, please let me know what you think.
Summary of the changes:
* adds an example and explanation about following links (fixes #608 )
* added note about CSS vs XPath, idea is to encourage people who know CSS to dig XPath too
* updated recommend XPath tutorials to the ones I felt were most helpful as a XPath beginner
* add a `watch` target to docs Makefile (note: depends on watchdog)
* a few other small changes
> Some improvements for Scrapy tutorial

- docs/topics/feed-exports.rst
- scrapy/contrib/feedexport.py
- scrapy/settings/default_settings.py
- scrapy/utils/testproc.py
- tests/mockserver.py
- tests/test_commands.py
- tests/test_contrib_feedexport.py
As discussed in https://github.com/scrapy/scrapy/pull/1081, this option is nice to have if we're yielding items as dicts. This also fixes #1050.
There were no tests for FeedExporter class, so I've added some.
> [MRG+1] FEED_EXPORT_FIELDS option

- scrapy/crawler.py
- tests/test_crawler.py
Fixed an issue with https://github.com/scrapy/scrapy/pull/1166 which @dangra spotted.
> [MRG +1]fixed backwards compatibility for SPIDER_MANAGER_CLASS option

- scrapy/crawler.py
- tests/test_crawler.py
Raising an exception when the interface of SpiderLoader doesn't comply with `scrapy.interfaces.ISpiderLoader` seems unnecessary restrictive since some of its methods aren't always needed, as noted in #1148 comments.
This PR changes that by issuing a warning instead of stopping the execution with an exception.
> Relax SpiderLoader interface check

- tox.ini
Also, Twisted version is bumped for Python 3.x tests, just in case.
service_identity is not added to Scrapy requirements because Scrapy
supports older Twisted / PyOpenSSL versions which don't use it.
> install service_identity package in tests to prevent warnings

- docs/conf.py
- docs/topics/api.rst
- docs/topics/practices.rst
- scrapy/crawler.py
As discussed in #1146, CrawlerProcess is generally a better fit than CrawlerRunner for scripting (see #1001 for example), so I made a couple of changes to reflect that in the documentation.
Changes made in this PR:
* Use Sphinx autodocs for CrawlerRunner so CrawlerProcess doesn't need to document again the inherited methods
* Document CrawlerProcess
* Add CrawlerProcess examples to "Run Scrapy from a script"
* Favor CrawlerProcess over CrawlerRunner in the "Run Scrapy from a script" section
> CrawlerProcess documentation

- conftest.py
This removes some deprecation warnings in tests.
To check it run
```
tox -e py27 -- scrapy tests --collect-only -s
```
> TST don't collect tests from deprecated modules.

- docs/topics/request-response.rst
In the example log is not imported
and not found in the global name space
For more recent branches than 0.24
requests documentation is adapted
with newer logging methods
so this patch is not needed
> Correct login request example

- scrapy/contrib/exporter/__init__.py
PythonItemExporter is not in `__all__`, so `from scrapy.contrib.exporter import PythonItemExporter` stopped working.
> fixed backwards compatibility for scrapy.contrib.exporter.PythonItemExporter

- docs/_ext/scrapydocs.py
- docs/topics/settings.rst
Hey, folks!
So, this PR intends to fix #518, changing the scrapydocs extension to do the following:
* collect all setting definitions in the documentation in the `env` variable
* adds a directive `settingslist` which will render a list of settings defined anywhere in the documentation except in the current document (I added this restriction to make it less verbose, the complete list is too big).
> Building settings list from docs

- .travis.yml
- tox.ini
`docs` build was removed from travis in 6c402d3cc4f because it took too long to run `sphinx-build linkcheck`. I separated two tox enviroments, one that only checks if the docs can be built without errors, and another one for checking links. I put the first one back in .travis.yml so we can avoid fixing manually occasional errors introduced in docs (#1127, #1219).
> Add docs build to travis

- scrapy/item.py
- tests/test_item.py
> item fields defined on fields class attribute fix

- pytest.ini
Running `tox -e py27 -- scrapy tests --collect-only -s -rw` shows that pytest issues 13 warnings from classes prefixed by `Test` that contain `__init__` methods. 
Since every TestCase we're using is a subclass from `unittest.TestCase` (`twisted.trial.unittest.TestCase` is a subclass of it too), we don't have to rely on discovering tests by their class name.
This PR overrides the default `python_class=Test` so the only test classes collected are the ones inherited from `unittest.TestCase`.
> Fix remaining warnings from pytest while collecting tests

- scrapy/log.py
This will avoid unexpected outputs when calling `log.start` explicitly.
Main change is setting `logstdout` to False, since it's broken in 0.24 and generates issues like #451.
> [MRG+1] Match default values in log.start

- scrapy/core/engine.py
- scrapy/core/scheduler.py
- scrapy/pipelines/files.py
- scrapy/utils/signal.py
- tests/test_utils_log.py
`logger.exception()` method didn't support keyword arguments until python 2.7.7.
I'm replacing all occurrences of this function (even those that don't have keyword arguments such as `extra`) so we discourage its usage.
> Replace logger.exception calls to logger.error for Python compatibility

- scrapy/core/engine.py
- scrapy/core/scraper.py
- scrapy/downloadermiddlewares/robotstxt.py
- scrapy/extensions/feedexport.py
- scrapy/log.py
- scrapy/pipelines/files.py
- scrapy/pipelines/media.py
- scrapy/utils/log.py
- scrapy/utils/signal.py
- tests/test_pipeline_media.py
- tests/test_utils_log.py
`logging.Filter`s can't override log messages in logger children, they can only do so in the logger they are attached. That's why FailureFormatter (the filter that takes care of extracting the exc_info from failures to print tracebacks) doesn't propagate to the descendants of the `scrapy` logger.
(TopLevelFormatter works because it doesn't override the "entire" log message, just the logger name, which is formatted at the end with string like `'%(name)s %(msg)'`. It's only the `msg` variable that is compute on the first logger and then propagated to the parents as it is).
I fixed it by converting each failure to exc_info before making the log call.
This pr fixes #1229 and fixes #1230.
> Replace FailureFormatter with direct failure to exc_info conversions in log calls

- scrapy/extensions/feedexport.py
``logfmt % "Stored"`` happens before logger formats the message, so `%` vs `%%` needs to be reversed.
This fixes the following error during shutdown:
```
2015-05-18 19:21:45+0500 [scrapy] ERROR: Error caught on signal handler: <bound method ?.close_spider of <scrapy.extensions.feedexport.FeedExporter object at 0x10c7ea390>>
File "/Users/kmike/envs/scraping/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/Users/kmike/envs/scraping/lib/python2.7/site-packages/Scrapy-0.25.1-py2.7.egg/scrapy/extensions/feedexport.py", line 187, in <lambda>
d.addErrback(lambda f: logger.error(logfmt % "Error storing", log_args,
TypeError: format requires a mapping
```
Export is …
> MRG+1 fixed FeedExporter shutdown log messages

- docs/topics/feed-exports.rst
- scrapy/extensions/feedexport.py
- tests/test_feedexport.py
> [MRG] fixed FEED_EXPORT_FIELDS handling (see #1223)

- scrapy/log.py
One of the projects had code that relied on `level_names` variable, I think while module is deprecated but not removed it makes sense to keep variable there for backwards compatibility.
Related to #1060
> [MRG+1] Keep level_names in scrapy.log for backwards compatibility

- docs/topics/selectors.rst
- scrapy/selector/unified.py
- tests/test_selector.py
It would be useful to have a default return value for `extract_first`, to avoid additional data type checks. 
For example, when expecting a string, this would raise an exception:
`something = selector.extract_first().lower()`
Allowing an optional `default` value can solve this elegantly:
`something = selector.extract_first(default='').lower()`
> [MRG+1] default return value for extract_first

- docs/news.rst
- scrapy/utils/defer.py
> Increase delay of defer calls

- scrapy/crawler.py
Blame suggested that it became useless somewhere in d40273561dad76a409f847b5f8ce1daafdb1dc7c
> [MRG+1] Remove CrawlerProcess.stopping as it isn't used any more

- scrapy/crawler.py
lambda is garbage collected and because receiver is added as weak reference by default - when `signals.engine_stopped` is fired `logging.root.removeHandler` is not executed. Fixed that by assigning lambda to a private argument and not by using `connect(..., weak=False)` because I believe this lambda function should be collected with crawler object and not stay in `dispatcher.connections` forever.
Tested in ScrapyRT where multiple crawls are running in the same process. Before the fix:
```
(Pdb) logging.root.handlers
[<scrapy.utils.log.LogCounterHandler object at 0x7f93caafca10>, <scrapy.utils.log.LogCounterHandler object at 0x7f93ca0ee690>, <scrapy.utils.log.LogCounterHandler object at 0x7f93c8048110>, <scrapy.utils.log.LogCounterHandler object at 0x7f93c806ba10>, <logging.FileHandler …
```
> [MRG +1] LogCounterHandler is never removed from root handlers list, fix that

- docs/topics/images.rst
Leads to this page in the /latest docs: http://doc.scrapy.org/en/latest/topics/PythonImagingLibrary
> Second PIL link no longer in use.

- scrapy/crawler.py
- tests/test_crawler.py
This is a follow-up to https://github.com/scrapy/scrapy/pull/1156.
Without this fix `CrawlerProcess({})` didn't work because `log_scrapy_info` wants `settings['BOT_NAME']`.
> fixed CrawlerProcess when settings are passed as dicts

- docs/faq.rst
incorrect use of "too" instead of "to"
> Tiny spelling correction

- scrapy/crawler.py
- tests/test_crawler.py
I noticed that a CloseSpider extension doesn't get activated when CLOSESPIDER_PAGECOUNT option is set in spider's `custom_settings`. Other extensions (AutoThrottle, LogStats, etc) are also not activated. 
This happens because extensions check settings in `from_crawler` methods, and `crawler.settings` doesn't contain spider settings yet because `spidercls.update_settings` call was moved to a later stage by #1128.
> Fix Spider.custom_settings

- docs/topics/practices.rst
- scrapy/crawler.py
- tests/test_crawler.py
I think that requiring users to write `CrawlerRunner({})` instead of `CrawlerRunner()` is unnecessary.
> make it easier to use default settings

- scrapy/commands/settings.py
[Cherry-picked from https://github.com/scrapy/scrapy/compare/scrapy:master...berkerpeksag:python3]
* intepreted -> interpreted
* "a list" instead of "an float" in --getlist help
* "an float"-> "a float"
Also, backslashes were redundant. So I removed them.
> Fix typos in scrapy/commands/setting.py

- docs/topics/signals.rst
For all other signals it is documented whether they support deferreds or not.
> spider_error doesn't support deferreds

- scrapy/crawler.py
* removed unnecessary lambda (@Curita - is it unnecessary? why did you add it?)  
* fixed #1279;
* DNS setup is extracted to `_get_dns_resolver` method.
> CrawlerProcess cleanup

- scrapy/linkextractors/sgml.py
- tests/test_selector.py
- tests/test_utils_deprecate.py
[Cherry-picked from https://github.com/scrapy/scrapy/compare/scrapy:master...berkerpeksag:python3]
> [MRG+1] Ignore ScrapyDeprecationWarning warnings properly.

- docs/topics/api.rst
- scrapy/signalmanager.py
This change is not 100% backwards compatible because of `*args` changes. Usage of `*args` is not documented, so we're not breaking the public interface. Users of `*args` will likely find their code broken if we change (https://github.com/scrapy/scrapy/issues/8) our signals implementation anyways.
Generated docs look almost the same as existing; the only difference is that order in which methods are documented is changed.
I got tired looking up what arguments SignalManager methods use - our signals docs is a maze, and source code is not helpful because of `*a, **kw`. Thus this PR :)
See also: #713
> DOC SignalManager docstrings. See GH-713.

- docs/topics/shell.rst
Otherwise, when the spider is executed from a standalone script as described in http://doc.scrapy.org/en/stable/topics/practices.html#run-scrapy-from-a-script it triggers an exception like this:
```
.../site-packages/scrapy/shell.py", line 131, in inspect_response
...
from scrapy.project import crawler
...
exceptions.ImportError: cannot import name crawler
```
> Use call to `inspect_reponse()` that works on 0.24.x

- scrapy/extensions/httpcache.py
By calling `CompactRange()` each time we save space and also recreate files to avoid them being removed in file storages with timestamp-based auto removal.
> Do leveldb compactation for httpcache on closing.

- docs/topics/logging.rst
- docs/topics/practices.rst
- scrapy/utils/log.py
After this change settings=None will mean "use default" instead of "don't create default root handler", making it more consistent with https://github.com/scrapy/scrapy/pull/1285. 
LOG_STDOUT handling is also changed: default is now applied even if `install_root_handler` is False.
Since this is a backwards-incompatible change in a new feature it may be better to decide if we want it before the 1.0 release. After a release we'll have to do a deprecation cycle.
> configure_logging: change the meaning of settings=None

- docs/intro/install.rst
In the installation guide, in the "Platform specific installation notes" section, Ubuntu and ArchLinux are currently subsections of Windows, which does not make sense imho.
This commit changes the section tree from:
* Platform specific installation notes
* Windows
- Archlinux
- Ubuntu
To:
* Platform specific installation notes
- Windows
- Ubuntu
- Archlinux
> DOC Bring Ubuntu and Archlinux outside of Windows subsection

- scrapy/core/downloader/handlers/ftp.py
- tests/test_downloader_handlers.py
Closes #1232 
For more details see debugging session in #1232 comments.
> [MRG +1] Unquote request path before passing to FTPClient, it already escape paths

- scrapy/core/downloader/__init__.py
* downloader.Slot becomes unaware of Scrapy settings;
* it got `__str__` and `__repr__` methods useful in manhole;
* unused import is dropped;
* absolute_imports future import is added (I like adding it everywhere).
> Small downloader slots cleanup

- scrapy/crawler.py
It provides an extension point where crawler instance is available; it should make it easier to write alternative CrawlerRunner.crawl implementations.
My use case: listen to signals from each crawler. As as @chekunkov pointed in https://github.com/scrapy/scrapy/pull/1256#issuecomment-105241481, currently it requires copy-pasting ~~large~~ chunks of code. After this change user can override CrawlerRunner._crawl method and connect signals there.
I don't know if we should make this method public & documented or not.
> extract CrawlerRunner._crawl method which always expects Crawler

- scrapy/downloadermiddlewares/httpproxy.py
- tests/test_downloadermiddleware_httpproxy.py
This fixes #1274, adding support to empty password authentication for proxies -- useful for API key based auth like:
`export http_proxy=http://<API key>:@paygo.crawlera.com:8010`
> [MRG+1] Support empty password for http_proxy config

- docs/topics/extensions.rst
- docs/topics/settings.rst
- scrapy/extensions/memusage.py
- scrapy/settings/default_settings.py
Hi folks, 
I noticed a scraper I was working with would spawn enough items to blow well past my assigned MEMUSAGE_LIMIT_MB before the MEMUSAGE extension ran its next scheduled check. 
I thought it might be useful to be able to alter the memory use check frequency, if you wanted, to have a better chance of a graceful shutdown.
Kept the default as it was, at 60.0 seconds.
> [MRG+1] Added MEMUSAGE_CHECK_INTERVAL_SECONDS to Memory usage extension options.

- scrapy/responsetypes.py
- tests/test_responsetypes.py
This content type is found in the ajax pagination on store.apple.com (eg http://store.apple.com/us/search/logitech).
```
ipdb> response.headers['Content-Type']
'application/x-json; encoding=UTF8;charset=UTF-8'
```
Currently gets returned as `Response`.
> interpreting application/x-json as TextResponse

- docs/Makefile
- docs/topics/settings.rst
Hey folks,
Here are some improvements to the settings docs, attempts to address the issues from #1300 .
Summary of the changes:
* added example of accessing settings from a spider
* adapted example of extension accessing settings to a more realistic-like scenario
* rewrote some explanations to make easier to understand in the simpler cases
* added watch in the help for docs Makefile
> [MRG+1] Improvements for docs on how to access settings

- docs/intro/tutorial.rst
Reference to passing additional data in callbacks was broken (had reference suffix instead of interpreted role prefix).
> Fix reference in tutorial.

- CONTRIBUTING.md
In response to more support questions on the issue tracker, add some text to `CONTRIBUTING` which GitHub links when creating new issues.
Unless you believe that would be too discouraging and being more lenient with these.
> Put a blurb about support channels in CONTRIBUTING

- docs/conf.py
This is more a question than a 'definitive' pull request. Without this line, Sphinx' `autodoc` extension uses my system-wide Scrapy installation (in my case, from `/usr/lib/python2.7/site-packages/scrapy`) instead of the one in my git working directory.
While I guess this is not a problem for the server which builds the docs from a current repository copy and probably doesn't have a system-wide Scrapy installation, it does build docs from the (possibly outdated) system-wide doctrings for me (w/ `make html`), and throws errors when I add new functions/classes and document them with `autodoc`. I don't quite see how it could be, but is this specific to my setup?
> Make Sphinx autodoc use local, not system-wide Scrapy

- scrapy/http/request/form.py
- tests/test_http_request.py
Add capability to search HTML Form using formid when using `FormRequest.from_response()`
refrenced issue :https://github.com/scrapy/scrapy/issues/1136
> Update form.py to improve existing capability

- scrapy/__init__.py
- scrapy/core/downloader/handlers/s3.py
- scrapy/pipelines/files.py
- tests/test_downloader_handlers.py
companion to #1357
removes s3/boto dependency on `optional_features`
> [MRG+1] lazy-load s3 boto

- docs/topics/downloader-middleware.rst
- scrapy/downloadermiddlewares/redirect.py
- tests/test_downloadermiddleware_redirect.py
Inspired by #1334 
I have decided not to include the `HTTPERROR_ALLOWED_CODES` setting, as, unlike the `handle_httpstatus_list` Spider attribute, the name of that setting implies that it is directly tied to the HttpErrorMiddleware.
> [MRG+1] Make RedirectMiddleware respect Spider.handle_httpstatus_list

- tests/__init__.py
because urllib doesn't handle `$no_proxy` env correctly
and the unittest webserver is always local.
> [MRG+1] Unset environment proxies for tests

- scrapy/core/downloader/handlers/__init__.py
- tests/test_downloader_handlers.py
After this change it is possible to run `scrapy crawl` without having to port all handlers enabled by default.
For example for https://github.com/scrapinghub/testspiders the "loremipsum" spider, that only use `file://` urls, works under python 3. Errors in log are on purpose and part of spider code.
```
$ scrapy crawl loremipsum
2015-08-10 18:20:58 [scrapy] INFO: Scrapy 1.1.0dev1 started (bot: testspiders)
2015-08-10 18:20:58 [scrapy] INFO: Optional features available: http11, ssl
2015-08-10 18:20:58 [scrapy] INFO: Overridden settings: {'COOKIES_ENABLED': False, 'CLOSESPIDER_PAGECOUNT': 1000, 'NEWSPIDER_MODULE': 'testspiders.spiders', 'CLOSESPIDER_TIMEOUT': 3600, 'RETRY_ENABLED': False, 'SPIDER_MODULES': ['testspiders.spiders'], 'BOT_NAME': 'testspiders'}
2015-08-10 18:20:58 [scrapy] …
```
> lazy-load downloadhandlers (continuation of #1357)

- requirements-py3.txt
- requirements.txt
- setup.py
- tox.ini
It looks like missing service_identity package is a common issue; #1418 is not the first time someone complains.
> add service_identity to scrapy install_requires. Fix GH-1418 and GH-850.

- scrapy/dupefilters.py
- tests/test_dupefilters.py
I was checking https://github.com/scrapy/scrapy/pull/1384 and found out that RFPDupeFilter with non-empty path is not tested. A test shows that persistence never worked: file is opened in 'a+' mode, this means a file pointer is at the end, so we get empty result when trying to read from it.
> Dupefilter persistence

- scrapy/commands/version.py
Motivated by #1429
```
$ scrapy version -v
Scrapy  : 1.1.0dev1
lxml    : 3.4.4.0
libxml2 : 2.9.2
Twisted : 15.3.0
Python  : 3.4.3 (default, Mar 25 2015, 17:13:50) - [GCC 4.9.2 20150304 (prerelease)]
OpenSSL : 0.15.1
Platform: Linux-4.1.4-1-ARCH-x86_64-with-arch
```
> Add openssl version to version command

- scrapy/linkextractors/htmlparser.py
- scrapy/linkextractors/lxmlhtml.py
- scrapy/linkextractors/regex.py
- scrapy/linkextractors/sgml.py
- tests/test_linkextractors.py
Because issue #907  is still around, this is a rebase of former PR #927 
But I re-wrote the RegexLE modification from that PR.
> [MRG+1] [LinkExtractors] Ignore bogus links (#907)

- docs/topics/downloader-middleware.rst
- scrapy/downloadermiddlewares/redirect.py
- tests/test_downloadermiddleware_redirect.py
Fixup for #1364
Makes `RedirectMiddleware` honour the `handle_httpstatus_list` and `handle_httpstatus_all` keys from the `Request.meta` dictionary.
> [MRG +1] Fix RedirectMiddleware not honouring handle_httpstatus meta keys

- scrapy/utils/template.py
- tests/test_utils_template.py
I fixed a potential bug (untriggered so far because of the `.py` extension of the template files)
but while writing the test, it ended taking up most of the changes done in this PR.
Please comment whether I should just push the bugfix.
The potential bug is that `.rstrip()` in `utils.template.render_templatefile()`
is used like it is expected to strip a string, not a character class
(think of using `re.sub(r'[\.tmpl]*$, '', path)` instead of `re.sub(r'\.tmpl$', '', path)`.
On filepaths that always end with '.py.tmpl', the problem goes unnoticed.
Also, shouldn't there be some expectation or even an assertion
that the template files have the '.tmpl' extension?
> fix utils.template.render_templatefile() bug +test

- docs/topics/commands.rst
- docs/topics/shell.rst
- scrapy/shell.py
- scrapy/utils/console.py
- tests/requirements.txt
- tests/test_utils_console.py
Related to #1100, this shows the banner correctly on standard python, ipython and bpython.
> [MRG +1] bpython support

- scrapy/linkextractors/lxmlhtml.py
- scrapy/linkextractors/sgml.py
- scrapy/utils/misc.py
- tests/test_linkextractors.py
`rel` attribute for `a` can have multiple values: http://www.w3.org/TR/html401/struct/links.html#adef-rel
fixes #1201
> [MRG+1] Support link rel attribute with multiple values

- docs/conf.py
I am not precisely sure why build without this patch works ok on my laptop but fails in a clean debian sid env, but I thought this wouldn't hurt ;-)
> [MRG+1] DOC(ENH): specify path to rtd theme explicitly

- scrapy/link.py
- scrapy/linkextractors/__init__.py
- scrapy/linkextractors/lxmlhtml.py
- scrapy/spidermiddlewares/depth.py
- scrapy/spidermiddlewares/offsite.py
- scrapy/spiders/crawl.py
- scrapy/spiders/init.py
- scrapy/spiders/sitemap.py
- scrapy/utils/gz.py
- tests/py3-ignores.txt
- tests/test_link.py
- tests/test_linkextractors.py
- tests/test_linkextractors_deprecated.py
- tests/test_spider.py
- tests/test_spidermiddleware_referer.py
- tests/test_utils_gz.py
The idea is to port LxmlLinkExtractor and leave other link extractors Python 2.x - only.
TODO:
.. after porting link extractors it was too easy to continue with scrapy.spiders and a couple more things
> [MRG] assorted Python 3 porting

- scrapy/http/request/form.py
- tests/test_http_request.py
Allow `<button type="submit">` controls to submit forms
[Forms - HTML5](http://www.w3.org/TR/html5/forms.html#the-button-element) and [Forms - HTML4](http://www.w3.org/TR/html401/interact/forms.html#h-17.5) both allow `button` controls as form submitter.
This patch extends `_get_clickable()` to allow submit buttons too.
The change from `el.name` and `el.value` to `el.get(...)` is needed,
because lxml parses buttons as `HtmlElement` and not `InputElement`.
> Form submit button plain

- scrapy/http/request/form.py
- tests/test_http_request.py
If there is no `value` attribute, provides the empty string as described
in http://www.w3.org/TR/html5/forms.html#attr-button-value:
>The value attribute gives the element's value for the purposes
of form submission. The element's value is the value of the
element's value attribute, if there is one, or the empty string
otherwise.
> [MRG+1] Incomplete submit button

- docs/topics/downloader-middleware.rst
- scrapy/core/downloader/middleware.py
- scrapy/downloadermiddlewares/robotstxt.py
- tests/test_downloadermiddleware.py
- tests/test_downloadermiddleware_robotstxt.py
Adds support for returning deferreds in middlewares, and makes use of this to fix a limitation in RobotsTxtMiddleware.
#1471
> [MRG+1] Support for returning deferreds in middlewares

- .travis.yml
Currently if a PR is open from a branch in main repo tests run twice.
If this PR is merged we'll have to add each new release branch to travis.yml. 
We can also add them all now? 1.0, 1.1, 1.2, etc.
> don't run tests twice on Travis if a PR is made from a scrapy/scrapy branch

- scrapy/utils/python.py
Please review. From my point of view now function looks better.
> equal_attributes function optimization

- scrapy/middleware.py
Inspired by today's mail from @dangra.
Before:
```
2015-05-29 09:45:57+0000 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware,
DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, CustomRetryMiddleware,
SlotDelayMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, 
MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, RedirectMiddleware,
CrawleraMiddleware, CustomCookiesMiddleware, CookiesMiddleware, SplashMiddleware,
HttpCompressionMiddleware, CustomHttpProxyMiddleware, RotateUserAgentMiddleware,
ChunkedTransferMiddleware, ResponseStats, DownloaderStats
```
After: 
```
2015-05-29 09:44:15+0000 [scrapy] INFO: Enabled downloader middlewares:
- HttpAuthMiddleware
- DownloadTimeoutMiddleware
- UserAgentMiddleware
- RetryMiddleware
- …
```
> Make list of enabled middlewares more readable

- scrapy/downloadermiddlewares/redirect.py
- tests/py3-ignores.txt
- tests/test_downloadermiddleware_redirect.py
Hey fellows!
So, here is my stab at porting the redirect downloader middleware to Python 3.
The important change here is decoding the `Location` header as latin1.
To verify that it's a reasonable assumption I wrote a [small Flask app](https://gist.github.com/eliasdorneles/ffd12f05811fee803fa0) and tested it on Chrome and FF.
You can see the screenshots of the app for Chrome here: http://imgur.com/a/1AfMt
Note that when using UTF-8 in the Location header we get a mojibake but things work normally when using latin1.
Se also this [related SO answer](http://stackoverflow.com/a/4410331/149872).
The other changes are a minor refactoring and adding the encoding argument to HtmlResponse in the tests.
> [MRG+1] PY3 redirect downloader mware

- scrapy/commands/check.py
- scrapy/commands/genspider.py
- scrapy/crawler.py
- scrapy/loader/__init__.py
- scrapy/shell.py
- scrapy/utils/defer.py
- scrapy/utils/request.py
> Optimization - avoid temporary list objects, unnecessary function call

- docs/topics/downloader-middleware.rst
- docs/topics/exceptions.rst
fix typos in files docs/topics/downloader-middleware.rst and docs/topics/exceptions.rst,  middlware  -> middleware.
> fix typo middlware

- docs/topics/loaders.rst
- scrapy/loader/__init__.py
- tests/test_loader.py
Adds a nested_loader() method to ItemLoader.  This is useful when you're selecting several related fields from a sub section of the document.  Because the nested loader shares the item and values with it's parent, everything works as expected.
For example, here is a snippet of scraping code using the new functionality:
```python
loader = MyLoader(item=MyItem(), response=response)
loader.add_xpath('images', "//div[@class = 'event_title_image']/img/@src")
header_loader = loader.nested_loader(xpath="//div[@id = 'event_header']")
header_loader.add_xpath('event_name', "//span[@class = 'summary']/text()")
header_loader.add_xpath('start_date', "//meta[@itemprop = 'startDate']/@content")
header_loader.add_xpath('end_date', "//meta[@itemprop = 'endDate']/@content")
loader.load_item()
```
You can …
> add support for a nested loaders

- scrapy/commands/startproject.py
shouldn't scrapy log be disabled on `startproject` command, like it is on `genspider` command?
> disable log on startproject command

- tests/requirements-py3.txt
- tests/requirements.txt
Scrapy testing suite starts to fail with pytest==2.8.0. I wrongly assumed it was a [problem](https://github.com/pytest-dev/pytest-cov/issues/91) with pytest-cov, but it seems I was wrong. It is better to debug and fix the issue properly; in case nobody has time to do that now we can pin pytest to a working version.
> TST pin pytest to 2.7.3

- docs/topics/request-response.rst
I don't believe it was intended to squish `cookiejar` and `dont_cache` onto a single list item on http://doc.scrapy.org/en/1.0/topics/request-response.html#topics-request-response-ref-request-callback-arguments:
> Fix list formatting

- scrapy/commands/shell.py
- scrapy/utils/url.py
- tests/test_utils_url.py
This change addresses the enhancement mentioned in #1487.
The add_scheme_if_missing function uses the parse_url function to parse the url. It checks if the scheme is missing, if it is, 'http' is added as the default scheme. It checks if the netloc field is empty. If it is empty, it replaces it with the path field and changes the path field to empty. This is done because when handing invalid url's like "www.example.com" where the scheme is missing, the parse_url function(which uses urlparse itself) leaves the netloc empty and puts the entire url in path. This leads to incorrect url generation when geturl() is called.
The add_scheme_if_missing function is called by the shell command right after it extracts the url from the arguments list. A check is performed to ensure that a null value is …
> [MRG+1] #1487 add_scheme_if_missing for `scrapy shell` command

- tox.ini
Pillow 3.0.1 should be released soon; in the meantime we can exclude Pillow 3.0.0 to make tests pass. 
See https://github.com/python-pillow/Pillow/issues/1460.
> TST don't use broken Pillow version in tests

- scrapy/utils/iterators.py
- tests/test_utils_iterators.py
A dot is a valid character for an xml node name.
See http://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameChar
Trying to match it leads to matching any character because it's not escaped.
`nodename` was treated like a regex which is a bug in itself
since it contradicts the function's doctring.
I'd rather discard the additional test.
Should I?
> [MRG+1] xmliter nodename with dot

- .travis.yml
I don't know why, but coveralls uploads on Travis started to take 30s recently. And we're not using them anyways. What about removing coveralls support?
> drop coveralls support

- docs/topics/downloader-middleware.rst
- scrapy/downloadermiddlewares/retry.py
A follow-up to #1289 - docs were not updated accordingly. 
It was explained in docs and in docstrings why is 400 retried; I still think removing 400 is a good change.
> [MRG+1] DOC fix docs after GH-1289.

- scrapy/core/engine.py
- scrapy/crawler.py
- tests/test_crawl.py
- tests/test_engine.py
Depending on what state the engine is in, there are different measures that need to be taken to shut it down gracefully (i.e. leaving the reactor clean): Stop the engine, close the spider, or close the downloader.
This PR adds a new method as a single entry point for shutting down the engine and integrates it into `Crawler.crawl()` for graceful error handling during the crawling process.
> [MRG+1] Add ExecutionEngine.close() method

- tests/test_settings/__init__.py
Not sure whether `__repr__`/`__str__` should be tested but I can' stand the red lines in codecov :<
> [MRG+1] Add some missing tests for scrapy.settings

- scrapy/crawler.py
- scrapy/utils/test.py
- tests/test_crawl.py
- tests/test_spiderloader/__init__.py
CrawlerRunner.crawl returns a Deferred, but in all cases I used this method in addition to waiting for crawl to finish it was necessary to connect signal handlers, and you need Crawler instance for that. So 
```python
d = runner.crawl('spidername')  # or runner.create_crawler(spider_cls)
```
was not enough, I wanted
```python
crawler = runner.create_crawler('spidername')  # or runner.create_crawler(spider_cls)
crawler.signals.connect(...)
d = runner.crawl(crawler)
```
This means it was necessary to copy-paste the same code 
```python
crawler = crawler_or_spidercls
if not isinstance(crawler_or_spidercls, Crawler):
crawler = runner._create_crawler(crawler_or_spidercls)
```
in all CrawlerRunner subclasses / wrappers, and using a private `_create_crawler` method. What about adding a public …
> public Crawler.create_crawler method

- docs/topics/downloader-middleware.rst
- docs/topics/extensions.rst
- docs/topics/feed-exports.rst
- docs/topics/settings.rst
- docs/topics/spider-middleware.rst
- scrapy/commands/check.py
- scrapy/commands/crawl.py
- scrapy/commands/runspider.py
- scrapy/core/downloader/handlers/__init__.py
- scrapy/core/downloader/middleware.py
- scrapy/core/spidermw.py
- scrapy/extension.py
- scrapy/extensions/feedexport.py
- scrapy/pipelines/__init__.py
- scrapy/settings/__init__.py
- scrapy/settings/default_settings.py
- scrapy/utils/conf.py
- tests/test_cmdline/__init__.py
- tests/test_settings/__init__.py
- tests/test_utils_conf.py
This is a partial reversal of #1149 that provides per-key priorities in a backwards compatible fashion.
The backwards incompatible API change in #1149 was that when writing to dictionary settings, their contents were updated, not completely overwritten. This PR brings back the old behaviour of completely discarding the previous contents of the dictionary. If the dictionary setting written to is a `BaseSettings` instance, it is not overwritten but cleared and then updated (resulting in the same contents, but conserving per-key priorities).
The price for this is:
- we cannot get rid of the `_BASE` settings
- it will again be much harder to disable single components from the command line or from a spider's `custom_settings` (because disabling a single component requires writing down the …
> [MRG+1] Backwards compatible per key priorities

- scrapy/core/engine.py
Hi guys,
during fixing premature spider closing bugs in Frontera (https://github.com/scrapinghub/frontera/issues/33), I faced with engine activity halt. 
Activity halt happens when scheduler constantly reports that there are requests available, by returning ``True`` from ``has_pending_requests()`` call, but doesn't returns them from ``next_request()`` call. This is done when it's known there are requests for processing, but backend is overloaded generating new batches and it needs some time to "rest". This could also happen in distributed system where not all parts have the same performance.
Halt happens because of downloading-driven nature of execution engine, meaning if no downloading/scraping happens there will be no calls to main engine function where all checks are happening …
> Nextcall heartbeats in engine (event loop halting)

- conftest.py
Trying to avoid collecting tests for newer Twisted versions.
> [MRG+1] Ignoring xlib/tx folder, depending on Twisted version.

- scrapy/commands/shell.py
#1083 again, implementing @nramirezuy's suggestion instead.
> [MRG+1] Disable dupefilter in shell to prevent hanging.

- docs/topics/settings.rst
- scrapy/commands/startproject.py
- tests/test_commands.py
Hello Scrapy-makers :-)
This would be my first, modest, contribution to Scrapy, that I have been pleased to use on and off for a couple of years now.
This is an attempt to address the missing override of TEMPLATES_DIR at project creation described in issue #671. 
I saw PR #1035, but it seems to be on a dead end, and the reasons for that seem to be:
- it implemented multiple override levels in a way that is not compatible with the new override mechanism,
- considering that there is no settings.py (let alone spiders) at startproject time, the only level of override is the command-line, so it was possibly a bit over-engineered.
With this in mind, this PR keeps to the simple route proposed in the issue and copies/pastes from genspider.py.
Looking forwards to your feedback.
> [MRG+1] Startproject templates override

- scrapy/http/request/form.py
- tests/test_http_request.py
#1595 FormRequest should consider input type values case-insensitive
#1596  FormRequest doesn't handle input elements without type attribute
Plus: I noticed a maybe-unicode xpath wasn't encoded
when raising an exception whose `str` message is formatting it with %s.
> [MRG+1] Various FormRequest tests+fixes

- scrapy/__init__.py
- scrapy/core/downloader/handlers/http.py
- scrapy/utils/log.py
- tests/test_downloader_handlers.py
- tests/test_downloadermiddleware_retry.py
- tests/test_toplevel.py
remove all `optional_features` support after the removal of 'boto' (#1357)
> [MRG+1] drop deprecated "optional_features" set

- docs/intro/install.rst
Latest build now include ``pywin32`` as dependency for the ``win`` packages.
> [MRG] Removed pywin32 from conda install instructions as it's already declared as dependency.

- docs/index.rst
This improve readability of TOC in the sidebar. As toctrees are all hidden, captions don't appear in other place (e.g. main content of index page), as far as I know.
Before                |  After
:-------------------------:|:-------------------------:
> [MRG+1] DOC: Add captions to toctrees which appear in sidebar

- scrapy/utils/iterators.py
- tests/py3-ignores.txt
- tests/test_utils_iterators.py
I was getting these errors
`_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`
and it seems to be about returning strings on `next()` calls to `csv.reader`'s first parameter
https://docs.python.org/3/library/csv.html#csv.reader:
> csvfile can be any object which supports the iterator protocol and returns a string each time its __next__() method is called
so I ended up using `StringIO` instead of `BytesIO`
> [MRG+1] PY3: port utils/iterators

- docs/topics/settings.rst
A setting variable `DOWNLOADER_MIDDLEWARES_BASE` contains `AjaxCrawlMiddleware` in the code, but the middleware is not listed in the document of 1.0.
Code:
https://github.com/scrapy/scrapy/blob/1.0/scrapy/settings/default_settings.py#L89
Document:
http://doc.scrapy.org/en/1.0/topics/settings.html#downloader-middlewares-base
Note that this problem has already fixed in the [master branch](http://doc.scrapy.org/en/master/topics/settings.html#downloader-middlewares-base).
> DOC: Add AjaxCrawlMiddleware to DOWNLOADER_MIDDLEWARES_BASE

- scrapy/_monkeypatches.py
In my case, while running datalad tests using nose, scrapy was failing
since v was None
> [MRG+1] BF: robustify _monkeypatches check for twisted - str() name first (Closes #1634)

- docs/topics/stats.rst
`pages_crawled` value doesn't exist. Replace it with `downloader/response_count` in order to avoid confusion.
> Update Stats Collection documentation for @master

- scrapy/core/downloader/handlers/http11.py
We got some troubles when we needed to  process such errors in our project. It is hard to link error in log with the specific download url.
> [MRG+1] added more verbosity for log and for exception when download is cancelled because of a size limit

- scrapy/core/downloader/handlers/http11.py
See  #1303
The warning message was too verbose. Now it is shown only a warning message per request. 
The warning message is updated to show the request and the DOWNLOAD_WARNSIZE variable.
2015-12-30 13:00:18 [scrapy] WARNING: Received more bytes than download warn size (1000) in request <GET https://codeload.github.com/aron-bordin/Android-Tutorials/zip/master>.
> [MRG+1] show download warnsize once

- scrapy/core/downloader/handlers/http10.py
- scrapy/core/downloader/handlers/http11.py
- scrapy/http/response/__init__.py
- tests/mockserver.py
- tests/py3-ignores.txt
- tests/test_downloader_handlers.py
- tests/test_http_response.py
This ports ``tests/test_downloader_handlers.py`` to py3 (with ftp tests skipped), and allows to run simple spider under py3. Is is a continuation of #1676, that contains all changes from there. Approach is the same. In some places, where twisted expects unicode args, we decode host from bytes to unicode, because ``scrapy.core.downloader.webclient._parse`` is used here as well, and returns all url parts as bytes.
I also filed an issue against twister here https://twistedmatrix.com/trac/ticket/8175 - this part remains skipped on py3.
~~Maybe https tunnel without noconnect is missing a test: I will check when porting other downloader tests and add if needed.~~
> [MRG+1] Py3: port http downloaders

- requirements-py3.txt
This is the latest Twisted release. There is no point in trying to check if it can be made lower, yes?
> [MRG+1] Raise minimal twisted version for py3

- docs/topics/downloader-middleware.rst
- docs/topics/settings.rst
* `REDIRECT_MAX_METAREFRESH_DELAY` has been deprecated and was
renamed to `METAREFRESH_MAXDELAY`.
* Merge duplicate documents about `METAREFRESH_MAXDELAY` appeared both
in the settings page and the downloader-middlewares page.
> [MRG+1] DOC: Update MetaRefreshMiddlware's setting variables

- scrapy/core/downloader/handlers/s3.py
- tests/test_downloader_handlers.py
~~(includes/based on #1357 's commit)~~
> [MRG+1] Support anonymous S3DownloadHandler (boto) connections

- scrapy/downloadermiddlewares/httpcompression.py
- scrapy/extensions/httpcache.py
- scrapy/settings/default_settings.py
- tests/py3-ignores.txt
- tests/requirements-py3.txt
- tests/test_downloadermiddleware.py
- tests/test_downloadermiddleware_httpcache.py
- tests/test_downloadermiddleware_httpcompression.py
- tox.ini
This port downloader cache middleware to py3, and is a continuation of #1678. Together with #1637 they port all downloader middlewares to py3, I think.
Here most fixes are about headers parsing (in bytes), and fixing leveldb (adding it to tox.ini and using bytes as keys).
One change that is maybe not necessary is changing ``headers.get('foo')`` to ``headers.get(b'foo')`` - both work, because keys are converted to bytes, but using bytes feels more natural as values are also bytes.
> [MRG+1] Py3: port downloader cache and compression middlewares

- docs/topics/request-response.rst
- scrapy/http/request/form.py
- tests/test_http_request.py
Since we have a `formxpath` argument, it makes sense to have `formcss` argument.
Solves #1374
> [MRG+1] Implement FormRequest.from_response CSS support

- tests/py3-ignores.txt
- tests/test_engine.py
Based on #1680, here are all changes in this branch https://github.com/lopuhin/scrapy/compare/324f2c1...py3-test-engine?expand=1
The fixes are only in tests, the main beeing 570367d, but this fix is in "user-level" crawler code - the minimal change was to use response.body_as_unicode() instead of response.body, because we later parse is with unicode regexps.
> [MRG+1] Py3: port test_engine

- tests/test_commands.py
os.mknod() is a privileged command on OS X, making the test fail
> [MRG+1] change os.mknod() for open()

- tests/py3-ignores.txt
- tests/test_mail.py
Here are py3 docs for Message.get_payload https://docs.python.org/3/library/email.message.html#email.message.Message.get_payload - it returns bytes when decode is True.
> [MRG+1] py3: fix test_mail

- scrapy/exporters.py
- tests/py3-ignores.txt
- tests/test_exporters.py
- tests/test_feedexport.py
Hey fellows,
I've started porting the exporters to Python 3, but I'm not sure how backward compatible we should be -- I'm creating the PR already hoping it'll help moving this forward.
There isn't much here yet, I just got the first few tests passing under Python 3, keeping the retrocompatibility. Current passings tests are:
```
tox -e py27,py34 -- tests/test_exporters.py::BaseItemExporterTest tests/test_exporters.py::PythonItemExporterTest tests/test_exporters.py::CustomItemExporterTest
```
According to issue #1080 (which I tend to agree), we should change the default output of BaseItemExporter to unicode text and only do encode to bytes for things that we can't use text (like CSV writer in Python 2 only). This would make porting easier, but would cause issues for users since we'd be …
> [MRG+1] PY3 exporters

- docs/topics/spider-middleware.rst
- docs/topics/spiders.rst
- tests/test_spidermiddleware_offsite.py
While explaining to a colleague how to restrict crawls to a specific vhost by specifying a subdomain
I noticed that the documentation doesn't demonstrate the subdomain behaviour clearly.
I then tried to point to the tests but they also lacked such an example.
As a test case it's redundant because the regex is actually tested on the TLD
so you may want me to amend the commit first.
I'd only consider it for the future possibility that someone tries to refactor the offsite middelware
and accidentally treats the top level and second level domains as a special case.
> [MRG+1] tests+doc for subdomains in offsite middleware

- scrapy/middleware.py
Wrong middlewares list was being pretty-printed
(introduced in #1263)
I noticed this while trying to disabled `CloseSpider`, it was still appearing in `scrapy shell`
Before (current `master` branch)
```
2016-01-26 12:44:20 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.closespider.CloseSpider',
'scrapy.extensions.feedexport.FeedExporter',
'scrapy.extensions.memdebug.MemoryDebugger',
'scrapy.extensions.memusage.MemoryUsage',
'scrapy.extensions.logstats.LogStats',
'scrapy.extensions.telnet.TelnetConsole',
'scrapy.extensions.corestats.CoreStats',
'scrapy.extensions.spiderstate.SpiderState',
'scrapy.extensions.throttle.AutoThrottle']
```
With this fix, it now shows like this:
```
2016-01-26 12:54:53 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.telnet.TelnetConsole', …
```
> [MRG+1] Fix logging of enabled middlewares

- scrapy/utils/datatypes.py
Hey,
It seems we have some dead code in scrapy.utils.datatypes: https://codecov.io/github/scrapy/scrapy/scrapy/utils/datatypes.py?ref=b20463183c6ae39f1e0f84fe0b5abbe4b2db44c2 - MultiValueDict and SiteNode are untested and not used by scrapy itself. I checked our internal codebase and haven't found a single usage of these classes; I also checked github briefly, and haven't found it either.
MultiValueDict looks like an unmaintained copy-paste of django code; I have no idea what is SiteNode origin.
> [MRG+1] deprecated unused and untested code in scrapy.utils.datatypes

- docs/topics/settings.rst
- scrapy/templates/project/module/settings.py.tmpl
A proposed fix for #1668. 
For backwards compatibility reasons the default value is not changed: settings for existing projects or settings used for CrawlerProcess won't change.
> [MRG+1] Enable robots.txt handling by default for new projects.

- scrapy/middleware.py
Continuation of https://github.com/scrapy/scrapy/pull/1722
> Use long classes names for enabled middlewares in startup logs

- docs/topics/request-response.rst
- scrapy/downloadermiddlewares/ajaxcrawl.py
- scrapy/downloadermiddlewares/robotstxt.py
- scrapy/http/request/form.py
- scrapy/http/response/text.py
- scrapy/selector/unified.py
- scrapy/utils/iterators.py
- scrapy/utils/response.py
- tests/test_engine.py
- tests/test_http_response.py
Fixes GH-1729.
TextResponse.body_as_unicode() is old and common, so it is not deprecated. I think it is better not to flood users with warnings without a compelling reason.
> [MRG+1] response.text

- docs/faq.rst
- docs/topics/settings.rst
> [MRG+1]Clarify priority adjust settings docs

- scrapy/exporters.py
- tests/test_exporters.py
This PR fixes the error related to PythonItemExporter with non-string types reported here: https://github.com/scrapy/scrapy/commit/c76190d491fca9f35b6758bdc06c34d77f5d9be9#commitcomment-15693798.
It also fixes how CSVItemExporter represents non-string datatypes in CSV.
Instead of generating this (for a datetime object):
```2,True,False,2015-01-01 01:01:01```
It was generating this:
```True,2,False,"datetime.datetime(2015, 1, 1, 1, 1, 1)"```
> [MRG+1] Fix PythonItemExporter and CSVExporter for non-string item types

- scrapy/exporters.py
- tests/test_exporters.py
This PR fixes https://github.com/scrapy/scrapy/issues/1738
> [MRG+1] Fix bug on XMLItemExporter with non-string fields in items

- scrapy/core/downloader/__init__.py
I'm getting this error without a fix:
```
2016-01-28 02:54:17 [twisted] CRITICAL: Unhandled error in Deferred:
File "/Users/kmike/envs/dl/lib/python3.5/site-packages/Twisted-15.5.0-py3.5.egg/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/Users/kmike/envs/dl/lib/python3.5/site-packages/Twisted-15.5.0-py3.5.egg/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
File "/Users/kmike/envs/dl/lib/python3.5/site-packages/Twisted-15.5.0-py3.5.egg/twisted/internet/base.py", line 825, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/Users/kmike/envs/dl/lib/python3.5/site-packages/Twisted-15.5.0-py3.5.egg/twisted/internet/task.py", line 213, in __call__
d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- …
```
> [MRG+1] PY3 fix downloader slots GC

- scrapy/commands/settings.py
- scrapy/settings/__init__.py
- tests/test_cmdline/__init__.py
- tests/test_settings/__init__.py
Settings instances as dict's are easier to print or pretty print in the shell
Fixes #1732
> [MRG+1] Remove __str__ and __repr__ from settings, introduce copy_to_dict()

- scrapy/downloadermiddlewares/robotstxt.py
- tests/test_downloadermiddleware_robotstxt.py
> [MRG+1] Fix for KeyError in robots.txt middleware

- scrapy/crawler.py
I'm not sure why (probably `stop` method removes crawler from self.crawlers), but in Python 3 existing code sometimes raises the following error at shutdown:
```
2016-02-03 00:58:57 [twisted] CRITICAL: Unhandled Error
File "/Users/kmike/svn/scrapy/scrapy/commands/crawl.py", line 58, in run
self.crawler_process.start()
File "/Users/kmike/svn/scrapy/scrapy/crawler.py", line 269, in start
reactor.run(installSignalHandlers=False)  # blocking call
File "/Users/kmike/envs/dl/lib/python3.5/site-packages/Twisted-15.5.0-py3.5.egg/twisted/internet/base.py", line 1194, in run
self.mainLoop()
File "/Users/kmike/envs/dl/lib/python3.5/site-packages/Twisted-15.5.0-py3.5.egg/twisted/internet/base.py", line 1203, in mainLoop
self.runUntilCurrent()
--- <exception caught …
```
> [MRG+1] PY3 fixed CrawlerRunner.stop

- docs/topics/email.rst
- scrapy/mail.py
- tests/test_mail.py
Resolves Issue #348.
The default behavior remains the same as before, but it is now possible to send utf-8 emails.
> [MRG+1] MailSender.send: allow passing a charset.

- scrapy/core/engine.py
After this PR Scrapy will avoid calling `scheduler.has_pending_requests()` unless necessary. Not sure it is important, but it may save some time if `scheduler.has_pending_requests()` is heavy (e.g. if it needs to read something from a database).
> [MRG+1] more efficient ExecutionEngine.spider_is_idle

- scrapy/spiders/sitemap.py
- tests/test_spider.py
Fix #1766, the problem that SitemapSpider fails to extract sitemap urls from robots.txt in Python 3.
* Pass `response.text` as an argument of `sitemap_urls_from_robots()` instead of `response.body`.
* Add an unit test.
> [MRG+1] PY3: Fix SitemapSpider to extract sitemap urls from robots.txt properly

- scrapy/http/cookies.py
- tests/test_http_cookies.py
Fix #1770, the failure to download the second or later requests to hosts using secure cookies. The problem is caused by missing `type` attribute of `scrapy.http.WrappedRequest`.
Though [the official document](https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.CookieJar.add_cookie_header) seems to be outdated, `request` argument of `CookieJar.add_cookie_header()` requires some attributes instead of methods in Python 3. This is because `urllib.request.Request`'s methods `get_hosts()`, `get_type()`, `unverifiable()` and `get_origin_req_host()` were deprecated in Python 3.3 and removed in Python 3.4.
See also:
Issue 15409: Deprecation Warning fix on cookiejar module - Python tracker
http://bugs.python.org/issue15409
cpython: ea8078365d3b …
> [MRG+1] PY3: Implement some attributes of WrappedRequest required in Python 3

- scrapy/extensions/feedexport.py
Fix #1768, the failure to output to stdout in Python 3.
* Use `sys.stdout.buffer` instead of `sys.stdout` in Python 3.
Buffering behavior seems to be different between Python 2 and 3, though I don't think it's a matter.
The exporeted item is shown at the line immediately after the scraped log, i.e. it seems to be unbuffered.
```
$ scrapy runspider myspider.py -o - -t jl
2016-02-07 08:06:55 [scrapy] INFO: Scrapy 1.1.0rc1 started (bot: scrapybot)
2016-02-07 08:06:55 [scrapy] INFO: Overridden settings: {'FEED_FORMAT': 'jl', 'FEED_URI': 'stdout:'}
2016-02-07 08:06:55 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
'scrapy.extensions.logstats.LogStats',
'scrapy.extensions.telnet.TelnetConsole',
'scrapy.extensions.corestats.CoreStats']
2016-02-07 08:06:55 …
```
> [MRG+1] PY3: Fix TypeError when outputting to stdout

- docs/news.rst
- scrapy/xlib/pydispatch.py
- tests/test_pydispatch_deprecated.py
Hey folks!
This adds fallback imports and a deprecation warning when importing from scrapy.xlib.pydispatch and adds a note it in the release notes.
> [MRG+1] Add fallback and deprecation warning for pydispatch (fixes #1762)

- docs/topics/feed-exports.rst
- scrapy/core/downloader/handlers/s3.py
- scrapy/extensions/feedexport.py
- scrapy/http/headers.py
- scrapy/pipelines/files.py
- scrapy/utils/boto.py
- scrapy/utils/test.py
- tests/py3-ignores.txt
- tests/requirements-py3.txt
- tests/test_downloader_handlers.py
- tests/test_feedexport.py
- tests/test_pipeline_files.py
- tox.ini
The main idea is that we try to use ``botocore`` by default, falling back to ``boto`` on Py2. ``botocore`` is more recent and has better Py3 support. Should fix #1718 (see comments there about some changes in test). boto code path is still tested in ``precise`` environment.
> [MRG+1] Py3 S3 botocore

- scrapy/responsetypes.py
- tests/test_responsetypes.py
Originally from https://github.com/scrapy/scrapy/pull/1786
Fixes #1782
> [backport][1.1.x] More liberal Content-Disposition header parsing

- scrapy/utils/test.py
I was getting these errors while running Py3 tests without recreating my local tox virtualenvs (ie. still without botocore)
```
self = <tests.test_downloader_handlers.S3AnonTestCase testMethod=test_anon_request>
def setUp(self):
>       skip_if_no_boto()
/home/paul/src/scrapy/tests/test_downloader_handlers.py:475: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
def skip_if_no_boto():
try:
is_botocore()
except NotConfigured as e:
>           raise SkipTest(e.message)
E           AttributeError: 'NotConfigured' object has no attribute 'message'
/home/paul/src/scrapy/scrapy/utils/test.py:27: AttributeError
```
With this patch, the skipped tests in this case …
> Fix SkipTest() message for botocore import test

- scrapy/core/downloader/handlers/http11.py
- tests/test_downloader_handlers.py
GH-823 was fixed only for HTTP/1.0 (in GH-1089)
This is not strictly required by HTTP RFCs but can cause trouble for some web servers.
See:
- https://github.com/scrapy/scrapy/issues/823
- https://issues.apache.org/jira/browse/TS-2902
- https://github.com/kennethreitz/requests/issues/405
- https://bugs.python.org/issue14721
> [MRG+1] Add "Content-Length: 0" for body-less HTTP/1.1 POST requests

- scrapy/core/downloader/handlers/http11.py
- tests/test_downloader_handlers.py
Commits from https://github.com/scrapy/scrapy/pull/1800
> [backport][1.1] Add "Content-Length: 0" for body-less HTTP/1.1 POST requests

- docs/topics/feed-exports.rst
- docs/topics/settings.rst
- scrapy/pipelines/files.py
- scrapy/settings/default_settings.py
See #1778 - this will make files uploaded via S3 private by default. If no settings customization is required, I can leave only the ``S3FilesStore.POLICY`` change.
> [MRG+1] Change default S3 ACL to "private" and allow customization via settings

- scrapy/core/downloader/contextfactory.py
- scrapy/core/downloader/handlers/http11.py
- scrapy/core/downloader/tls.py
- scrapy/settings/default_settings.py
Backporting (squashed commits from) https://github.com/scrapy/scrapy/pull/1794 into 1.1
Implement IPolicyForHTTPS
Backward compatibility for HTTP/10 context factory
New DOWNLOADER_CLIENT_TLS_METHOD setting to configure TLS method
Backward-compatibility for common Scrapy context factory patterns
Add warning for context factories not accepting `method` param
Use context factory class name in warning message
> [backport][1.1] Use best practices for TLS connections when using Twisted>=14.0

- scrapy/spiderloader.py
As discussed here https://github.com/scrapy/scrapy/issues/1805 I modified the SpiderLoader class making it possible to avoid pre-loading all spiders when subclassing from it without having to copy the constructor's code.
> [MRG+1] Refactored SpiderLoader class constructor for easier subclassing

- docs/news.rst
Adds more prominent warning after GH-1796
> [MRG+1] Update release notes about change of default S3 ACL policy to "private"

- scrapy/core/downloader/handlers/http11.py
- scrapy/core/downloader/webclient.py
- tests/test_downloader_handlers.py
This PR seperates the original `test_timeout_download_from_spider` into two.
Before the change on `_cb_timeout`:
- HTTP/1.1 failed on `Https11TestCase.test_timeout_download_from_spider_server_hangs` only, `Https11TestCase.test_timeout_download_from_spider_nodata_rcvd` passes
- HTTP/1.0 failed on both `Https10TestCase.test_timeout_download_from_spider_nodata_rcvd` and `Https10TestCase.test_timeout_download_from_spider_server_hangs`
With this change, both HTTP/1.0 and HTTP/1.1 tests pass.
~~HTTP/1.0 are not fixed (yet).~~
The trick is to explicitly call Twisted transport stopProducing()
**If more Twisted-familiar eyes could give their thoughts, I'd be grateful**
This solved dirty reactor errors for me:
```
DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<<class …
```
> Re-enable HTTPS tests for download timeouts

- scrapy/core/downloader/handlers/http11.py
- scrapy/core/downloader/webclient.py
- tests/test_downloader_handlers.py
Backport #1804 into 1.1 branch.
> [Backport][1.1] Re-enable HTTPS tests for download timeouts

- scrapy/linkextractors/__init__.py
Issue #1834 , extend IGNORED_EXTENSIONS in linkextractors with pps.
> [MRG+1] Add pps extension to IGNORED_EXTENSIONS

- scrapy/core/scheduler.py
- scrapy/settings/default_settings.py
It seems there are use-cases for replacing the PriorityQueue in the Scheduler.
This adds a setting to do so via `SCHEDULER_PRIORITY_QUEUE`.
> [MRG+1] Allow core Scheduler priority queue customization

- docs/contributing.rst
- docs/faq.rst
- docs/intro/install.rst
- docs/intro/overview.rst
- docs/intro/tutorial.rst
- docs/news.rst
- docs/topics/api.rst
- docs/topics/architecture.rst
- docs/topics/djangoitem.rst
- docs/topics/downloader-middleware.rst
- docs/topics/email.rst
- docs/topics/extensions.rst
- docs/topics/feed-exports.rst
- docs/topics/firebug.rst
- docs/topics/item-pipeline.rst
- docs/topics/media-pipeline.rst
- docs/topics/practices.rst
- docs/topics/request-response.rst
- docs/topics/selectors.rst
- docs/topics/settings.rst
- docs/topics/shell.rst
- docs/topics/signals.rst
- docs/topics/spider-middleware.rst
- docs/topics/spiders.rst
- docs/topics/webservice.rst
- docs/versioning.rst
Doing the docs linkchecker run found some new permanent redirects.
Most of which are only doing HTTPS enforcing.
> [MRG+1] Update documentation links

- docs/topics/selectors.rst
Changed sel. to response. to comply with the rest of the examples in the same section, to avoid confusion.
> Changed sel. to response. for clarity

- scrapy/extensions/httpcache.py
FS cache storage misuses mtime for expiration
> [MRG+1] FS cache storage misuses mtime for expiration

- docs/_ext/scrapydocs.py
- docs/topics/selectors.rst
- tox.ini
See http://www.sphinx-doc.org/en/stable/changes.html#release-1-4-released-mar-28-2016
* `sphinx_rtd_theme` has become optional, needs to be added to reqs
* https://github.com/sphinx-doc/sphinx/pull/2320 changes node entries tuples to 5 values instead of 4
* `sh` syntax highlighting added very locally in selectors.rst because of this warning/error with Sphinx 1.4:
```
Warning, treated as error:
/home/paul/src/scrapy/docs/topics/selectors.rst:743:
WARNING: Could not lex literal_block as "python". Highlighting skipped.
```
> Add support for Sphinx 1.4

- scrapy/utils/response.py
- tests/test_utils_response.py
utility is used in retry middleware and it was failing to handle non-standard HTTP codes. Instead of raising exceptions when passing through `to_native_str` it should return "Unknown status" message.
> [MRG+1] response_status_message should not fail on non-standard HTTP codes

- scrapy/responsetypes.py
- scrapy/utils/python.py
- tests/test_utils_python.py
See #1389
Since this suggested rename seemed to have positive responses, here is a PR which does just that, to resolve the issue.
> [MRG+1] Rename isbinarytext function to binary_is_text for clarity

- scrapy/pipelines/files.py
It did not work due to two reasons, one silly and one intricate:
- ``meta=None`` was not handled properly
- there was a race condition between persisting file and calculating checksum (explained in the commit message) - this in theory could lead to bugs with other stores as well.
> [MRG+1] Make FilesPipeline work with S3FilesStore using botocore

- docs/topics/architecture.rst
* spiders don't have to work on specific domains;
* explain what to use Downloader middleware for
and what to use Spider middleware for;
* Engine no longer locates spiders based on domains;
* "Spider middleware output direction" step was missing - this one was bugging me since 2013 :)
See also: GH-1569.
This overview is still incomplete because Extensions and Scraper are not explained.
> DOC improved Architecture overview

- docs/topics/settings.rst
- scrapy/extensions/feedexport.py
- scrapy/settings/default_settings.py
- tests/test_feedexport.py
I'm adding a new setting  BLOCKING_FEED_STORAGE_PATH to configure a folder used to save temporary files before uploading them. 
This setting defaults to None and will pick a system temporary folder. If a value is set, will raise an exception if it's not a valid directory and use it otherwise.
See https://github.com/scrapy/scrapy/issues/1779 for more details
> [MRG+2] added BLOCKING_FEED_STORAGE_PATH to settings

- scrapy/utils/sitemap.py
Reasons:
- The proposal on robots.txt is never standardized.
- The field "Sitemap:" is also merely a de facto standard since [the original robots.txt draft](http://www.robotstxt.org/norobots-rfc.txt) did not mention it at all.
- Many websites are currently using all-lowercase fields, e.g. "disallow" and "user-agent".
- Some big companies treat the field names as case-insensitive, like [Google](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt)
> [MRG+1] Added: Making it case-insensitive when extracting sitemap URLs from a robots.txt

- requirements.txt
- scrapy/downloadermiddlewares/ajaxcrawl.py
- scrapy/utils/response.py
- setup.py
Can't say if bumping the w3lib dependency to 1.13 is a good idea yet. But maybe it is once scrapy 1.2 sees a release. So this might be for then or later.
> [MRG+1] Remove duplicate code now handled by newer w3lib

- scrapy/utils/response.py
- tests/test_linkextractors.py
- tests/test_utils_response.py
Backporting https://github.com/scrapy/scrapy/pull/1857 into 1.0
utility is used in retry middleware and it was failing to handle non-standard HTTP codes.
Instead of raising exceptions when passing through to_native_str it should return
"Unknown status" message.
> [Backport][1.0] response_status_message should not fail on non-standard HTTP codes

- docs/topics/media-pipeline.rst
- scrapy/pipelines/files.py
- scrapy/pipelines/images.py
- scrapy/settings/default_settings.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
fix #1850
Addressed issues:
1. Move default settings from `FilesPipelines.py` and `ImagesPipelines.py` to `settings/default_settings.py`
2. Change class attributes from `FilesPipelines.py` and `ImagesPipelines.py` to instance attributes. It allows that distinct spiders running together have distinct custom settings for the pipelines.
Note: I have no way to test AWS related stuff. So I haven't touched any code related to AWS.
@kmike as you have looked at the issue before, I think you should review the PR.
> [MRG+1] Change Files/ImagesPipelines class attributes to instance attributes

- tests/sample_data/link_extractor/linkextractor_latin1.html
- tests/test_linkextractors_deprecated.py
URL path component should use UTF-8 before percent-encoding (that's what
browsers do when you open scrapy/tests/sample_data/link_extractor/linkextractor_latin1.html
and follow the links)
This matches current w3lib v1.14.1
> Fix link extractor tests for non-ASCII characters from latin1 document

- tests/sample_data/link_extractor/linkextractor_latin1.html
- tests/test_linkextractors_deprecated.py
https://github.com/scrapy/scrapy/pull/1913 into 1.1 branch
> [backport][1.1] Fix link extractor tests for non-ASCII characters from latin1 document (PR #1913)

- docs/faq.rst
Just noticed that FAQ still says that scrapy does not support python 3. Maybe it still makes sense to leave a separate entry for Python 3?
> [MRG+1] Fix FAQ entry about python versions support (add Python 3.3+)

- scrapy/core/downloader/handlers/http11.py
Should fix https://github.com/scrapy/scrapy/issues/1807
It adds the proxy host and port to the key used to cache HTTP connections, instead of just the remote host and port.
I have no concrete proposal for unittesting this though.
I only was able to debug-print HTTP pool keys and testing with https://httpbin.org/ip with a few open HTTPS proxies.
With current code, before this patch, connections do get mixed with current default Twisted `Agent` [`key = (parsedURI.scheme, parsedURI.host, parsedURI.port)`](http://twistedmatrix.com/trac/browser/tags/releases/twisted-16.0.0/twisted/web/client.py#L1597)
> [MRG+1] Fix HTTP Pool key for HTTPS proxy tunneled connections (CONNECT method)

- requirements.txt
- scrapy/http/request/__init__.py
- tests/test_http_request.py
Starting from w3lib 1.14.1, `safe_url_string` implementation follows browsers' behavior better.
Let's use it from now on.
These changes were originally part of https://github.com/scrapy/scrapy/pull/1874, split here so as to seperate topics.
> [MRG+1] Use newer w3lib.url.safe_url_string() and re-enable HTTP request tests

- scrapy/exporters.py
Placing the opening and closing brackets on their own lines makes it slightly easier to sort lines after the `spider_closed` signal is fired. (sorting is useful when using scrapy to generate open data sets that should have consistent item order, despite request disorder)
> [MRG+1] Place brackets on own lines with JsonItemExporter

- scrapy/exporters.py
Placing the opening and closing brackets on their own lines makes it slightly easier to sort lines after the `spider_closed` signal is fired.
> [backport][1.1] Place brackets on own lines with JsonItemExporter (PR #1950)

- scrapy/utils/url.py
- tests/test_utils_url.py
Bits of https://github.com/scrapy/scrapy/pull/1874 related to canonicalize_url()
Does NOT handle issues raised in https://github.com/scrapy/scrapy/issues/1941
> [MRG+1] Fix canonicalize_url() on Python 3 and re-enable tests

- scrapy/core/downloader/tls.py
Fixes #1976
`VerificationError` exception can have an empty string representation ([e.g. for `service-identity<16`](https://github.com/scrapy/scrapy/issues/1976#issuecomment-218422811))
This patch adds a (more) meaningful message before the exception message just in case.
> [MRG+1] Prevent empty warnings in case of certificate verification failures

- docs/news.rst
I'm removing "(non-Python 3 ported Twisted dependency)" as some of the limitations may already have been lifted in more recent Twisted versions, and because, in practice, we may not have tried enough to port them.
> [MRG+1] Update release notes and date for 1.1.0

- docs/topics/downloader-middleware.rst
Instead of hardcoded http://www.example.com, as noticed by Andrés Pérez-Albela H.: without it url variable is unused and only one request will make it past dupefilter.
> [MRG+1] Use "url" variable in the example

- scrapy/downloadermiddlewares/retry.py
It's a small change. Please just check the diff.
> [MRG+1] Added: Retrying scrapy.core.downloader.handlers.http11.TunnelError

- scrapy/downloadermiddlewares/httpcompression.py
- tests/test_downloadermiddleware_httpcompression.py
Not sure if this is required or not, but seems like a good way to start working on this project...
> [MRG+1] Fix issue HttpCompressionMiddleware tries to decode HEAD responses #1899

- docs/topics/downloader-middleware.rst
#2015 into 1.1 branch
Instead of hardcoded http://www.example.com: without it url variable is unused and only one request will make it past dupefilter.
> [backport][1.1] Use "url" variable in the example (PR #2015)

- docs/intro/tutorial.rst
Moving pull request to `master`. Reference:
https://github.com/scrapy/scrapy/pull/2031#issuecomment-223837912
> Typo fixes

- docs/faq.rst
See https://twitter.com/PackOsiris/status/741114216833241089 for motivation
> [MRG] Add FAQ entry on using BeautifulSoup in spider callbacks

- docs/faq.rst
- docs/intro/install.rst
- docs/news.rst
#2056 seems like common issue (e.g. user here: http://stackoverflow.com/questions/36857638/can-i-run-scrapy-on-windows-with-python-3/37418422) , should we also update [installation guide](http://doc.scrapy.org/en/1.1/intro/install.html) with note about Python 3? Currently it does not say anything about Python 3 but people assume 3 should be supported.
> [MRG+1] [docs] add note about windows + python3

- tests/requirements-py3.txt
- tests/requirements.txt
Scrapy testing suite is failing now. I've tried to downgrage/upgrade several dependencies; this looks related to pytest-cov 2.3.0 release. pytest is upgraded just in case; just upgrading pytest didn't help.
> [MRG+1] TST pin pytest-cov to 2.2.1; upgrade pytest

- scrapy/core/downloader/handlers/http11.py
- tests/test_downloader_handlers.py
"Host" request header is a MUST according to [RFC 2616](https://tools.ietf.org/html/rfc2616#page-128)
> A client MUST include a Host header field in all HTTP/1.1 request
>    messages . If the requested URI does not include an Internet host
>    name for the service being requested, then the Host header field MUST
>    be given with an empty value. An HTTP/1.1 proxy MUST ensure that any
>    request message it forwards does contain an appropriate Host header
>    field that identifies the service being requested by the proxy. All
>    Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request)
>    status code to any HTTP/1.1 request message which lacks a Host header
>    field.
so it must also be sent for CONNECT requests.
Fixes issue raised in …
> [MRG] Add "Host" header in CONNECT requests to HTTPS proxies

- docs/topics/commands.rst
- scrapy/commands/genspider.py
- scrapy/templates/spiders/crawl.tmpl
- scrapy/templates/spiders/csvfeed.tmpl
- scrapy/templates/spiders/xmlfeed.tmpl
- tests/test_commands.py
This PR enables the `genspider` CLI command even when the working dir is not a scrapy project.
The rationale behind is that some users (including me) are used to create standalone spiders and run it with the `runspider` command, because it's a quick and convenient way to fire up simple spiders. Having `genspider` available would make it even quicker.
> [MRG+1] Enable genspider command outside project folder

- scrapy/core/downloader/handlers/http11.py
- tests/test_downloader_handlers.py
Hey scrapy team!
This fix is connected to [this](https://github.com/scrapy/scrapy/issues/2000) issue. 
Little changes performed will fix detecting of response type. Seems that passing `body` into `responsetypes.from_args(...)` was missed. 
It caused a little incomprehension when I expected text type, and it should be text, but I had a simple `Response`, not `TextResponse`. 
Thanks, 
Matvei.
> [MRG+1] Fixed choosing of response class.

- docs/contributing.rst
Linking to an issue when creating a PR is useful
but authors sometimes replace the whole subject with "Fix+tests for #000"
which makes it hard to skim through the issue tracker or its feed
especially when the description is missing from the PR itself.
This is even more important for commit messages.
With this pr I want to open the discussion;
I'm not fully convinced that this is the role of the documentation
but I wrote it there as a start.
> [MRG+1] Encourage complete titles in pull requests

- scrapy/utils/url.py
- tests/test_utils_url.py
Fixes #2010
Not quite sure what to do with non-ASCII chars in netlocs that do not convert well with IDNA rules.
Left the netloc as is for now.
> [MRG] Do not fail on canonicalizing URLs with wrong netlocs

- scrapy/utils/gz.py
- tests/test_utils_gz.py
> [MRG+1] Is_gzipped for application/x-gzip;charset=utf-8

- scrapy/downloadermiddlewares/httpcompression.py
- tests/test_downloadermiddleware_httpcompression.py
> [backport][1.1] HttpCompressionMiddleware: don't decode HEAD responses (PR #2008)

- scrapy/downloadermiddlewares/retry.py
> [backport][1.1] Retrying scrapy.core.downloader.handlers.http11.TunnelError (PR #1974)

- docs/topics/feed-exports.rst
- scrapy/exporters.py
- scrapy/extensions/feedexport.py
- scrapy/settings/default_settings.py
- tests/test_feedexport.py
> [MRG+1] Added option to turn off ensure_ascii for JSON exporters

- docs/topics/practices.rst
Hello,
As I was reading the (current 😂) docs I noticed a small grammar error. I've fixed it in this pull request
I've made this PR target the master branch instead of the 1.1 branch as requested
> (docs) Fix small grammar issue in practices.rst (Supersedes #2119)

- scrapy/core/downloader/tls.py
- tests/test_downloader_handlers.py
Fixes GH-2092
FTR, this is what Twisted 16.3.0 gives with default `Agent` (for www.google.com at 216.58.208.132)
```
$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.internet import reactor
>>> from twisted.web.client import Agent
>>> from twisted.web.http_headers import Headers
>>> 
>>> agent = Agent(reactor)
>>> 
>>> d = agent.request(
...     'GET',
...     'https://216.58.208.132:443/',
...     Headers({'User-Agent': ['Twisted Web Client Example']}),
...     None)
>>> 
>>> 
>>> def cbResponse(ignored):
...     print('Response received')
... 
>>> 
>>> d.addCallback(cbResponse)
<Deferred at 0x7fc71fd89e18>
>>> 
>>> def cbShutdown(ignored):
...     reactor.stop()
... 
>>> …
```
> Catch and ignore certification verification exception for IP-address hosts

- docs/topics/commands.rst
- scrapy/commands/startproject.py
- tests/test_commands.py
I don't know if anyone creates project like me.
I have a habit to create git repository and then I create scrapy project.
You can see something similar at [django startproject command](https://docs.djangoproject.com/en/1.9/ref/django-admin/#startproject).
Unfortunately, I had to rewrite ``copytree`` function, to make sure that the ``startproject`` won't fail if it ``project_dir`` already exists.
I am available to any feedback,
Thanks.
> [MRG+1] Included new optional parameter in startproject command line

- docs/topics/media-pipeline.rst
- docs/topics/signals.rst
- scrapy/utils/misc.py
The signal docs did not have any examples showing how to connect callback functions to signals. Added an example with this PR (+ a few typos in documentation)
Fixes #1521
> [MRG+1] Include example for signal docs

- docs/topics/media-pipeline.rst
- docs/topics/settings.rst
- scrapy/pipelines/images.py
- scrapy/settings/default_settings.py
All images uploaded to S3 using the ImagesPipeline class have the default ACL policy (private), because ImagesPipeline is not respecting the FILES_STORE_S3_ACL setting.
This setting is correctly used in FilesPipeline: https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/files.py#L258
> [MRG+1] Apply the FILES_STORE_S3_ACL setting in ImagesPipeline

- scrapy/selector/unified.py
- tests/test_selector.py
> [MRG+1] Selector should not receive both response and text

- README.rst
I removed the readme's download stats badge because it's apparently broken. It's been showing small numbers for quite some time.
> [MRG+1] Remove README download count badge

- scrapy/pipelines/images.py
- tests/test_pipeline_images.py
It looks like commit 4cef1a1d0060148716ffec4ad6ce9bf709ad1ea2 introduced a little bug. According to the documentation IMAGES_EXPIRES should be 90.
> [MRG+1] Fix IMAGES_EXPIRES default value

- scrapy/commands/parse.py
Fixed typo in error message when selecting a callback method for the parse command.
Example:
```
scrapy parse http://www.example.com -c humpty
...
2016-08-08 13:20:27 [scrapy] ERROR: Cannot find callback <function Command.prepare_request.<locals>.callback at 0x7f61273ff730> in spider: <spider_name>
```
After:
```
scrapy parse http://www.example.com -c humpty
...
2016-08-08 14:32:11 [scrapy] ERROR: Cannot find callback 'humpty' in spider: <spider_name>
```
> [MRG+1] Typo fix for error in parse command 

- .bumpversion.cfg
Having the part:prerel setup as it's right now, it's forcing releases to go through a pre-release cycle dev1, rc1, before the actual release.
That is not desired for older branches, since they will have mostly minor and patch releases.
This disables that behavior, making minor and patch releases for this branch more predictable.
> [MRG+1] Better bumpversion config for branch 1.1

- scrapy/utils/serialize.py
- tests/test_utils_serialize.py
Tried using sets a few times as a way to get a list that avoid duplicates in field values. Only to remember that neither Python or Scrapy's encoder can serialize them.
> [MRG+1] Add set serialization to ScrapyJSONEncoder

- docs/topics/request-response.rst
> [MRG+1] Correct documentation about Response parameters

- docs/topics/settings.rst
The documentation currently states:
> By default, Scrapy doesn’t wait a fixed amount of time between requests, but uses a random interval between 0.5 and 1.5 * DOWNLOAD_DELAY
It might mislead readers to think that, for a DOWNLOAD_DELAY=2, the interval would be from 0.5 to 3.0, when it's actually from 1.0 to 3.0.
See: https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/__init__.py#L38
> [MRG+1] Fix RANDOMIZE_DOWNLOAD_DELAY description in the docs

- docs/_templates/layout.html
This PR includes a [Segment.io](http://segment.io) analytics [tracking snippet](https://segment.com/docs/sources/website/analytics.js/quickstart/#step-1-copy-the-snippet) to the Scrapy documentation (http://doc.scrapy.org).
We're already doing it on Scrapy.org, this just adds the same thing to the documentation website, which will allow to see the unified analytics data.
The analytics data is oversee by Scrapinghub staff, which include Scrapy core developers.
> [MRG+1] Add Segment Analytics to Documentation

- docs/topics/exceptions.rst
There are namely no constructors in classes in Python but an ``__init__`` method instead.
> [MRG+1] Update exceptions.rst

- scrapy/responsetypes.py
- tests/test_responsetypes.py
Amazon is using this content type to load reviews with ajax:
```
ipdb> response.headers['Content-Type']
'application/json-amazonui-streaming;charset=UTF-8'
```
Don't know if we want to add it since it's Amazon-specific.
> [MRG+1] interpreting json-amazonui-streaming as TextResponse

- docs/intro/tutorial.rst
**Please, don't merge this yet** because it's a WIP. For now, we have the old tutorial ported for quotes.toscrape.com, but we will now rewrite it.
This PR aims to fix https://github.com/scrapy/scrapy/issues/2233
> [MRG+1] Update broken Scrapy tutorial to use quotes.toscrape.com

- docs/intro/overview.rst
So, this will replace the spider example code from the overview that
scrapes questions from StackOverflow by a spider scraping quotes (much
like the one in the tutorial), and upates the text around it to be
consistent.
There are also minor wording changes plus a small Sphinx/reST syntax fix
on the features list at the bottom (it was creating a definition list,
causing one line to be bold).
Thanks!
> [MRG+1] docs: update overview spider code to use toscrape.com and minor changes

- scrapy/shell.py
- tests/test_command_shell.py
Maybe it's just me but I'm always a bit annoyed to have to do `import scrapy` in the shell.
Thoughts?
> [MRG+1] Make scrapy available in shell without explicit import statement

- scrapy/extensions/feedexport.py
- tests/test_feedexport.py
Fixes GH-872
This prevents the `[` files when spider outputs nothing.
* with `FEED_STORE_EMPTY` as `False` (the default), this changes produces empty files
* with `FEED_STORE_EMPTY` as `True`, for JSON output, you get an empty list, and for XML, you get a empty top `<items>` element.
> [MRG+1] Feed exporter: start exporting only on first item

- scrapy/utils/log.py
Fixes GH-2125
Local tests:
with a pretty simple spider:
```
$ cat stdoutlogging/spiders/example.py 
import scrapy
class ExampleSpider(scrapy.Spider):
name = "example"
allowed_domains = ["example.com"]
start_urls = (
'http://www.example.com/',
)
print("hello!")
return {"somekey": "somevalue"}
```
and Python 3.5:
```
$ scrapy version -v
Scrapy    : 1.2.0dev2
lxml      : 3.6.0.0
libxml2   : 2.9.3
Twisted   : 16.4.0
Python    : 3.5.1+ (default, Mar 30 2016, 22:46:26) - [GCC 5.3.1 20160330]
pyOpenSSL : 16.1.0 (OpenSSL 1.0.2g-fips  1 Mar 2016)
Platform  : Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
```
Before this change:
```
$ scrapy crawl example -s LOG_STDOUT=1
2016-09-14 12:07:35 [scrapy] INFO: Scrapy 1.2.0dev2 started (bot: stdoutlogging)
2016-09-14 …
```
> [MRG+1] Add flush() method to StreamLogger

- docs/topics/architecture.rst
This is a small tweak for https://github.com/scrapy/scrapy/pull/2165: I found it hard to read "Data Flow" section because the picture was far from the description. So in this PR the explanation is moved right below the picture. After that it becomes harder to understand what do components mean, so I added links to them.
By the way, I think the overview doesn't explain correctly the difference between URLs and Requests. It says that spider returns URLs, and Engine converts them to Requests, but this is confusing - spider returns Requests.
> [MRG+1] DOC move Data Flow below the picture; add links to components

- scrapy/pipelines/files.py
- scrapy/pipelines/images.py
- scrapy/pipelines/media.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
if user has some custom subclass of Image pipeline and no setting for
this pipeline, he should get default settings defined for Image Pipeline.
Fixes #2198
> [MRG+1] [image & file pipeline] loading setting for user classes

- scrapy/core/scheduler.py
> Log warning when request cannot be serialized (instead of error)

- scrapy/utils/console.py
Hi,
This PR fixes an issue in `scrapy shell` command with IPython shell on attempt to import some new module and complete its name with `<TAB>`, like:
```python
>>> import srap<TAB>
```
The following traceback occurs:
```python
In [1]: import scrException in thread Thread-16:
File "/home/ahlin/.pyenv/versions/2.7.11/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/home/ahlin/.pyenv/versions/2.7.11/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/ahlin/.pyenv/versions/2.7.11/envs/scrape27/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 836, in run
completions = list(buffer.completer.get_completions(document, complete_event))
File …
```
> [MRG+1] Fix completion in `scrapy shell` for new imports

- docs/intro/examples.rst
The [Examples section](https://doc.scrapy.org/en/latest/intro/examples.html) in the documentation is outdated and it doesn't reflect the tutorial anymore.
This PR:
* replaces `dirbot` references with [quotesbot](https://github.com/scrapy/quotesbot), the new Scrapy project example;
* removes the reference to the [Snipplr scrapy tag](http://snipplr.com/all/tags/scrapy/), because it hasn't been very active in the last few years and the examples there are outdated.
> [MRG+1] Update examples section in documentation with quotes.toscrape spiders

- docs/topics/architecture.rst
This brings back the original loop in the architecture explanation, as per comment https://github.com/scrapy/scrapy/commit/3ac3ac4d925ee7ef1eb8be8dc6519606c0fbf9b0#commitcomment-19223839
> [MRG+1] architecture docs: restore explanation loop to step 1 (see comment in 3ac3ac4)

- docs/intro/install.rst
- docs/topics/ubuntu.rst
@ashkulz's https://github.com/scrapy/scrapy/pull/2166 on top of master branch.
This PR is to complement it with recommendation on using virtualenvs
Original description:
> [Official Ubuntu packages] are not currently updated and fail to install on Ubuntu 16.04.
> Also update the instructions to refer to the earliest supported LTS (Ubuntu 12.04).
Fixes #2137 and closes #2076
> [MRG+1] Deprecate official Ubuntu packages and update installation instructions

- scrapy/utils/project.py
- tests/test_utils_project.py
I ran into an issue trying to enable cache with `scrapy runspider`: the middleware gets disabled because it tries to create the `httpcache` directory inside a project data directory.
The [`utils.project.data_path`](https://github.com/scrapy/scrapy/blob/389882eb131250a1eb8418580b165625dd854bf0/scrapy/utils/project.py#L42) currently assumes that you're inside the project dir (maybe reasonably, since it's in the project module?).
I know this solution breaks compatibility a little bit, but IMO it would be solving a bug.
Btw, I noticed that this `data_path()` function is only being used by the HttpCacheMiddleware -- does it make sense to keep it as an util function?
> [MRG+1] Make data_path work when outside project (used by HttpCacheMiddleware and Deltafetch plugin)

- docs/news.rst
This is for the case #1581 gets merged for Scrapy 1.2 (which I hope it will). :)
> Update 1.2 release notes with data_path changes from #1581

- docs/news.rst
A small thing that has been bugging me for some time.
I don't understand why it happens but sections like this,
```
1.1.3 (2016-09-22)
------------------
```
ie. starting with digits, end up as https://doc.scrapy.org/en/latest/news.html#id1
Pre-prending "Scrapy ":
```
Scrapy 1.1.3 (2016-09-22)
-------------------------
```
generates more stable links: https://doc.scrapy.org/en/latest/news.html#scrapy-1-1-3-2016-09-22
> Change release section titles to have correct links in ToC

- scrapy/core/downloader/contextfactory.py
- scrapy/core/downloader/tls.py
Twisted default TLS options restricts the ciphers list a bit -- "a secure default"
https://github.com/twisted/twisted/blob/e38cc25a67747899c6984d6ebaa8d3d134799415/src/twisted/internet/_sslverify.py#L1861
We want to be a bit more permissive with Scrapy
(at least as permissive as Scrapy 1.0 was, and which used a default OpenSSL Context)
See https://www.openssl.org/docs/manmaster/apps/ciphers.html#CIPHER_STRINGS
OpenSSL's `DEFAULT` seems to be reasonable enough.
Fixes #2311
> [MRG+1] Use OpenSSL default ciphers

- docs/topics/item-pipeline.rst
The current example does not save the file properly if crawler is called from within a script since file object is never closed. 
related stackoverflow question: http://stackoverflow.com/questions/39821693/scrapy-print-pipeline-data-in-a-scripts-context
> [MRG+1] Fix JsonWriterPipeline example in docs

- docs/topics/spiders.rst
'Sup guys,
This adds a note to the documentation fixing the issue #2251 
Does it looks good?
Thnaks!
> [MRG+1] Added a note about invalid spider names in python 2 (fixes #2251)

- scrapy/downloadermiddlewares/redirect.py
- tests/test_downloadermiddleware_redirect.py
Fixes GH-2321
The idea is to not guess the encoding of "Location" header value
and simply percent-encode non-ASCII bytes,
which should then be re-interpreted correctly by the remote website
in whatever encoding was used originally.
See https://tools.ietf.org/html/rfc3987#section-3.2
This is similar to the changes to safe_url_string in
https://github.com/scrapy/w3lib/pull/45
> Do not interpret non-ASCII bytes in "Location" and percent-encode them

- docs/topics/architecture.rst
- docs/topics/downloader-middleware.rst
- docs/topics/spider-middleware.rst
> [MRG+1] Better explain middleware orders and processing directions

- docs/topics/request-response.rst
Adds documentation to resolve #2320
> [MRG+1] Added documentation about accessing header values

- docs/topics/spiders.rst
Am I being pedantic about wanting to change the word "constructor" to "initializer"?
> [MRG+1] doc: wording

- scrapy/core/engine.py
- scrapy/extensions/logstats.py
- tests/pipelines.py
- tests/test_crawl.py
Also add a test on state of looping task in LogStats extension.
Fixes #2011 and #2362
Before (scrapy 1.2.1 Python 2.7.12):
(with my test bogus pipeline from https://github.com/scrapy/scrapy/issues/2362#issuecomment-258451020
```
class CryptictracebacksPipeline(object):
def open_spider(self, spider):
a = int(spider)/0
def process_item(self, item, spider):
return item
```
)
```
$ scrapy crawl example
2016-11-07 16:51:52 [scrapy] INFO: Scrapy 1.2.1 started (bot: cryptictracebacks)
(...)
2016-11-07 16:51:52 [scrapy] INFO: Enabled item pipelines:
['cryptictracebacks.pipelines.CryptictracebacksPipeline']
2016-11-07 16:51:52 [scrapy] INFO: Spider opened
2016-11-07 16:51:52 [scrapy] INFO: Closing spider (shutdown)
Unhandled error in Deferred:
2016-11-07 16:51:52 [twisted] CRITICAL: Unhandled …
```
> Test Slot's heartbeat state before stopping it

- scrapy/http/response/__init__.py
- tests/test_http_response.py
Here is a implementation for the idea at #2264.
Before, for a binary response:
```
>>> response.text
File "<console>", line 1, in <module>
AttributeError: 'Response' object has no attribute 'text'
>>> response.css('body')
File "<console>", line 1, in <module>
AttributeError: 'Response' object has no attribute 'css'
```
After:
```
>>> response.text
File "<console>", line 1, in <module>
File "/home/elias/hacking/scrapinghub/scrapy/scrapy/http/response/__init__.py", line 91, in text
raise AttributeError("Response content isn't text")
AttributeError: Response content isn't text
>>> response.css('body')
File "<console>", line 1, in <module>
File …
```
> [MRG+1] Add better messages for when response content isn't text (closes #2264)

- scrapy/utils/console.py
The InteractiveShellEmbed class is a singleton
and we need to drop the instance with its clear_instance() method
to rebuild the instance from scratch with fresh environment
for each subsequent Scrapy's shell drop in.
> [MRG+1] Fix #396 re-triggered issue

- MANIFEST.in
This avoids to include compiled files in the templates directory.
Without this change, `pyc` files are included in the build:
```
$ find build | grep pyc
build/lib/scrapy/templates/project/module/__init__.pyc
build/lib/scrapy/templates/project/module/spiders/__init__.pyc
```
> [MRG+1] Ignore explicitly compiled python files.

- tests/test_spiderloader/__init__.py
The method `test_load_spider_module` was repeated twice (different tests).
> [MRG+1] TST: Fix duplicated test name.

- docs/topics/api.rst
- tests/test_spiderloader/__init__.py
- tests/test_spiderloader/test_spiders/nested/spider4.py
Spiders are loaded recursively from `SPIDER_MODULES` directories, so it's good to state that explicitly.
There is a change in the test about using `tempfile` module because this particular change in the test failed with `self.mktemp()`, I haven't found why.
> [MRG+1] DOC State explicitly that spiders are loaded recursively.	

- scrapy/spidermiddlewares/httperror.py
- tests/test_spidermiddleware_httperror.py
Fixes #910
May mean log spam for some users.
> [MRG+1] Raise log level for HttpErrorMiddleware to INFO (from DEBUG)

- setup.py
if the `parsel` version == 0.9.3 which is the lowest version scrapy needed in `setup.py`, there will be attribute error.
tested in ubuntu 16.04 python 2.7.12 and 2.7.6 with scrapy==1.1.0 and 1.2.2
upgrade to `parsel==0.9.5` as `requirements.txt` will fix this attribute error
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scrapy.selector import Selector
File "<stdin>", line 1, in <module>
File "scrapy/__init__.py", line 34, in <module>
from scrapy.spiders import Spider
File "scrapy/spiders/__init__.py", line 116, in <module>
from scrapy.spiders.feed import XMLFeedSpider, CSVFeedSpider
File "scrapy/spiders/feed.py", line 8, in <module>
from …
```
> [MRG+1] Fix/low parsel version number

- scrapy/spiderloader.py
- tests/test_spiderloader/__init__.py
Proposal fix for #2430
Example output:
```
$ scrapy version
/home/paul/src/scrapy/scrapy/spiderloader.py:36: RuntimeWarning: Could not load spiders from module 'version_wrong_spiders.spiderssss'; Check SPIDER_MODULES setting (exception: No module named spiderssss)
warnings.warn(msg, RuntimeWarning)
Scrapy 1.2.2
```
> [MRG+1] Warn user instead of failing for wrong SPIDER_MODULES setting

- docs/topics/commands.rst
- docs/topics/shell.rst
- scrapy/commands/fetch.py
- scrapy/commands/shell.py
- scrapy/shell.py
- scrapy/utils/datatypes.py
- scrapy/utils/testsite.py
- tests/test_command_fetch.py
- tests/test_command_shell.py
- tests/test_utils_datatypes.py
Fixes #2290
I added `--no-redirect` option to `scrapy fetch` and `scrapy shell` to revert to previous behavior.
To do:
> [MRG+1] Transparently handle redirections in fetch and shell

- scrapy/core/downloader/handlers/http11.py
This not only use the standard form but helps error aggregation
libraries (i.e.: Sentry) to avoid duplicating the message.
> [MRG+1] ENH Pass arguments to logger rather than formatted message.

- CODE_OF_CONDUCT.md
- README.rst
Attempt to address latest comments on https://github.com/scrapy/scrapy/issues/1645
The idea is we want to show people how to contribute before showing them the Code of Conduct (which should be obvious for most people).
> [MRG+1] Upgrade CoC and mention it after main contributing docs

- docs/topics/spiders.rst
I refer to https://github.com/scrapy/scrapy/blob/1.3/scrapy/spiders/__init__.py#L30
I'm too verbose and I need some feedback to start editing out.
Also, should we include something about calling `super()` in subclasses?
> [MRG+1] Document copying of spider arguments to attributes

- docs/topics/request-response.rst
The `formid` argument on `FormRequest.from_response` was added, but never documented.
> [MRG+1] Adding formid to FormRequest documentation

- artwork/README.rst
- docs/README.rst
- sep/README.rst
README files are not readable (well-formatted) inside github because of the missing extension, we can  also exclude them from sphinx build with `:orphan:`
> [MRG+1] Changing README to README.rst

- .travis.yml
https://packaging.python.org/distributing/#standards-compliance-for-interoperability
> [MRG+1] .devN release suffix must be preceded with a dot

- extras/scrapy.1
The word "intepreted" should be "interpreted".
> Fix spelling error in scrapy.1 manpage.

- scrapy/templates/project/module/settings.py.tmpl
`scrapy startproject myproject` creates a `pipelines.py` with an example Pipeline with already the name of the project, it only feels natural that this should also be the name on `settings.py` pipelines section.
> [MRG+1] settings: fixing name of the pipeline template

- docs/topics/downloader-middleware.rst
LevelDB was missing in https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.httpcache
> DOC mention LevelDB cache storage backend

- scrapy/resolver.py
Fixes #2461 
As [@rolando noticed](https://github.com/scrapy/scrapy/issues/2461#issue-197219248), `DNS_TIMEOUT` setting was never actually used by Scrapy with 14<=Twisted<=16.6, because a `(1, 3, 11, 45)` tuple was always passed to the DNS resolver by Twisted internally:
```
Successfully installed twisted-14.0.2
$ scrapy fetch --headers https://www.example.com -s DNS_TIMEOUT=15
2017-01-13 16:06:33 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: scrapybot)
2017-01-13 16:06:33 [scrapy.utils.log] INFO: Overridden settings: {'DNS_TIMEOUT': '15'}
(...)
CachingThreadedResolver.getHostByName(name='www.example.com', timeout=(1, 3, 11, 45))
2017-01-13 16:06:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.example.com> (referer: None)
Successfully installed twisted-15.5.0
$ scrapy …
```
> [MRG] Enforce DNS resolution timeout

- scrapy/settings/__init__.py
- tests/test_settings/__init__.py
Revisiting https://github.com/scrapy/scrapy/pull/743
Fixes https://github.com/scrapy/scrapy/issues/2517
> [MRG+1] Support 'True' and 'False' strings as boolean settings values

- docs/topics/commands.rst
- scrapy/commands/view.py
> [MRG] Fix view command against new --no-redirect option

- docs/topics/selectors.rst
- requirements.txt
- scrapy/http/response/text.py
- setup.py
- tests/test_http_response.py
Allow passing named variables and `namespaces` dict arguments on `.xpath()` shortcut, now that https://github.com/scrapy/parsel/pull/45 is merged
> [MRG] Support kwargs for response.xpath()

- tests/test_crawl.py
> Make DNS retry test compatible with Twisted 17+

- scrapy/downloadermiddlewares/redirect.py
`isinstance(response, HtmlResponse)` condition is already checked above; this is also visible in branch coverage [report](https://codecov.io/gh/scrapy/scrapy/src/3b8e6d4d820bf69ed3ad2e4d57eb6ca386323a5f/scrapy/downloadermiddlewares/redirect.py).
> [MRG+1] Cleanup MetaRefreshMiddleware: remove redundant check

- scrapy/item.py
- tests/test_item.py
Fixes https://github.com/scrapy/scrapy/issues/2511
Python 3.6 added simpler customization of class creation but this
requires to propagate correctly the __classcell__ attribute in custom
__new__ methods.
See https://docs.python.org/3.6/whatsnew/3.6.html#pep-487-simpler-customization-of-class-creation
Related:
https://github.com/django/django/pull/7653
https://bugs.python.org/issue23722
> [MRG+1] BUG: Fix __classcell__ propagation required in Python 3.6.

- scrapy/linkextractors/__init__.py
> LinkExtractor: don’t check all regexes if one of them matches

- scrapy/core/downloader/handlers/http.py
- tests/mockserver.py
- tests/test_downloader_handlers.py
- tests/test_downloadermiddleware_retry.py
> [MRG+1] Remove code required to support ancient twisted versions.

- scrapy/utils/conf.py
- tests/test_utils_conf.py
Fixes #2420
~Just as a side note, I am intentionally leaving out floats because different values would
be converted to the same `int` (for instance: `int(1.1) == int(1.2) == 1` is `True`)~
/cc @redapple, @vshlapakov
> [MRG+2] Validate numeric values (components order)

- docs/topics/request-response.rst
In my project I found that `return` made the spider terminate early, while `yield` worked as intended. `yield` is also used throughout other examples of the `parse` function in the documentation, so even if functionality is similar, using `yield` in this example improves consistency.
> [MRG+1] Use yield with nested parsing of responses

- scrapy/utils/reqser.py
- tests/test_utils_reqser.py
> [MRG+1] Preserve request class when converting to/from dicts (utils.reqser)

- scrapy/core/downloader/tls.py
- tox.ini
I've replaced try/except with explicit version checks and ported code to be compatible with Twisted 17+. This should fix https://github.com/scrapy/scrapy/issues/2555.
For the record, issue was caused by https://twistedmatrix.com/trac/ticket/8916.
Also, we no longer support Ubuntu 12.04, so its tox environment is replaced with Ubuntu 14.04 environment (we still don't run it on Travis though).
> Fixed compatibility with twisted 17+

- docs/topics/downloader-middleware.rst
- scrapy/downloadermiddlewares/httpproxy.py
- scrapy/settings/default_settings.py
- tests/test_downloadermiddleware_httpproxy.py
Fixes #2526
At first I implemented this using [`w3lib.http.basic_auth_header`](http://w3lib.readthedocs.io/en/latest/w3lib.html#w3lib.http.basic_auth_header) but then I realized that would ignore the [`HTTPPROXY_AUTH_ENCODING`](https://scrapy.readthedocs.io/en/latest/topics/downloader-middleware.html#httpproxy-auth-encoding) setting. Would it make sense to add an `encoding` parameter to `w3lib.http.basic_auth_header`?
Also, I'm not sure how to add a test for this, I think I would need to publish credentials, but it works with something like the following (from the scrapy shell):
```
from scrapy.http import Request
req = Request('http://example.org', meta={'proxy': 'https://APIKEY:@proxy.crawlera.com:8010'})
fetch(req)
```
/cc: @vezunch1k, @redapple
> [MRG+1] Use credentials from request.meta['proxy']

- tests/test_downloader_handlers.py
- tests/test_feedexport.py
- tests/test_spiderstate.py
- tests/test_webclient.py
This PR makes sure temp files are deleted in tests. It also fixes a **weird** pytest+OS X issue. Previously tests failed for me with exception like this:
```
______________________________________________ ERROR at setup of WebClientTestCase.test_Encoding ______________________________________________
cls = <class 'py._path.local.LocalPath'>, prefix = 'test_Encoding'
rootdir = local('/private/var/folders/_5/cbsg50991szfp1r9nwxpx8580000gn/T/pytest-of-kmike/pytest-0'), keep = 0, lock_timeout = None
def make_numbered_dir(cls, prefix='session-', rootdir=None, keep=3,
lock_timeout = 172800):   # two days
""" return unique directory with a number greater than the current
maximum one.  The number is assumed to start directly after prefix.
if keep is true directories with a number less than …
```
> [MRG+1] TST remove temp files and folders

- docs/topics/link-extractors.rst
- requirements-py3.txt
- requirements.txt
- scrapy/linkextractors/htmlparser.py
- scrapy/linkextractors/lxmlhtml.py
- scrapy/linkextractors/regex.py
- scrapy/linkextractors/sgml.py
- scrapy/utils/url.py
- setup.py
- tests/sample_data/link_extractor/sgml_linkextractor.html
- tests/test_linkextractors.py
- tests/test_linkextractors_deprecated.py
I thought this fixes #838, but after re-reading the issue it was not only about link extractors :) But LinkExtractors should be fixed anyways, because html5 rules are clear.
See also: https://github.com/scrapy/scrapy/issues/1614, https://github.com/scrapy/scrapy/pull/1021, https://github.com/scrapy/scrapy/pull/1603.
This PR conflicts with https://github.com/scrapy/scrapy/pull/2537 - when one of them is merged the other have to be fixed.
> [MRG+1] LinkExtractors: strip whitespaces

- requirements-py3.txt
- requirements.txt
- scrapy/http/request/form.py
- setup.py
- tests/test_http_request.py
~~It requires w3lib 0.17.0+, but I haven't bumped the requirement in this PR.~~
> [MRG+1] FormRequest: handle whitespaces in action attribute properly

- scrapy/spiders/crawl.py
I use scrapy-splash for javascript and sometimes want to change the request to another request  like splash one because it should be convenient using same logic for html after runing javascript.
scrapy-splash's request is following:
https://github.com/scrapy-plugins/scrapy-splash#examples
What do you think about that? Should I implement new spider?
> [MRG+1] Separate building request from _requests_to_follow in CrawlSpider

- docs/topics/exporters.rst
Closes #2553
~I left `XmlItemExporter` out of the modifications, it's the only class which does not seem to have problems writing to either `bytes` or `str` streams (`io.BytesIO` or `io.StringIO`, for instance).~
```
from io import BytesIO, StringIO
with BytesIO(b'') as f:
exporter = XmlItemExporter(f)
exporter.start_exporting()
exporter.export_item({'some': 'value'})
exporter.finish_exporting()
print(f.getvalue())
with StringIO(u'') as f:
exporter = XmlItemExporter(f)
exporter.start_exporting()
exporter.export_item({'some': 'value'})
exporter.finish_exporting()
print(f.getvalue())
```
outputs:
```
b'<?xml version="1.0" encoding="utf-8"?>\n<items><item><some>value</some></item></items>'
<?xml version="1.0" encoding="utf-8"?>
<items><item><some>value</some></item></items>
```
/cc @kmike
> [MRG+1] Doc: binary mode is required for exporters

- docs/topics/request-response.rst
This can make the spider fail due to incorrect values being posted server-side, which is extremely hard to debug because it is easy to miss leading/trailing whitespace, even with a logging proxy.
The fix was merged for lxml 3.8 in lxml/lxml#228 so document that as well.
> [MRG+1] document issue with FormRequest.from_response due to bug in lxml

- tests/test_utils_project.py
Temp folder can be a symlink on OS X; tests failed for me with this exception:
```
tests/test_utils_project.py F.
================================================================== FAILURES ===================================================================
_______________________________________________ ProjectUtilsTest.test_data_path_inside_project ________________________________________________
self = <tests.test_utils_project.ProjectUtilsTest testMethod=test_data_path_inside_project>
def test_data_path_inside_project(self):
with inside_a_project() as proj_path:
expected = os.path.join(proj_path, '.scrapy', 'somepath')
>           self.assertEquals(expected, data_path('somepath'))
E           AssertionError: '/var/folders/_5/cbsg50991szfp1r9nwxpx85800[31 chars]path' != …
```
> TST fixed ProjectUtilsTest on OS X

- README.rst
Badge doesn’t work, and Scrapy already works fine in Python 3
for practical purposes.
> remove “Python 3 progress” badge

- docs/topics/settings.rst
- scrapy/settings/default_settings.py
Fixes GH-2187.
This change is backwards-incompatible; it is not only about stats. For example, someone may have `MEMUSAGE_LIMIT_MB=...` in settings.py and rely on MEMUSAGE_ENABLED=1 passed as a command line argument to enforce the limit. We shouldn't do this change in 1.3 release cycle.
> Enable memusage extension by default.

- docs/intro/overview.rst
- docs/intro/tutorial.rst
- docs/topics/request-response.rst
- requirements-py3.txt
- requirements.txt
- scrapy/http/response/__init__.py
- scrapy/http/response/text.py
- setup.py
- tests/__init__.py
- tests/test_http_response.py
A proposed fix for https://github.com/scrapy/scrapy/issues/1940.
TODO:
> response.follow

- docs/topics/spiders.rst
- scrapy/spiders/__init__.py
- scrapy/utils/deprecate.py
- tests/spiders.py
- tests/test_engine.py
- tests/test_spider.py
> deprecate Spider.make_requests_from_url. 

- .bumpversion.cfg
I propose to remove the prerelease configuration from bumpversion, because I think its behavior is just too confusing.
The rationale for this is that making the release procedure predictable is more important than facilitating making pre-releases, which are sort of the exception in the workflow.
The current configuration makes most common cases confusing:
- bug fix releases require you have to remember to use `--serialize "{major}.{minor}.{patch}"`
- to start a pre-release cycle, you actually use `minor` or `patch`
- to do the actual minor or patch release, you use `prerel`
Also, `prerel` breaks if you run it on a branch with a final release, because it can't parse the prerelease information.
Therefore, I propose keeping the bumpversion defaults, and do the prereleases (dev1, dev2, rc1, …
> [MRG+1] Remove bumpversion prerelease configuration

- docs/topics/settings.rst
- scrapy/core/downloader/handlers/ftp.py
- scrapy/settings/default_settings.py
- tests/test_downloader_handlers.py
Fixes #2342
This patch adds 2 settings: `FTP_ANONYMOUS_USER` and `FTP_ANONYMOUS_PASSWORD` that are used as credentials when FTP requests do not have explicit `"ftp_user"` and `"ftp_password"` keys in `meta`.
Missings:
Note: Using `None` for "ftp_password" (or `FTP_ANONYMOUS_PASSWORD`) works in practice, but the FTP server from Twisted (which we use in download handler tests) requires a password to be sent, so I haven't added a test for this case. Does anyone know how we could test it?
> [MRG+1] Support Anonymous FTP

- scrapy/core/downloader/handlers/http11.py
Fixes #2491 
See https://github.com/scrapy/scrapy/issues/2491#issuecomment-272229679 for rationale.
A simple fix, but ideally, we'd want to use a proper HTTP parser.
Something for another PR I believe.
> [MRG] Buffer CONNECT response bytes from proxy until all HTTP headers are received

- scrapy/spidermiddlewares/httperror.py
- tests/test_spidermiddleware_httperror.py
Similar to https://github.com/scrapy/scrapy/pull/2543.
> [MRG+1] HttpErrorMiddleware stats

- scrapy/templates/project/module/middlewares.py.tmpl
“self” argument is omitted in some methods.
> Add omitted "self" arguments

- scrapy/templates/spiders/basic.tmpl
The default spider template mixes single and double quotes. This fixes that.
> [MRG+1] Use single quotes uniformly

- scrapy/downloadermiddlewares/retry.py
- scrapy/downloadermiddlewares/stats.py
- scrapy/utils/misc.py
- scrapy/utils/python.py
- scrapy/utils/response.py
- tests/test_downloadermiddleware_retry.py
- tests/test_proxy_connect.py
What do you think about providing retry counts in scrapy stats?
~~This PR is not backwards compatible for anyone who used `RetryMiddleware.__init__` directly.~~
> [MRG+1] Retry stats

- scrapy/core/downloader/handlers/ftp.py
- tests/py3-ignores.txt
- tests/test_downloader_handlers.py
FTP support on Python 3 is available again with Twisted 17.1+
> Fix FTP downloader and re-enable FTP tests on Python 3

- docs/topics/request-response.rst
- docs/topics/settings.rst
- scrapy/core/downloader/handlers/http11.py
- scrapy/settings/default_settings.py
- tests/test_downloader_handlers.py
Websites that return a wrong ``Content-Length`` header may cause a data
loss error. Also when a chunked response is not finished properly.
This change adds a new setting ``DOWNLOAD_FAIL_ON_DATALOSS`` (default: ``True``) and request.meta key ``download_fail_on_dataloss``.
---
Related issues:
* https://github.com/scrapy/scrapy/issues/2513
* https://github.com/scrapy/scrapy/issues/2586
* https://github.com/scrapy/scrapy/pull/2493
* https://github.com/scrapy/scrapy/issues/2413
> [MRG+2] Handle data loss gracefully.

- docs/topics/link-extractors.rst
- scrapy/linkextractors/__init__.py
- scrapy/linkextractors/lxmlhtml.py
- scrapy/linkextractors/sgml.py
- tests/sample_data/link_extractor/sgml_linkextractor.html
- tests/test_http_response.py
- tests/test_linkextractors.py
- tests/test_linkextractors_deprecated.py
A fix for #1941 and #1982.
TODO:
> [MRG+1] Set canonicalize=False for LinkExtractor

- docs/topics/request-response.rst
- docs/topics/spider-middleware.rst
- scrapy/settings/default_settings.py
- scrapy/spidermiddlewares/referer.py
- scrapy/utils/url.py
- tests/test_spidermiddleware_referer.py
- tests/test_utils_url.py
Fixes #2142
I've based the tests and implementation on https://www.w3.org/TR/referrer-policy/
By default, with this change, `RefererMiddleware` does not send a `Referer` header (referrer value):
- when the source response is `file://` or `s3://`,
- nor from `https://` response to an `http://` request.
However, it does send a referrer value for any `https://` to another `https://` (as browsers do, [`"no-referrer-when-downgrade"` being the default policy](https://www.w3.org/TR/referrer-policy/#referrer-policy-no-referrer-when-downgrade))
This needs discussion.
User can change the policy per-request, using a new `referrer_policy` meta key, with values from "no-referrer" / "no-referrer-when-downgrade" / "same-origin" / "origin" / "origin-when-cross-origin" / "unsafe-url".
~~Still missing:~~ …
> [MRG] Referrer policies in RefererMiddleware

- scrapy/core/engine.py
The `slot.add_request(request)` in `download()` is also done in `_download()` which is called right after.
> Remove redundant slot.add_request() call in ExecutionEngine

- scrapy/downloadermiddlewares/httpcompression.py
- tests/test_downloadermiddleware_httpcompression.py
> [MRG] Use body to choose response type after decompression content

- scrapy/downloadermiddlewares/httpcompression.py
- scrapy/spiders/sitemap.py
- scrapy/utils/gz.py
- tests/test_downloadermiddleware_httpcompression.py
- tests/test_spider.py
Let SitemapSpider handle decoding of .xml.gz files if necessary.
Fixes #2389
The change here is to always decompress responses with `Content-Encoding: gzip`, whatever `Content-Type` says, and contrary to https://github.com/scrapy/scrapy/issues/193#issuecomment-12844809, #660, #2065
Therefore, SitemapSpider still has to decode "real" .gz files/content if the HTTP response was not "Content-Encoded", relying on gzip magic number instead of response headers.
I believe it follows [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.2.2) better:
> The "Content-Encoding" header field indicates what content codings
>    have been applied to the representation, beyond those inherent in the
>    media type, and thus **what decoding mechanisms have to be applied in
>    order to obtain data in …
> [MRG] Always decompress Content-Encoding: gzip at HttpCompression stage

- docs/contributing.rst
> [MRG+1] Removed contrib section in contribution documentation

- scrapy/downloadermiddlewares/httpcache.py
- scrapy/extensions/httpcache.py
> [MRG+1] [logging] HttpCacheMiddleware: log cache directory at instantiation

- scrapy/crawler.py
- scrapy/utils/log.py
- tests/test_crawl.py
- tests/test_crawler.py
See #1612: ~~this uses ``self.settings`` instead of ``settings``, as elsewhere in the crawler init.~~
Main change is that now a new root logger is installed when a crawler is created if one was already installed before. This allows to respect custom settings related to logging, such as LOG_LEVEL, LOG_FILE, etc.
As the result, in case of several spiders, logging settings from the last spider take precedence. Without this change, all logging settings in ``custom_settings`` are ignored. Both behaviours are not great, but it seems that in most cases there is just one spider running in the process, so the new behaviour seems less bad, but it's a tough call.
> [MRG+1] Respect custom log level: fixes GH-1612

- docs/intro/install.rst
Hey fellows,
As I commented in #2475 , I've installed Windows in a VM to test Scrapy installation.
Sure enough, Conda seems the easiest way, I've had no problems at all with it.
As for PyPI, I was unable to test it: I couldn't even get Python to work without Anaconda (CPython installation kept freezing). :(
Anyway, I know this is just a data point, but given the trouble that is installing and compiling stuff on Windows, I think it makes sense to mention the conda option right in the beginning and to remove all the complication about setting up Python on Windows.
What do you think?
> [MRG+2] docs: installation instructions, mention conda in the beginning (closes #2475)

- docs/topics/settings.rst
- scrapy/commands/list.py
- scrapy/commands/runspider.py
- scrapy/commands/settings.py
- scrapy/commands/startproject.py
- scrapy/commands/version.py
- scrapy/settings/default_settings.py
- scrapy/spiderloader.py
- tests/test_spiderloader/__init__.py
Related to https://github.com/scrapy/scrapy/pull/2433#issuecomment-281377231
> [MRG] Add SPIDER_LOADER_WARN_ONLY to toggle between spiderloader failure or warning

- scrapy/pipelines/files.py
More specific exception catching: [os.path.getmtime](https://docs.python.org/2/library/os.path.html#os.path.getmtime) can only raise [os.error](https://docs.python.org/2/library/os.html#os.error).
> [MRG+1] Fixed the FIXME in FSFilesStore

- scrapy/utils/datatypes.py
- tests/test_utils_datatypes.py
CaselessDict can process sequence of general Mapping/MutableMapping class or subclass of Mapping.
Documentations both for Python 2 and Python 3 declare that all instances of `Mapping` class have `items()` method, so it's safely to generalize check from `isinstance(seq, dict)`. 
Real usage example: `requests` package returns responses which headers are instances of `requests.structures.CaseInsensitiveDict` that is subclass of `MutableMapping` and this patch allows to pass these headers directly to `scrapy.Response` initializer.
> [MRG+1] Allowed passing objects of Mapping class or its subclass to the CaselessDict initializer

- scrapy/logformatter.py
- tests/test_logformatter.py
pass 'flags' kwarg to logger so that it is compatible with old format of CRAWLEDMSG. fixes #2647
> [MRG+2] [logformatter] 'flags' format spec backward compatibility

- scrapy/cmdline.py
Remove "commands" from the command list (the one that gets printed when you type e.g. "scrapy" in the command line), since that is the baseclass of all commands and cannot be executed.
> [MRG+1] command-list-fix

- LICENSE
Spotted while developping a license recognizer þ It was breaking my paragraph splitting (now fixed).
> [PEDANTIC] FIX trailing whitespaces in LICENSE.

- docs/topics/settings.rst
I'm a novice scrappy user and I noticed the documentation does not mention how to disable duplicate request filtering in the settings.
This was useful to me recently as a command line option to a spider.
I also added a warning to consider using the dont_filter parameter of Request instead.
> [MRG+1] Mention how to disable request filtering in documentation of DUPEFILTER_CLASS setting

- docs/README.rst
- docs/requirements.txt
- tox.ini
Concerns Sphinx 1.4 release #1893 . `sphinx_rtd_theme` has to be installed manually.
> [MRG+1] Add sphinx_rtd_theme to docs setup readme

- docs/topics/link-extractors.rst
This PR adds the missing word "from" that makes up statement 
```python
from scrapy.linkextractors import LinkExtractor
``` 
in link-extractor's documentation.
> [MRG+1] doc: fix documentation error in link-extractor.rst

- docs/topics/item-pipeline.rst
python: 3.6.0rc2
scrapy: 1.3.0
output:
```
TypeError: a bytes-like object is required, not 'str'
```
> Fix doc: open file with "wb" mode will get an error in python 3

- docs/topics/exporters.rst
- docs/topics/feed-exports.rst
- scrapy/exporters.py
- scrapy/extensions/feedexport.py
- scrapy/settings/default_settings.py
- tests/test_feedexport.py
Hello folks, these are my two cents to fix #1327.
I look forward to reading your comments 😄
> [MRG+1] Feed exports: beautify JSON and XML

- docs/topics/request-response.rst
- scrapy/http/request/form.py
- tests/test_http_request.py
Implements #667.  `FormRequest.from_response` is very helpful, but sometimes it includes a field that you would like to remove.  With this change, you can include a field with value `None` in `formdata` when calling `from_response`, and the field will be omitted from the body of the returned request.
> [MRG+1] Allow dropping field in from_response formdata

- docs/topics/downloader-middleware.rst
- docs/topics/request-response.rst
- scrapy/downloadermiddlewares/retry.py
- tests/test_downloadermiddleware_retry.py
Allows the user to set `RETRY_TIMES` per request using `request.meta` key `max_retry_times`.
Recommended in #2642
> [MRG+1] Add feature to set RETRY_TIMES per request (#2642)

- scrapy/__main__.py
This pull-request enable execute scrapy from python module.
```
python -m scrapy
```
On windows, this probably works, too. Although I did not test because I do not have Windows
```
py -3 -m scrapy
```
> [MRG+1] Add support for executing scrapy using -m option of python

- docs/topics/spiders.rst
Added a note to allowed_domains attribute, reminding users not to add urls into the list.
> [MRG+1] Update spiders.rst

- docs/topics/commands.rst
- docs/topics/settings.rst
- scrapy/cmdline.py
- scrapy/commands/edit.py
- scrapy/settings/default_settings.py
Avoid loading settings from Environment in scrapy core.
(Then it's not a _default setting_ but a user-defined one, by definition.)
Instead it's better to populate them from the starting shell or an embedding script.
Plug: noticed this while in the mindset of scrapy as a library (https://github.com/scrapy/scrapy/issues/1777#issuecomment-189419147).
> [MRG+1] Remove dependency on os.environ from default settings

- scrapy/pipelines/images.py
- tests/test_pipeline_images.py
Images with transparency using palette mode (pillow mode = "P") fails when converting to jpg. The resulting image will have a green background instead of white as expected.
By converting mode P images to RGBA before pasting into the white background and then converting the resulting image to RGB will fix the problem.
See #2452
> [MRG+1] Fixes conversion of transparent PNG with palette images to jpg #2452

- codecov.yml
Codecov moved from settings defined in UI to settings defined in codecov.yml file.
In this file I'm disabling project coverage check, because it is fine for project coverage % to decrease - it may happen if you e.g. remove unneeded code. Patch coverage is what is important.
> tweak coverage reports

- docs/contributing.rst
- docs/index.rst
This is part of the migration process from the scrapy-users mailing list to http://reddit.com/r/scrapy
> Include references to Scrapy subreddit in the docs

- .travis.yml
- scrapy/cmdline.py
- scrapy/extensions/httpcache.py
- scrapy/utils/python.py
- setup.py
- tests/test_loader.py
- tests/test_squeues.py
- tests/test_utils_python.py
- tox.ini
Individual commits have explanations for why they are needed. They are mostly independent, they are either garbage collection related, or concerning some corner cases.
This also installs PyPyDispatcher library - it's an experimental PyDispatcher fork with PyPy support (https://github.com/lopuhin/pydispatcher) - I intend to make it less experimental first.
> Fix PyPy test failures

- scrapy/resolver.py
- tests/test_commands.py
Fixes #2811 
I tried to build a test using `scrapy.utils.testsite.SiteTest` to connect succesfully to a server instead of https://github.com/scrapy/scrapy/pull/2816/commits/1f08d9a64884a05a541fe9649e3349cce5aa47be, but I could not get it to work.
> Fix DNS resolver when DNSCACHE_ENABLED=False

- scrapy/commands/parse.py
- scrapy/http/request/__init__.py
- tests/test_http_request.py
- tests/test_utils_reqser.py
This PR intends to fix https://github.com/scrapy/scrapy/issues/2766.
When users pass a string to `Request.__init__`'s `callback` parameter, they end up getting a Twisted exception, which doesn't help to uncover this, which is a rather simple issue.
This PR changes that, so that users get a proper message when passing something that's not callable to the `callback` and `errback` parameters.
> [MRG+1] Add verification to check if Request callback is callable

- docs/topics/spiders.rst
I was confused by the `headers` description, so this is my attempt to make it clearer.
> [MRG+1] Tweak the CSVFeedSpider documentation

- docs/topics/exceptions.rst
- docs/topics/signals.rst
> [MRG+1] Added doc for `scrapy.exceptions.DontCloseSpider`. Also fixes inaccurate doc for `scrapy.signals.spider_idle`.

- scrapy/shell.py
Currently the `spider` variable is not populated when using `scrapy.inspect_response`. It can be accessed through `crawler.spider`, but I think this could still be useful.
Before:
```
2017-07-03 11:07:18 [scrapy.core.engine] INFO: Spider opened
2017-07-03 11:07:18 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f5c17d50c50>
[s]   item       {}
[s]   request    <GET http://www.example.org>
[s]   response   <200 http://www.example.org>
[s]   settings   <scrapy.settings.Settings object at 0x7f5c17d508d0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help) …
```
> Populate spider variable when using shell.inspect_response

- scrapy/downloadermiddlewares/redirect.py
- tests/test_downloadermiddleware_httpcache.py
- tests/test_downloadermiddleware_redirect.py
> Handle HTTP 308 Permanent Redirect

- extras/qpsclient.py
> [MRG+1] xrange() --> range() for Python 3

- scrapy/commands/version.py
- scrapy/utils/log.py
- scrapy/utils/versions.py
This is an example startup log with this patch:
```
$ scrapy shell
2017-07-27 17:22:09 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: scrapybot)
2017-07-27 17:22:09 [scrapy.utils.log] INFO: Versions: lxml 3.7.3.0, libxml2 2.9.3, cssselect 1.0.1, parsel 1.2.0, w3lib 1.17.0, Twisted 17.1.0, Python 2.7.12+ (default, Sep 17 2016, 12:08:02) - [GCC 6.2.0 20160914], pyOpenSSL 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016), Platform Linux-4.8.0-59-generic-x86_64-with-Ubuntu-16.10-yakkety}
2017-07-27 17:22:09 [scrapy.utils.log] INFO: Overridden settings: {'LOGSTATS_INTERVAL': 0, 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter'}
```
@kmike , were you thinking of something like this?
> Log versions information at startup

- scrapy/templates/project/module/middlewares.py.tmpl
- scrapy/templates/project/module/settings.py.tmpl
While testing downloader middleware with media pipeline (for https://github.com/scrapy/scrapy/issues/2753#issuecomment-303678711), I looked for a sample downloader middleware and found only a spider middleware template.
I personally never remember what methods to implement, nor what they should return, hence the verbose comments in the template.
Related/alternative https://github.com/scrapy/scrapy/issues/2633
> [MRG+1] Add template for a downloader middleware

- scrapy/utils/python.py
fixes #2862
I also ran `tox` for the tests, but there are slight differences for the packages used inside the library, so in `tests/requirements.txt`:
- `netlib` can be easily updated to `0.17` to support both py2 and py3
- `mitmproxy` on the other hand can't w/o some modifications; its version `0.18+` that supports both py3 and py2 doesn't contain `libmproxy` that's used in `tests/test_proxy_connect.py`. So yea, related to https://github.com/scrapy/scrapy/issues/2545 actually, so nevermind.
Other than that issue, everything worked fine, no errors for py2 nor py3.
Also I tested the branch in our project and the `DeprecationWarning` has disappeared now :).
> Use getfullargspec under the scenes for py3 to stop DeprecationWarning

- tests/test_cmdline/__init__.py
- tests/test_downloader_handlers.py
- tests/test_downloadermiddleware_cookies.py
- tests/test_downloadermiddleware_defaultheaders.py
- tests/test_downloadermiddleware_downloadtimeout.py
- tests/test_downloadermiddleware_httpauth.py
- tests/test_downloadermiddleware_httpcompression.py
- tests/test_downloadermiddleware_httpproxy.py
- tests/test_downloadermiddleware_redirect.py
- tests/test_downloadermiddleware_useragent.py
- tests/test_http_cookies.py
- tests/test_http_request.py
- tests/test_loader.py
- tests/test_pipeline_images.py
- tests/test_selector.py
- tests/test_spider.py
- tests/test_spidermiddleware_depth.py
- tests/test_spidermiddleware_httperror.py
- tests/test_spidermiddleware_offsite.py
- tests/test_spidermiddleware_referer.py
- tests/test_spidermiddleware_urllength.py
- tests/test_urlparse_monkeypatches.py
- tests/test_utils_datatypes.py
- tests/test_utils_defer.py
- tests/test_utils_iterators.py
- tests/test_utils_misc/__init__.py
- tests/test_utils_project.py
- tests/test_utils_python.py
- tests/test_utils_signal.py
- tests/test_webclient.py
- change ``failIf`` to ``assertFalse``
- change ``asertEquals`` to ``assertEqual``
- change ``assert_`` to ``assertTrue``
https://docs.python.org/2/library/unittest.html#deprecated-aliases
> Update deprecated test aliases

- scrapy/spiders/__init__.py
- tests/test_spider.py
The scrapy parse method raises a NotImplementedError when not defined,
but for new comers it can be hard to debug what might be going wrong.
Adding an explicit message for NotImplementedError will help new users.
Refer #2831
> [MRG+1] Explicit message for scrapy parse callback

- scrapy/crawler.py
- scrapy/utils/log.py
Fixes https://github.com/scrapy/scrapy/issues/1343
Proposal for https://github.com/scrapy/scrapy/issues/1343.
The idea here is to keep `log_scrapy_info()` only with Scrapy-framework related stuff,
and move settings and custom settings logging closer to where the framework is instantiated to perform a crawl (Crawler, Engine etc)
> Move logging of overriden settings to Crawler init

- docs/conf.py
- docs/utils/linkfix.py
Fixes #2891 
* `ur'string'`is converted to `u'string'`in Python 2.
* `ur'string'`is a syntax error in Python 3.
> ur'string' not needed in Py 2, syntax error in Py3

- .travis.yml
PyPy changed naming convention since 5.8 release, not it's called pypy2.7-x.x.x
This fixes #2934
> Update pypy version regexp to get last release

- scrapy/commands/version.py
- scrapy/utils/versions.py
- tests/test_command_version.py
`scrapy version -v` does not currently output `cryptography` version, which can be useful.
I've added a `try/except` when reading cryptography's version because I don't know when it became a dependency of `pyOpenSSL`. But it may be fine to remove it.
Scrapy's current baseline of Debian Jessie uses `pyOpenSSL==0.14` and `cryptography==0.6`
> Print cryptography package version

- docs/topics/request-response.rst
Noted by `gr3yh47` in `#scrapy` IRC channel.
> [Doc] Update Response.body type

- docs/topics/media-pipeline.rst
- scrapy/pipelines/files.py
- scrapy/pipelines/images.py
- scrapy/utils/test.py
- tests/test_pipeline_files.py
- tox.ini
* Fixes #685
* [FilesPipeline](https://scrapy.readthedocs.io/en/stable/topics/media-pipeline.html#using-the-files-pipeline) support for Google Cloud Storage.
* This feature use two setting values.
* FILES_STORE = 'gs://your_bucket/'
* GCS_PROJECT_ID = 'your_project_id'
* Using [google-cloud-storage](https://cloud.google.com/storage/docs/reference/libraries) as optional dependency. For information about authenticating, see [this page](https://cloud.google.com/docs/authentication/production).
* Added some tests and passed. (the last line)
```bash
(venv) ~/github/scrapy/scrapy % GCS_PROJECT_ID="myproject" GCS_TEST_FILE_URI="gs://my-bucket/" tox -- tests/test_pipeline_files.py -v
...
tests/test_pipeline_files.py::FilesPipelineTestCase::test_file_expired <- …
```
> [MRG+2] Fixes #685 FilesPipeline support for Google Cloud Storage.

- docs/topics/email.rst
- scrapy/mail.py
twisted.mail.smtp was ported to Python 3 in this patch: https://github.com/twisted/twisted/pull/509
It is not in Twisted 17.1.0, but should be in the next released version of Twisted.
Fixes: https://github.com/scrapy/scrapy/issues/2375
> [MRG+1] ESMTPSenderFactory compatibility for Python 3

- docs/intro/tutorial.rst
Added middlewares.py to accurately reflect the file structure created by "scrapy startproject tutorial"
> Update tutorial.rst startproject files

- docs/topics/extensions.rst
Reference: https://web.archive.org/web/20170203104051/http://www.ferg.org/papers/debugging_in_python.html
> Link "Debugging in Python" article to its new location

- scrapy/linkextractors/__init__.py
Add m4v extension (video) to `IGNORED_EXTENSIONS` in LinkExtractor so it can be ignored by default in the same way other video formats are already ignored.
fix #2928
> [MRG+1] Add m4v extension to IGNORED_EXTENSIONS in LinkExtractor.

- scrapy/core/downloader/handlers/http11.py
Changed the warning message to give information about the request generating it
as requested in: [#2927](https://github.com/scrapy/scrapy/issues/2927)
Tested with spider:
```
import scrapy
class QuotesSpider(scrapy.Spider):
name = "test_spider"
custom_settings = {
'DOWNLOAD_WARNSIZE': '123',
}
def start_requests(self):
urls = [
'http://example.com',
]
for url in urls:
yield scrapy.Request(url=url, callback=self.parse)
page = response.url.split("/")[-2]
filename = 'test_spider-%s.html' % page
with open(filename, 'wb') as f:
f.write(response.body)
self.log('Saved file %s' % filename)
```
Which gives the requested warning message:
```
2017-10-05 15:41:01 [scrapy.core.downloader.handlers.http11] WARNING: Expected response size (606) larger than download warn size …
```
> [MRG+1] Changed unhelpful log message from core.downloader.handlers.http11

- README.rst
- artwork/README.rst
- docs/contributing.rst
- docs/faq.rst
- docs/intro/install.rst
- docs/intro/overview.rst
- docs/intro/tutorial.rst
- docs/topics/debug.rst
- docs/topics/deploy.rst
- docs/topics/firebug.rst
- docs/topics/firefox.rst
- docs/topics/jobs.rst
- docs/topics/loaders.rst
- docs/topics/media-pipeline.rst
- docs/topics/practices.rst
- docs/topics/request-response.rst
- docs/topics/selectors.rst
- docs/topics/settings.rst
- docs/topics/shell.rst
- docs/topics/spiders.rst
- extras/coverage-report.sh
I have manually followed all the http links in docs and converted them to https wherever possible. 
I didn't touch links for docs.scrapy.org, scrapy.org and sub-domains of it. Shall we convert them to https too?
> Use https for external links wherever possible in docs

- docs/topics/exporters.rst
Addresses #2932
@kmike pointed out that the concept of a file-per-spider no longer made sense, so I changed the use case to one inspired by my own experience. It's maybe a little more complicated than the previous example, but it still comes out to fewer lines of code after removing the overhead of manually connecting the signals.
> [MRG+1] Revise/modernize item exporter example in docs

- docs/topics/downloader-middleware.rst
- docs/topics/spider-middleware.rst
Fixing issue #3019 by adding the `from_crawler` classmethod to the documentation of middlewares to make this feature more visible.
> [MRG+1] Added from_crawler to middleware docs

- docs/topics/commands.rst
- scrapy/commands/parse.py
- tests/test_command_parse.py
This should fix [issue 2883](https://github.com/scrapy/scrapy/issues/2883) which I opened a couple of months ago. 
The gist of this commit is to allow the ability to pass extra meta data onto a request.
Example:
scrapy parse --callback=parse_category_page --meta='{"category" : "electronics", "sub-category" : "tablets"}' "https://some-ecommerce-website.com/electronics-38df9s9/tablets-3fsfs8"
```python
... some spider code
def parse_category_page(self, response):
category = response.meta.get('category', None)
sub_category = response.meta.get('sub-category', None)
yield {'product_name' : 'ipad' , 'category' : category, 'sub_category' : sub_category}
... more spider code
```
The idea is that as you start testing out your spider individual parsing methods, you want to inject custom values to …
> [MRG+1] Scrapy Command: add --meta/-m to the "parse" command to pass additional meta data into the request

- docs/contributing.rst
* suggest Stack Overflow for Scrapy usage questions;
* encourage users to submit test-only pull requests with reproducable examples;
* encourage users to pick up stalled pull requests;
* we don't use AUTHORS file as a main acknowledgement source;
* suggest using Sphinx autodocs extension
What do you think @dangra @eliasdorneles @cathalgarvey @redapple?
> DOC update "Contributing" docs

- docs/faq.rst
- docs/intro/install.rst
As discussed in #2213, mention that we have PyPy support, and describe installation issues. I put PyPy section at the end, along with platform issues, although it's not strictly a platform.
~~I discovered one issue though that I'll try to resolve in another PR: right now pypy-specific dependency PyPyDispatcher is never picked up. A way to check and a workaround is also in the docs, but not everyone reads them so I'd like to try fixing this before release.~~
> [MRG+1] Mention PyPy support, add PyPy to install docs

- .travis.yml
- docs/faq.rst
- docs/intro/install.rst
- tests/test_utils_python.py
- tox.ini
Just checking how they run on Travis. Turns out that lxml on PyPy3 is no longer a problem (``PyPy 5.9.0``, ``Cython==0.27.3`` and ``lxml==4.1.1``).
Related to #2213
> Add PyPy3 support

- docs/topics/downloader-middleware.rst
Add mention to dont_merge_cookies in the Documentation of CookiesMIddlewares issue: #2999
> Add mention to dont_merge_cookies in CookiesMiddlewares docs (#2999)

- tests/test_http_response.py
Currently tests are failing because of behavior change introduced in https://github.com/scrapy/w3lib/pull/101.
> Fix tests to account for changes in w3lib 1.19

- scrapy/utils/ossignal.py
Using Ctrl-C to stop Scrapy when running it on Python 2 leads to this message:
`Received SIGINT, shutting down gracefully. Send again to force`
However, on some Python 3 versions (at least Python 3.5 and 3.6) Scrapy does not correctly detect the SIGINT signal:
`Received SIG_SETMASK, shutting down gracefully. Send again to force` 
Some constants defined in the signal module need to be skipped in order to filter only the signals.
For reference:
https://github.com/python/cpython/blob/master/Lib/signal.py
> [MRG+1] Fix OS signal names

- scrapy/downloadermiddlewares/robotstxt.py
What do you think about adding mor stats for robots.txt middleware?
* `robotstxt/forbidden` is a number of requests forbidden by robots.txt;
* `robotstxt/request_count` is a number of requests to fetch robots.txt files;
* `robotstxt/response_count` and `robotstxt/response_status_count/..` are robots.txt response counts;
* `robotstxt/unicode_error_count` is a number of robots.txt files with broken unicode;
* `robotstxt/exception_count/..` is a number of exceptions (download errors, parse errors).
> [MRG+1] more stats for RobotsTxtMiddleware

- requirements.txt
- scrapy/squeues.py
- setup.py
- tests/test_squeues.py
~This addresses #3054 partially, as it catches the exception raised by `pickle`.
However, since this exception is only raised in python >= 3.6, for earlier versions it's still not able to realize it shouldn't serialize some requests.~
Fixes #3054.
~Added a monkey patch to prevent the pickling of `lxml.html.HtmlElement` objects.~
Updated: raise an exception when pickling Selector/SelectorList objects (https://github.com/scrapy/parsel/pull/108), catch it in the queue.
> [MRG+1] Do not serialize unpickable objects (py3)

- scrapy/extensions/telnet.py
Hey,
What do you think about using INFO log level for displaying telnet host/port information? 
In production log level is often changed to INFO+. At the same time, a concrete telnet port is chosen from a range of ports. It means that log may be useless when someone wants to figure out how to connect to a running production spider, and Scrapy doesn't announce this port by other means.
I can also imagine that using INFO can raise awareness of users of this feature; some may want to disable it after realizing Scrapy is starting a telnet server by default, and some may do the opposite and start using the feature.
> [MRG+1] use INFO log level to show telnet host/port

- scrapy/downloadermiddlewares/robotstxt.py
Add message to IgnoreRequest exception so that it can be detectedin the errbak method of a spider
> [MRG+1] Update robotstxt.py

- docs/_ext/scrapydocs.py
- docs/conf.py
- docs/requirements.txt
Don't use deprecated sphinx options and imports, to fix the build with sphinx 1.7
> fix docs building on CI

- docs/contributing.rst
> Updated contributing.rst

- scrapy/http/response/__init__.py
- tests/test_http_response.py
the issue reason should be: 'urljoin from urllib return baseurl if targeturl is None'
the empty url issue haven't been touched because @kmike says: 'this is an intended behavior.'
> [MRG+1] Fix part of issue #3128 - None should not be a valid type for 'url' in Response.follow

- scrapy/linkextractors/__init__.py
flv extension is missing. I run into downloading large .flv file while scraping.
> [MRG+1] Add 'flv' to ignored video extensions.

- scrapy/http/request/form.py
- tests/test_http_request.py
> [MRG+1] Fixed bug FormRequest.from_response() clickdata ignores input[type=image]

- docs/topics/downloader-middleware.rst
- docs/topics/request-response.rst
I just wanted to make the description flow a little better and also add the `reqmeta` for better linking.
> [MRG+1] Doc: update wording for COOKIES_ENABLED

- docs/topics/loaders.rst
I came across this earlier today, and after quite some (result-less) debugging, google led me to #2735 . Hopefully this improvement can help others avoid this pitfall.
> [MRG+1] Improve document about functions as processors

- docs/contributing.rst
Corrected minor grammatical issues and increased clarity of instructions.
> Minor edits to contributing.rst

- docs/topics/spider-middleware.rst
The return iterable of `process_spider_exception` should contain `scrapy.http.Request`, not `scrapy.http.Response`.
> [MRG+1] fix a mistake in topic spider-middleware.rst

- scrapy/utils/gz.py
Copied from discussion on #3270 , partial fix for #2658 
**Problem**
gunzip method runs forever for big files in python 3
bytes in Python 3 does not include string concatenation improvements that Python 2 has, effectively making the following take forever:
```
%%time
out = b""
for x in range(10000):
out += b"." * 8000
```
**Solution** 
Improve the gunzip method to not copy the entire output string in each iteration, but instead append to list + join, significantly improving performance from  O(n^2)
Thanks @kmike for your help debugging!
> [MRG+2] Improve gunzip performance for big files on Python 3

- scrapy/http/cookies.py
So it matches the signature of the underlying [`http.cookiejar.CookieJar.clear`](https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.CookieJar.clear) object.
> [MRG+2] Added: Allowing optional arguments for `scrapy.http.cookies.CookieJar.clear`

- docs/topics/leaks.rst
Add Python3 tools description.
see detail here; https://github.com/scrapy/scrapy/issues/3282
> [MRG+1] Update debugging memory leaks section in the docs

- tests/test_downloadermiddleware_httpproxy.py
As the title said, fix the test case name.
> [MRG+1] fix the test case name of HttpProxyMiddleware

- docs/topics/feed-exports.rst
The documentation of the S3 storage backend (https://doc.scrapy.org/en/latest/topics/feed-exports.html#s3) suggest the use of the libraries botocore (https://github.com/boto/botocore) or boto (https://github.com/boto/boto). However, boto library will work only if the user is using Python 2 (as it is correctly explained here https://doc.scrapy.org/en/latest/topics/feed-exports.html#storages).
Besides the fact of this information is there, I believe that it would be better for the user reading the documentation to have this note also inside the specific section of S3 storage backend.
When issue #1866 is resolved, this could be removed anyway.
> [MRG+1] Improve docs of S3 Storage to make Python version more explicit

- tests/requirements.txt
Make the version of ipython less than 6.0 in python 2.7, since ipython stop supporting python 2.7 in >= v6.0
> Make the version of ipython less than 6.0 in python 2.7

- .travis.yml
I think it is better to test against latest pypy, as it is still a moving target, and we don't absolutely need to support older pypy versions.
> [MRG+1] TST test agains latest pypy

- scrapy/downloadermiddlewares/httpproxy.py
* re-order the import, to keep it clear
* fix the bad smell code, don't use a reserved keyword as a variable name
> [MRG+1] change the bad smell code

- docs/topics/signals.rst
- scrapy/core/scraper.py
- scrapy/signals.py
- tests/pipelines.py
- tests/test_engine.py
add item_error to be catchable (ie. by `extension` with `signal`).
> [MRG+1] add item_error to be catchable

- scrapy/exporters.py
Fixed the issue I've mentioned there, this is the pull request to merge, (added one line), hope all is fine. 
https://github.com/scrapy/scrapy/issues/3034
Closes #3034
> [MRG+1] Fix for #3034, CSV export unnecessary blank lines problem on Windows

- .travis.yml
- requirements-py3.txt
- scrapy/extensions/telnet.py
- scrapy/utils/iterators.py
- tests/requirements-py3.txt
- tests/test_crawler.py
- tests/test_utils_log.py
- tox.ini
Continue @patiences work on python 3.7 compatibility from #3150, fixes #3143. Thanks a lot @patiences!
It's likely that we'll release scrapy 1.6 before new twisted version with https://github.com/twisted/twisted/pull/966 is released (sorry for making the PR stall), so in this PR I work around this issue, so that scrapy at least works, although without telnet console support yet.
Also pytest is updated, so that ``tox -e py37`` can collect the tests (2.9 was released more than 2 years ago).
~~WIP as I want to check how tests work on travis early (there are still a few failures due to PEP 479 left which didn't show up in #3150).~~
> Python 3.7 support

- scrapy/linkextractors/__init__.py
- tests/test_linkextractors.py
This might be the solution to the issue mentioned in #1381. I thought it might be a good idea to solve it :). I added ftp to link extractor so it recognizes ftp links. Please let me know if there's anything that I can do to improve this PR 😄
> [MRG+1] add ftp to the scheme list

- docs/news.rst
- scrapy/settings/__init__.py
- tests/test_settings/__init__.py
On the heels of removing those relocation shims, I believe the time has come for `CrawlerSettings`, `Settings.overrides` and `Settings.defaults` as well.
(`...is deprecated and won't be supported in Scrapy 0.26` ... yah, right. Lies!)
As a note to anyone napping the last four years; use `Settings.set(name, value, priority='cmdline')` (overrides) and `Settings.set(name, value, priority='default')` (defaults) instead.
> [MRG+1] Remove deprecated CrawlerSettings class and Settings attributes

- docs/topics/downloader-middleware.rst
The docs on `RETRY_HTTP_CODES` are outdated in regards to the list of HTTP status codes that are retried by default by the `RetryMiddleware`.
Here's the updated list: https://github.com/scrapy/scrapy/blob/master/scrapy/settings/default_settings.py#L239
> update default RETRY_HTTP_CODES on docs

- scrapy/extensions/feedexport.py
- scrapy/middleware.py
- scrapy/utils/misc.py
- tests/test_feedexport.py
- tests/test_utils_misc/__init__.py
Addresses #1567. This moves the "which constructor should I call" logic from the middleware manager into a util function, and re-uses it in the feed exporter extension.
Feed exporters and storages can now provide a `from_crawler()` class method and properly access settings.
> Add from_crawler constructor for feed exporters and storages

- scrapy/http/request/__init__.py
- tests/test_http_request.py
I noticed flags were missing after a request was retried by the retry downloader middleware, traced the issue and realized that they were not being copied.
Small test case included.
> [MRG+1] Include flags when copying requests

- docs/conf.py
The years have been updated. The hyphen was replaced with an en dash.
> Doc: update copyright notice

- scrapy/core/scheduler.py
- tests/test_dupefilters.py
> Add from_crawler support to dupefilters

- scrapy/http/request/form.py
- tests/test_http_request.py
Fix #3247 
Dicts do not allow duplicate keys. When form requests have duplicate keys, one of the values of the duplicate keys is dropped when created via the FormRequest's from_response method.
`formdata` is either a dict or iterable of tuples - this patch fixes the above issue by not converting `formdata` to a dict and keeping it as an iterable of tuples if possible.
Also, a unit test is added to verify correct functionality. This is my first PR, definitely let me know if any changes are needed!
> Fix #3247: Allow scrapy.FormRequest.from_response method to handle duplicate keys

- scrapy/contracts/__init__.py
- tests/test_contracts.py
Fix an `AttributeError` which was raised in Python 3 due to incorrect order of `exc_info` components.
Fixes #3370.
> [MRG+1] Fix contract errback (#3370)

- appveyor.yml
- scrapy/commands/startproject.py
- tests/mockserver.py
- tests/requirements-py3.txt
- tests/test_cmdline/__init__.py
- tests/test_command_parse.py
- tests/test_commands.py
- tests/test_crawler.py
- tests/test_downloader_handlers.py
- tests/test_feedexport.py
- tests/test_utils_iterators.py
- tests/test_utils_project.py
Test windows builds on Appveyor CI. 
Closes #1684
> Enable AppVeyor CI for running test suite on Windows env

- .gitignore
- docs/intro/overview.rst
- docs/intro/tutorial.rst
- docs/topics/commands.rst
- docs/topics/items.rst
- docs/topics/jobs.rst
- docs/topics/loaders.rst
- docs/topics/selectors.rst
- docs/topics/settings.rst
- docs/topics/shell.rst
- docs/topics/spiders.rst
- requirements-py2.txt
- requirements-py3.txt
- scrapy/linkextractors/sgml.py
- scrapy/loader/__init__.py
- scrapy/selector/unified.py
- scrapy/templates/spiders/crawl.tmpl
- scrapy/templates/spiders/xmlfeed.tmpl
- setup.py
- tests/test_command_shell.py
- tests/test_http_response.py
- tests/test_loader.py
- tests/test_pipeline_crawl.py
- tests/test_selector.py
- tests/test_spider.py
- tests/test_utils_iterators.py
Fixes https://github.com/scrapy/scrapy/issues/3317.
Todo:
> [MRG+1] update Scrapy to use parsel 1.5

- docs/intro/tutorial.rst
Hi there!
This is my pull request referencing the issue #3464.
I've removed the ad link "Dive into Python 3", and replaced it with [Crash into Python](https://stephensugden.com/crash_into_python/). It seems like a good resource for people to get up to speed with Python quickly.
Alternatively, I can just remove the link as well and point people to [The Python Tutorial](https://docs.python.org/3/tutorial). 
Thanks!
> [MRG+1] Update Scrapy Tutorial docs 

- MANIFEST.in
In particular this includes files needed for running the tests, as well as the changelog.
> [MRG+1] Include additional files in sdists

- docs/intro/install.rst
Its initial content covers the workaround for #2473.
> [MRG+1] Add a troubleshooting section to the installation instructions

- .travis.yml
- tox.ini
Our builds are failing for `TOXENV=jessie` with the following error
Related to https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262
> Fix boto import error under Jessie testing environment

- .travis.yml
https://changelog.travis-ci.com/deprecation-container-based-linux-build-environment-82037
> remove "sudo: false" now that travis no longer supports it

- scrapy/commands/shell.py
The special syntax required for local files (`./file.html`) is not documented as part of the `scrapy shell --help` output. This patch adds that.
> [MRG+1] Add documentation to `scrapy shell` command.

- setup.py
Scrapy supports 3.7 since #3326.
> declare Python 3.7 support in setup.py

- docs/topics/settings.rst
* labels were after setting description, while they should have been before them;
* BOT_NAME label was misplaced;
* new options from #2609 only work with botocore;
* document AWS_REGION_NAME introduced in #2609.
> fix docs for AWS_... settings. A follow-up to GH-2609.

- scrapy/core/downloader/middleware.py
- scrapy/core/spidermw.py
- scrapy/middleware.py
- tests/test_middleware.py
According to https://wiki.python.org/moin/TimeComplexity `list.insert` has an average time complexity of O(n), while `deque.appendleft` is O(1).
From that page (emphasis mine): 
> Internally, a list is represented as an array; the largest costs come from growing beyond the current allocation size (because everything must move), or from **inserting or deleting somewhere near the beginning** (because everything after that must move). **If you need to add/remove at both ends, consider using a collections.deque instead.**
It seems like for deques "_looking at the middle is slow, and adding to or removing from the middle is slower still_", which should not be a problem given that these method containers are iterated sequentially and not accessed randomly.
I first saw this while working on …
> [MRG+1] Use collections.deque instead of list to store MiddlewareManager's methods

- scrapy/core/downloader/handlers/__init__.py
- scrapy/core/downloader/handlers/datauri.py
- scrapy/core/downloader/handlers/file.py
- scrapy/core/downloader/handlers/ftp.py
- scrapy/core/downloader/handlers/http10.py
- scrapy/core/downloader/handlers/http11.py
- scrapy/core/downloader/handlers/s3.py
- tests/test_downloader_handlers.py
Download Handlers load only when first request for a scheme is needed, this was put in place because s3 download handler used to be very slow to create.
This makes it optional for Download Handlers to be lazy loaded which is relevant when writing custom handlers that have required settings and wants to raise `NotConfiguredException` during instantiation.
> Make lazy loading Download Handlers optional

- docs/topics/spiders.rst
- scrapy/spiders/sitemap.py
- tests/test_spider.py
it makes it possible to filter sitemap urls by any available attribute
for example, you can filter urls with lastmod greater than a given datetime
it can be helpful when the url loc itself does not aggregate that information
> [MRG+1] Add sitemap_filter function to SitemapSpider class

- scrapy/dupefilters.py
- tests/test_dupefilters.py
I just changed the log message when DUPEFILTER_DEBUG is active because it helps knowing which request is generating the duplicates (I'd this problem recently).
Also, I added some tests for the log method to check the proper messages and stats.
> [MRG+1] Adding requests referer to RFPDupeFilter log messages

- docs/topics/item-pipeline.rst
`if item['price']:` and `if item['price_excludes_vat']:` could return `KeyError` exception, this patch aims to solve it.
> Fix item-pipeline example

- docs/topics/request-response.rst
The example of form-based login could lead some users to think its authentication result
check was final. See https://stackoverflow.com/a/54410966/939364
This change should make it more obvious that users are expected to implement their
own logic to check whether authentication worked or not.
> Indicate that users must implement their own authentication result check

- scrapy/pipelines/images.py
AWS_ENDPOINT_URL in Settings was read by files.py but not by images.py. I don't know if it was intentionally but i couldn't connect to my local minio S3 Server when uploading images with ImagesPipeline
> [MRG+1] A different S3 Endpoint URL is now possible when uploading images

- scrapy/utils/misc.py
no need for if because expression already returns bool
> [MRG+1] rel_has_nofollow: remove redundant if statement

- docs/topics/link-extractors.rst
- scrapy/linkextractors/__init__.py
- scrapy/linkextractors/lxmlhtml.py
- scrapy/linkextractors/sgml.py
- tests/test_linkextractors.py
This is the proposed implementation of issue #3622 with unit tests and doc
> [MRG+1] Feature filteringlinkextractor restrict text

- docs/topics/selectors.rst
Fix numeration in selectors documentation.
> [MRG+1] Fix numeration

- docs/topics/downloader-middleware.rst
- docs/topics/request-response.rst
- scrapy/downloadermiddlewares/redirect.py
- tests/test_downloadermiddleware_redirect.py
According to @kmike's comment in https://github.com/scrapy/scrapy/issues/3581#issuecomment-463344378
> [MRG+1] Redirect codes in meta

- docs/topics/spiders.rst
- scrapy/spiders/crawl.py
- tests/test_spider.py
Allow for the `process_request` function passed to `Rule` objects to take the `Response` from which the `Request` was extracted as second positional argument.
This change grants the ability to access previously collected information in the `Response.meta` dict, for instance, which is not currently possible AFAICT (at least not without overriding private methods 🤷‍♂️ ). It is implemented in a backward compatible manner, i.e. request processing functions that take only one argument still work.
Updated docs, added tests for the existing and new functionality.
> [MRG+1] Rule.process_request: access Response object

- scrapy/utils/gz.py
The function seems to be no longer used.
I suspect its usage has been replaced by the inspecting the actual response bodies, which is more reliable than trusting headers.
> Deprecate the scrapy.utils.gz.is_gzipped function

- docs/topics/xpath-tutorial.rst
string(string(//body)) is equivalent to string(//body) in the example provided
> [MRG+1] FIX: Remove redundant string function

- docs/intro/tutorial.rst
I'm new to Scrapy, and the tutorial is great, but beyond that I got lost very fast.
I think it would be really helpful for all code blocks in all docs to mention the filename that they belong in. 
For example, in the Item Pipeline ```docs/topics/item-pipeline.rst```, I figured out that the very last code snippet goes in the ```settings.py``` file. (I eventually realized there's a link to the doc for settings, but writing it explicitly in addition would be helpful). 
Similarly, for Item Loaders ```docs/topics/loaders.rst``` it's not immediately clear that the Item Loader declaration goes in the ```items.py``` file while the parsing code stays in the spider files.
I'm also new to Sphinx/.rst format, so stylistically, what is a good way to do this? Is it possible to add a caption to the …
> Docs - Item Pipeline - Add filenames to code snippets

- scrapy/templates/project/module/middlewares.py.tmpl
Check [Spider Middleware docs](https://github.com/scrapy/scrapy/blob/b5c552d17ff9e9629434712c3d0595c02853bcfc/docs/topics/spider-middleware.rst) for more information
> [MRG+1] fix typo on Spider Middleware template (Response -> Request)

- scrapy/contracts/__init__.py
- scrapy/core/spidermw.py
- scrapy/utils/defer.py
- scrapy/utils/misc.py
- tests/mockserver.py
I noticed that occasionally my **Ctrl+C** is ignored.  In general this happens when using plain `except:`. In this case, you probably do not want to catch system-exceptions like `KeyboardInterrupt`.
> [MRG+1] fix: do not catch system exceptions like KeyboardInterrupt

- scrapy/extensions/corestats.py
- tests/test_closespider.py
Showing elapsed time in seconds in stats, also changing from utc to local time for better user experience.
(In my opinion time&date should be displayed based on the local time)
> [MRG+1] Show elapsed time in statscollector

- docs/topics/settings.rst
The setting `LOGSTATS_INTERVAL` is mentioned in various samples and issues but is not documented in the main topic.
> [MRG+1] doc: document LOGSTATS_INTERVAL setting

- scrapy/extensions/httpcache.py
> [MRG+1] Fixes a link in comment

- docs/contributing.rst
- tests/requirements-py2.txt
- tests/requirements-py3.txt
In summary:
- Add `pytest-xdist` to `tests/requirements*.txt` and remove versions from `pytest*` packages.
- In the tox configuration, add `-n auto` for all environments running `pytest`.
- Because Windows does not seem to support `pytest-xdist` cleanly, create a new tox environment specifically for Windows that does not use `pytest-xdist` (no `-n auto`).
> Use pytest-xdist

- docs/contributing.rst
The help link for creating pull requests in the contributing documentation is broken. Have updated it with the correct link
> [MRG+1] Fix a broken github help link

- docs/topics/logging.rst
Update to the `configure_logging` docs in order to prevent users from using this function with `CrawlerProcess` as this produces unexpected behavior.
Fixes #1347
> [MRG+1] doc: update configure_logging docs to discourage use with CrawlerProcess

- docs/topics/spiders.rst
When I translated in Chinese, I found a needless "is"
> [MRG+1] remove a "is"

- docs/intro/tutorial.rst
Tutorial: scrapy shell example should say "text" not "title"
Fixes #3812
> [MRG+1] Tutorial: scrapy shell example should say "text" not "title" (#3807)

- setup.py
[Twisted 19.2.0 is the final release with Python 3.4 support](https://github.com/twisted/twisted/blob/twisted-19.2.0/NEWS.rst).
These changes are based on the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies) and [PEP 508](https://www.python.org/dev/peps/pep-0508/#environment-markers).
Fixes #3821
> Require Twisted<=19.2.0 for Python 3.4

- scrapy/loader/__init__.py
- tests/test_loader.py
Issue: https://github.com/scrapy/scrapy/issues/3804
> [MRG+1] Fix missing values

- docs/conf.py
I made the following assumptions:
- `Contract`’s `add_pre_hook` and `add_post_hook` are not documented because they should be transparent to contract developers, for whom `pre_hook` and `post_hook` should be the actual concern.
- `ContractsManager` is an internal class, developers are not expected to interact with it directly in any way.
- For default contracts we only want to document their general purpose in their constructor, the methods they reimplement to achieve that purpose should be irrelevant to developers using those contracts.
> Skip scrapy.contracts private APIs in the documentation coverage report

- scrapy/settings/default_settings.py
I believe 429 should be added to RETRY_HTTP_CODES. It literally means to be retried after a certain while.
> [MRG+1] Add 429 to RETRY_HTTP_CODES

- docs/topics/contracts.rst
- scrapy/commands/check.py
- scrapy/utils/misc.py
- tests/test_utils_misc/__init__.py
This PR implements the environment variable when running `scrapy check` as asked in #3704 . This way it is possible to have different behaviour in the scraper when running the check (like requiring less settings to be set)
fixes #3704
> [MRG+1] Add SCRAPY_CHECK environment variable

- scrapy/utils/reqser.py
- tests/test_utils_reqser.py
Sorry for making a PR without an issue~ just hit an issue where mixins with similarly named methods used private names to prevent method conflicts.  The spider worked properly in memory but had errors when requests were serialized to a disk queue.
The Python documentation specifically documents the mangling convention so I think it's reasonable to assume it works in other implementations, but I haven't tested except with CPython.
> [MRG+1] Account for mangling when serializing requests with private callbacks

- scrapy/pipelines/media.py
- tests/test_pipeline_media.py
We're storing exceptions captured by Twisted on the media pipeline
cache, but we're also using the defer.returnValue method with our
own methods decorated with @defer.inlineCallbacks.
The defer.returnValue method passes returned values forward by
throwing a defer._DefGen_Return exception, which in its turn
extends the BaseException class and is captured by Twisted.
This way, the latest exception stored in the Failure's object may
also have an HtmlResponse object in its `__context__` attribute. As
the Response object also keeps track of the Request object that
has originated it, you could figure it out how many RAM we're
wasting here.
This could easily lead to a Memory Leak problem when running
spiders with Media Pipeline enabled and a particular Request set
that tends to raise a …
> Fix a memory leak on the Media Pipeline (Files and Images)

- docs/index.rst
- docs/topics/dynamic-content.rst
Write a new topic that addresses [Can scrapy be used to scrape dynamic content from websites that are using AJAX?](https://stackoverflow.com/q/8550114/939364), one of the StackOverflow questions about Scrapy with the most votes.
Note to self: https://docs.scrapy.org/en/latest/topics/developer-tools.html
> Add a topic about reaching data that selectors cannot reach

- scrapy/http/request/form.py
- tests/test_http_request.py
> [MRG+1] Fix form methods in FormRequest.from_response (#3777)

- docs/topics/downloader-middleware.rst
> [MRG+1] doc for creating custom cache storage backend.

- docs/topics/media-pipeline.rst
> Document FilesPipeline.file_path and ImagesPipeline.file_path

- scrapy/loader/__init__.py
- scrapy/loader/processors.py
- tests/test_loader.py
Added error messages to ItemLoader (for input processor, and processor as argument) and also for MapCompose and Compose. 
For MapCompose and Compose, I'm not sure though if the format is correct, since these errors will be displayed when processing the input/out processors and they will be nested to these ones, example:
```
ValueError: Error with processor MapCompose value=['change,deep-thoughts,thinking,world'] 
error='ValueError: Error in MapCompose with function _strip 
value=['change,deep-thoughts,thinking,world'] error='TypeError: must be str, not int''
```
I would appreciate some suggestions here.
Fixes #3836
> [MRG+1] Itemloader errors #3836

- scrapy/utils/http.py
- scrapy/utils/markup.py
- scrapy/utils/multipart.py
I noticed that there are 2 import-only modules in scrapy.utils, and one which is almost import-only. It looks like we should start sending deprecation warnings for them all, and this should have been done a while ago.
> More deprecations

- docs/faq.rst
- docs/topics/spider-middleware.rst
> Add a FAQ entry about splitting items in item pipelines

- docs/faq.rst
> Document that the crawl order is BFO for small numbers of start requests

- docs/conf.py
- docs/topics/contracts.rst
This removes 2 out of 3 API members of `scrapy.exceptions` from the documentation coverage report. The remaining class is to be covered by #3636.
> Increase the documentation coverage of exceptions

- docs/topics/broad-crawls.rst
This is built on top of the changes proposed at #1264.
I refactored the original documentation proposed by removing the new section and, instead, extending the existing section about concurrency with memory information, and creating two separate sections about crawling in BFO order and debugging memory leaks.
I also increased reliance on existing documentation through `:ref:` links. For example, the section about crawling in BFO order does not elaborate on DFO vs BFO or FIFO vs LIFO, and instead expects users to follow the link to the corresponding FAQ entry for more information.
> [MRG+1] Extend the topic about broad crawls with information about memory usage

- scrapy/_monkeypatches.py
- scrapy/core/downloader/handlers/ftp.py
- scrapy/core/downloader/handlers/http11.py
- scrapy/item.py
- scrapy/settings/__init__.py
- scrapy/utils/conf.py
- scrapy/utils/datatypes.py
- scrapy/utils/template.py
- tests/__init__.py
- tests/test_command_parse.py
- tests/test_downloadermiddleware_cookies.py
- tests/test_downloadermiddleware_robotstxt.py
- tests/test_engine.py
- tests/test_exporters.py
- tests/test_http_headers.py
- tests/test_http_request.py
- tests/test_http_response.py
- tests/test_linkextractors.py
- tests/test_loader.py
- tests/test_selector.py
- tests/test_spider.py
- tests/test_spiderloader/__init__.py
- tests/test_utils_datatypes.py
- tests/test_utils_url.py
I messed up #3876, had to open a new PR :man_facepalming: 
I left out some Twisted warnings, I believe they are more delicate and deserve their own treatment.
> Prevent deprecation warnings

- scrapy/loader/processors.py
- scrapy/utils/datatypes.py
Use `collections.ChainMap` when available, fall back to `scrapy.utils.datatypes.MergeDict` (currently in use only in `scrapy.loader.processors.MapCompose`)
> Deprecate scrapy.utils.datatypes.MergeDict in favor of collections.ChainMap

- docs/conf.py
- docs/contributing.rst
- docs/faq.rst
- docs/news.rst
- docs/topics/contracts.rst
- docs/topics/downloader-middleware.rst
- docs/topics/feed-exports.rst
- docs/topics/items.rst
- docs/topics/settings.rst
Current coverage: https://github.com/scrapy/scrapy/commit/44eb21aa51cc0212e68dc0709aaa5c10bfe64e7e
Includes a note about dropping Python 2 support in Scrapy 2.0.
Fixes #3872.
> Write the 1.7 release notes

- scrapy/utils/conf.py
Fixes #3893, fixes #3889
Cleaning up my own mess :sweat_smile:
> Fix ConfigParser import in py2

- docs/topics/logging.rst
- docs/topics/settings.rst
- scrapy/logformatter.py
Fixes #3616 by documenting `logFormatter` class.
> [MRG+1] docs for scrapy.logformatter

- docs/topics/settings.rst
- scrapy/core/downloader/contextfactory.py
- scrapy/core/downloader/handlers/http10.py
- scrapy/core/downloader/handlers/http11.py
- scrapy/core/downloader/tls.py
- scrapy/settings/default_settings.py
- scrapy/utils/ssl.py
- tests/test_downloader_handlers.py
Fix #2111. Also related to #2726, though that ticket most likely asks for a programmatical access to all of this (I don't know if it's easily doable).
Output example:
> 2018-10-05 20:08:36 [scrapy.core.downloader.tls] DEBUG: SSL connection to market.yandex.ru using protocol TLSv1.2, cipher ECDHE-RSA-AES128-GCM-SHA256
> 2018-10-05 20:08:36 [scrapy.core.downloader.tls] DEBUG: SSL connection certificate: issuer "/C=RU/O=Yandex LLC/OU=Yandex Certification Authority/CN=Yandex CA", subject "/C=RU/O=Yandex LLC/OU=ITO/L=Moscow/ST=Russian Federation/CN=market.yandex.ru"
> 2018-10-05 20:08:36 [scrapy.core.downloader.tls] DEBUG: SSL temp key: ECDH, P-256, 256 bits
I'm not sure this should be enabled by default as a lot of websites are now HTTPS and this will be printed on all requests including …
> Log cipher, certificate and temp key info on establishing an SSL connection

- docs/topics/downloader-middleware.rst
Added 429 code to documentation about default RETRY_HTTP_CODES.
> fix default RETRY_HTTP_CODES value in docs

- scrapy/pipelines/files.py
Fix https://github.com/scrapy/scrapy/issues/3904.
The new headers mapping are read from botocore service json file:
```python
import requests, json
r = requests.get('https://raw.githubusercontent.com/boto/botocore/master/botocore/data/s3/2006-03-01/service-2.json')
s3_service_json = r.json()
members = s3_service_json['shapes']['PutObjectRequest']['members']
def to_camel_case(s):
return '-'.join(x.upper() if x.lower() in ('acp', 'md5') else x.capitalize() for x in s.split('-'))
print({
to_camel_case(v['locationName'].encode()): k.encode()  
for k, v in members.items()
if v.get('location') == 'header' and k.lower() not in ('meta', 'acl' )
})
```
Tested manually with:
```python
import os
from twisted.internet import reactor
os.environ['AWS_ACCESS_KEY_ID'] = 'xxx' …
```
> s3 file store persist_file should accept all supported headers

- .travis.yml
Travis-ci changed the default build environment to Xenial as explained in https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
This causes builds meant for Debian Jessie to break as noted by @wRAR in https://github.com/scrapy/scrapy/issues/3917#issuecomment-516426389
This change pins the environment to known working ubuntu trusty distribution prior to dropping Jessie support and upgrade to Xenial as base.
Closes #3917
Note: Backport this change to `1.7` branch once it is merged to master.
> Pin Travis-ci build environment to previous default: Trusty
