- CONTRIBUTING.md
- docs/contributing.rst
> Contribute to master branch

- tests/__init__.py
- tests/test_crawl.py
- tests/test_downloadermiddleware_robotstxt.py
- tests/test_pipeline_files.py
- tests/test_settings/__init__.py
- tests/test_spider.py
- tests/test_utils_deprecate.py
- tox.ini
mock is in the stdlib since Python 3.3.
> Import unittest.mock if available.

- docs/topics/downloader-middleware.rst
- docs/topics/request-response.rst
- docs/topics/settings.rst
- docs/topics/spider-middleware.rst
Hey, folks!
So, here is an update for the meta special keys, this fixes #615.
Thank you!
> updating list of Request.meta special keys

- README.rst
> DOC contribute to master branch

- docs/intro/tutorial.rst
Addresses Issue #1107.
I can rebase this on another branch as needed. It's not clear to me which branch is bring used to build the official docs.
> Converted sel.xpath() calls to response.xpath() in Extracting the data

- docs/intro/overview.rst
Hey folks, some minor grammar fixes here -- thanks @breno!
@nyov maybe you want to review this too?
> Some minor grammar fixes

- docs/topics/commands.rst
- docs/topics/items.rst
These lines threw warnings on sphinx-build.
> documentation build warning fixes

- docs/topics/api.rst
- scrapy/crawler.py
> Allow passing Crawler instances directly to CrawlerRunner.crawl()

- docs/topics/deploy.rst
> deployment docs tweaks

- docs/intro/tutorial.rst
these are just some minor corrections made along the way of reading the scrapy docs.
> add some minor stylistic and grammar corrections to tutorial.rst.

- README.rst
- debian/control
- docs/intro/overview.rst
- docs/topics/selectors.rst
- scrapy/__init__.py
- setup.py
This fixes #586 that was reopened after more discussion, [see last comments](https://github.com/scrapy/scrapy/issues/586#issuecomment-86022684).
> [MRG+1] Favoring web scraping over screen scraping in the descriptions

- tests/test_downloadermiddleware_robotstxt.py
I've lost my chance to add test in right time for PR #1131. But maybe it's never late for tests? :)
> Test for robotstxt error

- scrapy/linkextractors/htmlparser.py
- scrapy/linkextractors/sgml.py
> [MRG+1] Deprecate htmlparser link extractor

- docs/news.rst
Release Notes for next stable release. Closes #1195.
> 1.0 release notes

- scrapy/loader/processors.py
Docstring says it takes a json string, but it actually takes a loaded data structure.
> Fix SelectJmes documentation

- docs/Makefile
Otherwise build seems to succeed (exit code 0) whenever it does not
> [MRG+1] BF: fail if docs failed to build

- scrapy/downloadermiddlewares/robotstxt.py
- tests/test_downloadermiddleware_robotstxt.py
Kindly let me know if the reorganized testcases are okay, I have some trouble finding the best organization here.
(Side note; I watched Eugene’s talk on "Sustainable way of testing your code" from EuroPython, but had some trouble to follow the video. Are those slides available somewhere?)
> PY3 port scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware

- scrapy/pipelines/files.py
- scrapy/responsetypes.py
- scrapy/utils/defer.py
- scrapy/utils/misc.py
- tests/py3-ignores.txt
- tests/test_downloadermiddleware_decompression.py
- tests/test_middleware.py
- tests/test_pipeline_files.py
- tests/test_pipeline_media.py
- tests/test_responsetypes.py
@kmike, @dangra 
nice sprint :)
i'm probably already too late with this
> [MRG+1] [py3] replace rfc822 with email.utils

- scrapy/downloadermiddlewares/cookies.py
- scrapy/http/cookies.py
- scrapy/mail.py
- tests/py3-ignores.txt
- tests/test_downloadermiddleware_cookies.py
- tests/test_http_cookies.py
> PY3 port http cookies handling

- scrapy/_monkeypatches.py
- tests/test_squeues.py
An alternative implementation of #1413
> Twisted 15.3.0 does not raises expected exception serializing lambdas

- requirements-py3.txt
- scrapy/cmdline.py
- scrapy/core/downloader/handlers/s3.py
- scrapy/core/downloader/middleware.py
- scrapy/core/spidermw.py
- scrapy/linkextractors/htmlparser.py
- scrapy/pipelines/files.py
- scrapy/pipelines/images.py
- scrapy/utils/testproc.py
- tests/py3-ignores.txt
- tests/requirements-py3.txt
- tests/test_cmdline/__init__.py
- tests/test_command_version.py
- tests/test_crawl.py
- tests/test_loader.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
- tests/test_selector_csstranslator.py
- tests/test_selector_lxmldocument.py
- tests/test_utils_iterators.py
- tests/test_utils_reqser.py
- tox.ini
This is a follow-up to https://github.com/scrapy/scrapy/pull/1400.
~~Any ideas why [this](https://github.com/scrapy/scrapy/commit/99a532c480d85f79b8464afaac719a39fbeca24f) seemingly innocent change causes pipeline tests to fail? I can reproduce test failures locally.~~
> nyov's PY3 changes

- README.rst
Badge is updated every 15 minutes based on Travis results. There are 5 achievements to unlock (orange, yellow, yellow-green, green and bright green colors); they are unlocked as soon as a certain % of tests pass in Python 3.
Raw data is available at http://static.scrapy.org/py3progress/progress.json.
> add Python 3 porting status badge to README

- scrapy/linkextractors/__init__.py
> [MRG+1] Replace usage of deprecated class by its parsel\'s counterpart

- .gitignore
- scrapy/core/scraper.py
- scrapy/logformatter.py
- scrapy/pipelines/files.py
- scrapy/statscollectors.py
- scrapy/utils/request.py
- tests/py3-ignores.txt
- tests/test_logformatter.py
- tests/test_stats.py
> Small Python 3 fixes

- scrapy/downloadermiddlewares/httpauth.py
- scrapy/downloadermiddlewares/useragent.py
- tests/py3-ignores.txt
- tests/test_downloadermiddleware_ajaxcrawlable.py
- tests/test_downloadermiddleware_defaultheaders.py
- tests/test_downloadermiddleware_httpauth.py
- tests/test_downloadermiddleware_stats.py
- tests/test_downloadermiddleware_useragent.py
Easy stuff, mostly fixing tests.
> [MRG] port some downloader middlewares to Python 3

- scrapy/utils/python.py
> [MRG+1] Avoid creation of temporary list object in iflatten

- docs/contributing.rst
- docs/intro/install.rst
Some needed updates from the recent issues we're receiving.
> Updates in Installation and Contributing sections in the docs

- scrapy/templates/project/module/settings.py.tmpl
* added blank lines around `=`;
* added `AUTOTHROTTLE_TARGET_CONCURRENCY` option.
> [MRG+1] style fixes for settings.py created by `scrapy startproject`

- docs/topics/deploy.rst
- docs/topics/firebug.rst
- docs/topics/loaders.rst
- docs/topics/shell.rst
I've made a few small corrections, some spelling changes and typo fixes.
I've tried to respect regional spelling differences and avoided proposing hyphenating compound words.
Please enter the commit message for your changes. Lines starting
> Typos corrections

- docs/topics/selectors.rst
I fixed some invalid xpath errors on docs
> Docs fixes

- scrapy/commands/genspider.py
- scrapy/commands/parse.py
- scrapy/utils/template.py
- tests/py3-ignores.txt
- tests/test_commands.py
parse command should also work, but its tests are disabled because they require HTTP download handler.
> PY3 port bench, startproject, genspider, list and runspider commands

- docs/topics/media-pipeline.rst
Hi, people! Just submitting a PR to fix a typo in the docs.
> fix typo in the documentation

- scrapy/http/request/form.py
- tests/test_http_request.py
> [MRG+1] fixed: Issue #1562 (Incorrectly picked URL in `scrapy.http.FormReques t.from_response` when there is a `<base>` tag)

- docs/faq.rst
- docs/topics/broad-crawls.rst
- docs/topics/extensions.rst
- docs/topics/item-pipeline.rst
- docs/topics/items.rst
- docs/topics/leaks.rst
- docs/topics/practices.rst
- docs/topics/selectors.rst
Fixing grammar issues through http://languagetool.org.
> Fixed minor grammar issues.

- docs/intro/install.rst
This PR adds installation notes about installing Scrapy via conda and the Scrapinghub's anaconda.org channel.
> Added installation notes about using Conda for Windows.

- docs/topics/shell.rst
* update the scrapy.org example to deal with the new layout.
* replaced slashdot.org by reddit.com, because it seems that slashdot is blocking requests.
> [MRG+1] Update deprecated examples

- scrapy/linkextractors/htmlparser.py
- scrapy/linkextractors/lxmlhtml.py
- scrapy/linkextractors/regex.py
- scrapy/linkextractors/sgml.py
- tests/test_linkextractors.py
https://github.com/scrapy/scrapy/pull/1352 into 1.0 branch
> [MRG+1] [1.0.x backport] [LinkExtractors] Ignore bogus links

- tests/test_downloader_handlers.py
Fixes the broken test suites after #1358 merge.
> [MRG+1] optional_features has been removed

- scrapy/core/downloader/handlers/http11.py
As discussed here https://github.com/scrapy/scrapy/pull/1678#discussion-diff-50129295 - this way is indeed much more readable :)
> [MRG+1] Cleanup http11 tunneling connection after #1678

- scrapy/commands/fetch.py
- scrapy/utils/testsite.py
- tests/py3-ignores.txt
- tests/test_command_fetch.py
- tests/test_command_shell.py
Based on #1680, here are all changes in this branch https://github.com/lopuhin/scrapy/compare/7ffcc58...py3-commands-fetch-shell?expand=1
I am not sure about fetch command - right now I try to print bytes as-is, but if their encoding is different from terminal encoding, than the output will be messed up. On the other hand, one could redirect output to a file and then do whatever is needed. Another option is to just print body_as_unicode(), and do something else for headers.
> [MRG+1] Py3: port commands fetch and shell

- docs/topics/request-response.rst
Fix the next version number for feature added in #1382, as per comment: https://github.com/scrapy/scrapy/pull/1382/files#r50368769
> Fix version number to appear new feature

- tests/mockserver.py
- tests/py3-ignores.txt
- tests/spiders.py
- tests/test_crawl.py
Based on #1680, here are all changes in this branch https://github.com/lopuhin/scrapy/compare/7ffcc58...py3-test-crawl?expand=1
No "interesting" changes, only fixing bytes in tests - just hard to debug failures due to high-level nature of tests.
> [MRG+1] Py3: port test crawl

- tests/test_commands.py
scrapy parse command is already ported.
> PY3 enable tests for scrapy parse command

- tests/py3-ignores.txt
- tests/requirements-py3.txt
- tests/test_downloader_handlers.py
added boto to py3 test requirements - tests themselves are fine
> [MRG+1] py3: test_pipeline_files and test_pipeline_images

- CODE_OF_CONDUCT.md
- README.rst
> [MRG+1] Add Code of Conduct Version 1.3.0 from http://contributor-covenant.org/

- scrapy/http/response/text.py
as per @nramirezuy's suggestion (https://github.com/scrapy/scrapy/pull/1730#issuecomment-175803818)
> [MRG+1] micro-optimize response.text

- tests/test_exporters.py
As suggested [here](https://github.com/scrapy/scrapy/pull/1737#issuecomment-175819639), this PR adds tests for the JSON, JSON-Lines, Pickle and Marshall item exporters, regarding to items with non-string fields.
> [MRG+1] Include tests for non-string items to Exporters

- scrapy/commands/shell.py
- scrapy/utils/url.py
GH issue: https://github.com/scrapy/scrapy/issues/1550
RM issue: https://intranet.scrapinghub.com/issues/47619
> #1550 - shell command's ability to open local files

- docs/news.rst
Hey, @eliasdorneles and me went through the release notes and did some editing.
Does it look good?
> Add overview to release notes and other edits

- docs/news.rst
I haven't touched updates 2 and 3 from API changes.
> edit API changes, Deprecations, and Relocations sections.

- docs/news.rst
- docs/topics/autothrottle.rst
- docs/topics/downloader-middleware.rst
- docs/topics/settings.rst
Submitting early to get more eyes on it.
Anyone can help get each subsection of the release notes nice and pretty (and readable).
~~You can comment in this PR with patches, I'll include them in seperate commits within this PR~~
Submit a PR to branch "release-notes-1.1"
- ~~[ ] Tests, CI and Deploys~~
- ~~[ ] Other changes~~
- ~~[ ] Contributors~~
> [MRG+2] Release notes 1.1

- docs/news.rst
- docs/topics/email.rst
- scrapy/core/engine.py
- scrapy/http/cookies.py
- scrapy/mail.py
- scrapy/spiders/sitemap.py
- scrapy/xlib/pydispatch.py
- tests/test_http_cookies.py
- tests/test_mail.py
- tests/test_pydispatch_deprecated.py
- tests/test_spider.py
Cherry-picked commits from:
- https://github.com/scrapy/scrapy/pull/1767
- https://github.com/scrapy/scrapy/pull/1771
- https://github.com/scrapy/scrapy/pull/1750
- https://github.com/scrapy/scrapy/pull/1662
- https://github.com/scrapy/scrapy/pull/1765
into 1.1 branch
> [MRG+1] [1.1.x][backport] #1766, #1770, #1750, #1662, #1765

- scrapy/responsetypes.py
- tests/test_responsetypes.py
> More liberal Content-Disposition header parsing

- docs/topics/feed-exports.rst
- scrapy/core/downloader/handlers/s3.py
- scrapy/extensions/feedexport.py
- scrapy/http/headers.py
- scrapy/pipelines/files.py
- scrapy/utils/boto.py
- scrapy/utils/test.py
- tests/py3-ignores.txt
- tests/requirements-py3.txt
- tests/test_downloader_handlers.py
- tests/test_feedexport.py
- tests/test_pipeline_files.py
- tox.ini
Originally from https://github.com/scrapy/scrapy/pull/1761
@lopuhin , I squashed the 22 commits into one. I did not manage to submit a correct PR with your individual commits.
Does it look correct?
> [backport][1.1.x] Py3 S3 botocore

- scrapy/crawler.py
- tests/test_commands.py
> [MRG+1] Better tracebacks

- scrapy/core/downloader/handlers/http11.py
Reverts scrapy/scrapy#1701
As discussed in https://github.com/scrapy/scrapy/pull/1701#issuecomment-187703015
> Revert "Cleanup http11 tunneling connection after #1678"

- scrapy/utils/test.py
Squashed https://github.com/scrapy/scrapy/pull/1801
> [backport][1.1] Fix SkipTest() message for botocore import test

- scrapy/core/downloader/handlers/http11.py
> [backport][1.1] Revert "Cleanup http11 tunneling connection after #1678"

- scrapy/crawler.py
- tests/test_commands.py
Commits from https://github.com/scrapy/scrapy/pull/1787
> [backport][1.1] Better tracebacks

- docs/topics/feed-exports.rst
- docs/topics/settings.rst
- scrapy/pipelines/files.py
- scrapy/settings/default_settings.py
Commits from https://github.com/scrapy/scrapy/pull/1796
> [backport][1.1] Change default S3 ACL to "private" and allow customization via settings

- scrapy/extensions/feedexport.py
Backporting #1769 into 1.1 branch.
> [backport][1.1] PY3: Fix TypeError when outputting to stdout

- docs/news.rst
- docs/topics/settings.rst
> [MRG+1] Document DOWNLOADER_* settings for HTTP/1.0 and TLS

- scrapy/spiderloader.py
Backporting #1818  into 1.1 branch
> [backport][1.1] Refactored SpiderLoader class constructor for easier subclassing

- scrapy/core/downloader/handlers/http11.py
This is to prevent regressions like those fixed by GH-1808.
> [MRG+1] Extract a function to build CONNECT request; add tests for it. 

- docs/faq.rst
- docs/topics/email.rst
- docs/topics/media-pipeline.rst
- docs/topics/request-response.rst
- docs/topics/settings.rst
- docs/topics/signals.rst
Just some small fixes to the doc :P
> small doc style fixes

- scrapy/core/scheduler.py
- scrapy/settings/default_settings.py
Backporting #1822 into 1.1 branch
> [Backport][1.1] Allow core Scheduler priority queue customization

- scrapy/pipelines/files.py
Same as https://github.com/scrapy/scrapy/pull/1883
> [Backport][1.1] Make FilesPipeline work with S3FilesStore using botocore

- docs/contributing.rst
A good read: https://stackoverflow.com/help/mcve
> Reference StackOverflow's "minimal, complete, and verifiable example" guide

- requirements.txt
- scrapy/downloadermiddlewares/ajaxcrawl.py
- scrapy/utils/response.py
- setup.py
Backporting #1881 into 1.1 branch
> [backport][1.1] Remove duplicate code now handled by newer w3lib (PR #1881)

- docs/topics/media-pipeline.rst
- scrapy/pipelines/files.py
- scrapy/pipelines/images.py
- scrapy/settings/default_settings.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
Same as https://github.com/scrapy/scrapy/pull/1891
> [backport][1.1] Change Files/ImagesPipelines class attributes to instance attributes (PR #1891)

- scrapy/core/downloader/handlers/http11.py
(maybe) fixing https://github.com/scrapy/scrapy/issues/1936
> Set SNI properly when using CONNECT

- scrapy/core/downloader/handlers/http11.py
Cherry-picking https://github.com/scrapy/scrapy/pull/1938 into 1.1 branch
> [backport][1.1] Set SNI properly when using CONNECT (PR #1938)

- scrapy/core/downloader/handlers/http11.py
Cherry-picking #1912 into 1.1 branch.
> [backport][1.1] Fix HTTP Pool key for HTTPS proxy tunneled connections (PR #1912)

- requirements.txt
- scrapy/http/request/__init__.py
- tests/test_http_request.py
Cherry-picking #1923 into 1.1 branch.
> [backport][1.1] Use newer w3lib.url.safe_url_string() (PR #1923)

- scrapy/utils/url.py
- tests/test_utils_url.py
Cherry-picking #1947 into 1.1 branch
> [backport][1.1] Fix canonicalize_url() on Python 3 and re-enable tests (PR #1947)

- docs/news.rst
> Update release notes with recent features and bug fixes.

- README.rst
Added Python 3.3+ to the readme, as suggested in #1961
> Added Python 3.3+ to readme

- scrapy/core/downloader/tls.py
> [backport][1.1] Prevent empty warnings in case of certificate verification failures (PR #1979)

- docs/topics/request-response.rst
Revisiting http://stackoverflow.com/a/31149178/
> DOC Add info and example on errbacks

- docs/intro/overview.rst
> [backport][1.1][DOC] Use idiomatic .extract_first() (PR #1994)

- docs/topics/request-response.rst
> [backport][1.1] Add info and example on errbacks (PR #1995)

- docs/faq.rst
- docs/intro/install.rst
- docs/news.rst
> [backport][1.1] [docs] Add note about Windows + Python3 (PR #2060)

- scrapy/utils/url.py
- tests/test_utils_url.py
> [backport][1.1] Do not fail on canonicalizing URLs with wrong netlocs (PR #2038)

- docs/topics/logging.rst
Hello,
I've corrected a minor grammar issue in the logging topic
> (docs) Minor grammar fix in logging.rst

- docs/_templates/layout.html
Same as PR #2217, but for 1.1 branch (shown as latest on RTD).
> Add Segment Analytics to Documentation (backport to 1.1 branch)

- scrapy/downloadermiddlewares/httpproxy.py
Just a small typo fix in a comment
> typo fix in HttpProxyMiddleware

- docs/intro/tutorial.rst
https://github.com/scrapy/scrapy/pull/2236 into 1.1 branch
> [backport][1.1] Tutorial update (PR #2236)

- docs/index.rst
My take at #2255 -- mentioning it before the scrapy-users mailing list just because I tend to lurk more there, feel free to nitpick. :)
> Mentions stackoverflow as support channel (fixes #2255)

- docs/intro/overview.rst
Backporting #2249 to branch 1.1
> [backport][1.1] docs: update overview spider code to use toscrape.com and minor changes

- docs/intro/tutorial.rst
> Fix a dict key in the tutorial

- .travis.yml
- tox.ini
Testing if this could make a good baseline
> Add Debian Jessie test env

- scrapy/pipelines/files.py
- scrapy/pipelines/images.py
- scrapy/pipelines/media.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
#2243 backported to 1.1 branch.
> [backport][1.1][PR#2243][image & file pipeline] loading setting for user classes

- docs/versioning.rst
> [MRG+1] Remove mention of odd-numbered versions for development releases

- docs/topics/email.rst
> [MRG+1] Add note on "to" and "cc" as lists for sending emails

- docs/intro/tutorial.rst
> [backport][1.1][PR#2252] Rewrite tutorial seeking to improve learning path

- docs/topics/item-pipeline.rst
> [docs] document that process_item can return Deferred

- docs/topics/item-pipeline.rst
* quote url
* use hash of url as filename
cc @kmike
> [MRG+1][docs/item_pipeline] process_item returning Deferred docs

- docs/news.rst
Related to @dangra 's comment: https://github.com/scrapy/scrapy/pull/2212#issuecomment-248616113
> Mention new Debian Jessie baseline

- docs/intro/tutorial.rst
In the AuthorSpider, original css selector failed to get links of author pages
> fix example code

- scrapy/templates/spiders/basic.tmpl
- scrapy/templates/spiders/crawl.tmpl
- scrapy/templates/spiders/csvfeed.tmpl
- scrapy/templates/spiders/xmlfeed.tmpl
> genspider: removing www. from starturl templates

- docs/intro/tutorial.rst
> Fix tutorial AuthorSpider

- docs/topics/firefox.rst
Simply add closing tag in <tbody>
> Document update in "Using Firefox for scraping"

- README.rst
- docs/intro/install.rst
> [MRG+1] Update conda channel to conda-forge and show conda version badge.

- scrapy/linkextractors/htmlparser.py
- scrapy/linkextractors/sgml.py
Nothing really useful.
Fixing the SGML parser is useless anyway, but oh well.
> [MRG+1] LinkExtractor PY3 'unicode' type fix

- docs/topics/request-response.rst
This PR aims to fix #2033
Thoughts on it?
> [MRG+1] Document `download_latency` meta key

- docs/index.rst
- docs/topics/ubuntu.rst
Continuation of https://github.com/scrapy/scrapy/issues/2137
> [MRG] DOC Remove "Ubuntu" section from sidebar/ToC

- scrapy/spiders/sitemap.py
- scrapy/utils/sitemap.py
- tests/test_spider.py
- tests/test_utils_sitemap.py
> [MRG+1] Handle relative sitemap URLs in robots.txt

- scrapy/downloadermiddlewares/robotstxt.py
- tests/test_downloadermiddleware_robotstxt.py
Fixes #2373 
Simpler fix than https://github.com/scrapy/scrapy/pull/2385
> [MRG+1] Parse robots.txt content as native str

- docs/faq.rst
- docs/topics/settings.rst
> [MRG+1] Add docs for some scheduler settings

- tests/test_pipeline_images.py
> TST: Randomize IMAGES_EXPIRES above 90 days

- docs/topics/downloader-middleware.rst
- docs/topics/settings.rst
- scrapy/downloadermiddlewares/chunked.py
- scrapy/settings/default_settings.py
Following up on https://github.com/scrapy/scrapy/pull/1896
> [MRG+1] Remove ChunkedTransferMiddleware from default settings

- tests/test_pipeline_files.py
Continuation of https://github.com/scrapy/scrapy/pull/2427
> TST: Randomize FILES_EXPIRES above 90 days

- scrapy/resolver.py
Backporting #2496 into 1.2 branch
> [backport][1.2] Enforce DNS resolution timeout

- docs/topics/selectors.rst
> [MRG+1] Fix documentation about HTML entities decoding with selector extraction

- docs/intro/tutorial.rst
> Use consistent selectors for author field in tutorial

- requirements-py3.txt
- requirements.txt
- setup.py
This is required by several pull requests: https://github.com/scrapy/scrapy/pull/2334, https://github.com/scrapy/scrapy/pull/2548, https://github.com/scrapy/scrapy/pull/2540, https://github.com/scrapy/scrapy/pull/2547.
> require w3lib 1.17+

- .gitignore
These are temporary files created when running tox tests.
> add a couple more lines to gitignore

- scrapy/core/downloader/contextfactory.py
> Set context factory implementation based on Twisted version

- docs/topics/request-response.rst
> [MRG+1] Document ftp_user and ftp_password meta keys

- scrapy/spidermiddlewares/referer.py
- tests/test_spidermiddleware_referer.py
> Fix referrer policy from response headers and support explicit empty string

- docs/topics/downloader-middleware.rst
Fixes https://github.com/scrapy/scrapy/issues/2575
> DOC Mention brotli support in HttpCompressionMiddleware section

- scrapy/spiderloader.py
- tests/test_spiderloader/__init__.py
Fixes #2181 
Continuation of @MrMenezes ' #2353
> [WIP] Add warning on duplicate spider name

- docs/topics/settings.rst
- scrapy/commands/list.py
- scrapy/commands/runspider.py
- scrapy/commands/settings.py
- scrapy/commands/startproject.py
- scrapy/commands/version.py
- scrapy/settings/default_settings.py
- scrapy/spiderloader.py
- tests/test_spiderloader/__init__.py
Backport #2632  into 1.3.x branch (before releasing 1.3.3)
> [backport][1.3] Add SPIDER_LOADER_WARN_ONLY

- docs/intro/install.rst
#2477 backported into 1.3.x branch
> [backport][1.3] Installation instructions, mention conda in the beginning

- docs/Makefile
Fixes [#2661](https://github.com/scrapy/scrapy/issues/2661)
> [MRG+1] Update Makefile to open webbrowser in MacOS (#2661)

- docs/faq.rst
- docs/intro/install.rst
Backport #2690 into 1.3.x branch
> [backport][1.3] FAQ Rewrite note on Python 3 support on Windows

- docs/topics/selectors.rst
Same motivations as for https://github.com/scrapy/parsel/pull/79
> DOC Rearrange selector sections

- docs/topics/selectors.rst
> [MRG+1] Remove __nonzero__ from SelectorList docs

- scrapy/core/downloader/handlers/http11.py
- tests/mockserver.py
- tests/test_downloader_handlers.py
Fixes https://github.com/scrapy/scrapy/issues/2677
> Set bodyproducer with empty content for POST

- scrapy/core/downloader/handlers/http11.py
- tests/test_downloader_handlers.py
Fixes #1616 
A symptom of this issue was having the log message "Received (X) bytes
larger than download max size (Y)" several times printed, with increased
X values.
```
2017-03-04 09:55:58	ERROR	[scrapy.core.downloader.handlers.http11] Received (3538944) bytes larger than download max size (524288).
2017-03-04 09:55:58	ERROR	[scrapy.core.downloader.handlers.http11] Received (3542211) bytes larger than download max size (524288).
2017-03-04 09:55:58	ERROR	[scrapy.core.downloader.handlers.http11] Received (3542212) bytes larger than download max size (524288).
2017-03-04 09:55:58	ERROR	[scrapy.core.downloader.handlers.http11] Received (3547136) bytes larger than download max size (524288).
2017-03-04 09:55:58	ERROR	[scrapy.core.downloader.handlers.http11] Received (3550280) bytes larger …
```
> [MRG+1] Abort connection earlier and avoid to buffer data when max size limit is reached

- docs/topics/item-pipeline.rst
insert is deprecated, use insert_one instead.
> [MRG+1] Update item-pipeline.rst

- docs/topics/item-pipeline.rst
see http://api.mongodb.com/python/current/api/pymongo/collection.html?highlight=insert#pymongo.collection.Collection.insert
> use suggest method instead of DEPRECATED one

- docs/_static/xpathdemo.css
- docs/topics/xpath-tutorial.rst
Hey @stummjr , I converted part 1 of https://github.com/scrapinghub/xpathcsstutorial/blob/master/xpathtutorial.ipynb to use your xpathdemo widget.
Part 2 and Part 3 to come.
> XPath tutorial: Convert part1 of the tutorial to use the live widget

- docs/topics/broad-crawls.rst
Fix spelling mistake in broad-crawls.rst
> Spelling mistake

- tox.ini
trying to fix recent Travis build failures
> [WIP] Jessie toxenv: Add cryptography as per https://packages.debian.org/jessie/python-cryptography

- scrapy/http/response/text.py
- tests/test_http_response.py
> [MRG+1] Added: Now supporting <link> tags in Response.follow

- scrapy/utils/console.py
Added support for ptpython embed shell for `scrapy shell` and such.
Related issue: https://github.com/scrapy/scrapy/issues/2654
> [MRG+1] add support for embeded ptpython shell

- README.rst
What do you think about changing the content of "Releases" section in README?
> DOC change "releases" section content

- scrapy/settings/default_settings.py
> Added: HTTP status code 522/524 to retry.

- docs/topics/spider-middleware.rst
Update DepthMiddleware docs with request.meta['depth'].
closes #2374 
closes #2455
> Add note about request.meta['depth'] in DepthMiddleware

- .travis.yml
Fixes #2990
We'll see if it fixes it.
> Fix PyPy build

- scrapy/commands/edit.py
Just separated the import statements. Tiny change - testing GitHub!
> Separated import statements

- .travis.yml
- README.rst
- docs/faq.rst
- docs/intro/install.rst
- setup.py
- tox.ini
> [MRG+1] Drop support for EOL Python 3.3

- setup.py
Mention in setup.py that we support CPython and PyPy.
> [MRG+1] setup.py: mention that we support PyPy. See GH-2213.

- scrapy/core/downloader/handlers/http11.py
Fixes https://github.com/scrapy/scrapy/issues/2743
> [MRG+1] Use HTTP pool and proper endpoint key for ProxyAgent

- docs/news.rst
A follow-up to https://github.com/scrapy/scrapy/pull/2858 with all changes.
TODO:
> Release notes for the upcoming 1.5.0 version 

- docs/news.rst
Fix link pointing to issue 2884.
> Fix link in news.rst

- scrapy/utils/defer.py
This is my first PR, so on going through the code, I found some typos, and corrected it.
Corrected Files: scrapy/utils/defer.py
> Changes in Documentation

- docs/news.rst
> fix typo in news.rst

- docs/contributing.rst
> make amendments to grammer

- docs/intro/tutorial.rst
As detailed in #3366, I expanded the beginner resources to include more and up-to-date resources, instead of only an outdated version of *Learn Python The Hard Way*.
> [MRG+1] Updated tutorial.rst to include more and up-to-date beginner resources

- scrapy/contracts/__init__.py
- tests/test_contracts.py
> Use inspect.getmembers in tested_methods_from_spidercls

- docs/topics/debug.rst
#3097  Corrected the unclear comments by adding # < processing code not shown >
> [MRG+1] Updating debug example file (#3097)  

- docs/topics/commands.rst
> Document the SCRAPY_PROJECT environment variable

- docs/intro/overview.rst
Just a minor modification of quote (use single quote for string).
> unify the quote style

- docs/news.rst
This is work in progress. TODO:
> 1.6 release notes

- docs/topics/settings.rst
> Clarify the documentation of DEPTH_PRIORITY further

- docs/topics/downloader-middleware.rst
- scrapy/downloadermiddlewares/retry.py
> Remove the unexisting retry_complete signal from the documentation

- docs/topics/architecture.rst
> Fix a link inside docs

- docs/news.rst
- docs/topics/request-response.rst
- docs/topics/spiders.rst
- docs/versioning.rst
- scrapy/cmdline.py
- scrapy/conf.py
- scrapy/core/downloader/handlers/http.py
- scrapy/extensions/feedexport.py
- scrapy/log.py
- scrapy/signals.py
- scrapy/utils/conf.py
- sep/sep-018.rst
- tests/test_downloader_handlers.py
- tests/test_feedexport.py
- tests/test_utils_conf.py
Based on https://english.stackexchange.com/a/2449/87187
Applied to documentation, source comments and a test name.
> backwards → backward (adj.)

- docs/topics/items.rst
- scrapy/item.py
- tests/test_item.py
> Implement Item.deepcopy()

- docs/intro/tutorial.rst
I made a few small edits to docs/intro/tutorial.rst:  
- deleted apostrophe from "let's" to "lets"
- deleted extra word "shell" which was repeated in reference link
- changed "browser developer tools" to "browser's developer tools" (add apostrophe + s)
- deleted 2 extra words from "(see section about ...)" to "(see ...)"
I did each edit on a separate commit in case you want to change or revert any of them.
Let me know if this is helpful. I'm new to Scrapy and I have a few other ideas of how to improve the docs.
If I make any more edits, does it make sense to do a separate branch/pull request per file?
> [MRG+1] Docs - Tutorial - Minor grammar edits

- scrapy/extensions/httpcache.py
> [MRG+1] Changes a parameter name in class `DummyPolicy`

- docs/contributing.rst
Based on a [comment](https://github.com/scrapy/scrapy/pull/3671#discussion_r268213806) by @kmike.
> Cover PEP 257 in the documentation policies

- docs/topics/api.rst
Docs mentioned the wrong module.
> [MRG+1] Fix documentation for spiderloader

- tests/test_downloadermiddleware.py
Removes unused variables in `tests/test_downloadermiddleware.py`
> removes unused var

- scrapy/cmdline.py
> PEP8 in cmdline.py

- scrapy/utils/ssl.py
Found in #3892. Tested on xenial with various pyOpenSSL and cryptography combinations.
> Fix memory handling and error handling in utils.ssl.get_temp_key_info.

- scrapy/contracts/default.py
- tests/test_contracts.py
Hijacking of #766 addressing remaining feedback.
> Report all missing fields when a scrapes contract fails

- docs/topics/exporters.rst
> Fix the item exporter example

- docs/topics/request-response.rst
> Clarify the effects of dont_merge_cookies

- docs/topics/developer-tools.rst
- docs/topics/downloader-middleware.rst
> Fix some typos

- docs/topics/contracts.rst
> Remove old note for contracts.

- pytest.ini
- scrapy/commands/check.py
- scrapy/commands/startproject.py
- scrapy/commands/version.py
- scrapy/core/downloader/handlers/ftp.py
- scrapy/core/downloader/webclient.py
- scrapy/core/scraper.py
- scrapy/http/headers.py
- scrapy/interfaces.py
- scrapy/link.py
- scrapy/spiders/feed.py
- scrapy/spiders/init.py
- scrapy/statscollectors.py
- scrapy/utils/http.py
- tests/test_cmdline/extensions.py
- tests/test_settings/default_settings.py
- tests/test_spidermiddleware_depth.py
- tests/test_spidermiddleware_urllength.py
- tests/test_utils_datatypes.py
- tests/test_utils_http.py
- tests/test_utils_spider.py
I have fixed this rule in all the files because I think that it doesn’t compromise the original idea of the code author as well as it doesn’t create noise in the git history/blame.
> fix W391 Blank line at end of file

- docs/topics/logging.rst
Usage of basicConfig() together with crawlerRunner is not recommended.
Update documentation to highlight this fact.
Closes #2149, closes #2352, and closes #3146
> Update documentation for logging manually

- docs/conf.py
Follow up to #4173 :man_facepalming:
> Enable sphinx-hoverxref for all references

- scrapy/downloadermiddlewares/cookies.py
This commit removes unused import and re-arrange the imports in cookies
module
> Remove the used import and re-arrange the imports in the cookies module

- scrapy/__init__.py
- scrapy/contracts/default.py
- scrapy/core/downloader/__init__.py
- scrapy/core/downloader/handlers/http.py
- scrapy/core/downloader/handlers/s3.py
- scrapy/linkextractors/__init__.py
- scrapy/linkextractors/regex.py
This commits converts the relative imports to absolute imports in the
entire package
> Convert the relative imports to absolute imports

- tests/test_pipelines.py
This is another small PR that first adds simple tests for stuff where I needed asyncio tests.
> Add simple tests for pipelines.

- tests/test_engine.py
This helps with adding new similar tests to that class.
> Split a long test in test_engine.py into three.

- docs/topics/media-pipeline.rst
- scrapy/exporters.py
Rephrasing documentation for image and file pipelines
Fixes #4034
> Rephrasing documentation for image and file pipelines

- scrapy/http/request/__init__.py
- tests/test_http_request.py
> Request: remove restriction about errback without callback

- tox.ini
> Remove elusive six occurrence from tox.ini

- docs/topics/settings.rst
- scrapy/core/downloader/__init__.py
- scrapy/core/downloader/handlers/ftp.py
- scrapy/core/downloader/handlers/http10.py
- scrapy/core/downloader/handlers/http11.py
- scrapy/extensions/closespider.py
- scrapy/http/response/text.py
- scrapy/mail.py
- scrapy/utils/benchserver.py
- scrapy/utils/testproc.py
- scrapy/utils/testsite.py
- tests/requirements-py3.txt
- tests/test_http_response.py
Cherry-pick [changes for 2.0.1](https://github.com/scrapy/scrapy/milestone/28?closed=1) into the `2.0` branch.
> Cherry-pick changes for 2.0.1 into the 2.0 branch

- scrapy/crawler.py
> [fix] zope interface 5.0.0 unsupported

- scrapy/responsetypes.py
changed Content-type header name to Content-Type
(Edit) fixes #4473
> Changed Content-type header name to Content-Type (capitalization)

- pytest.ini
- scrapy/commands/fetch.py
- scrapy/commands/parse.py
- scrapy/core/downloader/webclient.py
- scrapy/linkextractors/__init__.py
- scrapy/linkextractors/lxmlhtml.py
- tests/test_downloadermiddleware_cookies.py
- tests/test_exporters.py
- tests/test_pipeline_media.py
- tests/test_utils_python.py
- tests/test_utils_signal.py
http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
> Fix pycodestyle E731 ("do not assign a lambda expression, use a def")

- docs/topics/practices.rst
> Docs: replace deprecated FEED_FORMAT and FEED_URI settings

- docs/topics/coroutines.rst
Resolves: https://github.com/scrapy/scrapy/issues/4511
> Remove the asyncio warning from coroutines page #4511

- .travis.yml
Related to https://github.com/scrapy/scrapy/pull/4261
> Run quick tests first in Travis CI

- .travis.yml
- tox.ini
> Simplify the asyncio Tox environment

- .travis.yml
> Remove TOXENV from .travis.yml unless needed

- pytest.ini
- scrapy/core/downloader/handlers/ftp.py
- scrapy/core/engine.py
- scrapy/pipelines/media.py
- scrapy/utils/deprecate.py
- scrapy/utils/request.py
- tests/spiders.py
- tests/test_closespider.py
- tests/test_downloader_handlers.py
- tests/test_downloadermiddleware_decompression.py
- tests/test_downloadermiddleware_redirect.py
- tests/test_http_request.py
- tests/test_selector.py
- tests/test_spidermiddleware_httperror.py
- tests/test_spidermiddleware_referer.py
- tests/test_utils_url.py
_Continuation line with same indent as next logical line_
Based on #4538 to avoid merge conflicts, actual changes in 63600243e08cb7e783798bd6c59fb97595488e9e
> Flake8: remove E125

- pytest.ini
- scrapy/core/downloader/contextfactory.py
- scrapy/core/downloader/handlers/s3.py
- scrapy/core/downloader/webclient.py
- scrapy/downloadermiddlewares/retry.py
- scrapy/spiderloader.py
- tests/test_downloadermiddleware_cookies.py
- tests/test_downloadermiddleware_retry.py
- tests/test_http_request.py
- tests/test_pipeline_crawl.py
- tests/test_webclient.py
_Continuation line over-indented for hanging indent_
~Based on #4542 to avoid merge conflicts.~ (merged)
> Flake8: remove E126

- docs/topics/dynamic-content.rst
> Cover chompjs in documentation

- pytest.ini
- tests/pipelines.py
- tests/test_crawler.py
- tests/test_dependencies.py
- tests/test_extension_telnet.py
- tests/test_feedexport.py
- tests/test_item.py
- tests/test_pipeline_images.py
- tests/test_spidermiddleware_referer.py
- tests/test_utils_defer.py
- tests/test_utils_deprecate.py
- tests/test_utils_signal.py
_Local variable name is assigned to but never used_
All occurrences were in test files.
> Flake8: remove F841

- docs/topics/item-pipeline.rst
> Fix the description of the ScreenshotPipeline example item pipeline

- docs/intro/tutorial.rst
I found the previous a bit clunky, it seemed to change tense, but I think it just meant as I have suggested.
> Small suggestion to make this a bit more clear.

- docs/topics/exporters.rst
- docs/topics/loaders.rst
- docs/topics/request-response.rst
- docs/topics/selectors.rst
Subset of https://github.com/scrapy/scrapy/pull/4661, fixes #4547
> Update unicode references from Python 2 times in the documentation

- scrapy/commands/check.py
> SCRAPY_CHECK will be set while running contact (Fixes #4222)

- docs/topics/feed-exports.rst
> Document FEED_URI_PARAMS

- scrapy/spiders/__init__.py
- scrapy/spiders/crawl.py
- setup.cfg
- tests/spiders.py
Not really a comprehensive annotation, just a few attributes to remove several files from the ignore list.
> Typing: annotate a few Spider attributes

- scrapy/downloadermiddlewares/cookies.py
- tests/test_downloadermiddleware_cookies.py
> Improve check for invalid cookie in CookiesMiddleware

- docs/topics/jobs.rst
This won't be an issue if **your** spider doesn't rely on cookies.
> Correct some typos

- docs/topics/exporters.rst
Implements https://github.com/scrapy/scrapy/issues/4907
> Removed wrong super argument in overriding serialize_fields code example

- docs/conf.py
- docs/intro/install.rst
Fixes https://github.com/scrapy/scrapy/issues/4892  
Insured all the other links are working.
> Update links in installation guide

- scrapy/utils/curl.py
Co-authored-by: alkazaz alkazaz@kth.se
Co-authored-by: swill swill@kth.se
Co-authored-by: lerjevik lerjevik@kth.se
Co-authored-by: aljica aljica@kth.se
Resolves #5001
> Refactor curl_to_request_kwargs #5001

- docs/faq.rst
- docs/topics/spider-middleware.rst
> Add a FAQ entry on how to deal with long lists of allowed domains

- .vscode/settings.json
- docs/topics/benchmarking.rst
> DOCS: Cover scrapy-bench in the documentation

- scrapy/__init__.py
- scrapy/commands/__init__.py
- scrapy/commands/parse.py
- scrapy/contracts/__init__.py
- scrapy/http/cookies.py
- scrapy/item.py
- scrapy/mail.py
- scrapy/spidermiddlewares/referer.py
- scrapy/utils/httpobj.py
- scrapy/utils/request.py
- scrapy/utils/response.py
- scrapy/utils/trackref.py
- setup.cfg
Just a few annotations to remove exceptions from `setup.cfg`
> Some type hints

- scrapy/core/scraper.py
This is minor cleanup of, I suppose, remains of multiple slots per Scraper, similar to parts of #5090, but I think there is nothing else to clean up/deprecate here.
> Cleanup of slot handling in Scraper.

- scrapy/core/engine.py
> Engine: remove unnecessary parameter

- docs/topics/request-response.rst
- scrapy/http/request/__init__.py
- scrapy/http/request/json_request.py
- scrapy/squeues.py
- scrapy/utils/reqser.py
- scrapy/utils/request.py
- tests/test_request_dict.py
An alternative approach to #4945, considering https://github.com/scrapy/scrapy/pull/4945#discussion_r553504035.
Closes #4945.
~I plan to do the same thing with the `Response` class in a later PR (`Response.to_dict` and `scrapy.utils.response.response_from_dict`)~ see #5131
> Refactor request to/from dict

- tests/CrawlerProcess/asyncio_deferred_signal.py
- tox.ini
> Typing: switch to a newer version of MyPy to check types

- docs/topics/media-pipeline.rst
> Add docs sections describing default and custom file names

- docs/topics/request-response.rst
- scrapy/http/response/__init__.py
- scrapy/http/response/text.py
- tests/test_http_response.py
Closes #1877.
This is a subset of the changes from #5131, as [suggested](https://github.com/scrapy/scrapy/pull/5131#issuecomment-879711114) by @Gallaecio
> Response.attributes

- docs/topics/jobs.rst
- docs/topics/spiders.rst
Documented `state` attribute in `Spider` documentation.
> Document spider.state attribute (#5174)

- docs/topics/spider-middleware.rst
Fixes ambiguity of return type for `process_spider_exception` function.
> Improve documentation for spider middlewares

- README.rst
Logo scrapy used in readme.md made looks nicer
<strong>Before</strong>
<strong>After</strong>
> Using Logo Scrapy in Readme.md

- scrapy/http/cookies.py
- tests/test_http_cookies.py
> Remove Python 2 code from WrappedRequest

- docs/index.rst
> added discord link in help section

- docs/intro/tutorial.rst
Small edit. Changed a grammar mistake.
> Fixed typo/grammar mistake

- docs/faq.rst
Hey @wRAR I have removed  the pywin32 docs section from the FAQ. Please Review my PR!
Fixes #5369, resolves #5373, resolves #5373, resolves #5446
> Removed  the pywin32 docs section

- tox.ini
Related to #5454 
Should this go into 2.6.2?
> Pin mitmproxy to < 8 for now.

- docs/news.rst
> 2.6 release notes request serialization

- docs/news.rst
> Unset 2.6 release date

- docs/topics/coroutines.rst
- docs/topics/signals.rst
> Document coroutines for signals.

- docs/requirements.txt
https://github.com/scrapy/scrapy/pull/5535#discussion_r899994814
> Pin documentation requirements

- docs/README.rst
I changed 'to cleanup' into 'to clean up' into docs/README.rst.  
Have a good one.
> grammary correction

- sep/sep-014.rst
> Fix typo in sep-014.rst

- tests/test_crawler.py
- tests/test_spider.py
This fix failed tests from this issue: https://github.com/scrapy/scrapy/issues/5612
~- tox.wiki is offline that's why checks is failing (https://github.com/tox-dev/tox/issues/2486)~
> Fix failed tests related to w3lib

- .github/workflows/checks.yml
- .github/workflows/publish.yml
Updated setup-python workflow to version 4 and action checkout workflow to version 3.
> Updated setup-python and checkout actions workflow

- README.rst
Add copy to clipboard button in install command
> docs(README.rst): make install command copyable

- INSTALL
- INSTALL.md
Reformatted the file so that it displays content better.
> Update and rename INSTALL to INSTALL.md

- .github/workflows/checks.yml
- .github/workflows/publish.yml
- .github/workflows/tests-ubuntu.yml
Updated ubuntu workflow image latest ubuntu stable image as Ubuntu 18.04 is a bit old and will soon meet its end-of-life support. 
Resolves https://github.com/scrapy/scrapy/issues/5671
> Updated ubuntu workflow image to latest stable image

- scrapy/commands/parse.py
- tests/test_command_parse.py
> add async callbacks support to parse 

- scrapy/utils/log.py
> Silence the `filelock` logger

- .github/workflows/checks.yml
- .github/workflows/tests-ubuntu.yml
- tox.ini
> Remove Reppy from CI

- scrapy/utils/defer.py
- scrapy/utils/reactor.py
- tests/test_utils_asyncio.py
Fixes https://github.com/scrapy/scrapy/issues/5765
> test_install_asyncio_reactor: restore the original reactor when done

- docs/faq.rst
- docs/intro/tutorial.rst
- docs/topics/contracts.rst
- docs/topics/coroutines.rst
- docs/topics/debug.rst
- docs/topics/downloader-middleware.rst
- docs/topics/email.rst
- docs/topics/exporters.rst
- docs/topics/item-pipeline.rst
- docs/topics/link-extractors.rst
- docs/topics/media-pipeline.rst
- docs/topics/practices.rst
- docs/topics/request-response.rst
- docs/topics/settings.rst
- docs/topics/signals.rst
- docs/topics/spider-middleware.rst
- docs/topics/spiders.rst
> Skip/fix failing code block tests.

- artwork/README.rst
Convert Pidgin English to actual English.
> Copyedit README.rst

- docs/intro/tutorial.rst
Cherry-pick of #5893 to master
> Fix typo on tutorial.rst 

- docs/topics/selectors.rst
> Enable doc tests for selectors.rst, fix issues

- docs/topics/request-response.rst
This is my first PR for Scrapy so any feedback would be welcome. Having looked at https://github.com/scrapy/scrapy/issues/5707, I've changed the text to reflect the comments in that issue and from my own reading of the code. Was a nice exercise in getting a little more familiar with the code base, learned a few things. 
Fixes https://github.com/scrapy/scrapy/issues/5707
> Change redirect text from Response.request docs

- scrapy/utils/conf.py
- tests/test_utils_conf.py
> Deprecate the custom attribute of build_component_list().

- scrapy/core/engine.py
- tests/test_engine.py
> Remove deprecated `spider` parameter from engine

- docs/topics/asyncio.rst
Resolves https://github.com/scrapy/scrapy/issues/5981.
Changes:
- Changed section sorting, let me know if it makes sense to you.
- Reworded the Windows section to avoid Python version references not necessary since the 3.7 drop, and to simplify things. I removed the instructions to manually changing the loop because I cannot think of a need for them given `install_reactor`, but I am not 100% sure.
- Added a section about handling early module-level Twisted imports that install the default, non-asyncio reactor. This was the initial goal here.
I wonder if we need to cover better the possibility of using a Twisted-powered software that installs a reactor before any user code is executed. I checked and [scrapyd seems not to have an issue with that …
> asyncio docs: cover accidental bad reactor installation

- scrapy/crawler.py
- tests/test_crawler.py
It was deprecated in the same release (1.0.0) it was added.
> Remove deprecated CrawlerRunner.spiders.

- setup.py
> Forbid Twisted 23.8.0+

- tests/requirements.txt
> Pin brotli for pypy tests.

- .github/workflows/tests-ubuntu.yml
- .pre-commit-config.yaml
- tox.ini
> Update tool versions

- docs/news.rst
> mention PythonItemExporter changes

- scrapy/core/http2/stream.py
- scrapy/http/headers.py
- scrapy/http/request/__init__.py
- scrapy/http/response/__init__.py
- scrapy/http/response/text.py
- scrapy/utils/datatypes.py
- tests/test_http2_client_protocol.py
> Add typing hints to CaselessDict and Headers.

- .github/workflows/checks.yml
- .github/workflows/publish.yml
- .github/workflows/tests-ubuntu.yml
- scrapy/contracts/__init__.py
- tests/requirements.txt
- tox.ini
> Re-enable uvloop tests on 3.12

- docs/topics/settings.rst
- scrapy/core/scheduler.py
- scrapy/settings/default_settings.py
- scrapy/utils/job.py
> [Solved] JOBDIR= None for when Scheduler initializes disk queue even if JOBDIR is empty string

- tests/test_linkextractors.py
Making the assert statements more readable, the use of assertTrue, assertFalse.
> Fix assert statements in test

- scrapy/spidermiddlewares/depth.py
- scrapy/spidermiddlewares/httperror.py
- scrapy/spidermiddlewares/offsite.py
- scrapy/spidermiddlewares/referer.py
- scrapy/spidermiddlewares/urllength.py
I've removed the `or ()` parts because `result` shouldn never be `None` (well, because mypy said `async for r in ()` is incorrect code and I looked at it closely).
> Full typing for scrapy/spidermiddlewares.

- tests/test_downloader_handlers.py
> Remove test_download_gzip_response test

- tests/test_feedexport.py
> Remove a defer.returnValue call.

- docs/news.rst
> Update release logs for response_httprepr removal

- docs/topics/media-pipeline.rst
- scrapy/core/http2/stream.py
- scrapy/downloadermiddlewares/redirect.py
- tests/CrawlerRunner/ip_address.py
- tests/test_http_cookies.py
- tests/test_http_request.py
- tests/test_scheduler_base.py
- tests/test_spidermiddleware_referer.py
> Replace urlparse with urlparse_cached where possible

- docs/topics/feed-exports.rst
- scrapy/extensions/postprocessing.py
- tests/test_feedexport.py
> Do not close the underlying file from compression plugins

- tox.ini
Found when running `tox` locally.
> Address tox issues

- tests/test_linkextractors.py
Added tests to increase coverage.
> Added tests for LxmlLinkExtractor

- tests/test_http_request.py
Improving branch coverage within json_request.py
> Improve json_request.py coverage

- tests/test_http_request.py
Improving code and branch coverage within form.py
> Added tests for form.py

- .bandit.yml
- scrapy/commands/bench.py
- scrapy/commands/edit.py
- scrapy/commands/genspider.py
- scrapy/core/downloader/__init__.py
- scrapy/exporters.py
- scrapy/extensions/httpcache.py
- scrapy/extensions/spiderstate.py
- scrapy/pqueues.py
- scrapy/settings/default_settings.py
- scrapy/shell.py
- scrapy/squeues.py
- scrapy/utils/benchserver.py
- scrapy/utils/engine.py
Ignore inline (`# nosec`) some security issues reported by Bandit that are not actual security issues in Scrapy.
> bandit: allow-list false positives

- scrapy/utils/_compression.py
- tox.ini
Increase compatibility across different virtual environments, particularly with Conda, when using brotli.Decompressor()
> Solve incompatibility errors in _compression.py

- tests/test_command_check.py
Added tests for the check command to increase coverage.
> Added tests for check command

- docs/topics/dynamic-content.rst
- docs/topics/selectors.rst
- scrapy/selector/unified.py
> Document missing parts of response.json method

- docs/topics/link-extractors.rst
> Removing empty example reference

- docs/intro/overview.rst
Made some minor grammatical adjustments to the "Scrapy at a glance" section of the documentation.
> Some grammatical adjustments

- docs/topics/item-pipeline.rst
[Found](https://github.com/zytedata/duplicate-url-discarder/pull/23#issuecomment-2259413875) by @BurnzZ.
> Do not suggest logging dropped items twice

- scrapy/pipelines/media.py
Backport to 2.11, https://github.com/scrapy/scrapy/pull/6460#discussion_r1713029223
> Fix a typing error with Twisted 24.7.0.

- docs/topics/contracts.rst
- scrapy/contracts/default.py
- scrapy/settings/default_settings.py
- tests/test_contracts.py
> Add support for meta in Spider Contracts

- scrapy/pipelines/media.py
- scrapy/utils/misc.py
Fixes #6305 
Updated deprecated ast.NameConstant with ast.Constant
> Updated deprecated ast.NameConstant with ast.Constant #6305

- docs/topics/extensions.rst
- docs/topics/jobs.rst
Fix #6278 
Created documentation for spider state for the extensions page
Pls review
> Documentation added for Spider State in extensions.rst

- docs/topics/autothrottle.rst
- docs/topics/request-response.rst
- docs/topics/settings.rst
- scrapy/core/downloader/__init__.py
- scrapy/extensions/throttle.py
- tests/test_core_downloader.py
- tests/test_downloaderslotssettings.py
- tests/test_extension_throttle.py
https://github.com/scrapy/scrapy/pull/6246#discussion_r1827583470
cc @GeorgeA92, @VMRuiz
> Replace Slot.throttle with Request.meta['dont_throttle']

- docs/contributing.rst
Resolves #6561, closes #6566, closes #6572.
> Contributing: add a section on finding work

- docs/topics/settings.rst
- scrapy/commands/version.py
- scrapy/settings/default_settings.py
- scrapy/utils/log.py
- scrapy/utils/versions.py
- tests/test_crawler.py
> Allow customizing logged software versions

- scrapy/extensions/logstats.py
- tests/test_logstats.py
I noticed that the values are always null and figured out there is a typo in the stats key name
> Fix calculate_final_stats method

- scrapy/crawler.py
- scrapy/extensions/httpcache.py
- scrapy/pipelines/media.py
> Fix Crawler.request_fingerprinter typing

- .github/workflows/tests-macos.yml
- .github/workflows/tests-ubuntu.yml
- .github/workflows/tests-windows.yml
> Switch CI to codecov/codecov-action and enable it on Windows.

- pyproject.toml
- tests/__init__.py
- tox.ini
Fixes #6255.
It would be interesting to do some profiling after this is implemented but that's a separate question.
> Fix and speed up subprocess coverage tracking

- pyproject.toml
- tests/test_downloader_handlers.py
- tests/test_downloader_handlers_http2.py
- tox.ini
> Refactor downloader tests

- scrapy/signals.py
> Remove deprecated signals

- docs/topics/coroutines.rst
- scrapy/core/spidermw.py
Related to #6590 
Open to further improvements/refinements
> Add more docs for updating sync spider middlewares.

- tests/test_addons.py
- tests/test_closespider.py
- tests/test_cmdline/__init__.py
- tests/test_cmdline_crawl_with_pipeline/__init__.py
- tests/test_command_check.py
- tests/test_command_fetch.py
- tests/test_command_parse.py
- tests/test_command_shell.py
- tests/test_command_version.py
- tests/test_commands.py
- tests/test_contracts.py
- tests/test_core_downloader.py
- tests/test_crawl.py
- tests/test_crawler.py
- tests/test_dependencies.py
- tests/test_downloaderslotssettings.py
- tests/test_dupefilters.py
- tests/test_engine.py
- tests/test_engine_stop_download_bytes.py
- tests/test_engine_stop_download_headers.py
- tests/test_webclient.py
> Converting tests to plain asserts, part 2.

- docs/topics/dynamic-content.rst
> Remove the Splash recommendation.

- tests/test_spider.py
- tests/test_spiderloader/__init__.py
- tests/test_spidermiddleware.py
- tests/test_spidermiddleware_depth.py
- tests/test_spidermiddleware_httperror.py
- tests/test_spidermiddleware_offsite.py
- tests/test_spidermiddleware_output_chain.py
- tests/test_spidermiddleware_referer.py
- tests/test_spidermiddleware_urllength.py
- tests/test_spiderstate.py
- tests/test_squeues.py
- tests/test_squeues_request.py
- tests/test_stats.py
> Converting tests to plain asserts, part 4.

- docs/news.rst
- scrapy/spiders/init.py
- tests/test_spider.py
> Deprecate InitSpider

- tests/test_item.py
- tests/test_link.py
- tests/test_linkextractors.py
- tests/test_pipeline_crawl.py
- tests/test_pipeline_files.py
- tests/test_pipeline_images.py
- tests/test_pipeline_media.py
> Converting tests to plain asserts, part 6.

- tests/test_downloader_handlers.py
- tests/test_downloader_handlers_http2.py
- tests/test_exporters.py
- tests/test_feedexport.py
- tests/test_http2_client_protocol.py
- tests/test_http_cookies.py
- tests/test_http_headers.py
> Converting tests to plain asserts, part 7.

- tests/test_http_request.py
- tests/test_http_response.py
- tests/test_loader.py
- tests/test_settings/__init__.py
> Converting tests to plain asserts, part 8.

- tests/test_logformatter.py
- tests/test_logstats.py
- tests/test_mail.py
- tests/test_middleware.py
- tests/test_pipelines.py
- tests/test_pqueues.py
- tests/test_proxy_connect.py
- tests/test_request_attribute_binding.py
- tests/test_request_cb_kwargs.py
- tests/test_request_dict.py
- tests/test_request_left.py
- tests/test_responsetypes.py
- tests/test_robotstxt_interface.py
- tests/test_scheduler.py
- tests/test_scheduler_base.py
- tests/test_selector.py
- tests/test_signals.py
- tests/test_toplevel.py
- tests/test_urlparse_monkeypatches.py
> Converting tests to plain asserts, part 5.

- .github/workflows/publish.yml
- .pre-commit-config.yaml
- README.rst
- docs/_tests/quotes.html
- docs/_tests/quotes1.html
- docs/faq.rst
- docs/intro/install.rst
- docs/intro/tutorial.rst
- docs/news.rst
- docs/topics/api.rst
- docs/topics/architecture.rst
- docs/topics/exporters.rst
- docs/topics/extensions.rst
- docs/topics/feed-exports.rst
- docs/topics/logging.rst
- docs/topics/media-pipeline.rst
- docs/topics/practices.rst
- docs/topics/request-response.rst
- docs/topics/selectors.rst
- docs/topics/spiders.rst
- docs/topics/stats.rst
- sep/sep-004.rst
- sep/sep-007.rst
- sep/sep-008.rst
- sep/sep-014.rst
- sep/sep-018.rst
Split off from https://github.com/scrapy/scrapy/pull/6715.
> Remove trailing whitespace

- .github/workflows/checks.yml
- .github/workflows/tests-macos.yml
- .github/workflows/tests-ubuntu.yml
- .github/workflows/tests-windows.yml
Split off from https://github.com/scrapy/scrapy/pull/6715.
> Do not run the CI on branches, only on the main branch and on PRs

- scrapy/core/scraper.py
- tests/test_closespider.py
> feat: Add count to spider_exceptions stats

- docs/topics/settings.rst
- scrapy/settings/default_settings.py
- scrapy/utils/misc.py
- tests/test_utils_misc/test_return_with_argument_inside_generator.py
> Syntax Error Fixed 

- scrapy/core/engine.py
- scrapy/core/scraper.py
- scrapy/core/spidermw.py
- tests/test_engine.py
> Remove the unnecessary spider argument from Scraper and related code.

- scrapy/core/scraper.py
- tests/test_crawl.py
This is also important for future refactorings of this code.
> Improve test coverage of Scraper.

- tests/test_crawl.py
The existing tests don't seem enough for refactoring the related code.
> Improve tests for start items.

- tests/CrawlerProcess/sleeping.py
- tests/test_crawler.py
The change in 2cb1e10 was broken from the beginning :-/
> Fix shutdown tests.

- docs/topics/feed-exports.rst
- docs/topics/settings.rst
> Document default values set by startproject

- docs/topics/coroutines.rst
> Add a list of Deferred-only APIs.

- tests/test_downloadermiddleware_httpcache.py
Fixes #6649 
I did a refactoring so that the test options that are being covered are more clear. What I did was the following:
- Remove of policy_class and storage_class attributes from TestBase class
- Added StorageTestMixin and PolicyTestMixin classes that contain tests specific from storage and policy, respectively
- Added DummyPolicyTestMixin and RFC2616PolicyTestMixin that contain tests specific from those options
- Finally, added classes that contain all possible combinations between storage and policy options. Those classes are:
TestFilesystemStorageWithDummyPolicy
TestFilesystemStorageWithRFC2616Policy
TestDbmStorageWithDummyPolicy
TestDbmStorageWithRFC2616Policy
TestDbmStorageWithCustomDbmModule (inherits from DummyPolicy version)
TestFilesystemStorageGzipWithDummyPolicy …
> refactor tests/test_downloadermiddleware_httpcache.py

- docs/topics/signals.rst
- scrapy/core/engine.py
- scrapy/core/scraper.py
- scrapy/extensions/feedexport.py
- scrapy/signalmanager.py
- scrapy/utils/signal.py
- tests/test_utils_signal.py
> Add `send_catch_log_async()`.

- scrapy/core/scraper.py
- scrapy/logformatter.py
- tests/test_crawl.py
> Fix a regression in errback result handling.

- docs/topics/settings.rst
I forgot we should have done this.
> Document the new defaults of throttling settings

- scrapy/templates/project/module/middlewares.py.tmpl
Changed "maching" to "matching"
> Fix small typo in middlewares.py.tmpl

- tests/test_pqueues.py
> Improve the assumption in test_queue_push_pop_priorities().

- scrapy/shell.py
Fixes : [6915](https://github.com/scrapy/scrapy/issues/6915)
Essentially all that required is a new line
Test steps:
run `scrapy shell` on  normal terminal and an interactive terminal like ipython
Interactive before
```
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x0000021FEB0AD700>
[s]   item       {}
[s]   settings   <scrapy.settings.Settings object at 0x0000021FEB37EA80>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a …
```
> fix for formatting interactive shell : 6915

- scrapy/core/downloader/__init__.py
- scrapy/core/scraper.py
- tests/test_core_scraper.py
`chainDeferred()` is hard to understand so I removed it.
> Refactor chainDeferred() usages.

- scrapy/crawler.py
- tests/test_commands.py
Per https://github.com/scrapy/scrapy/pull/6845#discussion_r2115755264
It looks like this:
```
2025-08-30 01:28:51 [scrapy.utils.log] INFO: Scrapy 2.13.3 started (bot: scrapybot)
2025-08-30 01:28:51 [scrapy.utils.log] INFO: Versions:
{'lxml': '6.0.0',
'libxml2': '2.14.4',
'cssselect': '1.3.0',
'parsel': '1.10.0',
'w3lib': '2.3.1',
'Twisted': '25.5.0',
'Python': '3.13.7 (main, Aug 20 2025, 22:17:40) [GCC 14.3.0]',
'pyOpenSSL': '25.1.0 (OpenSSL 3.5.0 8 Apr 2025)',
'cryptography': '45.0.4',
'Platform': 'Linux-6.16-amd64-x86_64-with-glibc2.41'}
2025-08-30 01:28:51 [scrapy.crawler] DEBUG: Using AsyncCrawlerProcess
2025-08-30 01:28:51 [asyncio] DEBUG: Using selector: EpollSelector
2025-08-30 01:28:51 [scrapy.addons] INFO: Enabled addons:
[]
```
Note that it's DEBUG, I think that's the best level …
> Log when AsyncCrawlerProcess or CrawlerProcess is instantiated.
