scrapy/_monkeypatches.py
The workarounds are not required assuming the bugs regarding urlparse are absent in  Python versions >2.7. We already exit the program if Python  version<2.7 in the __init__.py(line 17).The monkeypatches are deployed after this check at line 27  in  the __init__.py .
=> [MRG+1] Update _monkeypatches.py

docs/topics/developer-tools.rst, docs/topics/dynamic-content.rst, docs/topics/request-response.rst, pytest.ini, scrapy/http/request/__init__.py, scrapy/utils/curl.py, tests/test_http_request.py, tests/test_utils_curl.py
This is a WIP, but I open this PR to discuss how to implement this feature. 
Based on: https://github.com/scrapy/scrapy/pull/2985 (abandoned)
=> [MRG+1] Create Request from curl command 

scrapy/extensions/feedexport.py, tests/test_feedexport.py
Since it's not too rare a case to have special characters involved in the password.
=> [MRG+1] Added: Properly handling quoted passwords in FEED_URI for FTP

scrapy/utils/project.py
As mentioned by @Gallaecio in issue #3871, the 'hack'  is cleared. I also  double checked whether the environment variable "SCRAPY_PICKLED_SETTINGS_TO_OVERRIDE" was ever set in our codebase and it turns out we didn't set it or used it anywhere else.So I guess the 'hack' was not used in the current version.
=> [MRG+1] Update project.py removed one 'hack', seems irrelevant.

scrapy/utils/ssl.py, scrapy/utils/versions.py
After the recent updates of #3892 the minimum package versions for `w3lib` and `pyOpenSSL` were upgraded beyond the cases considered in the existing checks, I think those checks are not needed anymore.
Also, I'm sure there is a historical reason for catching `ImportError` on `cryptography`, but it is also required in `setup.py` so it should always be available for import.
=> [MRG+1] Simplify version reporting

scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/handlers/http11.py, scrapy/core/downloader/tls.py
Removing more version checks after bumping minimum package versions in #3892 (Twisted, pyOpenSSL)
I must admit, in the last commit I might have got too excited about indentation and PEP8 (but not the 79-char limit), so feel free to disregard that one (hopefully you won't :crossed_fingers: :smile:)
=> Remove obsolete version checks

docs/topics/settings.rst, scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/handlers/http11.py, scrapy/settings/default_settings.py, scrapy/utils/ssl.py, tests/mockserver.py, tests/test_downloader_handlers.py, tests/test_webclient.py
This adds the `DOWNLOADER_CLIENT_TLS_CIPHERS` setting which is then used in `ScrapyClientContextFactory`. There is a real-world example of when it may be needed in #3392 (the server offers a cipher that is rejected by the client so we need to not advertise it), there are other theoretical  problems e.g. a server supports only ciphers that are supported by the client but disabled. I've constructed the second case in the tests because constructing the first case seems to be impossible with a modern OpenSSL.
There are two tests, the one in `tests/test_webclient.py` uses `ScrapyClientContextFactory` directly (its base class also just tests the default context factory with the default SSL server) and the one in `tests/test_downloader_handlers.py` uses the setting and the download handler. I …
=> Support for overriding OpenSSL ciphers

docs/topics/downloader-middleware.rst, scrapy/robotstxt.py, tests/test_robotstxt_interface.py, tox.ini
[For Google Summer of Code 2019] Make Scrapy support [Protego](https://github.com/anubhavp28/protego) robots.txt parser.
=> [GSoC 2019] Adds integration with Protego robots.txt parser.

docs/topics/downloader-middleware.rst, docs/topics/settings.rst, scrapy/downloadermiddlewares/robotstxt.py, scrapy/settings/default_settings.py, tests/test_downloadermiddleware_robotstxt.py
=> Adds ROBOTSTXT_USER_AGENT setting

docs/news.rst, docs/topics/request-response.rst, scrapy/http/__init__.py, scrapy/http/request/json_request.py, tests/test_http_request.py
Change `JSONRequest` to `JsonRequest` to follow the same format/style as the other JSON classes (`JsonLinesItemExporter`, `JsonItemExporter` and `JsonWriterPipeline`) and the other response/request classes (`HtmlResponse`, `XmlResponse`, `XmlRpcRequest`)
fixes:
* issue: https://github.com/scrapy/scrapy/issues/3929
* old PR: https://github.com/scrapy/scrapy/pull/3930
=> Fix JSONRequest naming

docs/topics/contracts.rst, scrapy/contracts/__init__.py, scrapy/contracts/default.py, scrapy/settings/default_settings.py, tests/test_contracts.py
Fixes #3985
~This patch works _partially_, in the sense that it prevents the reported `TypeError` (I checked, for instance by adding a simple `print(request.cb_kwargs)` to https://github.com/scrapy/scrapy/blob/1.7.3/scrapy/core/scheduler.py#L90, and the generated request does include a valid `cb_kwargs` attribute). However, adding the `@cb_kwargs` contract causes the whole callback to be excluded from the tests, and I can't for the life of me figure out why.~
Update: Working now, thanks to @victor-torres :rocket: 
Remaining tasks:
=> CallbackKeywordArgumentsContract

scrapy/pipelines/files.py, tests/test_pipeline_files.py
If a media extension is empty string or is unregistered with [IANA](http://www.iana.org/assignments/media-types), then try to guess the MIME type from the url then the extension from MIME type using built-in `mimetypes` lib..
Fixes #3953, fixes #1287
=> Disallow media extensions unregistered with IANA 

docs/topics/spiders.rst, scrapy/spiders/crawl.py, tests/test_spider.py
=> Crawling rules: make link extractors optional

scrapy/utils/request.py
Fixes #3597
While this change will not be necessary after #3975 is merged, that could take a while, or not happen at all.
=> Fix documentation typo: accesible → accessible

docs/conf.py, docs/topics/items.rst, scrapy/item.py, tests/test_item.py
As part of these changes I was going to document `scrapy.item.DictItem`. However, trying to understand its purpose, I came to the conclusion that it is a leftover that no longer has a purpose, so in this set of changes I’m deprecating it.
I believe it was introduced in decbdc534644384c18a603dc35650b044d0b5a0a so that `DjangoItem` could have everything that `Item` has but using a different metaclass. However, [`Item` seems to be currently used in scrapy-djangoitem instead](https://github.com/scrapy-plugins/scrapy-djangoitem/blob/bfe9622c2e618bcd117ce248fb3a2d463f24bce1/scrapy_djangoitem/__init__.py).
I am not 100% sure about `scrapy.item.DictItem` no longer having a purpose, though. So please, look into it for yourselves before approving these changes.
=> Provide complete API documentation coverage of scrapy.item

scrapy/commands/parse.py, scrapy/commands/runspider.py, tests/test_command_parse.py
This is a small straight forward refactor to avoid creating a list or keyview object ( list in 2.x and key in 3.x ). 
There are other folders where this change can be made but starting with commands folder.
=> remove .keys() to avoid creating a tmp list/keyview obj

docs/topics/downloader-middleware.rst, docs/topics/settings.rst, requirements-py2.txt, requirements-py3.txt, scrapy/settings/default_settings.py, setup.py, tox.ini
Implementation of proposal https://github.com/scrapy/scrapy/issues/3969
=> Use protego as a default robots.txt parser

scrapy/extensions/corestats.py, tests/test_stats.py
=> Fix TypeError when using DummyStatsCollector

docs/topics/request-response.rst
As suggested in https://github.com/scrapy/scrapy/pull/4054#discussion_r330207869, plus other wording fixes.
=> [Doc] Use autoclass in topics/request-response.rst

docs/topics/settings.rst
Issue https://github.com/scrapy/scrapy/issues/4072
=> Fixed BOT_NAME documentation

extras/scrapy_zsh_completion
Features:
- full option completion
- automatic project detection
- spider name completion
=> update zsh completion

docs/intro/install.rst
The previous link was a 404 (https://conda.io/docs/user-guide/install/index.html)
I updated to https://docs.conda.io/en/latest/miniconda.html
EDIT: https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html
=> Updating link for miniconda

scrapy/extensions/feedexport.py, tests/test_feedexport.py
=> Fix windows file descriptor leak

.travis.yml, docs/topics/downloader-middleware.rst, scrapy/extensions/httpcache.py, setup.py, tests/test_downloadermiddleware_httpcache.py, tox.ini
=> Add Python 3.8 official support

docs/news.rst, docs/topics/logging.rst, scrapy/logformatter.py
Last covered commit: 7731814cc25c57fe31db9ba749450cd5a27eed39
Also covers #4092
=> Cover Scrapy 1.8.0 in the release notes

scrapy/utils/request.py, tests/test_utils_request.py
w3lib's canonicalize_url has an option to keep fragments but it is not accessible from scrapy's request_fingerprint method, so it's impossible without changing scrapy's code to make a custom dedupe filter which would keep urls identical except for fragments.
We need this in our webcrawler Hyphe for our future headless crawling feature using chromedriver (currently developed in https://github.com/medialab/hyphe/pull/288 ) to crawl modern websites with routing included in the fragment.
For what I understand the solution discussed in #4067 using `dont_filter=False` on each query would completely disable deduping for the spider which is not an option for a crawler that adds new links from each crawled page as it would then run indefinitely in loop
cc @arnaudmolo
=> Allow not to dedupe urls with different fragments

tests/mockserver.py, tests/test_crawler.py
Fixes #4014
When using pipes, and we are using a pipe for `stdout` in `MockServer`, you are meant to call `process.communicate()` instead of `process.wait()`.
This was causing unexpected warnings in `test_crawler.py` tests, when the garbage collection happened to warn about unclosed resources while one of the affected tests was capturing warnings.
I’ve run the tests a few rounds with this fix, and it seems to have worked.
=> Use communicate() instead of wait() after killing the mock server

extras/scrapy_zsh_completion
Look for `.html` files instead of `.http` when completing `scrapy shell` command.
=> fix zsh completion file extension

docs/conftest.py, pytest.ini, tests/requirements-py3.txt, tox.ini
The documentation is now searched for code examples to test.
I’ve marked all currently-failing pages as ignored, to be fixed in later changes. Probably after I find a solution for https://github.com/cjw296/sybil/issues/16.
=> Set the bases for testing code examples from the documentation

docs/topics/jobs.rst
=> Improve the details about request serialization requirements for JOBDIR

scrapy/utils/datatypes.py, tests/test_utils_datatypes.py
Taken from https://github.com/scrapy/scrapy/pull/3869/files#r342049190
This piece of code can fail with `TypeError: '>=' not supported between instances of 'int' and 'NoneType'`
I think this patch is smaller and easier than #3869, it can be merged earlier.
=> Fix LocalCache limit issue, add tests

scrapy/linkextractors/__init__.py
I run into downloading large files while scraping
Fixes #1837, fixes #2067
=> Add .dmg, .iso & .apk to ignored other extensions

CODE_OF_CONDUCT.md, README.rst
Added some periods where missing in readme and code of conduct.
=> Make punctuation consistent

pytest.ini, tests/test_downloader_handlers.py, tests/test_downloadermiddleware_httpcache.py
Fix `E711` ("Comparison to none should be 'if cond is none:'") and `E713` ("Test for membership should be 'not in'")
=> fix E711 and E713

scrapy/utils/reactor.py
This should be the proper ordering.This is the explanation.
If `'not portrange'` is True ,it is guaranteed that `not hasattr(portrange, '__iter__')`  is also True  the converse of this is not always true.(for example, consider portrange=None, for such case we were executing the logic for `not hasattr(portrange, '__iter__')` . ).Such case is eliminated by this PR.
=> Update reactor.py, updated 'if' sequencing .

scrapy/core/scraper.py, scrapy/logformatter.py, tests/test_logformatter.py
Fixes #3986
~I'll add tests shortly~ Done
=> LogFormatter improvements

scrapy/http/request/__init__.py, tests/test_http_request.py
This PR should fix issue #2552 by improving the request schema validation on its initialization. 
The implementation is based on feedback posted by @pawelmhm and @hsumerf
=> Improve URL schema validation on scrapy.Request initialization

docs/requirements.txt
With #4152 I broke the documentation build, because in Read the Docs we are installing the requirements from `/requirements-py3.txt`, and #4152 introduced into `/docs/requirements.txt` a new requirement that is not installed in Read the Docs by default.
After this change, I count on fixing the Read the Docs build by changing the requirements file in Read the Docs to `/docs/requirements.txt`.
=> Include /requirements-py3.txt from /docs/requirements.txt

scrapy/utils/python.py, tests/test_utils_python.py
https://lgtm.com/rules/4850080/
=> MutableChain: return self from __iter__

docs/topics/loaders.rst, scrapy/loader/__init__.py, tests/test_loader.py
Python 3 only: `__qualname__` was added in Python 3.3 ([PEP 3155](https://www.python.org/dev/peps/pep-3155/)). I thought about a py2-compatible version using `six.get_method_function` (which accesses `__func__` in py3 and `im_func` in py2) and doing some regex checks on the obtained function's name, but that wasn't pretty. Since we're dropping py2 support soon and this is technically backward incompatible I figured it would be ok to leave this for Scrapy 2.0
Initially reported in #2735
=> [Py3] Item loaders: allow single argument functions as processors

scrapy/crawler.py
This commit use pprint.pformat on overridden settings to keep consistent
with scrapy.middleware, for example:
Original:
```
2019-11-28 22:23:57 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'spider_demo', 'NEWSPIDER_MODULE': 'spider_demo.spiders', 'SPIDER_MODULES': ['spider_demo.spiders'], 'USER_AGENT': 'Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36'}
2019-11-28 22:23:57 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
'scrapy.extensions.telnet.TelnetConsole',
'scrapy.extensions.memusage.MemoryUsage',
'scrapy.extensions.logstats.LogStats']
```
```
2019-11-28 22:23:57 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'spider_demo',
'NEWSPIDER_MODULE': …
```
=> Use pprint.pformat on overridden settings

docs/topics/loaders.rst
Attempts to clear up the doc misunderstanding in #3574 that results in wrong expected behavior due to incorrect usage.
Fixes #3574
=> update docs of scrapy.loader.ItemLoader.item

scrapy/downloadermiddlewares/httpproxy.py
This commit re-arranges the imports in the httpproxy module to follow
pep8
=> Re-arrange the imports in the httpproxy module

scrapy/downloadermiddlewares/httpcache.py
This commit re-arrange the imports in httpcache module to follow pep8
=> Re-arrange the imports in httpcache module

docs/intro/overview.rst
There exists an inconsistency between the code (line 37 - 38) and the output 'quotes.json' (line 56 - 68). 
Note that even though according to line 53 - 54  'quotes.json' is "reformatted here for better readability", it cannot explain why the "author" field precedes the "text" field. 
Intended output for the code BEFORE change: 
[{
"text": "\u201cThe person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.\u201d",
"author": "Jane Austen"
},
{
"text": "\u201cOutside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.\u201d",
"author": "Groucho Marx"
},
{
"text": "\u201cA day without sunshine is like, you know, night.\u201d",
"author": "Steve Martin"
},
...]
Intended output for the code After change (the inconsistency is …
=> Update overview.rst | Fix an inconsistency

pytest.ini, scrapy/core/downloader/webclient.py, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/exporters.py, scrapy/settings/default_settings.py, scrapy/spiders/feed.py, scrapy/utils/console.py, tests/test_command_fetch.py, tests/test_downloader_handlers.py, tests/test_engine.py, tests/test_http_request.py, tests/test_pipeline_media.py, tests/test_spidermiddleware_referer.py, tests/test_utils_defer.py, tests/test_utils_spider.py
Please, pay special attention to the change to `tests/test_engine.py`. I’m hoping tests will pass, but even if they do, I wonder what consequences this change may have.
I also removed a class from a test file, as it did not seem used anymore.
=> Keep 2 spaces between code and inline comments

scrapy/mail.py
When the file name consists of alphanumeric characters, it is normal to receive the attachment name.
However，However, problems will occur if the file name is changed to Chinese.
This has nothing to do with the file type
Fixes #4229
=> Fix mail attachs tcmime *** (#4229)

scrapy/core/downloader/handlers/http11.py, tests/test_downloader_handlers.py, tests/test_proxy_connect.py
This deprecates the noconnect mode for HTTPS proxies and removes related tests. As the mode was made for old Crawlera, it doesn't look like anything else needs it.
scrapy_crawlera version is important because before 1.3.0 it added '?noconnect' to all Crawlera URLs automatically.
Closes: #4187 (as not needed anymore).
=> Deprecate the HTTPS proxy noconnect mode.

tests/test_crawl.py
Take the ~30s `DOWNLOAD_DELAY` test (see #4163) and split it in 2 ~2s tests.
=> Improve the performance of the DOWNLOAD_DELAY test

.readthedocs.yml, .travis.yml
I broke the build changing it to 3.8 in #4140, it turns out Read The Docs does not support 3.8 yet.
=> Use Python 3.7 to build the documentation

scrapy/core/scraper.py, scrapy/utils/datatypes.py, scrapy/utils/misc.py, tests/test_utils_datatypes.py, tests/test_utils_misc/test_return_with_argument_inside_generator.py
Fixes #3484
I also considered a version using `ast.NodeVisitor`, I think the `walk`-based solution _should_ be more efficient since it can stop the iteration if the conditions are satisfied, while the `NodeVisitor` class would visit _all_ `Return` nodes.
```python
class ReturnNodeVisitor(ast.NodeVisitor):
def __init__(self, *args, **kwargs):
super(ReturnNodeVisitor, self).__init__(*args, **kwargs)
self.return_value = False
def visit_Return(self, node):
"""
Sets the 'return_value' instance variable to True if the value returned
by the node is not None (either explicitly or implicitly)
"""
if not is_safe_return_node(node):
self.return_value = True
def check_gen_with_no_none_return_visitor(callable):
"""
Logs a warning if a callable is a generator function and includes
a 'return' statement …
```
=> [MRG+1][Py3] Check for 'return' with arguments inside generators

scrapy/exporters.py
https://lgtm.com/rules/5990072/
This change is not necessary from a functional perspective, but instead of marking the code to be ignored, I though it may be best to switch to an implementation that allows calling `super().__init__`.
=> Use super().__init__ in BaseItemExporter subclasses

docs/intro/install.rst
The link "https://lxml.de" is redirecting to a completely different and unintended website. I changed the link to the index page of lxml's official website. I thought of changing it to the PyPi page of lxml, but even they are providing the same "https://lxml.de" link which doesn't seem to be working now.
=> Edited the link provided to homepage of lxml's website

docs/topics/settings.rst, scrapy/core/scraper.py, scrapy/settings/default_settings.py
This PR fixes https://github.com/scrapy/scrapy/issues/1410
In our setup we had urls that were bigger than 5Mb (the default value) and we were reaching a deadlock scenario.
These changes allow for configuration of the `max_active_size` by setting the `SCRAPER_SLOT_MAX_ACTIVE_SIZE` configuration.
Thanks!
=> [MRG+1] Add ability to change max_active_size by setting

docs/intro/tutorial.rst
I did not test this code, but the change from `href` to this
`author_page_links` seems to have a typo ?
=> [Docs] Fix variable name `author_page_links`

scrapy/downloadermiddlewares/retry.py
=> [MRG+1] change _retry() in RetryMiddleware log from debug to error

scrapy/downloadermiddlewares/httpcompression.py, tests/test_downloadermiddleware_httpcompression.py
Accept-Encoding header should have `, `  (with space) as a delimiter between encodings instead of `,` (non space) (https://tools.ietf.org/html/rfc2616#section-14.3)
=> [HttpCompressionMiddleware] fix delimiter for Accept-Encoding header

docs/topics/downloader-middleware.rst
Fixing 2 small typos and adding 1 word as clarification in the downloader-middlewares.
Also, I was confused with the entries like `ref:Reppy <reppy-parser>` and similar entries.
Are these supposed to be links to other parts of the doc, or is this the intended way of showing these references ?
=> [Docs] 2 typos + 1 clarification in docs

scrapy/utils/spider.py, tests/spiders.py, tests/test_crawl.py
This is not very useful yet, as it doesn't allow `yield` in callbacks, but it's a first step.
=> Support for async def callbacks.

scrapy/dupefilters.py, tests/test_dupefilters.py
Hey guys, found another small non-breaking glitch that I'm not sure if anybody else noticed that existed since RFPDupfilter was implement back on commit 549725215e79fbd3c7b3590c2a47fc9c0ad30a1b that's specific to Windows and the RFPDupeFilter used in Scrapy. It looks like when RFPDupeFilter writes its request hashes to the `requests.seen` file for a job, it seems to be using [Python's universal newlines](https://docs.python.org/3.8/library/functions.html#open-newline-parameter) feature incorrectly and ends up writing '\r\r\n' as each line ending instead of '\r\n', though it works fine in Linux and writes '\n' as expected.
Here's an example file demonstrating what's happening, opened in Notepad++ and a Hex editor with one of the line endings highlighted:
I've tested this PR (using a …
=> Updated RFPDupeFilter line separator for correct universal newlines mode usage.

docs/news.rst
@Gallaecio created an issue #4264, in which I had to add in the backward-incompatible changes that scrapy 1.7.0 version breaks custom schedulers. 
I have added it to **news.rst**, please check it out and let me know if it needs to be more thorough.
I have ran all the tests using **tox**
(edit) Fixes #4264
=> added custom scheduler breakage in news.rst

tests/spiders.py, tests/test_crawl.py
=> Add a test for an async callbacks that returns requests.

scrapy/core/spidermw.py, scrapy/utils/python.py, tests/test_spidermiddleware_output_chain.py
Fixes #4260.
Evaluates the output iterable right after the spider callback, as it's currently being done in the `process_spider_output` chain.
(Plus some minor styling adjustments)
=> Spider middleware: catch spider callback exceptions early

docs/topics/media-pipeline.rst
Documented signature doesn't match the actual interface in [files.py](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/files.py#L520).
Specifically, it looks like it may be [called](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/files.py#L422) without a response value.
I found this when I was implementing the pipeline with the signature `file_path(self, request, response, info)` and the following error was being return in my results :
[(False, <twisted.python.failure.Failure builtins.TypeError: file_path() missing 1 required positional argument: 'response'>)]
Scrapy==1.8.0
=> FilesPipeline.file_path has optional arguments

extras/scrapy_zsh_completion
This PR adds autocompletion for `-h` option for zsh. 
This option was not added to #4069 due to the problem described in [this so question](https://stackoverflow.com/q/58312199/5745120).
=> add zsh -h autocomplete option

docs/conf.py
The current link for the Twisted API is not working for me when I generate the docs. There are no public links to show, since this change has not been deployed to the main docs yet.
=> [Docs] Fix Twisted links

scrapy/utils/project.py
Related to issue: https://github.com/scrapy/scrapy/issues/3871
=> Deprecate overriding settings with SCRAPY-prefixed environment variables

docs/intro/install.rst
Simplify by not repeating information that can be found in upstream, linked documentation.
Fixes #4001, closes #4101
=> Update installation instructions regarding Python 3 and virtual environments

docs/intro/tutorial.rst, docs/topics/downloader-middleware.rst, docs/topics/extensions.rst, docs/topics/feed-exports.rst, docs/topics/jobs.rst, docs/topics/link-extractors.rst, docs/topics/request-response.rst, docs/topics/selectors.rst, docs/topics/settings.rst, docs/topics/signals.rst, scrapy/shell.py, scrapy/utils/misc.py, scrapy/utils/request.py, scrapy/utils/spider.py, sep/sep-003.rst, sep/sep-013.rst, sep/sep-021.rst
changed ie. -> i.e.(spelling error) on lines 667, 763 (issue scrapy#4332)
=> Updated scrapy/docs/topics/request-response.rst  #4332

scrapy/linkextractors/lxmlhtml.py, tests/test_linkextractors.py
Fixes #1403, fixes #998 (https://github.com/scrapy/scrapy/issues/998#issuecomment-247001012), closes #1949
There are 2 test output changes:
- 1 test change is to adjust expectations to those reported at https://github.com/scrapy/scrapy/pull/1949#issuecomment-212954241 in line with the issue being fixed
- Another test change consists of link extractors encoding whitespace, something they [stopped doing in 1.4.0](https://github.com/scrapy/scrapy/commit/2b4d46315f2ce7ce20e7355fe4ad184bb041d6f4) and would be doing again now. I don’t think it is a major issue, and in fact I find it weird that everything in the path was quoted but whitespace, so it may even be a change for the better, consistency-wise.
=> Use safe_url_string in link extraction

scrapy/core/scraper.py, scrapy/logformatter.py, tests/test_logformatter.py
Fixes #374
It also fixes a small compatibility issue introduced in #3989: the simple quotes in the [new message](https://github.com/scrapy/scrapy/pull/3989/files#diff-30acb9d6d17690962b4ffab6297b39c3R11) were not present in the [original one](https://github.com/scrapy/scrapy/pull/3989/files#diff-efe9358e1656d355258b3d73c1a4d189L234).
I originally wanted to make this change as part of the above PR, I think there should be no problems with the renaming (`LogFormatter.error` -> `LogFormatter.item_error`) since that patch was not released yet.
=> LogFormatter error formatting

scrapy/shell.py
It was 6 years ago when this deprecation warning was added, before Scrapy 1.0 was released.
Could we remove it when releasing the new Scrapy 2.0 version?
=> Remove deprecated `sel` shortcut in scrapy shell

pytest.ini, scrapy/core/downloader/tls.py, scrapy/core/engine.py, scrapy/responsetypes.py, scrapy/utils/console.py, scrapy/utils/gz.py, tests/test_command_parse.py, tests/test_crawler.py, tests/test_dependencies.py, tests/test_downloadermiddleware_cookies.py, tests/test_downloadermiddleware_httpcache.py, tests/test_downloadermiddleware_redirect.py, tests/test_exporters.py, tests/test_http_response.py, tests/test_item.py, tests/test_mail.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_pipeline_media.py, tests/test_responsetypes.py, tests/test_utils_conf.py, tests/test_utils_defer.py, tests/test_utils_deprecate.py, tests/test_utils_iterators.py, tests/test_utils_python.py, tests/test_utils_request.py, tests/test_utils_template.py, tests/test_utils_url.py, tests/test_webclient.py
This PR fixes all the exceptions to the E30X rules of flake8:
* E301: Expected 1 blank line, found 0 --> 1 case
* E302: Expected 2 blank lines, found 0 --> 0 cases
* E303: Too many blank lines --> 12 cases
* E304: Blank lines found after function decorator --> 0 cases
* E305: Expected 2 blank lines after end of function or class --> 16 cases
* E306: Expected 1 blank line before a nested definition --> 11 cases
=> fix E30X flake8

scrapy/utils/python.py
Hi there!
I deleted 4 deprecated functions from `scrapy.utils.python` (as mentioned here: https://github.com/scrapy/scrapy/issues/4356), the deprecation warnings were added in 07/2015 for three of them and in 03/2016 for the other.
As they are in the same file I decided to do just one PR, but if you prefer I can separate them in different PRs. There are two more deprecated functions in this file but as they were deprecated in 2019 I decided not to change them. Let me know what you think. :slightly_smiling_face:
=> delete old deprecated functions from scrapy.utils.python

pytest.ini, scrapy/utils/iterators.py, tests/test_downloadermiddleware_httpcompression.py, tests/test_item.py, tests/test_pipeline_crawl.py, tests/test_pipeline_files.py, tests/test_squeues.py, tests/test_utils_python.py, tests/test_utils_url.py
This fixes the next flake8 rules:
* E131: Continuation line unaligned for hanging indent --> 1 affected file
* E211: Whitespace before '(' --> 1 affected file
* E251: Unexpected spaces around keyword / parameter equals --> 2 affected files
* E271: Multiple spaces after keyword --> 1 affected file
* E701: Multiple statements on one line (colon) --> 5 affected files
=> Fix flake8 E131, E211, E251, E271, E701

scrapy/exporters.py
Make the new `dont_fail` parameter of `BaseItemExporter` keyword only.
Otherwise, we are adding an non-intuitive positional parameter to a class that used to require keyword parameters only.
`dont_fail` was introduced after 1.8, so it would be great to have this change in for 2.0, otherwise we will need to introduce this change with a deprecation message for positional argument usages.
Split out from #4329
=> Make BaseItemExporter’s dont_fail parameter keyword-only

docs/conf.py, docs/contributing.rst, docs/faq.rst, docs/intro/install.rst, docs/intro/tutorial.rst, docs/news.rst, docs/topics/broad-crawls.rst, docs/topics/downloader-middleware.rst, docs/topics/dynamic-content.rst, docs/topics/item-pipeline.rst, docs/topics/items.rst, docs/topics/leaks.rst, docs/topics/request-response.rst, docs/topics/selectors.rst, docs/topics/shell.rst, docs/topics/spiders.rst
=> Documentation linkcheck run, fixing some links.

scrapy/utils/project.py, tests/test_utils_project.py
Noticed by @nyov.
I’m thinking that this is technically backward-incompatible. Before, we were actually defining a `SETTINGS_MODULE` setting, and potentially other variables. Should I just whitelist warning-wise but still allow the setting to be defined?
Do we issue a specific warning about that? i.e. If a setting named after one of those white-listed variables is read from `Settings`, warn about it.
To-Do:
Fixes #4374
=> Stop deprecation warnings on arbitrary SCRAPY-prefixed env vars

scrapy/spidermiddlewares/offsite.py, tests/test_spidermiddleware_offsite.py
`allowed_domains = [None]` leads to the following exception:
```
2020-03-07 20:40:02 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method OffsiteMiddleware.spider_opened of <scrapy.spidermiddlewares.offsite.OffsiteMiddleware object at 0x7f57c2a22d60>>
File "/home/lukas/Projects/3rd/scrapy/scrapy/utils/defer.py", line 161, in maybeDeferred_coro
result = f(*args, **kw)
File "/home/lukas/.pyenv/versions/3.8.2/envs/scrapy/lib/python3.8/site-packages/pydispatch/robustapply.py", line 55, in robustApply
return receiver(*arguments, **named)
File "/home/lukas/Projects/3rd/scrapy/scrapy/spidermiddlewares/offsite.py", line 67, in spider_opened
self.host_regex = self.get_host_regex(spider)
File …
```
=> Fix handling of None in allowed_domains

docs/topics/feed-exports.rst, scrapy/commands/crawl.py, scrapy/commands/runspider.py, scrapy/extensions/feedexport.py, scrapy/settings/default_settings.py, scrapy/utils/conf.py, tests/test_commands.py, tests/test_feedexport.py, tests/test_utils_conf.py
Fixes #1336
Introduced a new setting (`FEEDS`) and deprecated `FEED_URI` and `FEED_FORMAT`. `FEEDS` is a dictionary of feed definitions, which enables the user to override certain parameters independently for each feed. An example of this can be seen at https://github.com/scrapy/scrapy/pull/3858#issuecomment-511924714
In the CLI, format is deduced according to https://github.com/scrapy/scrapy/issues/1336#issuecomment-125750712, falling back to the feed extension.
A simple snippet to illustrate:
```python
import scrapy
class ExampleSpider(scrapy.Spider):
name = 'example'
start_urls = ['https://example.org']
return {
'url': response.url,
'link': response.xpath('//a/@href').get(),
}
```
```
$ scrapy runspider example.py -o items.dat:jsonlines -o jitems.json -o …
```
=> [MRG+1] Support for exporting to multiple feeds in a single crawl

scrapy/http/response/text.py, tests/test_http_response.py
=> Response.follow_all: return empty generators for empty sequences

scrapy/spiders/__init__.py, tests/test_spider.py
Follow-up for #1728, 
Blocking #4178
=> Deprecate Spider.make_requests_from_url, part 2

scrapy/spidermiddlewares/offsite.py, tests/test_spidermiddleware_offsite.py
Fix for issue #50, see discussion there for a rationale.
Note that this PR is based on PR #4410 and would make PR #3198 obsolete.
Fixes #50, closes #3198
=> Ignore a domain in allowed_domains with port and issue a warning

tests/requirements-py3.txt
Let us see if that’s what is breaking the tests.
=> Restrict pytest to versions prior to 5.4

docs/topics/settings.rst, scrapy/core/downloader/__init__.py, scrapy/core/downloader/handlers/ftp.py, scrapy/core/downloader/handlers/http10.py, scrapy/core/downloader/handlers/http11.py, scrapy/extensions/closespider.py, scrapy/mail.py, scrapy/utils/benchserver.py, scrapy/utils/testproc.py, scrapy/utils/testsite.py
- Error occured when TWISTED_REACTOR in settings.py was set
- remove all top-level imports for twisted.internet.reactor
- add example, reason for top-level imports in TWISTED_REACTOR in `docs/settings.rst`
Fixes #4401
=> [fix] wrong reactor installed error

scrapy/crawler.py, tests/test_crawler.py
Two commits,
the 1st removing `Crawler.spiders`; deprecated since 4190266 (2014, Scrapy 0.25)
~the 2nd removing `CrawlerRunner.spiders`; deprecated since ad587ea (2015, Scrapy 0.25.1)~
~Adding `SPIDER_MANAGER_CLASS` to `scrapy/settings/deprecated.py` is somewhat too late, just for completeness' sake; so it's been there and can be removed again next commit?~
=> Remove deprecated Crawler.spiders property

extras/scrapy_zsh_completion
- Fix bug introduced in https://github.com/scrapy/scrapy/pull/4291
- Enforce `[command] [options] [arguments]` syntax. Do not allow options after arguments
- Exclude already used option aliases from completion list
=> edit zsh completion

setup.py
Compare "Project Links" section from [scrapy pypi page](https://pypi.org/project/Scrapy/) with [one for doit](https://pypi.org/project/doit/)
=> Project URLs in machine-readable format for showing in pypi

scrapy/core/downloader/handlers/http11.py
We are already [requiring Twisted>17](https://github.com/scrapy/scrapy/blob/2.0.1/setup.py#L71). Relevant tests [here](https://github.com/scrapy/scrapy/blob/2.0.1/tests/test_downloader_handlers.py#L322-L348).
=> Remove empty _RequestBodyProducer for POST requests

pytest.ini, scrapy/commands/genspider.py, scrapy/commands/shell.py, scrapy/core/downloader/middleware.py, scrapy/core/engine.py, scrapy/mail.py, scrapy/utils/deprecate.py, tests/test_pipeline_media.py
Related to #4237, #4392, #4468
=> Fix pycodestyle E502 ("the backslash is redundant between brackets")

pytest.ini, scrapy/core/downloader/tls.py, scrapy/dupefilters.py, scrapy/pipelines/files.py, scrapy/pipelines/images.py, scrapy/pipelines/media.py, tests/test_crawl.py, tests/test_downloadermiddleware_cookies.py, tests/test_http_response.py, tests/test_spidermiddleware_referer.py, tests/test_utils_iterators.py, tests/test_utils_url.py, tests/test_webclient.py
Most of the changes are to test files.
This PR deals with E2XX errors exclusively: for instance, the changed lines in `tests/test_webclient.py` are still affected by E122 ("continuation line missing indentation or outdented")
Some of the above changes conflict with #4392 (please take alook @noviluni)
=> Fix pycodestyle E2XX (whitespace)

docs/conf.py, docs/requirements.txt, docs/topics/downloader-middleware.rst, docs/topics/settings.rst
It's green! :heavy_check_mark: 
Closes #4475
=> Pin version for Sphinx and extensions, configure hoverxref

scrapy/core/downloader/middleware.py, scrapy/pipelines/media.py, tests/test_feedexport.py, tests/test_pipeline_media.py, tests/test_spidermiddleware_output_chain.py
Fixes #4443, closes #4446 
The underlying memory leak issue seems to remain, we just need to check for a different exception class now. The following failures appear if the context is not cleared:
<details>
<summary>Test session</summary>
```
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
cachedir: .tox/py36/.pytest_cache
rootdir: /.../scrapy, inifile: pytest.ini
plugins: xdist-1.31.0, forked-1.1.3, twisted-1.12, cov-2.8.1
collected 27 items …
```
=> Remove twisted.internet.defer.returnValue occurrences

docs/topics/developer-tools.rst, docs/topics/dynamic-content.rst, scrapy/http/request/__init__.py
Added mention of curl2scrapy tool in Docs referring to Request.from_curl
Resolves: #4206 
See also #3991
=> [Docs] mention curl2scrapy in Request.from_curl

docs/conf.py, tox.ini
=> Fix the hoverxref configuration

scrapy/utils/reqser.py, tests/test_utils_reqser.py
You could define a spider attribute that references a callback method
but if this method has a different name than your spider attribute,
the request serializer is not able to find it on the spider class.
With this commit we're fixing this behavior as we're searching for
callback references in the spider object itself instead of looking
for attributes with the same function's name, that could be different.
=> Serialize requests with callback references as spider attribute

docs/topics/settings.rst
In setup.py more recent versions are required, so there is no need to warn users about require Twisted and pyopenssl versions in docs.
=> Don't mention unsupported package versions in docs

scrapy/pipelines/files.py
Added a warning in case of lack of read access to GCS bucket used with `FilePipeline` and error in case of lack of write access (as it makes it impossible to upload files). Incorrect GCS permissions could be the cause of a problem described in #4346 .
=> Add a warning/error in case of incorrect gcs permissions

pytest.ini, scrapy/core/downloader/handlers/ftp.py, scrapy/core/engine.py, scrapy/utils/deprecate.py, scrapy/utils/request.py, tests/spiders.py, tests/test_closespider.py, tests/test_downloader_handlers.py, tests/test_downloadermiddleware_decompression.py, tests/test_downloadermiddleware_redirect.py, tests/test_http_request.py, tests/test_selector.py, tests/test_spidermiddleware_httperror.py, tests/test_utils_url.py
_Continuation line over-indented for visual indent_
=> Flake8: remove E127

pytest.ini, scrapy/core/downloader/handlers/ftp.py, scrapy/core/engine.py, scrapy/extensions/closespider.py, scrapy/http/request/form.py, scrapy/pipelines/media.py, scrapy/utils/deprecate.py, scrapy/utils/request.py, tests/spiders.py, tests/test_closespider.py, tests/test_downloader_handlers.py, tests/test_downloadermiddleware_decompression.py, tests/test_downloadermiddleware_httpcompression.py, tests/test_downloadermiddleware_redirect.py, tests/test_http_request.py, tests/test_scheduler.py, tests/test_selector.py, tests/test_spidermiddleware_httperror.py, tests/test_spidermiddleware_referer.py, tests/test_utils_url.py, tests/test_webclient.py
_Closing bracket does not match indentation of opening bracket's line_
Based on #4539, which is in turn based on #4538, to avoid merge conflicts.
Relevant changes in 8643e8d3557449393989b15b9b8f2ec813f3e6ad
=> Flake8: remove E123

.travis.yml, tox.ini
I did not realize that, due to https://github.com/scrapy/scrapy/commit/fc3af54dbd5b7fdcbc44c82ba4ced528a104cd88#diff-b91f3d5bd63fcd17221b267e851608e8R7, removing TOXENV from Travis CI entries would cause security and Flake8 checks to be run in those jobs as well.
=> Travis CI: do not run security and Flake8 on multiple jobs

pytest.ini, tests/test_dupefilters.py, tests/test_exporters.py, tests/test_linkextractors.py, tests/test_utils_sitemap.py, tests/test_webclient.py
* Continuation line missing indentation or outdented (E122)
* Closing bracket does not match visual indentation (E124)
=> Flake8: remove E122 and E124

pytest.ini, tests/test_utils_iterators.py
_Visually indented line with same indent as next logical line_
=> Flake8: remove E129

docs/conf.py, scrapy/downloadermiddlewares/ajaxcrawl.py, scrapy/spiderloader.py, scrapy/templates/project/module/items.py.tmpl, scrapy/templates/project/module/middlewares.py.tmpl, scrapy/templates/project/module/pipelines.py.tmpl, scrapy/templates/project/module/settings.py.tmpl, scrapy/templates/spiders/basic.tmpl, scrapy/templates/spiders/crawl.tmpl, scrapy/templates/spiders/csvfeed.tmpl, scrapy/templates/spiders/xmlfeed.tmpl, scrapy/utils/log.py, scrapy/utils/ssl.py, tests/test_downloadermiddleware_redirect.py, tests/test_downloadermiddleware_robotstxt.py, tests/test_http_response.py, tests/test_pipeline_crawl.py, tests/test_responsetypes.py, tests/test_utils_deprecate.py, tests/test_utils_iterators.py, tests/test_utils_log.py, tests/test_utils_url.py
-*- coding: utf-8 -*- no longer needed.
(edit) fixes #4550
=> Remove Python 2 encoding header from files

pytest.ini, scrapy/pipelines/files.py, scrapy/selector/unified.py, tests/test_spidermiddleware_httperror.py
* E111: indentation is not a multiple of four
* E114: indentation is not a multiple of four (comment) - unused
* E116: unexpected indentation (comment)
* E117: over-indented - unused
* E121: continuation line under-indented for hanging indent
=> Flake8: remove E111, E114, E116, E117, E121

scrapy/linkextractors/lxmlhtml.py, tests/test_linkextractors.py
Removes `lambda` attributes in the default link extractor, allowing instances to be serialized using `pickle`.
Motivated by https://github.com/scrapinghub/scrapy-autounit/issues/74, but this would also mean that requests which include link extractors in their `meta` attribute would be serializable too. I imagine that might be a rare use case, most link extractors I've seen are stored as spider attributes, but the possibility exists.
I intentionally left extractors other than `LxmlParserLinkExtractor` unmodified because they're deprecated. Let me know if that's an issue, I could update them as well.
/cc @fcanobrash
=> Remove lambda attributes in default link extractor

pytest.ini, scrapy/exporters.py, scrapy/extensions/httpcache.py, scrapy/extensions/spiderstate.py, scrapy/squeues.py, tests/test_squeues.py
Fixes #4135
I started by adding a `PICKLE_PROTOCOL` setting, but that didn't work well with `scrapy.squeues._pickle_serialize` because it's defined as a top level function. There is probably a way around that, I just didn't think it was worth the trouble.
I simplified the testing of unserializable objects, since https://twistedmatrix.com/trac/ticket/7989 only affects py2 AFAICT.
A simple and non-rigorous benchmark shows a performance improvement of about 10%:
```python
from tempfile import mkdtemp
from scrapy import Request
from scrapy.utils.test import get_crawler
from scrapy.squeues import PickleFifoDiskQueue
def test(request_count):
jobdir = mkdtemp()
crawler = get_crawler(settings_dict={"JOBDIR": jobdir})
queue = PickleFifoDiskQueue(crawler, jobdir)
for i in range(request_count): …
```
=> Pickle: use protocol 4, update tests

docs/topics/request-response.rst, scrapy/http/response/text.py, tests/test_http_response.py
Fixes #4546 
My first PR on this project so advice/corrections are very welcome.
=> Deprecate body as unicode

scrapy/utils/misc.py, tests/test_utils_misc/__init__.py
Currently create_instance() can return None (or any value) if an extension is
incorrectly implemented, but the extension will still show up as
enabled in the logs. This can cause confusion, as in the linked bug.
This change prevents this occurring by throwing an error if
create_instance() will not return an instance of the correct class.
(edit) fixes #4528
=> Ensure create_instance does not return None

tests/test_spiderloader/__init__.py
Removal of [Line-31](https://github.com/scrapy/scrapy/commit/4c12a234ae65d49678a9840708ff5e7b9d6dcecc#diff-04eeb72b0ac2a03d00f2b1dcc3268ebcL31) in 4c12a234ae65d49678a9840708ff5e7b9d6dcecc do not fail the tests. If we update the tests to check that
1. The number of occurence in the warning should be 2
2. Spider classes not having duplicate names do not show in warning
The tests will fail for 4c12a234ae65d49678a9840708ff5e7b9d6dcecc
Fixes #4549
=> test(spiderloader): no duplicate spider names

scrapy/core/spidermw.py, scrapy/utils/console.py, scrapy/utils/python.py
It seems that the last released version of `pytest-flake8` fixes the issue causing the Travis pipeline to fail. However, I've seen that it's raising some new cases.
=> Flake8: remove E306 and F523

scrapy/http/response/text.py
A follow-up to #4555.
In Scrapy master the following warning is logged:
```
[py.warnings] WARNING: /Users/kmike/envs/foo/lib/python3.8/site-packages/scrapy/http/response/text.py:66: ScrapyDeprecationWarning: Response.body_as_unicode() is deprecated, please use Response.text instead.
warnings.warn('Response.body_as_unicode() is deprecated, '
```
It is not easily actionable because it doesn't point to the user code; it is unclear where the problem is actually happening. Adding stacklevel=2 fixes it:
```
[py.warnings] WARNING: /Users/kmike/svn/myspider/foo/bar/spiders/newsmonitor.py:53: ScrapyDeprecationWarning: Response.body_as_unicode() is deprecated, please use Response.text instead.
print(response.body_as_unicode())
```
=> better deprecation warning for Response.body_as_unicode()

docs/topics/media-pipeline.rst, scrapy/pipelines/files.py, tests/test_pipeline_crawl.py, tests/test_pipeline_files.py
- adds file status to the downloaded files information, as emitted by media pipelines. 
- updates the documentation accordingly.
File status can be a very useful metric to many Scrapy-based applications, especially the ones that heavily rely on `FilesPipeline` or `ImagesPipeline`. This extra information available can be utilized with various (and creative) ways, enabling the end-user to have more control to his file processing algorithms, creating more synergy with other features such as file expiration policy or `file_status_count` statistics.
fixes #2893
=> Add status (downloaded, uptodate) to files information

.readthedocs.yml, docs/conf.py
FIxes #4578 
From 2.0.0 on, a .readthedocs.yml config file was added but there was no line specifying that a downloadable version should be built.  It is now set to build "all" formats, which means pdf, epub and zipped html.
When I first tested it on readthedocs.org the following warning was raised during the epub creation :
`WARNING: unknown mimetype for _static/selectors-sample1.html, ignoring`
This is expected since sphinx does not parse HTML natively, and actually it never parses it, only quotes it literally in the doc, so it _should_ be ignored.  However .readthedocs.yml is set to fail on sphinx warnings. Sphinx issue [3214](https://github.com/sphinx-doc/sphinx/issues/3214) suggests a way to mute only this type of warning, which I find preferable as opposed to let readthedocs.org …
=> Make doc downloadable on ReadTheDocs.org

docs/topics/logging.rst
=> logging.rst: remove unused, misleading import

docs/topics/downloader-middleware.rst, docs/topics/logging.rst, scrapy/downloadermiddlewares/cookies.py, tests/test_downloadermiddleware_cookies.py
Fixes #1992.
This PR modifies the `CookiesMiddleware._get_request_cookies` method to prevent the middleware from discarding cookies already set in the headers (either by the `DefaultHeadersMiddleware` or by using the `Request`'s `headers` constructor parameter).
Update: also fixes #3575
=> [MRG+1] CookiesMiddleware: keep cookies from 'Cookie' request header, fix encoding

scrapy/utils/datatypes.py, tests/test_utils_datatypes.py
Fixes #4597
`LocalWeakReferencedCache` uses a `LocalCache` object, which is size-limited, to store references. However, in this case the limit is set to `None`, so I'm not sure that's the issue. Another theory is that somehow all strong references to the key object, which is a spider callback, got deleted and so Python itself deleted the key (from the [upstream implementation](https://github.com/python/cpython/blob/v3.8.3/Lib/weakref.py#L332-L341), "_Entries in the dictionary will be discarded when there is no longer a strong reference to the key_"), but that wouldn't make much sense because the key does exist when trying to access it.
In any case, the key is not available so we are better off catching the `KeyError`.
`LocalWeakReferencedCache` is only used to warn in case of generators …
=> Fix KeyError in LocalWeakReferencedCache

docs/faq.rst, docs/topics/exceptions.rst, docs/topics/request-response.rst, docs/topics/signals.rst, scrapy/core/downloader/handlers/http11.py, scrapy/core/scraper.py, scrapy/exceptions.py, scrapy/utils/signal.py, tests/spiders.py, tests/test_crawl.py, tests/test_engine.py
Allow the cancellation of a download while it's in progress.
Motivated by https://github.com/scrapy/scrapy/pull/4205#issuecomment-588155415.
Tasks:
=> Stop response download from signal handler

docs/topics/request-response.rst, scrapy/http/response/text.py, tests/test_http_response.py
- added property .json 
- added tests 
Fixes #2444, closes #4460.
=> Returns a JSON serializable Python object.

docs/README.rst, docs/conf.py
Additionally, I think the documentation in docs/README.rst is out
of date: none of the commands built the docs properly for me (I had to
revert the changes in 901892da to docs/conf.py to get them to build
properly, and even then no tooltips displayed).
Building them with tox worked for me, but other developers say they
can still use the original method, so the docs now contain both.
Fixes #4495.
=> Extend hoverxref_roles to custom crossrefs (#4495)

docs/topics/api.rst, docs/topics/contracts.rst, docs/topics/exporters.rst, docs/topics/loaders.rst, docs/topics/spiders.rst
removed unneeded escape sequences from method arguments in the docs
folder
Fixes #4592
=> remove unneeded escape sequence

scrapy/utils/spider.py, tests/spiders.py, tests/test_crawl.py
Currently, single elements cannot be returned from coroutine callbacks.
Consider the following sample spider:
```python
from scrapy import Spider, Request
class AsyncDefSpider(Spider):
name = "async_def"
start_urls = ["https://example.org"]
async def parse(self, response):
return Request("https://example.com")
```
which produces:
```
2020-06-01 17:10:24 [scrapy.core.engine] INFO: Spider opened
2020-06-01 17:10:24 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-06-01 17:10:24 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-06-01 17:10:25 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2020-06-01 17:10:25 [scrapy.core.scraper] ERROR: Spider error processing <GET …
```
=> Return single element from coroutine callback

scrapy/commands/startproject.py
`scrapy startproject myproject` fails with permission denied if the original template permissions are read-only. This is the case on nix-based systems that ensure that installed libraries are immutable. I am not sure what the best place is to put these permissions but here is a quick fix.
=> give write access to template files after copying with startproject

.travis.yml, README.rst, docs/faq.rst, docs/intro/install.rst, scrapy/__init__.py, setup.py
See https://github.com/scrapy/scrapy/pull/4243#issuecomment-632899356
=> Bump minimum Python version to 3.5.2

scrapy/utils/python.py
This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.
=> Use chain.from_iterable in python.py

scrapy/extensions/feedexport.py, tests/test_feedexport.py
=> Fix missing storage.store calls in FeedExporter.close_spider

docs/topics/request-response.rst
Update docs with the info on accessing callback arguments
(cb_kwargs) in errback. Also, included an example for the same.
Fixes #4598
=> DOC: Update docs on accessing callback arguments in errback

docs/topics/loaders.rst
I only commented this as part of the description of #3881, but it should be documented in the actual docs.
=> Docs: add note about dataclass items and loaders

.gitignore, .travis.yml, setup.cfg, tox.ini
As discussed recently, here's a PR that contains only the Tox/CI changes, not any specific type annotations.
See also #4243.
=> Typing: Tox env, CI job

scrapy/extensions/feedexport.py, tests/test_feedexport.py
=> Fix duplicated feed logs

tests/test_scheduler.py
=> Spider constructor expects name as argument, not start_urls.

scrapy/utils/curl.py, tests/test_utils_curl.py
When copying a cURL command from the browser I got the `--data-raw` parameter.
After reading this:
* https://curl.haxx.se/docs/manpage.html#--data-raw
* https://curl.haxx.se/docs/manpage.html#-d
I think we can safely add it as a synonym of `--data`.
On the other side, this also fixes when missing the method but specifying the data (body), as the method should be interpreted by default as `POST`.
=> add --data-raw to utils.curl and fix missing method with data

docs/topics/loaders.rst
@ejulio's example [here](https://github.com/scrapy/itemloaders/pull/13/files#diff-2873a0f550b5bf030b1bb1545b09c842R67-R79) made me realize the example from #4642 is needlessly complicated.
Perhaps #4516 gets merged first, but it probably doesn't hurt to merge this one too.
=> Docs: Simplify dataclass example in item loader page

docs/topics/settings.rst
OpenSSL `ciphers(1)` is now almost empty: https://www.openssl.org/docs/manmaster/man1/ciphers.html
Alternative would be linking to 1.1.1 docs specifically.
=> Update the OpenSSL cipher list format link

scrapy/utils/python.py
This function is not used, is not tested and is not documented, so we should probably remove it.
It was introduced to be used in `test_commands.py` but is not used anymore (ref: https://github.com/scrapy/scrapy/commit/6217f108cce8a7db0c0ee3682848159b06c9e9d3)
=> deprecate retry_on_eintr

scrapy/http/cookies.py, tests/test_http_cookies.py
The `getheaders` method was implemented to be compatible with Python 2, but as we dropped the support for Python 2 we don't need it anymore. It's enough to delete it or do you prefer to add a deprecation warning before doing it?
=> remove python 2 reminiscence in cookies

setup.cfg
No need to ignore the `_monkeypatches` module during the typing check, it does not exist any more since #4568
=> Remove monkeypatches module from mypy section in setup.cfg

docs/news.rst, docs/topics/commands.rst, docs/topics/developer-tools.rst, docs/topics/feed-exports.rst, scrapy/utils/curl.py
[See rendered](https://scrapy-gallaecio.readthedocs.io/en/release-notes-2.3/news.html).
=> Cover Scrapy 2.2.1 and 2.3 in the release notes

scrapy/settings/__init__.py
When value is None, it is not necessary to invoke update and run other methods and conditions to make the code complicated there.
=> Unnecessary update when value is None

docs/topics/media-pipeline.rst, scrapy/pipelines/files.py, scrapy/pipelines/images.py, scrapy/pipelines/media.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_pipeline_media.py
Closes #4628, closes #4677 
The existing media pipelines (`FilesPipeline` and `ImagesPipeline`) do not allow the user to dynamically define downloaded file location based on the item returned by the spider, thus, forcing the users to use other workarounds like using the `Request.meta` to pass item data or creating their own `Request` subclass with the item passed to it.
I've updated the media pipelines to pass `item` as a parameter to the `file_path` function and have updated the same in the tests as well. This will now allow the user to define file paths based on the item.
=> Support defining file path based on item in media pipelines

.gitattributes, tests/__init__.py, tests/test_utils_iterators.py
It should solve some issues caught by Conda Forge: https://github.com/conda-forge/scrapy-feedstock/pull/44
They were caught by Conda Forge because it uses the test files from the PyPI tarball, not from Git, so in Conda Forge the line endings of files are never changed.
=> test_utils_iterators.py: support Windows the right way

tests/requirements-py3.txt, tox.ini
While working on HTTP/2 support, @adityaa30 [discovered](https://github.com/scrapy/scrapy/pull/4669) that simply upgrading the pinned Travis CI job to 3.6 would cause tests to fail.
[It turns out](https://github.com/scrapy/scrapy/pull/4681) we need to first upgrade some pinned dependencies for that to work.
This does so, in preparation for the upcoming removal of Python 3.5 support, but without actually dropping such support yet just in case.
=> Upgrade minimum dependencies for Python 3.6 support

scrapy/extensions/feedexport.py, tests/test_feedexport.py
I have taken this PR https://github.com/scrapy/scrapy/pull/4411 and added fix for a failure in tests (not used import).
I hope @nyov is fine with that.
https://github.com/scrapy/scrapy/issues/4356
=> Remove obsolete S3FeedStorage instancing without AWS credentials

.travis.yml, setup.py
https://bitbucket.org/pypy/pypy/ now says:
> ### Repository unavailable
> Bitbucket no longer supports Mercurial repositories.
PyPy source and issues has moved to https://foss.heptapod.net/pypy/pypy
Downloads are now at downloads.python.org:
* https://www.pypy.org/download.html
* https://downloads.python.org/pypy/
=> Update PyPy links

scrapy/utils/misc.py, tests/test_utils_misc/test_return_with_argument_inside_generator.py
=> smarter generator check for combined return/yield statements

tests/mockserver.py
This should fix cipher tests on platforms where TLS 1.2 is the minimum supported version such as modern Debian. I don't remember why I disabled 1.2 initially as only 1.3 adds ciphers unconditionally (check `openssl ciphers -s -tls1_2 CAMELLIA256-SHA` and `openssl ciphers -s -tls1_3 CAMELLIA256-SHA`).
We'll need to do something else (and probably in Scrapy too, not just in tests) when TLS version reqs are even stricter.
Fixes #4726.
Note that `tests/test_downloader_handlers.py::Https11CustomCiphers` is fine when additional ciphers are enabled (so e.g. won't fail when `SSL_OP_NO_TLSv1_3` is removed) while `tests/test_webclient.py::WebClientCustomCiphersSSLTestCase` also checks for an error when the ciphers don't match (and will fail without `SSL_OP_NO_TLSv1_3` as in that case the custom …
=> Re-enable TLS 1.2 in cipher tests.

scrapy/core/downloader/handlers/http11.py, tests/test_downloader_handlers.py
Fixes #3874, closes #3886.
Previously @WinterComes  tried to solve the issue but hasn't responded to one final query by @kmike.
I completed the simple query.
=> DOWNLOAD_MAXSIZE logger level changed from Error to Warning

scrapy/utils/reqser.py, tests/test_utils_reqser.py
It is useful to split the spider code around some helper classes if the spider code is too big. Using inheritance and mixings is the regular approach in this case. But using callback delegation could be a useful alternative in some cases but Scrapy does not support it. For example, this is not allowed currently:
```py
class UKHomepageParser:
...
class USHomepageParser:
...
class MySpider(Spider):
def __init__(self, location):
if location == "UK:
self.parse = UKHomepageParser().parse
else:
self.parse = USHomepageParser().parse
...
```
Nothing prevents Scrapy to support this case. This PR changes the function `_find_method` in `reqser.py` removing the constraint that forces a callback `self` to be the spider. Being a method from a …
=> Support for delegated methods as callbacks

docs/topics/exporters.rst, scrapy/exporters.py, tests/test_exporters.py
Additional context from https://github.com/scrapy/scrapy/issues/4754
=> Add errors parameter for CsvItemExporter with tests

scrapy/utils/template.py, tests/test_commands.py
This should allow permission tests to pass in Conda Forge builds (see https://github.com/conda-forge/scrapy-feedstock/pull/42).
Includes changes (`maxDiff = None`, `get_permissions`) aimed at making test failures more readable.
=> Do not let umask affect the permissions of startproject-generated files

tests/test_crawl.py
This adds a single function to run a spider and collect the items, logs and stats, to simplify existing and future test cases.
Includes #4764
=> Simplify tests/test_crawl

docs/topics/media-pipeline.rst
At the beginning of this doc, in "Specifying where to store the media" feature details, FTP server storage mention was missing
=> add mention of FTP server storage in media storage intro

scrapy/core/downloader/handlers/s3.py, scrapy/extensions/feedexport.py, scrapy/pipelines/files.py, scrapy/utils/boto.py, scrapy/utils/test.py, tests/test_feedexport.py, tests/test_pipeline_files.py
This:
* deprecates is_botocore() and adds an explanation how does it currently work (return True if `botocore` is available, raise an exception otherwise) and that it cannot help with boto/botocore code path choice.
* adds is_botocore_available() that should be used to check if `botocore` is available.
* for all `if is_botocore(): code1 else: code2` keeps just `code1`, adding `if not is_botocore_available(): raise NotConfigured()` (or `skip_if_no_boto()` in tests) where it makes sense.
* removes two tests which tested some dead code but were not skipped because they mock things.
Note that we currently don't run tests without `botocore` installed and because of that not all tests that need it are properly skipped and fail instead. This PR doesn't fix this.
Consider tagging `discuss` if you …
=> Remove dead boto2 code, deprecate is_botocore().

scrapy/core/downloader/tls.py
We now require pyOpenSSL>=16.2.0 so the code can be simplified.
There is another conditional that is used by this feature, in utils.ssl, it checks `hasattr(pyOpenSSLutil.lib, 'SSL_get_server_tmp_key')` which requires OpenSSL 1.0.2. I don't know how does Scrapy itself work on systems with older OpenSSL, and how many such systems are there, but I decided to keep it for now.
=> Simplify TLS logging for the modern pyOpenSSL.

scrapy/core/downloader/tls.py
I decided to not deprecate `set_tlsext_host_name` as I doubt anybody used it.
Note that this is the only use of `scrapy.twisted_version`, but we may want to use it in the future and we definitely will need to deprecate it before removing, so I kept it.
=> Drop the conditional code for old Twisted.

scrapy/spiders/crawl.py, tests/test_spider.py
Deprecated in #3682, which was released in [1.7](https://github.com/scrapy/scrapy/releases/tag/1.7.0) (Jul 18, 2019).
Personally I don't see a problem with removing the `Rule.process_request_argcount` attribute (which should have been underscored from the beginning, my bad :raising_hand:) without deprecating it first, because it's not documented, but I understand if any objections are made. What are your thoughts on this?
=> Crawl rule: remove deprecated code

scrapy/crawler.py
I have opened this pull request in accordance to #4805 
I have essentially removed the data type specification for *args and **kwargs as it had some unforeseen consequences.(refer to #4805 )
Fixes #4805
=> removed datatype specification for *args & ** kwargs

scrapy/downloadermiddlewares/httpproxy.py, tests/test_downloadermiddleware_httpproxy.py
Fixes #3331 
`/var/run/docker.sock` seemed an exceptional case when a socket file is used in `no_proxy` env variable which is unparseable by the `urllib.request._parse_proxy` method.
=> Check for unparseable no_proxy values

docs/topics/feed-exports.rst, scrapy/extensions/feedexport.py, scrapy/utils/conf.py, tests/test_feedexport.py, tests/test_utils_conf.py
Resolves https://github.com/scrapy/scrapy/issues/4606
=> Pass info from FEEDS to ItemExporter

tests/test_dupefilters.py, tests/test_logformatter.py, tests/test_pipelines.py, tests/test_request_attribute_binding.py, tests/test_request_cb_kwargs.py, tests/test_spidermiddleware_output_chain.py
=> Tests: use classes instead of paths in settings

docs/contributing.rst
Noticed in @elacuesta’s quote of the documentation at https://github.com/scrapy/scrapy/issues/3055#issuecomment-678800672
=> as soon as → as long as

scrapy/utils/test.py, tests/test_downloader_handlers.py, tests/test_feedexport.py, tests/test_pipeline_files.py, tox.ini
Fixes #1790
I used the built-in mocking mechanism from `botocore`, the client library we use.
-   [x] `tests/test_downloader_handlers.py::S3TestCase::test_request_signing5` (removed, only meant to work on Python 2)
-   [x] `tests/test_feedexport.py::S3FeedStorageTest::test_store`
-   [x] `tests/test_feedexport.py::BatchDeliveriesTest::test_s3_export`
-   [x] `tests/test_pipeline_files.py::TestS3FilesStore::test_persist`
=> Use mocking for S3 tests that currently need server credentials

scrapy/http/request/__init__.py, tests/test_http_request.py
https://github.com/scrapy/scrapy/pull/4094#issuecomment-704092404
=> Do not consider about: URLs invalid

docs/topics/downloader-middleware.rst, docs/topics/request-response.rst, docs/topics/settings.rst, scrapy/downloadermiddlewares/cookies.py, tests/test_downloadermiddleware_cookies.py
Fixes #4717
Revert the behaviour introduced in #2400, because of the bug reported in #4717. Once we merge this, we'll need to either reopen #1992 or create a new issue to keep track of the work towards supporting cookies in the `Cookie` request header (#4812, for instance).
Tasks:
=> Do not process cookies from headers

pytest.ini
Following up https://github.com/scrapy/scrapy/pull/4823#issuecomment-704433174
=> Add xfail_strict=true to pytest.ini

scrapy/extensions/feedexport.py, tests/test_commands.py
related to #4857  and #4845 
`FeedExporter._get_storage()` updated - `feed_options` successfully passed to Storage objects
`CrawlCommandTest.test_overwrite_output` and
`RunSpiderCommandTest.test_overwrite_output` aimed to test `-O` arg - updated.
=> overwrite an output file with -O, (FeedExporter updated)

docs/topics/settings.rst, scrapy/utils/reactor.py, tests/CrawlerProcess/asyncio_deferred_signal.py, tests/test_crawler.py
Fixes #4855. See https://github.com/scrapy/scrapy/issues/4855#issuecomment-721964440 for the rationale of this change.
In the docs, I intentionally only mentioned `set_event_loop` and omitted the call to `get_event_loop` when the default event loop is used. I've grown more convinced that this is "harmless", in the sense that `get_event_loop` will call `set_event_loop` only if it hasn't been called, and if that's the case, the user most likely does not care about the loop being used.
=> Call asyncio.get_event_loop when installing the asyncio reactor

scrapy/commands/genspider.py, tests/test_commands.py
When running inside a project, the `genspider` command is outputting string placeholders rather than their actual contents.
Example:
```
$  scrapy genspider example example.com
Created spider 'example' using template 'basic' in module:
{spiders_module.__name__}.{module}
```
This PR fixes it, by adding the missing f-string prefix to the string that represents that message.
=> Fix incorrect output on the genspider command

tests/requirements-py3.txt
This should have been removed in #4869, I didn't realize it was there.
=> Remove unnecessary pytest-azurepipelines package

scrapy/extensions/feedexport.py, tests/test_feedexport.py
Resolves https://github.com/scrapy/scrapy/issues/3947
Example:
```
import scrapy
from scrapy.crawler import CrawlerProcess
class QuotesToScrapeSpider(scrapy.Spider):
name = "quotes"
custom_settings = {
"DOWNLOAD_DELAY": 1,
"COOKIES_DISABLED": True,  # mistyped, should be enabled
"CONCURRENCY": 5,
"FEEDS": {
"file:///tmp/tmp-%(batch_time)s.json": {
"format": "json",
},
"s3://mybucket/path/to/export-%(batch_time)s.csv": {
"format": "csv",
},
},
"FEED_EXPORT_BATCH_ITEM_COUNT": 5,
}
def start_requests(self):
yield scrapy.Request(url='http://quotes.toscrape.com/', callback=self.parse)
for quote in response.css("div.quote"):
yield {
"quote": quote.css("span.text::text").extract(),
"author": quote.css("small.author::text").extract(),
"tags": …
```
=> Add failed and success count stats to feedstorage backends

scrapy/utils/asyncgen.py, scrapy/utils/py36.py, scrapy/utils/python.py, scrapy/utils/spider.py, setup.cfg
Now that the minimum Python version is 3.6, there is no need to keep this helper in a different file and catch the `SyntaxError` when importing.
=> Deprecate scrapy.utils.py36 module

scrapy/utils/project.py
Deprecated in #3910, released as part of [`1.8`](https://docs.scrapy.org/en/latest/news.html#scrapy-1-8-0-2019-10-28)
=> Remove deprecated SCRAPY_PICKLED_SETTINGS_TO_OVERRIDE

docs/topics/request-response.rst, scrapy/core/downloader/handlers/http11.py, scrapy/core/downloader/webclient.py, scrapy/http/response/__init__.py, tests/test_downloader_handlers.py
Motivated by #4769 and #4770
```
$ scrapy shell https://example.org
(...)
>>> response.protocol
'HTTP/1.1'
>>> 
```
=> Response.protocol attribute

scrapy/http/request/form.py
There is a small typo in scrapy/http/request/form.py.
Should read `without` rather than `wihout`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, wihout -> without

scrapy/pipelines/media.py, setup.py
Minor fix: **twisted.internet.defer.DeferredList**  parameter  **consumeErrors** expects _boolean_, got _integer_ instead.
=> Fix warning: Expected type 'bool', got 'int' instead

docs/news.rst
There is a small typo in docs/news.rst
Should read EXTENSIONS rather than EXTENIONS.
As it is written as `EXTENSIONS` in `settings` file.
=> docs: fix simple typo, EXTENIONS -> EXTENSIONS 

scrapy/core/spidermw.py
I decided to extract nested functions from the method because after adding more code there in #4978 pylint was raising "Too many statements". Looks like they were nested to be able to access several vars from the outside scope so now they are passed explicitly. I don't know if this is the best way to resolve this, so suggestions are welcome.
=> Refactor SpiderMiddlewareManager.scrape_response.

tests/requirements-py3.txt
uvloop 0.15.0, released yesterday, dropped support for Python 3.6 and lower.
=> Skip uvloop 0.15.0+ on py36.

conftest.py, pytest.ini, tests/requirements-py3.txt, tests/test_utils_defer.py
With `twisted.trial` we are able to write asynchronous test functions by returning a Deferred from them. We also have the `deferred_f_from_coro_f` higher order function that can be used as a decorator for an `async def` test function and everything should work as expected. So I'm adding this small test case to check that we indeed can write working tests this way.
Unfortunately, a naked `async def` test function will always succeed, with a warning that a coroutine was not awaited (ideally we should get rid if warnings from tests, but this is still easy to miss).
I added these tests because I've just found for #4978 that such tests fail with old Twisted. So this PR should fail too.
=> Making sure we can run async def tests

scrapy/core/http2/protocol.py, tests/test_http2_client_protocol.py
I felt like this change was big enough not to make it directly to the `http2` branch. With this PR, test coverage in #4769 should reach the build target (not 100% though, but I don't feel familiar enough with the original patch to be able to simulate every scenario).
=> http2: acceptable protocol update, tests

docs/topics/exporters.rst
=> Close files in the PerYearXmlExportPipeline documentation example

tox.ini
@kmike @wRAR @elacuesta I figured out this package upgrade was the issue so far.
According to the [Twisted 21.2.0 release notes](https://github.com/twisted/twisted/releases/tag/twisted-21.2.0):
> trial now allows the @unittest.skipIf decorator to specify that an entire test class should be skipped. (#9829)
This confuses me greatly, as what is failing now are tests that were already using this feature that is supposed to be new in Twisted 21.2.0.
I’ll continue looking into it later.
Fixes #5020
=> Limit tests to Twisted < 21

.readthedocs.yml, docs/pip.txt
Tested in a custom ReadTheDocs project.
=> Use pip<20.3 to fix ReadTheDocs builds

scrapy/spidermiddlewares/urllength.py, tests/test_spidermiddleware_urllength.py
I guess it's a good idea to not just send the skipped info to debug, since it could be critical and not so obvious to debug in case of accidental long url generating.
So it's better to log to `INFO` at least, and add count to crawler stats.
=> UrlLengthMiddleware: don't skip silently

scrapy/selector/unified.py
Resolves #4961, paving the way for https://github.com/scrapy/parsel/pull/181
=> Remove unnecessary reference to private parsel.Selector._default_type

scrapy/core/downloader/handlers/http11.py, tests/test_downloader_handlers.py
Alternative to #5034 to deal with #5009 without changes in Twisted, based on https://github.com/scrapy/scrapy/pull/5034#issuecomment-803297647
Fixes #5009, closes #5034, closes #5045
=> Include Content-Length in HTTP/1.1 responses

docs/topics/request-response.rst
Creating the pull request for Sort the list of Request.meta keys alphabetically #5061 sorted the file request-response.rst and arranged them in order.
Resolves #5061
=> Sort the list of Request.meta alphabetically #5061

scrapy/core/downloader/handlers/http11.py
I wasn't fast enough to comment this on #5057 before it got merged.
The following happens with the current `master` (ec5a7918ec2d8888ba356f9e3295dcd1ee935884):
```python
$ scrapy shell http://quotes.toscrape.com
(...)
2021-03-22 10:42:40 [scrapy.core.engine] INFO: Spider opened
resp2021-03-22 10:42:41 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://quotes.toscrape.com> (referer: None)
onse.2021-03-22 10:42:41 [asyncio] DEBUG: Using selector: EpollSelector
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f24d38fc790>
[s]   item       {}
[s]   request    <GET http://quotes.toscrape.com>
[s]   response   <200 http://quotes.toscrape.com>
[s]   settings …
```
=> [HTTP/1.1] Skip Content-Length header if its value is UNKNOWN_LENGTH

setup.py, tox.ini
Closes #5058, fixes #5059
Taken from [`Twisted[http2]`](https://github.com/twisted/twisted/blob/twisted-21.2.0/setup.cfg#L83). The current `h2>=3.2.0` results in the installation of the latest `h2==4.0.0`, which then gets uninstalled because it doesn't comply with the Twisted constraints.
@Gallaecio @wRAR @kmike Not exactly what we discussed, but it works nonetheless.
=> Adjust h2 version requirement

docs/topics/extensions.rst
The previous documentation suggested there was a single instance of each extension. This is not the case. For example, when [running multiple spiders in the same process](https://docs.scrapy.org/en/latest/topics/practices.html#running-multiple-spiders-in-the-same-process), the [LogStats extension](https://docs.scrapy.org/en/latest/_modules/scrapy/extensions/logstats.html#LogStats) still works correctly, and it doesn't track stats per spider.
=> docs: Clarify there's one extension instance per crawler

docs/_static/custom.css, docs/conf.py, docs/topics/exceptions.rst, docs/topics/feed-exports.rst, docs/topics/selectors.rst, docs/topics/shell.rst
This has been bothering me for a while.
I’ve not reviewed the effect in the whole documentation, but I’ve had a look at pages from the main page to the settings page, which is about half the documentation, and it looks good to me.
Before: 
After:
Changes to reStructuredText files are so that lists which were put within a blockquote because of the empty space that precedes their `*` are now regular lists.
=> Move lists closer to their introducing paragraph

docs/topics/logging.rst
Added a tutorial example how to filter root logger or any custom logger with a regular expression.
Resolves #4216, closes #4257
=> added customized filtering examples in logging.rst

docs/intro/install.rst
Added few steps. Will add all the steps soon.
Fixes #4715
=> Windows pip installation guide

docs/topics/spider-middleware.rst, scrapy/spidermiddlewares/httperror.py, tests/test_spidermiddleware_httperror.py
Fixes [#3851](https://github.com/scrapy/scrapy/issues/3851)
on this spider 
```
from scrapy import Spider, Request
class HttpStatusSpider(Spider):
name = "http_status"
def start_requests(self):
http_status = [200, 300, 400, 500]
urls = [
f"http://httpbin.org/status/{status}" for status in http_status
]
for url in urls:
yield Request(
url=url,
callback=self.parse,
meta={
"handle_httpstatus_all": False
}
)
def parse(self, response, **kwargs):
print(f"response url: {response.url}")
```
previous the fix was printing all elements on the list, after the fix just print 200 status
=> Improve http status all on http error middleware

scrapy/commands/crawl.py
This message was added 10 years ago (`Scrapy 0.25.1`), and I think that we can update it like this, as the feature of running more than one spider was deprecated a long time ago.
However, as this appears when we write more than one `arg`, it could be also a good idea to reformulate the whole message to give a hint like _"did you forget to add `-a` / `-s` , etc"_. Or something similar. 
Let me know what you think. :)
=> Update UsageError message

scrapy/commands/bench.py, tests/spiders.py
Continuation of #4950 (https://github.com/scrapy/scrapy/pull/4950#pullrequestreview-564527188)
=> Fix type for urlencode's doseq argument

setup.cfg, tests/test_engine.py, tox.ini
Currently the `AttrsItemsSpider` is using an item class that inherits from `scrapy.item.Item`
=> Engine tests: fix item class spider, add minimal type hints

docs/topics/settings.rst
`DOWNLOAD_HANDLERS_BASE` default setting [mentioned in docs](https://docs.scrapy.org/en/master/topics/settings.html#download-handlers-base) is missing DataURI download handler, that is present in `scrapy/settings/default_settings.py`
=> Add DataURI download handler in DOWNLOAD_HANDLERS_BASE documentation

scrapy/core/scraper.py
This was left out of the previous PR for several reasons.
This removes a check from `_log_download_errors`, I believe this check can't be False.
=> Additional typing for scraper and a small code change.

docs/topics/practices.rst
The example in the documentation doesn't take into account how to load the project's settings.
I assume most people want to load the settings when running multiple spiders concurrently. If they don't, it's at least more straightforward to remove that functionality than to notice the settings are being ignored and then find out how to fix it.
I had to find it in a third-party example: https://botproxy.net/docs/how-to/scrapy-crawl-multiple-spiders-sharing-same-items-pipeline-and-settings-but-with-separa/
=> Include loading settings in `Running multiple spiders in the same precess` section

docs/topics/telnetconsole.rst, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/downloadermiddlewares/robotstxt.py, scrapy/extensions/memusage.py, scrapy/pipelines/media.py, scrapy/shell.py, scrapy/utils/engine.py, tests/test_downloadermiddleware_robotstxt.py, tests/test_engine.py
As discussed earlier @wRAR 
Type hints adapted from #3559
Deprecated methods:
* `ExecutionEngine.open_spiders`: I didn't check the history, but I suspect this probably comes from the time when multiple spiders could run in a single crawl. That hasn't been the case for a long time, so it's not necessary to have a plurally-named property with only one element.
* `ExecutionEngine.has_capacity`: same as the above, the engine only handles one spider slot, which can be checked directly. Not called from outside the engine.
* `ExecutionEngine.schedule`: Not called from outside the engine, deprecated as per https://github.com/scrapy/scrapy/issues/542#issuecomment-32621164
Also, the `spider` argument is deprecated for the `spider_is_idle`, `crawl` and `download` methods, the spider instance saved …
=> Engine: deprecations and type hints

docs/Makefile
Instead of hard coding executable path, we can use `/usr/bin/env` 
It searches for bash in $PATH: https://unix.stackexchange.com/a/29620/420806
This fixes #5080
=> Find bash from PATH instead of /bin/bash

docs/topics/settings.rst
Previous link doesn't exist anymore.
Looking into the content of archived content (https://web.archive.org/web/20180308145804/https://boutell.com/newfaq/misc/urllength.html) I realized that this default value is related to the article of Microsoft support.
Perhaps we should reconsider this default (or this middleware in future), but at least it will be good to have an updated doc.
=> Update link for reasoning value of URLLENGTH_LIMIT

CODE_OF_CONDUCT.md
The contributor covenant at http://contributor-covenant.org/version/1/4/ includes a link to FAQ under Attribution at the bottom of the page. I added the link to update the CODE_OF_CONDUCT.md file to be consistent with the contributor-covenant page.
=> Add FAQ to code of Conduct

docs/topics/spiders.rst
=> spiders.rst: indent warnings into class descriptions

docs/topics/signals.rst, scrapy/core/engine.py, scrapy/utils/signal.py, tests/test_engine.py
The execution of a spider might have been successful or not depending on many conditions. For example, you might have expected many items to be extracted but none were extracted. It might be useful to be able to evaluate at the end of the crawling if the results are successful, and if not, close the spider using the appropriate message (e.g. "too_few_results") instead of the regular one "finished".
The `spider_idle` signal handler looks like the perfect place to put such logic. At this stage, all the work has been done, so all the stats are ready to be queried to decide the final status. The problem I found is that is not possible to set the closing reason in this handler. 
In this PR I propose to reuse the exception `CloseSpider` to provide the closing reason. The required changes are …
=> CloseSpider can be raised on spider_idle signal handler to set the closing reason

.github/workflows/checks.yml, .github/workflows/tests-macos.yml, .github/workflows/tests-ubuntu.yml, .github/workflows/tests-windows.yml
Allow remaining jobs to keep running even if some of them fail (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast).
As discussed with @Gallaecio
=> [CI] fail-fast: false

.github/workflows/tests-ubuntu.yml
[libxml2 bug report](https://gitlab.gnome.org/GNOME/libxml2/-/issues/255)
[lxml bug report](https://bugs.launchpad.net/lxml/+bug/1928795)
=> Pin the libxml2 version in CI as a newer one breaks lxml.

scrapy/core/downloader/handlers/s3.py
Remove leftover attribute `S3DownloaderHandler.conn`. Seems we forgot to remove it in 5e99758.
=> Cleanup leftover boto2 code in S3DownloaderHandler

docs/topics/feed-exports.rst, docs/topics/settings.rst, scrapy/core/downloader/handlers/s3.py, scrapy/extensions/feedexport.py, scrapy/pipelines/files.py, scrapy/pipelines/images.py, tests/test_feedexport.py, tox.ini
Support temporary security credentials by adding a new setting `AWS_SESSION_TOKEN`. S3 client or credentials creation is done by
- `Session.create_client()` in pipelines, feed exporter
-  `Credentials.__init__()` in `S3DownloadHandler`
Both of the methods from `botocore` accept another token parameter.
`AWS_SESSION_TOKEN` is only required by temporary security credentials, which is short term.
References about the `AWS_SESSION_TOKEN`
- [Temporary access keys](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#temporary-access-keys)
- [aws_session_token](https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-aws_session_token.html)
=> Add support for temporary security credential in AWS auth

tests/test_feedexport.py
FileFeedStoragePreFeedOptionsTest fails due to missing permissions to the file, as in CI/CD pipeline random users are created. I have used tempfile.NamedTemporaryFile to generate a random file on every test run.
Fixes #5157
=> Fix FileFeedStoragePreFeedOptionsTest fails in CI/CD pipeline

scrapy/utils/misc.py, tests/test_utils_misc/__init__.py
Comma-separated `rel` values are often seen in the wild, because Google allows it (see https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links).
=> Allow comma-separated values in the rel attribute

.github/workflows/tests-ubuntu.yml, scrapy/utils/signal.py, tests/test_http_response.py, tests/test_request_cb_kwargs.py, tests/test_spiderloader/__init__.py
Closes: #5212.
There is an elusive problem in `SpiderLoaderTest` which I can't reproduce when running tests only for that module. It's related to #5160 because that test checks the warning list and gets an unexpected one ("_SixMetaPathImporter.find_spec() not found;").
=> Fixing tests for upcoming 3.10.

docs/topics/settings.rst, scrapy/settings/default_settings.py
=> Document JOBDIR option

tests/test_spidermiddleware.py
When adding new tests for async middlewares I've found that the default ones are silently enabled in the existing tests, which interferes with things I want to test, I think if we need to test how it works with the default ones we can do that explicitly.
=> Disable builtin middlewares in spider middleware tests.

docs/topics/downloader-middleware.rst
=> updated documentation for python version for reppy

scrapy/spiders/__init__.py, tests/test_spider.py
As mentioned in https://github.com/scrapy/scrapy/pull/4170#discussion_r348275969
This method was deprecated in #1728, released in [`1.4.0`](https://github.com/scrapy/scrapy/blob/1.4.0/docs/news.rst#deprecations-and-backwards-incompatible-changes)
Should we also remove `scrapy.utils.deprecate.method_is_overridden`? It was introduced in the above PR and it's not currently used anywhere else, but I think its purpose is still valid.
Closes #4356
=> Remove deprecated Spider.make_requests_from_url method

scrapy/commands/startproject.py, tests/test_commands.py
Fixes #4665
The issue was that empty directories in an import path can be imported as namespace packages since Python 3.3: https://stackoverflow.com/a/49082183/939364
I’ve switched `import_module` to `find_spec`, which does something similar without actually importing, and now we are also checking whether `spec.loader` is `None` (indicating it’s a namespace package).
I suspect this has been happening forever when using Python 3.
=> Fix startproject failing for existing folders

scrapy/core/scraper.py, tests/test_request_cb_kwargs.py
Fixes #5237
Use `Deferred.addCallbacks` instead of `Deferred.addCallback`. Modified the test case to work with this patch but fail with the current code in master.
=> Allow 'callback' key in keyword arguments for request callbacks

docs/conftest.py
=> fix: `CodeBlockParser` has been renamed to `PythonCodeBlockParser`

.github/workflows/tests-windows.yml
Looks like the Twisted build bug was fixed (or it just uses pre-built wheels).
=> Re-enable Windows tests for Python 3.9 and 3.10.

scrapy/core/downloader/handlers/http11.py, scrapy/core/http2/stream.py, tests/test_request_left.py
Changed the 3 instances mentioned in Issue #5314 
Fixes #5314, closes #5321.
=> augmented assignment statements #5314 update

scrapy/utils/response.py, tests/test_utils_response.py
Fixes #5319
Use of `re.sub` instead of `replace` to inject `<base>` tag.
=> Improve open_in_browser base tag injection (#5319)

scrapy/commands/__init__.py
you do not need a comma if the clause comes at the end of the sentence. This applies to all subordinate clauses, not just. should i merg ?
=> correction of comma

scrapy/utils/conf.py
I have no idea why this started to fail with a TypeError and I cannot reproduce it locally but it's definitely a mistake.
=> Fix a warning message.

docs/topics/architecture.rst
The process repeats from step 3, the scheduler feeds request to the engine. Steps 1 and 2 are not parts of the loop as their incarnations steps 7 and 8 are parts of the loop.
=> correct process repetition start step

scrapy/core/downloader/webclient.py
All reactor imports must be local not top level because twisted.internet.reactor import installs default reactor, and if you want to use non-default reactor like asyncio top level import will break things for you. 
In my case I had a middleware imported in spider
in spider
```python
from project.middlewares.retry import CustomRetryMiddleware
```
this was importing
```
from scrapy.downloadermiddlewares import retry
```
then retry was importing
```
from scrapy.core.downloader.handlers.http11 import TunnelError
```
and http11 was importing
```
from scrapy.core.downloader.webclient import _parse
```
and webclient was importing and installing reactor. I wonder how this was not detected earlier? It should break things for people trying to be using asyncio reactor in more complex projects.
This …
=> downloader.webclient: make reactor import local

docs/topics/asyncio.rst, docs/topics/settings.rst
I also added a line about `TWISTED_REACTOR` and `custom_settings`.
=> Remove the experimental note about asyncio.

.github/workflows/tests-windows.yml, docs/topics/asyncio.rst, scrapy/utils/reactor.py, tests/CrawlerProcess/asyncio_enabled_reactor.py, tests/test_commands.py, tests/test_crawler.py, tests/test_downloader_handlers.py, tests/test_utils_asyncio.py
Closes: #4976
Needs fixing tests that expect a default loop to be used, and adding docs, including manual setting for CrawlerProcess/Runner in https://docs.scrapy.org/en/latest/topics/asyncio.html#installing-the-asyncio-reactor
=> Set WindowsSelectorEventLoopPolicy on Windows.

docs/news.rst, docs/topics/practices.rst, docs/topics/settings.rst, scrapy/commands/shell.py, scrapy/crawler.py, scrapy/utils/log.py, tests/CrawlerProcess/twisted_reactor_custom_settings.py, tests/CrawlerProcess/twisted_reactor_custom_settings_conflict.py, tests/CrawlerProcess/twisted_reactor_custom_settings_same.py, tests/test_commands.py, tests/test_crawler.py
=> Install the reactor after reading spider settings 

scrapy/core/downloader/middleware.py, scrapy/core/spidermw.py, scrapy/middleware.py
Unfortunately, `MiddlewareManager.methods` contains methods in most cases, but methods or None for spider middleware `process_spider_output` and `process_spider_exception` methods, because those need to keep their mutual order, as they can call each other.
=> Fix typing of middleware methods.

scrapy/settings/__init__.py, tests/test_cmdline/__init__.py, tests/test_cmdline/settings.py
=> Fix TypeError on using pathlib.Path as key on FEEDS settings

.github/workflows/checks.yml, .github/workflows/tests-ubuntu.yml
=> CI: stop using tox-pip-version

scrapy/http/response/text.py, tests/test_http_response.py
Safe to remove according to the [deprecation policy](https://docs.scrapy.org/en/2.5/versioning.html#deprecation-policy), as it was deprecated 1.5 years ago with version [2.2](https://docs.scrapy.org/en/2.5/news.html#scrapy-2-2-0-2020-06-24)
=> Remove deprecated TextResponse.body_as_unicode

docs/conf.py, scrapy/exporters.py, scrapy/item.py, scrapy/utils/misc.py, tests/test_item.py
More deprecation removals:
* `DictItem` deprecated on [1.8](https://docs.scrapy.org/en/latest/news.html#scrapy-1-8-0-2019-10-28)
* `BaseItem` deprecated on [2.2](https://docs.scrapy.org/en/latest/news.html#scrapy-2-2-0-2020-06-24)
=> Remove deprecated DictItem/BaseItem classes

docs/intro/examples.rst, docs/intro/overview.rst, docs/intro/tutorial.rst, docs/topics/developer-tools.rst, docs/topics/logging.rst, docs/topics/settings.rst, docs/topics/signals.rst
Fixes the issue raised in #5395 by replacing each occurrence of `http://quotes.toscrape.com` with `https://quotes.toscrape.com`.
=> docs: use https scheme for each quotes.toscrape.com url occurrence

scrapy/spiders/feed.py, tests/test_spider.py
=> Fix csviter call, add parse_rows test

pytest.ini, tests/mockserver.py, tests/test_downloader_handlers.py, tests/test_webclient.py, tox.ini
Fixes #5400, see the explanation there.
I've decided to put the classes into mockserver.py because it already has a resource class and other two files already import from it. But it's possible to move them into a separate file (in which case I'd discuss if we want to keep those supplementary modules in tests/ or move them into a subdir).
=> Fix running tests with Twisted 22.1.0

tests/test_command_check.py
=> Use toscrape.com instead of example.com in test_command_check.

tox.ini
=> Pin old markupsafe when we pin old mitmproxy.

docs/topics/practices.rst
Closes #3582
The terms of use allow scraping as long as Scrapy honours the restrictions of robot.txt files and NOFOLLOW metatags
Common Crawl terms of use: https://commoncrawl.org/terms-of-use/
=> Recommend Common Crawl instead of Google Cache

scrapy/cmdline.py, tests/test_commands.py
Closes: #5444 
This happen because `argparse` module treats the `-` as prefix chars: https://github.com/python/cpython/blob/main/Lib/argparse.py#L2205:L2207
Since we cannot change the internal implementation of `_parse_optional` i created a class that inherits from `ArgumentParser` class and override the method with our use case calling the default `_parse_optional`.
=> Fix -o - broken in 2.6

docs/topics/downloader-middleware.rst, tests/requirements.txt
I have noticed that the offcial documentation suggests using [brotlipy](https://pypi.org/project/brotlipy/). While this works, the project seems to be stale or abandoned. Most recent release was in 2017 and most recent commit - in 2018.
I suggest replacing that with a more recent and seemingly more actively supported [Brotli](https://pypi.org/project/Brotli) by google. It's most recent release was in 2018 and most recent commit - this month. This library has same API and judging by my experience, has proved to work seamlessly.
=> change link for brotli package to a supported one

docs/topics/downloader-middleware.rst
Fix small typo in the docs about number of storage backends available by default with Scrapy
=> fixed typo in httpcache docs

docs/topics/developer-tools.rst
Updated the documentation for developer tools to have JavaScript instead of Javascript, as JavaScript is the more correct way to write it
=> Fix capitalization of JavaScript within the Developer Tools documentation

scrapy/core/engine.py, tests/test_engine.py
Fixes: #5437
I must say, however, that I do not fully understand the code involved, and I suspect there must be a cleaner way to address this.
To-Do:
=> engine: prevent slot method call after unsetting the slot

scrapy/crawler.py, tests/CrawlerProcess/multi.py, tests/test_crawler.py
=> CrawlerProcess: initialize the reactor only once

docs/topics/practices.rst
i noticed passing settings to configure logging function made weird output go away. checked documentation and it says first parameter is settings file. Is this correct?
=> documentation update for multiple spiders

scrapy/commands/parse.py, tests/test_commands.py
Fixes #5481 
`scrapy parse -h`   now displays the appropriate help message.
=> Fix TypeError in parse command

scrapy/extensions/memusage.py, scrapy/extensions/statsmailer.py, tests/CrawlerProcess/twisted_reactor_custom_settings_same.py
Some fixes in the extensions files memusage.py and statsmailer.py and in the test file twisted_reactor_custom_settings_same.py
were needed in order for the flake8 check to be succesful.
=> Fix typos in three files for Flake8 check

scrapy/commands/parse.py, tests/test_command_parse.py
Changes
Implementation:
- Check whether Spider exists or is None, and if it's None skip execution of start_requests() with non existing Spider
Testing:
- Add a test case with invalid url inside test_command_parse
Test proves that non-matched Spider does not throw an AttributeError
Fixes #3264, resolves #5376
=> Issue #3264, fix error handling when spider is not matched

docs/topics/media-pipeline.rst, scrapy/pipelines/images.py, scrapy/pipelines/media.py, tests/test_pipeline_images.py, tests/test_pipeline_media.py
=> pass on item to thumb_path function as additional argument 

docs/intro/install.rst, tests/test_downloadermiddleware.py, tests/test_utils_signal.py, tests/test_webclient.py
=> Remove minimal versions that Scrapy is tested against, cleanup

docs/_static/selectors-sample1.html, tests/sample_data/link_extractor/linkextractor.html, tests/sample_data/link_extractor/linkextractor_latin1.html, tests/sample_data/link_extractor/linkextractor_no_href.html, tests/sample_data/link_extractor/linkextractor_noenc.html, tests/sample_data/test_site/index.html, tests/sample_data/test_site/item1.html, tests/sample_data/test_site/item2.html
I have updated the HTML files following SonarCloud's recommendations.
=> HTML Conventions

docs/topics/settings.rst, scrapy/crawler.py, scrapy/utils/reactor.py, tests/CrawlerProcess/reactor_default.py, tests/CrawlerProcess/reactor_default_twisted_reactor_select.py, tests/CrawlerProcess/reactor_select.py, tests/CrawlerProcess/reactor_select_subclass_twisted_reactor_select.py, tests/CrawlerProcess/reactor_select_twisted_reactor_select.py, tests/test_crawler.py
=> If TWISTED_REACTOR is None, reuse any pre-installed reactor

docs/conf.py, docs/news.rst
Fixes the docs build and covers #5525
=> Update 2.6 release notes

scrapy/downloadermiddlewares/cookies.py
Updated the code with the f-string method for better and cleaner understanding.
=> MAINT: Updated f-string format

scrapy/http/headers.py, tests/test_http_headers.py
=> Merge values of multiple headers with same name 

scrapy/downloadermiddlewares/decompression.py
=> Deprecate the `scrapy.downloadermiddlewares.decompression` module

docs/topics/exporters.rst
Fix the import in the example.
=> Fix doc: `scrapy.exporter` to `scrapy.exporters`

docs/conf.py
Build is failing at master because a few pages changed their location. It should be fixed in this PR.
=> Fixed intersphinx references

tests/test_exporters.py, tests/test_loader.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_utils_serialize.py
It was Python 3.6 compat code, and Python 3.6 support is dropped.
test_engine is not handled in this PR, to avoid conflicts with https://github.com/scrapy/scrapy/pull/5561; it's solved in https://github.com/scrapy/scrapy/pull/5561/commits/f3801f1126a42682b9a8188e64345e524295c38c.
=> remove compatibility code from tests for the case dataclasses module is not available

tests/__init__.py, tests/test_command_shell.py, tests/test_crawl.py, tests/test_downloader_handlers.py
This is an attempt to fix https://github.com/scrapy/scrapy/runs/7377071488?check_suite_focus=true failure.
```
================================== FAILURES ===================================
_________ Http11ProxyTestCase.test_download_with_proxy_https_timeout __________
self = <tests.test_downloader_handlers.Http11ProxyTestCase testMethod=test_download_with_proxy_https_timeout>
@defer.inlineCallbacks
def test_download_with_proxy_https_timeout(self):
""" Test TunnelingTCP4ClientEndpoint """
http_proxy = self.getURL('')
domain = 'https://no-such-domain.nosuch/'
request = Request(
domain, meta={'proxy': http_proxy, 'download_timeout': 0.2})
d = self.download_request(request, Spider('foo'))
>       timeout = yield self.assertFailure(d, error.TimeoutError) …
```
=> make Scrapy testing suite more robust in environments where non-existing hosts are resolvable

pytest.ini, tests/test_contracts.py, tests/test_crawl.py, tests/test_crawler.py, tests/test_downloadermiddleware_httpauth.py, tests/test_downloadermiddleware_httpproxy.py, tests/test_downloadermiddleware_stats.py, tests/test_dupefilters.py, tests/test_engine.py, tests/test_engine_stop_download_bytes.py, tests/test_engine_stop_download_headers.py, tests/test_feedexport.py, tests/test_logformatter.py, tests/test_pipeline_crawl.py, tests/test_request_attribute_binding.py, tests/test_request_cb_kwargs.py, tests/test_scheduler.py, tests/test_scheduler_base.py, tests/test_spiderloader/__init__.py, tests/test_utils_project.py, tests/test_utils_request.py, tests/test_utils_response.py
These warnings don't really affect anything, but there's a lot of them at the end of the test run, which make it harder to read the results.
It should be more reasonable after this PR. Some unique warnings are still there; total count is reduced from 569 to 207 warnings (Ubuntu + Python 3.10 env).
=> Less warnings in tests

scrapy/utils/url.py, tests/test_utils_url.py
#4066 added more extensions to ignore by default such as `.rar` or `.zip`, which is great. 
Unfortunately, the addition of `.tar.gz` as an extension to exclude is not working because of the implementation of the function `url_has_any_extension` which can be found in `scrapy/utils/url.py`.
The actual function looks like this:
```python3
def url_has_any_extension(url, extensions):
return posixpath.splitext(parse_url(url).path)[1].lower() in extensions
```
Here is an example that does not work:
```python3
import posixpath
from urllib.parse import urlparse
from scrapy.utils.url import parse_url
parsed_url = urlparse("https://dl.google.com/go/go1.7rc3.freebsd-amd64.tar.gz")
url_has_any_extension(parsed_url, [".tar.gz"])
posixpath.splitext(parse_url(parsed_url).path)[1].lower() in [".tar.gz"] …
```
=> fixed detection of extensions like ".tar.gz" in URL

docs/topics/downloader-middleware.rst
Currently a couple of headers are not properly nested; this affects the sidebar:
=> Fixed heading levels in downloader middleware docs

scrapy/http/response/text.py, tests/test_http_response.py
=> BOM should take precedence over Content-Type header when detecting the encoding

docs/intro/tutorial.rst
=> fix: typo in tutorial

docs/contributing.rst
correcting
```
arning, treated as error:
/home/runner/work/scrapy/scrapy/docs/contributing.rst:216:unknown document: twisted:core/development/policy/test-standard
ERROR: InvocationError for command /home/runner/work/scrapy/scrapy/.tox/docs/bin/sphinx-build -W -b html . /home/runner/work/scrapy/scrapy/.tox/docs/tmp/html (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
```
=> Update test-standard link in contributing docs

docs/topics/settings.rst
Resolves https://github.com/scrapy/scrapy/issues/5607
=> Documented how settings must be picklable

setup.py, tests/test_crawler.py, tox.ini
Resolves #5621
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
Correcting https://github.com/scrapy/scrapy/actions/runs/3052958225/jobs/4922962575
```
from twisted.internet import error, tcp, udp
.tox/py/lib/python3.8/site-packages/twisted/internet/tcp.py:38: in <module>
from twisted.internet._newtls import (
.tox/py/lib/python3.8/site-packages/twisted/internet/_newtls.py:18: in <module>
from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
.tox/py/lib/python3.8/site-packages/twisted/protocols/tls.py:45: in <module>
from twisted.internet._sslverify import _setAcceptableProtocols
.tox/py/lib/python3.8/site-packages/twisted/internet/_sslverify.py:1828: in <module>
defaultCiphers = OpenSSLAcceptableCiphers.fromOpenSSLCipherString( …
```
=> Match pyOpenSSL and service_identity to Twisted

docs/topics/settings.rst, scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/tls.py
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
docs generation is not running for PRs?
Fixes #5632, fixes #5635.
=> Cleanup METHOD_SSLv3

docs/topics/spiders.rst
Fixes #5602. I could not find any other similar errors (i.e. places where it says that the return type of a `Request` callback function must only be an iterable).
=> Changed incorrect info in documentation regarding the return type of parse method.

.github/workflows/checks.yml, tox.ini
=> CI: add Twine check in check workflow

scrapy/spiders/crawl.py, scrapy/utils/asyncgen.py, tests/spiders.py, tests/test_crawl.py
I stumbled upon this by seeing reports of people getting errors when trying to use the CrawlSpider in combination with scrapy-playwright.
=> CrawlSpider: add support for async callbacks

scrapy/utils/display.py, setup.py
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
=> Correct distutils deprecation warning

tox.ini
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Match pyOpenSSL and types-pyOpenSSL versions

tests/test_feedexport.py
Workaround for #5633
~~While debugging in Windows to identify the root cause i noticed that the test don't fail. So it seems that in Windows the test run too fast and this result in a invalid output, so in order to fix the test i add a delay only for Windows and this make the test suceed, since now the output is correct.~~
Check https://github.com/scrapy/scrapy/pull/5639#issuecomment-1259300827 for details.
=> fix: `batch_path_differ` test

.github/workflows/tests-ubuntu.yml, scrapy/utils/python.py
It looks like we can finally run CI on 3.11 and it fails. So this is the first step for adding support for 3.11.
=> Python 3.11 support

.github/workflows/tests-ubuntu.yml
This is evidently no longer needed.
=> Remove a pin on libxml2-dev.

README.rst
minor modifications to the readme to use relative links for the docs dir and code of conduct for easier navigation
=> docs: update readme to use links

docs/intro/install.rst
The first one i bumped to match the same version of pypy3.7, after this PR was merged:
- https://github.com/scrapy/scrapy/pull/5667
I was in doubt about what version to use in second statement but both pypy3.7 and pypy3.9 use the same version, maybe we could remove this paragraph altogether since now is redundant? Version 5.9.0 is from 2017-10-05.
=> Update PyPy version in documentation

docs/topics/settings.rst, scrapy/templates/project/module/settings.py.tmpl, tests/test_commands.py
=> Change TWISTED_REACTOR in the default template.

scrapy/pipelines/images.py
fixes #5684 
Using try except block to support backward compablility of order version of Pillow. It can we removed when the minimum requirement of Pillow is updated.
=> Handle deprecated warning with try except block

scrapy/utils/misc.py, tests/test_utils_misc/test_return_with_argument_inside_generator.py
closes #5323
Replace starting indentation with pattern `(^[\t ]+)` and replace the matching indentation in other lines.
=> Replace indentation of source before parsing with ast.

.github/workflows/tests-macos.yml
The GitHub Actions macos-10.15 runner image is now deprecated, and GitHub Actions has begun to temporarily fail jobs referencing it during brownout periods. The image will be fully unsupported by 2022-12-01, which is just about a month away.
This change updates the macOS runner image to the latest generally-available version, to help reduce spurious CI failures during the brownout periods, and to stay abreast of the sunsetting of the macos-10.15 image.
See also: actions/runner-images#5583
=> ci: Update macos runner

scrapy/utils/defer.py, scrapy/utils/reactor.py, tests/test_utils_asyncio.py
Fixes #5685
Use `policy.get_event_loop()` instead of `asyncio.get_event_loop()`.  
If there is no event loop running, policy will create new_event_loop.
=> Get eventloop from event_loop_policy to avoid deprecation warning.

pytest.ini
fixes #5686  
Added typing.io and typing.re in pytest warning filter to ignore.
=> added typing.io and typing.re in pytest warning filter to ignore

scrapy/spiders/crawl.py, tests/spiders.py, tests/test_crawl.py
`CrawlSpider._callback` is not passing any keyword arguments it might receive to `CrawlSpider._parse_response`.
I'm currently giving priority to the arguments set in `process_request` over the ones set in the rule, this could be open to discussion.
~~Missing tests, will add them soon.~~ Added
Sample spider:
```python
from scrapy.spiders import CrawlSpider, Rule
class ExampleSpider(CrawlSpider):
name = "example"
start_urls = ["https://example.org"]
rules = (
Rule(
process_request="process_request",
callback="parse_item",
),
)
def process_request(self, request, response):
request.cb_kwargs["foo"] = "bar"
return request
def parse_item(self, response, foo):
return {"url": response.url, "foo": foo}
```
Without this patch, at 9077d0f9b490114f117c668f115240c16afccedf (latest `master` branch)
``` …
```
=> CrawlSpider: pass cb_kwargs from process_request

scrapy/utils/boto.py, scrapy/utils/gz.py, scrapy/utils/python.py, tests/test_utils_python.py
The [Deprecation policy](https://docs.scrapy.org/en/latest/versioning.html#deprecation-policy) of Scrapy state:
> We aim to maintain support for deprecated Scrapy features **for at least 1 year**.
Here the list of deprecated functions/class and they correspond release notes/date:
=> Remove deprecated code

scrapy/extensions/memusage.py
Fixes #5717 
Request for additional memory logging when scrapy jobs with `MEMUSAGE_ENABLED : True` and `MEMUSAGE_LIMIT_MB` defined are stopped early. This should further assist with memory debugging by providing the size of the current process.
=> Adds get_virtual_size to _check_limit Logging

scrapy/utils/project.py, tests/test_cmdline/__init__.py, tests/test_utils_project.py
Another cleanup. 🧹 (Last one this week i promise 🤞🏻 )
We could change the `valid_envvars` and append `SCRAPY_` prefix, but i choose to leave the dictionary intact and just add another condition to if statement, changed tests accordingly.
=> Remove support for override settings with `SCRAPY_` environment variables

scrapy/core/http2/stream.py, scrapy/http/request/__init__.py, scrapy/http/response/__init__.py, scrapy/settings/__init__.py, scrapy/spiders/__init__.py
Changing all dunder-str to dunder-repr
Some **\_\_repr__** were being set as **\_\_repr__** = **\_\_str__**, we actually dont need this because if the compiler does not find \_\_str__, then it will get **\_\_repr__** as an alternative. 
https://onecompiler.com/python/3wxqqch57
=> changing dunder-str to dunder-repr

scrapy/core/downloader/handlers/http11.py, scrapy/core/downloader/handlers/http2.py, tests/test_downloader_handlers.py, tests/test_downloader_handlers_http2.py
I was in doubt about how to approach this one, so i basically remove all logic that depends upon `omitConnectTunnel`, maybe should we also pop the `b'noconnect` parameter?
=> Remove `noconnect` deprecate code

scrapy/settings/__init__.py, scrapy/utils/deprecate.py
This change removes the `_DictProxy` class from `scrapy/settings/__init__.py` since it is no longer used. It also removes `scrapy.telnet` from the `DEPRECATION_RULES` as part of the cleanup. It resolves https://github.com/scrapy/scrapy/issues/5729, resolves https://github.com/scrapy/scrapy/issues/5725.
=> Cleanup settings._DictProxy and scrapy.telnet

scrapy/extensions/memusage.py
Fixes outstanding comments within #5722 
1. Changed comments referencing "Current" memory usage to "Peak".
2. Changed comments referencing "M" to "MiB" where applicable.
=> Better language surrounding logging

scrapy/utils/conf.py
Related: https://github.com/scrapy/scrapy/issues/5726. The code seems to still be in use and is being invoked therefore, we can remove the backwards compatibility comment since it is part of the feature still. I didn't come across any code that would suggest this use-case will never be executed.
=> Remove unnecessary backwards compatibility comments

tests/test_downloader_handlers.py
I had no idea why is this needed and how should it be used (https://github.com/scrapy/scrapy/pull/5285/files#r844017508, https://github.com/scrapy/scrapy/pull/5682/files/726680c7125ab3a6622b12e25d45dbfedc5a39b3#r1027288466) so I tracked it down to 3012030b2faea43b00cb8ae233321c1f9eb8a579 and added this comment.
=> Add a comment about `tmpname + '^'`.

scrapy/commands/__init__.py, scrapy/core/scraper.py, scrapy/crawler.py, scrapy/http/response/__init__.py, scrapy/http/response/text.py, scrapy/middleware.py, tox.ini
I've tried flake8 6.0.0 and it looks like it ignores types used in type hint comments (I didn't know we have those), so I updated them and also bumped mypy and fixed its (non-error) output about not checking untyped functions.
=> Bump mypy and flake8

tests/test_http_response.py
The tests are failing because after release 2.1.1, w3lib is striping spaces from url, so i add a validation to append `%20` if the version that is running is minor than 2.1.1.
- https://github.com/scrapy/w3lib/pull/207
resolves #5750
=> fix test_follow_whitespace_* tests

scrapy/shell.py, scrapy/utils/reactor.py, tests/test_command_shell.py
This is an alternative to PR https://github.com/scrapy/scrapy/pull/5748 which addresses the issues https://github.com/scrapy/scrapy/issues/5740 and https://github.com/scrapy/scrapy/issues/5742
The alternative approach used in this PR is to explicitly set the event loop in the new thread created by the scrapy shell when using the fetch command.
The main benefit to this strategy is the ability to honor the `ASYNCIO_EVENT_LOOP` setting.
Closes #5748, fixes #5740.
=> set asyncio event loop at start of new thread

docs/topics/settings.rst
To be consistent with the other settings' descriptions
=> docs: change DOWNLOAD_DELAY description format

.github/workflows/publish.yml, tox.ini
Closes #5774
We don't need to install `setuptools` and `wheel` packages anymore in publish workflow because build create a virtual environment in order to build the package. We don't need to pass any argument to `build` command because the default behaviour already create a wheel/source distribution
=> Deprecate direct invocation of `setup.py`

tox.ini
Partial fix for https://github.com/scrapy/scrapy/issues/5749
=> Fix test_pinned_twisted_version

setup.py, tox.ini
Fixes #5785.
I am not sure exactly why CI started failing, I assume because the Docker image started using a newer OpenSSL. [3.4.6 recompiled wheels for OpenSSL 1.1.1j](https://cryptography.io/en/latest/changelog/#v3-4-6). I think increasing the minimum cryptography version is a small price to pay.
=> Minimum cryptography: 3.3 → 3.4.6

scrapy/shell.py
Currently, after calling `scrapy.shell.inspect_response` and then closing the opened shell, SIGINT (Ctrl-C) no longer works to terminate the spider.  This is because `Shell.start`, called in `inspect_response`, removes the signal handler.  To fix this, save the SIGINT handler before calling `Shell.start` in `inspect_response` and add it again after the shell has closed.
It doesn't appear that there are any tests for `inspect_response`, so I haven't added any tests for this fix.
=> Fix SIGINT handling when using inspect_response

scrapy/core/http2/stream.py, tests/test_downloader_handlers.py
This commit fixes the overwriting bug of repeated header values using HTTP2
```py
raw_response = \
"""
HTTP 1.1 200 OK
Set-Cookie: first=1
Set-Cookie: second=2
"""
>>> response.headers.getlist(b'Set-Cookie')
[b'second=2']
>>> response.headers.getlist(b'Set-Cookie')
[b'first=1', b'second=2']
```
=> Fix overwriting repeated headers in HTTP2

scrapy/extensions/feedexport.py, tests/test_feedexport.py
Figured I'd take a crack at #5537 since it's been stale for a while.
This patch moves the call to `slot.finish_exporting()` up to before the conditional that checks if `slot.item_count > 0` so that if an exception occurs when an exporter's `export_item()` method is called, `slot.finish_exporting()` will still be called (as discussed in the issue).
I've included 4 new tests to that each check that:
1. if `slot.start_exporting()` was called that there is a call to `slot.finish_exporting()` after
2. `slot.finish_exporting()` is not called before a call to `slot.start_exporting()`. I.e. they assert that `slot.finish_exporting()` isn't called twice in a row without a call to `slot.start_exporting()` in between and that `slot.finish_exporting()` isn't called before an initial call to …
=> Finish exporting for each start exporting

scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/tls.py, scrapy/utils/ssl.py, tests/mockserver.py
Fixes #5491.
I don't know if we can have a test for it: it would require a server configured in a certain way, I need to check if it's even possible when using OpenSSL 3 on the server side. Locally I tested it on https://dorotheum.com/ with "pyOpenSSL 21.0.0 ('OpenSSL 1.1.1j  16 Feb 2021'), cryptography 3.4.6" (no error and website is accessible with and without the change) and "pyOpenSSL 23.0.0 ('OpenSSL 3.0.7 1 Nov 2022'), cryptography 39.0.0" (website is accessible only with the change).
=> Enable unsafe legacy renegotiation

scrapy/utils/console.py
Since version 3.7, it makes no sense to use OrderedDict because python keeps data in dictionaries in order. Ordinary dictionaries are fastest than OrderedDict
=> Replace OrderedDict to dict

scrapy/mail.py, tests/test_mail.py
Pass hostname to the ESMTPSenderFactory when the twisted version is higher than 21.2.0 to use STARTTLS.
Fixes #5386
=> Fix SMTP STARTTLS for Twisted >= 21.2.0 (5386)

docs/topics/feed-exports.rst, scrapy/templates/project/module/settings.py.tmpl
=> Set `FEED_EXPORT_ENCODING='utf-8'` in the default template

scrapy/downloadermiddlewares/robotstxt.py, tests/test_downloadermiddleware_robotstxt.py
Currently robots.txt is attempted to be checked for local files (and data urls). You can reproduce with:
```python
from scrapy import Spider
class TestSpider(Spider):
name = "test"
start_urls = [
"data:text/plain,Hello World data",
"file:///home/cj/hello world.txt",
]
def parse(self, response, **kwargs):
print(response.text)
```
`$ pipenv run scrapy runspider test.py -s ROBOTSTXT_OBEY=True`
```
2023-01-26 15:50:47 [scrapy.core.engine] INFO: Spider opened
2023-01-26 15:50:47 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-01-26 15:50:47 [scrapy.downloadermiddlewares.robotstxt] ERROR: Error downloading <GET data:/robots.txt>: invalid data URI
File …
```
=> Don't check robots.txt for local files

scrapy/templates/project/module/middlewares.py.tmpl, scrapy/templates/project/module/settings.py.tmpl, scrapy/templates/spiders/basic.tmpl, scrapy/templates/spiders/crawl.tmpl, scrapy/templates/spiders/csvfeed.tmpl, scrapy/templates/spiders/xmlfeed.tmpl, tests/test_commands.py
I ran black formatter on all of the template files in `scrapy/templates`.  There were very few changes that it made, most of which were changing single quotes `'` to double quotes `"`, or adding a single space in between the hash character and everything else for commented out values in the `settings.py` file.  
It did break a few unit tests for the `genspider` command used regex for string comparisons.  I fixed these by making the regex patterns ambiguous to single or double quotes. 
Fixes #5809 
This shouldn't have any effect on #5808 since I used the same quote ambiguous patterns for the regex in that PR as well.
=> apply black to templates and fixed unit tests Fixes #5809

.github/workflows/publish.yml
Simplify publish workflow by using official PyPI publish action.
=> Simplify Publish workflow

scrapy/settings/__init__.py, tests/test_settings/__init__.py
Added the `setdefault` method to the `BaseSettings` class.
Now `setdefault` works as expected, if the _key_ does not exist in `BaseSettings` then this _key_ will be added and _default value_ will be assigned to it and this _value_ will be returned. For example:
```python
from scrapy.settings import BaseSettings
settings = BaseSettings()
print(settings.setdefault("some_key", "default_value"))
print(settings.get("some_key"))
```
Closes https://github.com/scrapy/scrapy/issues/5811
=> Added `setdefault` to `BaseSettings`

scrapy/commands/parse.py, scrapy/utils/spider.py, tests/test_command_parse.py
=> Fixed #5819 -- Bug of parse command

scrapy/downloadermiddlewares/decompression.py
`BadZipfile` (with a small `f`) has been deprecated since Python 3.2, use `BadZipFile` (big `F`) instead, added in 3.2.
* https://docs.python.org/3/library/zipfile.html#zipfile.BadZipfile
* https://github.com/python/cpython/issues/86437
=> Replace deprecated BadZipfile with BadZipFile

scrapy/utils/ssl.py
=> Don't call SSL_get_server_tmp_key() if not available.

docs/topics/dynamic-content.rst
I've been reading scrapy documentation and I've realized that a slash is missing in one of the examples. This PR adds the missing slash in the "selecting dynamically-loaded content" documentation.
=> Add missing slash in selecting dynamically-loaded content documentation

scrapy/mail.py
=> return failure added to _sent_failed 

scrapy/pipelines/files.py, tests/test_pipeline_files.py
Fixes #5874 
Replace the raw checksum with b64 decoded checksum for GCS
=> Replace the raw checksum with b64 decoded checksum for GCS

scrapy/linkextractors/lxmlhtml.py, tests/test_linkextractors.py, tox.ini
When processing links, in certain edge-cases I have noticed crawlers crashing with the following/similar error, when all other links are parsed successfully:
```
File "/usr/local/lib/python3.11/site-packages/scrapy/utils/defer.py", line 254, in aiter_errback
yield await it.__anext__()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/scrapy/utils/python.py", line 366, in __anext__
return await self.data.__anext__()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/scrapy/utils/python.py", line 347, in _async_chain
async for o in as_async_generator(it):
File "/usr/local/lib/python3.11/site-packages/scrapy/utils/asyncgen.py", line 14, in as_async_generator
async for r in it:
File …
```
=> Patched LxmlParserLinkExtractor

scrapy/utils/python.py, tests/test_utils_python.py
=> Replace get_func_args

scrapy/utils/request.py, tests/test_utils_request.py
Implement request_to_curl util function that generates a curl command string from a scrapy.Request object
=> implement request_to_curl function

scrapy/core/downloader/__init__.py, scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/handlers/__init__.py, scrapy/core/downloader/middleware.py, scrapy/core/downloader/tls.py, scrapy/core/downloader/webclient.py, scrapy/utils/python.py, scrapy/utils/ssl.py
It doesn't seem worth it to add typing for code that uses Twisted HTTP stuff, as that code is itself untyped and also some of our code uses zope.interface which is not really supported by mypy.
=> Typing for scrapy/core/downloader

scrapy/utils/curl.py, tests/test_utils_curl.py
Hi @wRAR 
I added an [`action`](https://docs.python.org/3/library/argparse.html#action) for the `--data` argument that removes the _string prefix_ and decodes the string. Although `Request.from_curl()` now works correctly with requests like the one you shared in the issue, I don't know if this is the best way to approach this.
```python
curl_command = "curl 'https://www.example.org/' --data-raw $'{\"$filters\":\"Filter\u0021\"}'"
curl_to_request_kwargs(curl_command)
```
Closes https://github.com/scrapy/scrapy/issues/5899
=> Fix: Request.from_curl() with $-prefixed string literals

docs/intro/tutorial.rst, pytest.ini, tox.ini
Fix docs/intro/tutorial.rst checks:
command:
```
pytest docs
```
output:
```
FAILED docs/intro/tutorial.rst::line:254,column:1
FAILED docs/intro/tutorial.rst::line:350,column:1
FAILED docs/intro/tutorial.rst::line:412,column:1
```
=> fix: docs/intro/tutorial.rst checks

.bandit.yml, .pre-commit-config.yaml, tox.ini
No code changes (but we don't bump flake8 until we drop 3.7).
=> Update tool versions

scrapy/http/response/text.py, scrapy/responsetypes.py, tests/test_http_response.py, tests/test_responsetypes.py
Resolve #5914
Applied the proposed solution: https://github.com/scrapy/scrapy/issues/5914#issuecomment-1527319928
⚠️ Failed tests don't have anything to do with the change.
=> fix: non-UTF-8 content-type headers

docs/topics/feed-exports.rst
Fixes #5579, closes #5593
Adds to the documentation the description of the default value of the overwrite option in feeds for the Google Cloud Storage backend.
Adds alerts about the risk of losing your data for storage backends that have this default value equal to true.
=> Improve the overwrite feed option documentation

tests/test_utils_asyncio.py
The test added in #5832 was never actually run. It was also broken.
=> Actually run test_set_asyncio_event_loop().

tests/mockserver.py, tests/test_cmdline/__init__.py, tests/test_crawler.py, tests/test_proxy_connect.py
Fixes #4914 by using get_testenv() only for `python3 -m scrapy.cmdline` and finding files under `tests` via different mechanisms.
For some reason running these as-installed tests in the Debian autopkgtest chroot always fails on `tests/test_crawl.py::CrawlTestCase::test_start_requests_laziness` with "All start requests consumed before any download happened". I've looked at the test and the spider it runs and I don't understand if it just relies on mockserver replying faster than start_requests schedules requests or there is something more stable. When I extracted this spider and ran it via `scrapy crawlspider` on a separately started mockserver it also often (but not always) fails with the same problem. It's possible that the test is just flaky and depends on performance of various …
=> Allow running tests against the installed version

docs/topics/feed-exports.rst, scrapy/extensions/feedexport.py, tests/test_feedexport.py
This PR is related to #5739  as well as some conflicting information in the docs.
On the [Feed Exports](https://docs.scrapy.org/en/latest/topics/feed-exports.html#topics-feed-storage-fs) page, in the [FEEDS](https://docs.scrapy.org/en/latest/topics/feed-exports.html#feeds) subsection it mentions that you can use a URI or a `pathlib.Path` object as the target.
https://github.com/scrapy/scrapy/blob/33b418dc846c8a0de21bef7a71c7ed259e24b269/docs/topics/feed-exports.rst?plain=1#L412-L423
Earlier on the same page however under the [Storage Backends](https://docs.scrapy.org/en/latest/topics/feed-exports.html#local-filesystem) section it mentions that you can use a standard string path as long as its an absolute path, but only on Unix systems. …
=> Adding support for windows absolute pathlib.Path objects in FeedExporter

scrapy/settings/__init__.py, tests/test_settings/__init__.py
=> chore: Implement `pop` method on `BaseSettings` class

scrapy/settings/__init__.py, tests/test_settings/__init__.py
As reported on https://github.com/scrapy/scrapy/issues/5959#issuecomment-1609832116, the implementation of `pop` method is returning `SettingsAttribute` object instead of the value itself which break interface. Mea culpa, sorry! 😅
=> fix: Return value instead of `SettingsAttribute` object when using `pop` method

scrapy/utils/project.py
Just removing hard code statements
=> Removing hard code entries

scrapy/extensions/feedexport.py, scrapy/utils/conf.py, tests/test_commands.py
=> fix: -O/-o option does not work with absolute paths on Windows

docs/topics/feed-exports.rst, scrapy/extensions/feedexport.py, tests/test_feedexport.py
Similar PRs:
- https://github.com/scrapy/scrapy/pull/5092
- https://github.com/scrapy/scrapy/pull/4429
- https://github.com/scrapy/scrapy/pull/4417
=> expose AWS_REGION_NAME in S3FeedStorage

scrapy/crawler.py, scrapy/settings/__init__.py, scrapy/utils/conf.py, tests/test_settings/__init__.py, tox.ini
This adds full typing for `BaseSettings`. There is one potential optimisation here: `BaseSettings` is both the Scrapy settings as a whole (with keys that can only be strings) and setting values for things like `FEEDS` (with keys of various types), if it's possible to separate these it's possible to type the former more correctly. But that seems to require changing the class hierarchy and so it's more harm than good.
Another things that is out of scope and not really useful is `Settings` vs `BaseSettings` in the annotations of the code that uses settings. The code difference between those classes is only the `__init__` method so their interfaces are currently identical.
=> Typing for scrapy.settings.BaseSettings

docs/topics/extensions.rst, scrapy/extensions/closespider.py, tests/spiders.py, tests/test_closespider.py
**Motivation:** Sometimes spiders still keep running without producing any items. This could be due to a variety of reasons like poor dupe URL filtration, bad crawling strategy, etc.
**Proposal:** Auto-close the spider if it hasn't produced any items in the past number of seconds.
=> introduce CLOSESPIDER_TIMEOUT_NO_ITEM in CloseSpider

docs/topics/settings.rst, docs/topics/spiders.rst
Added documentation for the `Spider.update_settings` class method.
Fixes #5745, closes #5757, closes #5784.
=> Added documentation for Spider.update_settings

.github/workflows/tests-windows.yml
Seems that now we have lxml available for 3.11 on Windows. 😄
=> Enable Python 3.11 on Windows CI

scrapy/exporters.py, tests/test_exporters.py
=> Remove deprecated PythonItemExporter.binary

docs/topics/item-pipeline.rst
Fixes #6008 
I looked in other files and this is the only place where we still have an example of passing an extra spider parameter.
=> Remove extra spider parameter in item pipeline docs

scrapy/extensions/corestats.py, scrapy/extensions/feedexport.py, tests/keys/__init__.py, tests/test_spiderstate.py, tests/test_stats.py
Make our datetime calls timezone-aware, `utcnow()` is deprecated and scheduled for removal, check why in this [article.](https://blog.ganssle.io/articles/2019/11/utcnow.html)
=> Remove datetime.utcnow() usage

docs/news.rst, scrapy/http/response/text.py, tests/test_http_response.py
Now `response.json()` uses `response.body` to retrieve the `dict` object, so the str response is no longer stored in RAM.
Closes https://github.com/scrapy/scrapy/issues/5968
=> Fix: response.json() call makes unnecessary memory allocation

scrapy/core/downloader/__init__.py, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/logformatter.py
=> Update type hints for Twisted 23.8.0.

docs/topics/api.rst, scrapy/crawler.py, tests/test_crawl.py, tests/test_crawler.py, tests/test_downloader_handlers.py
=> Deprecate running Crawler.crawl() twice.

scrapy/downloadermiddlewares/retry.py, tests/test_downloadermiddleware_retry.py
Fixes #6049 (with the code provided by the reporter)
=> Improve the backwards compatibility for RetryMiddleware.EXCEPTIONS_TO_RETRY

docs/news.rst
Updated the docs with the ``scrapy.utils.boto.is_botocore()`` function is removed at 2.8.0 release note.
Fixes #6056
=> #6056 Issue: Updated news.rst

.github/ISSUE_TEMPLATE/question.md
Maybe a specific entry for questions/help when opening an issue, and a shorter text to read, can minimize the chance of issues like https://github.com/scrapy/scrapy/issues/6065 further. Maybe.
=> Add a template for question/help issues

.github/workflows/checks.yml, .github/workflows/publish.yml, .github/workflows/tests-macos.yml, .github/workflows/tests-ubuntu.yml, .github/workflows/tests-windows.yml
Leverage concurrency groups along with cancel-in-progress to favor running the most recent job.
Closes #5997 
Concurrency groups are on a per workflow, per branch/tag basis. So, pushing newer updates to a branch, e.g. as part of a PR, should cancel any in progress runs of workflows that have been retriggered.
Note that I've added these to all workflows, since I couldn't think of a case where it wouldn't make sense to favor the more recently added jobs. Let me know if I've missed something, or that should be done differently.
Note as well that the documentation lists a caveat about order not being guaranteed. In practice I've never had issues with the ordering, though that was for smaller repos with less chance of parallel collaboration.
See:
- …
=> Use concurrency groups to limit duplicate jobs

docs/topics/request-response.rst
- Removed the whole part about sending custom cookies with `dont_merge_cookies` from the example
- Added warning that the custom cookies are ignored when `dont_merge_cookies` is set to true
Resolves #5936.
=> Fixed the dont_merge_cookies example in docs

.github/workflows/checks.yml, .github/workflows/publish.yml, .github/workflows/tests-macos.yml, .github/workflows/tests-ubuntu.yml, .github/workflows/tests-windows.yml
This PR updates all actions to use `actions/checkout` version 4.
=> Update checkout action to version 4

docs/news.rst
Typo fixed in docs/news.rst file:
correponding -> corresponding
=> Fixed Typo in news.rst file

docs/topics/downloader-middleware.rst, scrapy/robotstxt.py
Closes #5230. Note that we don't run tests for reppy because of https://github.com/seomoz/reppy/issues/132
=> Deprecate ReppyRobotParser.

scrapy/linkextractors/__init__.py
I have added a collection of extensions to the ignored extensions in [scrapy/linkextractors/__init__.py](https://github.com/scrapy/scrapy/blob/master/scrapy/linkextractors/__init__.py#L11) the additional extensions are `.jar .sh .rb .js .hta .bat .cpl .msi .msp .py`.
I think these extensions fit with the other extensions in the ignored list. All tests are currently passing. The only file that has changed is `__init__.py`.
=> added_extensions

docs/intro/tutorial.rst
When I used the tutorial, I was confused about how to run the spider again. I later realized that I never exited the Scrapy shell. 
This edit should provide more guidance to future users of Scrapy and the tutorial.
=> Update tutorial.rst: clarify how to run spider

scrapy/utils/project.py
Updating type hint for `scrapy.utils.project.data_path`. 
This is a small change which brings a part of solution of the issue [#5739](https://github.com/scrapy/scrapy/issues/5739).
The type hint change was suggested [here](https://github.com/scrapy/scrapy/issues/5739#issuecomment-1789203848).
=> scrapy.utils.data_path type hint change

docs/news.rst, docs/topics/spiders.rst
Fixes #6057, closes #6076, closes #6080.
I decided not to modify the signal doc because I'm not sure anymore that it makes sense to put that there.
=> Improve the docs about Crawler attributes and settings initialization.

scrapy/addons.py, scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/handlers/__init__.py, scrapy/core/downloader/handlers/http10.py, scrapy/core/downloader/handlers/s3.py, scrapy/core/engine.py, scrapy/core/scheduler.py, scrapy/crawler.py, scrapy/extensions/feedexport.py, scrapy/middleware.py, scrapy/pqueues.py, scrapy/utils/misc.py, tests/test_addons.py, tests/test_downloader_handlers.py, tests/test_downloader_handlers_http2.py, tests/test_settings/__init__.py, tests/test_utils_misc/__init__.py, tests/test_webclient.py
Converted `create_instance` to 2 separate functions (`build_from_crawler` and `build_from_settings`).
Changed other calls to `create_instance` in other files.
Added tests for the new functions.
Fixes #5523, closes #5884, closes #6162.
=> Converting create_instance to 2 separate functions

docs/contributing.rst
In https://github.com/scrapy/scrapy/pull/5823, `black` has been removed from `tox`, so running `tox -e black` no longer work.
```
> tox -e black
ROOT: HandledError| provided environments not found in configuration file:
black
```
Updated docs to `tox -e pre-commit` instead.
=> Update black reference in docs

scrapy/pipelines/files.py, scrapy/pipelines/images.py
Related https://github.com/scrapy/scrapy/issues/5739
Follow-up to https://github.com/scrapy/scrapy/pull/5801, where compatibility with `Path` was added but type hints were not updated.
=> Add type hints to FilesPipeline and ImagesPipeline

scrapy/pipelines/files.py
`os.error` is an alias of the preferable `OSError`.
https://docs.astral.sh/ruff/rules/os-error-alias/
=> refactor(): use `OSError` exception

scrapy/core/spidermw.py, scrapy/spiders/crawl.py, scrapy/spiders/feed.py, scrapy/spiders/sitemap.py, scrapy/utils/python.py, scrapy/utils/request.py, tests/spiders.py, tests/test_feedexport.py, tests/test_spider.py, tests/test_spidermiddleware.py, tests/test_utils_defer.py
The syntax is simpler to read.
Was introduced with Python 3.3.
https://peps.python.org/pep-0380/
=> refactor(yield): use `yield from` syntax

tests/test_extension_periodic_log.py
=> fix(typo): correct `successfully`

tests/test_proxy_connect.py, tox.ini
As usual, a two-character fix.
Fixes #5454.
=> Fix and re-enable newer mitmproxy usage in tests.

scrapy/extensions/memusage.py, tests/test_utils_iterators.py
Fixes new errors thrown with Python 3.12. (current gh ci passes because older py version)
- E226 missing whitespace around arithmetic operator
- E201 whitespace after '{'
=> fix(flake8): lint errors

scrapy/crawler.py, tests/test_crawler.py
[Suggested](https://github.com/scrapinghub/scrapy-poet/pull/172/files/99ba579a3d25454774c01f44a02df15e60e1a0eb#r1385084947) by @BurnzZ.
=> Add component getters to crawler

scrapy/commands/parse.py, tests/test_command_check.py, tests/test_command_parse.py
Fixes https://github.com/scrapinghub/scrapy-poet/issues/39.
It feels kind of hacky, specially the fact that it will not work for “rules”, but I see no way about it given rules depend on the response.
=> scrapy parse: fix the signature of callbacks from the CLI

docs/requirements.txt
Update `sphinx` dependencies to latest version.
Currently do not use sphinx v7 a lot is being reworked and often breaks.
#6177
=> chore(docs): update `sphinx` dependencies

docs/faq.rst
This PR addresses issue #6203, adding a FAQ entry on making a blank requests.
```python
yield Request(
url="data:,", 
callback=self.your_call_back
)
```
suggested by: @Gallaecio
=> Add FAQ on making a blank request

docs/topics/items.rst, docs/topics/selectors.rst
Removed `auto[function|class]` declarations from external projects
Resolves https://github.com/scrapy/scrapy/issues/5920, closes https://github.com/scrapy/scrapy/pull/6043, closes https://github.com/scrapy/scrapy/pull/6131.
=> Fix: Remove docs for other projects from the Scrapy docs

docs/topics/autothrottle.rst, scrapy/extensions/throttle.py, tests/test_extension_throttle.py
Also disables the plugin if `AUTOTHROTTLE_TARGET_CONCURRENCY` is equal or lower than `0.0`.
=> Complete coverage for the AutoThrottle extension

scrapy/http/request/rpc.py, setup.py
=> Use defusedxml.xmlrpc

.bandit.yml, scrapy/http/request/form.py, scrapy/linkextractors/lxmlhtml.py, scrapy/selector/unified.py, scrapy/utils/_compression.py, scrapy/utils/iterators.py, scrapy/utils/sitemap.py, scrapy/utils/versions.py
In most cases, the actual loading of the document is done by parsel, not Scrapy.
`form.py` was 1 exception, but I have refactored it to use the response selector instead. The application of `get_base_url` in `unified.py` was a bug fix detected in the process.
Another exception is `iterparse_lxml`, which now uses `resolve_entities=False` as parsel does.
And then there was the sitemap code, which was already disabling entity resolution.
=> Bandit: allow-list lxml usages

tests/test_commands.py
Fixes https://github.com/scrapy/scrapy/issues/6286
=> Fix WindowsRunSpiderCommandTest skip outside Windows for older Twisted

scrapy/robotstxt.py, tests/test_robotstxt_interface.py
Fixes https://github.com/scrapy/scrapy/issues/6292.
cc @Gallaecio
=> Handle robots.txt files not UTF-8 encoded

scrapy/http/cookies.py, tests/test_http_cookies.py
Fixes https://github.com/scrapy/scrapy/issues/6308 
Alternatives: 
```python
def get_header(self, name, default=None):
value = self.request.headers.get(name, default)
if not value:
return value
return to_unicode(value, errors="replace")
```
But I don't like repeating value so much 
```python
def get_header(self, name, default=None):
if not (value := self.request.headers.get(name, default)):
return value
return to_unicode(value, errors="replace")
```
The parenthesis and walrus operator make the line too convoluted
```python
def get_header(self, name, default=None):
try: 
to_unicode(self.request.headers.get(name, default), errors="replace")
except TypeError:
return default
```
Using try/except this way is pythonic, but I'm always afraid I may unexpectedly capture another unrelated exception
=> Fix WrappedRequest.get_header raising TypeError if default is None

tests/test_utils_python.py
=> fix test expectations

docs/conf.py
Closes #5019.
Follows https://hynek.me/til/copyright-years/ / https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects / https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/
=> Remove the auto-generated copyright years from the docs footer.

scrapy/selector/unified.py
added json as one of the value for type argument.
Closes #6328
=> Closes #6328. Document 'json' selector type

scrapy/core/downloader/handlers/http11.py
=> Closes #6343. Make certain args of ScrapyAgent and TunnelingAgent required

docs/news.rst, scrapy/core/downloader/__init__.py, scrapy/pqueues.py, tests/test_scheduler.py
=> Closes #6340. Deprecate the spider argument to Downloader._get_slot_key()

scrapy/cmdline.py, scrapy/core/downloader/handlers/ftp.py, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/core/spidermw.py, scrapy/mail.py, scrapy/pipelines/files.py, scrapy/pipelines/media.py, scrapy/shell.py, scrapy/utils/decorators.py, scrapy/utils/defer.py, scrapy/utils/python.py, scrapy/utils/reactor.py
I also changed most of `addCallbacks()` to `addCallback()`/`addErrback()`, as the official docs say the former has worse type hints (the ones I kept need to stay for various reasons).
I plan to add parameter specifications to more generics as separate PRs.
=> Use ParamSpec for callables.

docs/faq.rst, docs/topics/benchmarking.rst, docs/topics/downloader-middleware.rst, docs/topics/settings.rst, docs/topics/signals.rst, docs/topics/spider-middleware.rst, docs/topics/spiders.rst, scrapy/core/engine.py, scrapy/downloadermiddlewares/offsite.py, scrapy/extensions/memusage.py, scrapy/settings/default_settings.py, scrapy/utils/_compression.py, scrapy/utils/python.py, tests/test_downloadermiddleware.py, tests/test_downloadermiddleware_offsite.py, tests/test_engine.py, tests/test_utils_iterators.py
Scrapy was enforcing [Spider.allowed_domains](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.Spider.allowed_domains) only for requests coming from [spider callbacks](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.Spider.parse), but not for:
- Requests coming from [`Spider.start_requests`](https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.Spider.start_requests).
- Requests coming from the redirect middlewares ([`RedirectMiddleware`](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.redirect.RedirectMiddleware) and [`MetaRefreshMiddleware`](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware)), or custom middlewares yielding new …
=> Fix the offsite middleware missing some requests

.flake8, .github/workflows/tests-macos.yml, docs/topics/practices.rst, scrapy/crawler.py, tests/CrawlerRunner/change_reactor.py, tests/test_crawler.py
=> docs: Remove top-level reactor imports from CrawlerProces/CrawlerRunner examples

scrapy/core/downloader/handlers/s3.py, scrapy/extensions/feedexport.py, tox.ini
Also installs pytest and switches attrs and Pillow from separate stubs to built-in ones following the separate stub package descriptions.
=> Install typing stubs for boto3 and botocore.

scrapy/pipelines/media.py, tests/test_pipeline_media.py
The callback, if it exists, was called with a result dict as the first arg, not with a response, so it didn't make sense to have callbacks on these requests and so I'm almost sure there is no code that has them (I checked several 3rd-party pipelines in the github search, all of them don't use even the errback feature which at least seems to make sense).
=> Don't run callbacks of requests from get_media_requests().

scrapy/contracts/__init__.py, tests/test_contracts.py
Added a condition to check if `m` is `None`.
The presence of `@ foo` in the docstring would result in an `AttributeError: 'NoneType' object has no attribute 'groups'`. Checking for `None` will prevent this error.
Closes #6383
=> added  AttributeError: 'NoneType' handling in contract parsing

scrapy/utils/defer.py, tests/test_utils_defer.py
This function was never used except by `MiddlewareManager._process_chain_both()` which was also never used and was removed in 2021.
=> Deprecate scrapy.utils.defer.process_chain_both().

tox.ini
This pin currently causes version conflicts but it's also no longer needed as current `Twisted` allows `h2==4.1.0` which is compatible with current `mitmproxy`.
=> Unpin markupsafe in extra-deps.

tox.ini
The older version is incompatible with just released importlib-metadata.
=> Bump twine in twinecheck.

scrapy/crawler.py
The code using it was removed earlier.
=> Remove an obsolete import.

docs/intro/install.rst, docs/intro/overview.rst
Removed bullet point about the latest versions of python having pip bundled with them, as all suppported versions of python now do.
=> removed bullet point about python versions for macOS installation

docs/topics/signals.rst, docs/topics/spider-middleware.rst, docs/topics/spiders.rst, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/logformatter.py, tests/spiders.py, tests/test_crawl.py, tests/test_spidermiddleware.py
resolve https://github.com/scrapy/scrapy/issues/5289
based on code sample from https://github.com/scrapy/scrapy/issues/5289#issuecomment-1522396870
I used this сode sample to test this locally.
<details><summary>script.py</summary>
```python
import scrapy
from scrapy.crawler import CrawlerProcess
class QuotesToScrapeSpider(scrapy.Spider):
def start_requests(self):
yield scrapy.Request(url='http://quotes.toscrape.com/', callback=self.parse)
yield {"quote": ['“It is possible to return items on start_requests. But I don\'t understand Why it\'s needed?“'], "author": ["Georgiy"], "tags": ["scrapy"]}
for quote in response.css("div.quote"):
yield {
"quote": quote.css("span.text::text").getall(),
"author": quote.css("small.author::text").getall(),
"tags": …
```
=> start_requests can return items

scrapy/core/engine.py, tests/test_engine.py
Removed the debug log message in the `_schedule_request method` of the `ExecutionEngine` class. This change removes unnecessary logging created by the `core.engine` signal handler.
Resolves #6433
=> Remove log pollution from core.engine signal handler (#6433)

setup.py, tox.ini
It was added (in #5122) because we imported `pkg_resources`, which we no longer do since 2.10.
=> Remove the installation dependency on setuptools.

docs/conf.py
https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> Explictly set html_baseurl on RTD.

scrapy/pipelines/media.py
Fixes #6504 
1. Simplified the version check using format `Version` as requested.
2. Added `type: ignore` comments to handle the typing errors flagged by `mypy`.
3. Pre-commit checks have been run.
- Ran `tox -e typing` with `Twisted>=24.10.0rc1` as suggested
- Reverted the changes to the `tox.ini` file.
- Some other errors were found on windows for the file `scrapy/extensions/debug.py`
Made a new Pr as I got lost with the changes and had to reset my fork
Let me know if you need any more modifications!
=> Fixes for Twisted Version Check and Typing Issues

scrapy/extensions/debug.py, scrapy/utils/console.py
This pull request addresses Windows-specific issues encountered during type checking with MyPy, `# type: ignore` comments have been added to the respective lines to suppress type checking errors that are only relevant to Windows environments:
- **In `scrapy/extensions/debug.py` and  `scrapy/utils/console.py`**
- Added `# type: ignore` to suppress type checking errors for Windows-specific attributes that are not defined.
Pls review it
=> Added ignore statements for Windows specific typing issues

scrapy/__init__.py, tests/test_scrapy__getattr__.py
=> Deprecate `scrapy.twisted_version`

conftest.py, docs/topics/commands.rst, extras/scrapy_zsh_completion, pytest.ini, scrapy/commands/__init__.py, scrapy/crawler.py, scrapy/downloadermiddlewares/httpcompression.py, scrapy/downloadermiddlewares/retry.py, scrapy/extensions/feedexport.py, scrapy/pipelines/images.py, scrapy/utils/conf.py, scrapy/utils/reactor.py, scrapy/utils/request.py, tests/test_crawler.py, tests/test_downloader_handlers.py, tests/test_downloadermiddleware_httpcompression.py, tests/test_downloadermiddleware_retry.py, tests/test_feedexport.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_utils_conf.py, tox.ini
* ``--output-format/-t`` argument: deprecated in 2.1.0
* Running `Crawler.crawl()` more than once on the same instance: deprecated in 2.11.0
* Subclassing `HttpCompressionMiddleware` without `from_crawler()` support: deprecated in 2.5.0
* `RetryMiddleware.EXCEPTIONS_TO_RETRY`: deprecated in 2.10.0
* S3 feed exports without `boto3`: deprecated in 2.10.0
* `_FeedSlot` as an alias for `FeedSlot`: deprecated in 2.10.0
* `NoimagesDrop`: deprecated in 2.8.0
* `convert_image()` without `response_body`: deprecated in 2.8.0
* The `custom` argument of `build_component_list()`: deprecated in 2.10.0
* `get_asyncio_event_loop_policy()`: deprecated in 2.9.0
I'm not 100% sure that nothing needs to be changed for the `botocore`/`botocore-pinned` test envs.
I still hesitate to remove the `FEED_URI` …
=> Deprecation removals.

scrapy/utils/misc.py, scrapy/utils/python.py, scrapy/utils/request.py, scrapy/utils/serialize.py, scrapy/utils/test.py, tests/test_utils_python.py, tests/test_utils_request.py
Fixes #6517 
This PR deprecates following unused functions and classes in `scrapy.utils`:
- `flatten`
- `iflatten`
- `equal_attributes`
- `request_authenticate`
- `ScrapyJSONDecoder`
- `assert_samelines`
I have also changed some other warnings for a grammatical uniformity
pls review this PR
=> Deprecate unused scrapy utils

docs/topics/email.rst, docs/topics/request-response.rst, scrapy/core/downloader/contextfactory.py, scrapy/dupefilters.py, scrapy/extensions/feedexport.py, scrapy/extensions/memusage.py, scrapy/extensions/statsmailer.py, scrapy/mail.py, scrapy/middleware.py, scrapy/pipelines/files.py, scrapy/pipelines/images.py, scrapy/pipelines/media.py, scrapy/spidermiddlewares/urllength.py, scrapy/utils/misc.py, tests/test_dupefilters.py, tests/test_middleware.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_pipeline_media.py, tests/test_spidermiddleware_urllength.py, tests/test_utils_misc/__init__.py, tests/test_utils_request.py, tests/test_webclient.py
=> Remove build_from_settings() and deprecate from_settings() code

.github/workflows/publish.yml
Motivated by _[Are we PEP 740 yet?](https://trailofbits.github.io/are-we-pep740-yet/)_
> What is PEP 740?
>
> [PEP 740](https://peps.python.org/pep-0740/) is a Python standard for defining cryptographically verifiable attestations hosted by indices like PyPI.
What are attestations?
> 
> Attestations are digitally signed, publicly verifiable statements about Python packages, including their provenance (e.g., the exact source repository that produced them).
>
> Attestations are built on top of [Sigstore](https://sigstore.dev/) and use short-lived signing keys bound to trusted identities (like [Trusted Publishers](https://docs.pypi.org/trusted-publishers/)), making them misuse-resistant and less susceptible to key loss and theft.
PyPI's Scrapy project is ready to accept uploads from Github …
=> Verified PyPI releases (a.k.a. PEP740)

scrapy/core/downloader/contextfactory.py, tests/test_webclient.py
Related to #6546.
Not running `ScrapyClientContextFactory.__init__()` in subclasses became unsupported in 1.8.0 when we added `self.tls_ciphers`.
=> Add tests for DOWNLOADER_CLIENT_TLS_METHOD, remove dead code.

.pre-commit-config.yaml, pyproject.toml, scrapy/http/request/form.py, tests/test_pipeline_crawl.py, tests/test_pipeline_media.py
This adds `ruff check` to `pre-commit`. The enabled rules are the default ones ("By default, Ruff enables Flake8's F rules, along with a subset of the E rules, omitting any stylistic rules that overlap with the use of a formatter, like ruff format or Black."). As next steps we can enable more of the rules and disable the other linters/formatters that are duplicated by ruff.
=> Add ruff with basic rules.

conftest.py
This minor change makes the reference to `tests/ignore.txt` absolute instead of relative, allowing tests to run from any other directory, rather than just inside the main directory.
=> Made path absolute to enable running pytest from any directory

scrapy/utils/url.py, tests/test_utils_url.py
Close: #4577
Close: #6583
We will emit a warning everytime someone import functions of `w3lib` from `scrapy.utils.url`
=> Deprecate w3lib objects importable from scrapy.utils.url

.github/workflows/tests-ubuntu.yml
Looks like the CI runner has just changed from Ubuntu 22.04.5 to Ubuntu 24.04.1 and Pillow can no longer be installed, because it needs to be compiled but `libjpeg-dev` is not installed. As it's unlikely that some binary Pillow build was being installed before (there is no 3.9 wheel for Pillow 7.1.0 on PyPI) I assume `libjpeg-dev` was installed by default in the image before. This change installs it for more envs that need it but the impact should be negligible.
=> Install libjpeg-dev on pinned envs to be able to install Pillow.

docs/conf.py, docs/requirements.txt
From RTD template v2 to v3.
notable change: Drop support for all versions of Internet Explorer.
Mentioned in #6620
=> chore(docs): migrate to RTD template v3

docs/news.rst
Pillow website is shut down permanently. Target github repository before website is taken by evil 3rd party.
See https://github.com/python-pillow/Pillow/issues/8585
=> fix(docs): pillow domain is shut down permanently

tests/test_feedexport.py
fix: #6619
Closes https://github.com/scrapy/scrapy/pull/6625.
=> fix: test_s3_export fails with boto3 >= 1.36.0

.github/workflows/tests-ubuntu.yml, tox.ini
Fixes #6271.
I'm somewhat on the fence with removing PyPy 3.9 though: on one hand it's not supported anymore, on the other hand if we want a `pypy3-pinned` job we need to maintain a separate slightly different list of dep versions as long as the minimum supported version of PyPy is newer than the CPython one.
Additionally, I wonder if we want a `pypy3-asyncio` job and a `pypy3-extra-deps-pinned` one.
=> Drop PyPy 3.9, add a pypy3-extra-deps CI job.

scrapy/commands/bench.py, tests/test_commands.py
Resolve https://github.com/scrapy/scrapy/issues/6632 (And [the Stack Overflow question](https://stackoverflow.com/q/79386410/4387278)  as well)
`scrapy bench` is erroring due to an incorrect param passed to `isinstance`. The first param must be the object to be verified, but a class was being passed instead. This is leading to `AssertionError` when the command is executed.
Changes here fix it by replacing the `Response` class with the `response` object.
See the difference in the logs when running `scrapy bench` before and after these changes:
<details>
<summary>Before</summary>
```
2025-01-25 13:50:18 [scrapy.core.engine] INFO: Spider opened
2025-01-25 13:50:18 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-01-25 13:50:18 …
```
=> Fix error when running `scrapy bench`

scrapy/core/downloader/contextfactory.py, scrapy/core/downloader/handlers/http10.py, scrapy/core/downloader/webclient.py, tests/test_core_downloader.py, tests/test_downloader_handlers.py, tests/test_webclient.py
Related to #6450 
Several things here:
1. `scrapy.core.downloader.handlers.http10.HTTP10DownloadHandler` is deprecated.
2. `scrapy.core.downloader.webclient.ScrapyHTTPPageGetter` and `scrapy.core.downloader.webclient.ScrapyHTTPClientFactory`, only needed for the handler, are deprecated.
3. As in the past I added several `ScrapyClientContextFactory` tests to `test_webclient.py`, not realizing that they use old APIs, these are now either copied or moved to `test_core_downloader.py` (depending on their usefulness for the HTTP/1.0 code).
4. Overriding `ScrapyClientContextFactory.getContext()` is deprecated, as it's the "old" interface (`IOpenSSLContextFactory`, for the record) and when we remove the HTTP/1.0 support we should merge `getContext()` into `creatorForNetloc()` which is the "new" …
=> Deprecate HTTP/1.0 code.

tests/test_engine.py, tests/test_engine_stop_download_bytes.py, tests/test_engine_stop_download_headers.py
All `EngineTest.test_*()` tests ran ~~thrice~~ 5 (?) times before this. Related to #6645
=> Refactor EngineTest tests.

tests/test_closespider.py, tests/test_crawl.py, tests/test_downloader_handlers.py, tests/test_downloaderslotssettings.py, tests/test_feedexport.py, tests/test_logformatter.py, tests/test_pipeline_crawl.py, tests/test_pipelines.py, tests/test_proxy_connect.py, tests/test_request_attribute_binding.py, tests/test_request_cb_kwargs.py, tests/test_request_left.py, tests/test_signals.py, tests/test_spidermiddleware_httperror.py
Fixes #6637, related to #6645.
A better solution, as mentioned in the issue, would be switching to pytest fixtures but that's a much bigger thing.
=> Optimize mockserver calls

tests/test_downloadermiddleware_httpcache.py
Related to #6645 and #6649. 
This also makes some methods that previously ran with `DbmCacheStorage` to run with `FilesystemCacheStorage` (but if that breaks anything it's a bug in them). Not sure which methods, though, maybe just `tests.test_downloadermiddleware_httpcache._BaseTest.test_dont_cache()`.
=> Remove a duplicate test.

scrapy/crawler.py
fix: #6636
Tested manually with:
```
python tests/CrawlerRunner/change_reactor.py
```
and
```
scrapy shell -s TWISTED_REACTOR="twisted.internet.asyncioreactor.AsyncioSelectorReactor"
```
=> fix: Reactor info logged twice

docs/_static/custom.css, docs/conf.py, docs/requirements.txt
This PR attempts to support dark mode for scrapy's documentation by adding [sphinx-rtd-dark-mode](https://pypi.org/project/sphinx-rtd-dark-mode/) extension to sphinx
By default, this extension places the toggle button at the bottom right corner and enables dark mode. It allows to configure whether dark mode should be enabled by default. I wanted to place the toggle button at top right corner so I added custom style in custom.css. This extension adds text to the footer.
It's not an essential feature as there are browser extensions that can enable dark mode for sites, for example [dark reader browser extension](https://darkreader.org/) but I thought it will be nice to have.
I am also mentioning https://github.com/readthedocs/sphinx_rtd_theme/issues/224#issuecomment-722655021 which used dark …
=> Support dark mode in scrapy's documentation

scrapy/core/spidermw.py, scrapy/utils/python.py, tests/test_spidermiddleware.py
One step for #6590.
We likely want to improve the page being linked to, maybe even by adding a "what to do as a user" section linked in the downgrading code and a "what to do as an mw developer" section linked in the mw loading code. It's fine to do in a separate PR as the parent issue needs several PRs in any case.
=> Improve diagnostics for sync-only spider middlewares.

scrapy/spiders/sitemap.py, tests/test_poet.py, tests/test_spider.py
Fixes #6665 (hopefully there are no other functions where this is important).
=> Fix getting annotations for _parse_sitemap() at the runtime.

scrapy/utils/curl.py, tests/test_utils_curl.py
When parsing `curl` command line options, Scrapy currently supports grabbing cookie values from `-H "Cookie: ..."` parameters. However, curl also supports specifying cookies via `-b` and `--cookie`. This PR adds support for that.
I updated an existing test case to use the `-b` method to specify one of the cookies.
Motivation: Previously, the `Copy as cURL` option in Google Chrome's Developer Tools would generate a curl command with cookies specified via `-H "Cookie: ..."`. A recent update seems to have changed that feature to use `-b`.
=> curl: add support for parsing -b,--cookie

conftest.py, scrapy/utils/test.py, tests/test_command_fetch.py, tests/test_command_parse.py, tests/test_command_shell.py, tests/test_command_version.py, tests/test_feedexport.py, tests/test_pipeline_files.py, tests/utils/testproc.py, tests/utils/testsite.py
This moves `scrapy.utils.{testproc,testsite}` into the newly created `tests.utils` package, moves some functions from `scrapy.utils.test` that are only used in some tests into those test modules and just deprecates ones that aren't used. The old code is kept with deprecation warnings.
Motivation: the stuff moved is very specific and unlikely to be useful outside the Scrapy test suite, and even there it's useful only for specific tests, but having it in the Scrapy itself requires us to keep it and maintain compatibility in it. `testproc` and `testsite` are used in several modules so it's better to put them into an utils package than to put them inside some test module and import from there. Other functions are only used in one test module and I'm not sure if it's possible to have more …
=> Move most of the test utils inside tests.

tests/test_squeues.py
The problem appeared in #6702 and is caused by https://github.com/scrapy/queuelib/issues/70
=> Work around a queuelib test file close problem.

tests/test_squeues.py
Failures in Scrapy and queuelib are independent, even though they are similar.
=> Better fix for test_non_pickable_object on Windows.

docs/topics/request-response.rst, scrapy/http/request/__init__.py
Split off from https://github.com/scrapy/scrapy/pull/6715.
- Moves the `__init__` parameter docs of `dont_filter`, `callback` and `errback` to matching attribute entries loaded from code documentation, with slight improvements.
- Moves `cb_kwargs` above `meta` in the docs.
=> Move some reference docs of Request to the code

docs/faq.rst, docs/topics/items.rst, scrapy/commands/parse.py, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/exporters.py, scrapy/templates/project/module/middlewares.py.tmpl, scrapy/utils/serialize.py, tests/test_crawl.py
See https://github.com/scrapy/itemadapter/issues/59.
Split off from https://github.com/scrapy/scrapy/pull/6715 and extended.
=> Remove or post-pone the use of itemadapter.is_item, as a potentially expensive call

pyproject.toml, scrapy/utils/test.py, tests/test_downloadermiddleware_robotstxt.py, tests/test_engine.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_utils_template.py
Partial fix for #6658
There are some more `self.assert*` calls via Deferred callbacks, but that doesn't trigger `ruff` and should be rewritten separately anyway. I used `tmp_path` in some easy cases, other `mkdtemp()` etc. calls can be converted later.
=> Convert remaining unittest assert* calls, use the tmp_path fixture.

docs/topics/asyncio.rst, docs/topics/coroutines.rst, scrapy/utils/defer.py
This improves the docs about wrapping deferreds, adds docs about wrapping futures and leaves a place for a list of deferred APIs for #6677
=> More docs about Deferred<->Future interoperability.

conftest.py
Broken by #6732. When some tests are run individually, e.g. `tests/test_downloadermiddleware_ajaxcrawlable.py`, the code may create a crawler via `get_crawler()` and that calls `is_asyncio_reactor_installed()` while nothing has installed the reactor yet. Technically, these tests don't use the reactor themselves but doing something better for this would complicate 
getting a crawler instance for tests even further. And it's a no-op when you run the full test suite.
=> Fix running simple tests with --reactor=default.

.github/workflows/tests-macos.yml, .github/workflows/tests-ubuntu.yml, .github/workflows/tests-windows.yml, .gitignore, tox.ini
This PR sets up Codecov [Test Analytics](https://docs.codecov.com/docs/test-analytics), which enhances this project's existing Codecov coverage PR notification with details about failing, flaky, and slow tests. More details can be found [here](https://about.codecov.io/blog/find-failing-and-flaky-tests-with-codecov-test-analytics/), and below is an example screenshot.
The PR proposes the below edits to this end:
1. Output a JUnit XML file with pytest runs by adding flag `--junitxml={env}.junit.xml`
- Include option `-o junit_family=legacy` to ensure nicer formatting within the Codecov UI (scrapy's existing Codecov instance can be accessed [here](https://app.codecov.io/github/scrapy/scrapy), where a new tab "Tests" will appear when this PR is merged).
- Any file with suffix *.junit.xml will …
=> feat: Add test analytics

docs/_templates/layout.html
Overrides [the sidebar block](https://github.com/readthedocs/sphinx_rtd_theme/blob/5a263753d52c1628c88392fbf52c729f5a8e79b5/sphinx_rtd_theme/layout.html#L114-L138) to switch [this](https://github.com/readthedocs/sphinx_rtd_theme/blob/5a263753d52c1628c88392fbf52c729f5a8e79b5/sphinx_rtd_theme/layout.html#L120-L125) to:
```html
<a href="https://scrapy.org">scrapy.org</a> / <a href="{{ pathto(_root_doc) }}">docs</a>
```
=> Link to scrapy.org from the docs

conftest.py, docs/topics/api.rst, docs/topics/practices.rst, scrapy/crawler.py, tests/AsyncCrawlerRunner/multi_parallel.py, tests/AsyncCrawlerRunner/multi_seq.py, tests/AsyncCrawlerRunner/simple.py, tests/AsyncCrawlerRunner/simple_default_reactor.py, tests/CrawlerRunner/explicit_default_reactor.py, tests/CrawlerRunner/multi_parallel.py, tests/CrawlerRunner/multi_seq.py, tests/CrawlerRunner/simple.py, tests/test_crawler.py
Fixes #6789 
Includes a partial fix for #6047. Partial because the `CrawlerProcess` examples (which don't save the result of `crawl()` and don't call `join()`, and `CrawlerProcess.start()` eats the exceptions from `join()` which it calls) are still aftected.
=> Add AsyncCrawlerRunner.

scrapy/utils/defer.py, tests/test_utils_defer.py
- futures and coroutines are awaitables
- replace `ensureDeferred` with `Deferred.fromCoroutine` which does the same but without an additional check that we already do and IIRC is recommended over the former
- add tests for `deferred_from_coro()`, `deferred_f_from_coro_f()`, `deferred_to_future()`, `maybe_deferred_to_future()`
=> Simplify deferred_from_coro(), add more tests.

docs/topics/spiders.rst
This pull request fixes a consistent typo where the term `needs_backoff` was incorrectly used instead of the correct `needs_backout`.
Closes #6812
=> Fix typo in documentation (closes #6812)

pyproject.toml
Follow more strict https://docs.pypi.org/project_metadata/#icons instead of https://packaging.python.org/en/latest/specifications/well-known-project-urls/
=> Make the release notes URL work better on PyPI.

README.rst, docs/contributing.rst
The original goal was to remove 2 links to https://scrapy.org/ pages that no longer work after the recent redesign.
However, I went a bit overboard, and took the chance to trim the README quite a bit. I even pondered removing the installation instructions altogether, and let people follow the docs to get install instructions.
I’m OK with reverting to a minimal changeset that simply removes the 2 sections with broken links.
=> Shorten the README and remove broken links to scrapy.org

docs/topics/asyncio.rst, scrapy/utils/asyncio.py, scrapy/utils/defer.py, scrapy/utils/reactor.py, tests/CrawlerProcess/asyncio_enabled_reactor.py, tests/test_utils_asyncio.py, tests/test_utils_defer.py, tests/test_utils_deprecate.py, tests/test_utils_reactor.py
This is currently a copy of is_asyncio_reactor_installed() but with a future-proof name and semantics.
=> Add is_asyncio_available().

README.rst
The use of inline images through rst replacement makes it possible to have each row of image(s) in its own paragraph, ensuring nice spacing with the first paragraph, neither too much (I tested with an empty paragraph with a single non-breaking space) neither too little (which I feel is the case in the current main branch).
=> Avoid raw HTML in the README

scrapy/core/engine.py, tests/test_engine.py
Fixes #6857, closes #6860, closes #6862
=> Don't try to close ExecutionEngine.downloader when it doesn't exist.

tests/test_downloader_handler_twisted_http11.py, tests/test_downloader_handler_twisted_http2.py, tests/test_downloader_handlers.py, tests/test_downloadermiddleware_robotstxt.py, tests/test_downloaderslotssettings.py, tests/test_engine_loop.py, tests/test_extension_telnet.py, tests/test_feedexport.py, tests/test_http2_client_protocol.py, tests/test_pipeline_crawl.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py, tests/test_pipeline_media.py, tests/test_scheduler_base.py, tests/test_signals.py, tests/test_spider_start.py, tests/test_spidermiddleware_process_start.py, tests/test_utils_defer.py, tests/test_utils_signal.py, tests/test_webclient.py
* Rename remaining test classes to TestFoo
* Replace `skip =` with `pytest.skip(if)`
* Rewrite remaining callback-style test functions that used `self.assert*` (except `tests.test_utils_defer.TestMustbeDeferred`, that needs more work but also we should deprecate `mustbe_deferred()` separately)
* Replace `addCleanup()` with `tearDown()`
* Remove the remaning `self.mktemp()` usage
=> Further reduce deps on unittest.

scrapy/extensions/feedexport.py, tests/test_feedexport.py
This PR addresses an issue in the `FileFeedStorage` class where passing a Windows-style path without the `file://` URI scheme causes incorrect path resolution. Specifically, using a path like `C:/foo` was incorrectly processed by `w3lib.url.file_uri_to_path()`, which expects a proper URI. This led to malformed paths such as `\\foo`, causing files to be written relative to the spider's working directory instead of the intended absolute path.
The problematic code was:
```python
self.path = file_uri_to_path(uri)
```
which always called file_uri_to_path() regardless of whether uri was a valid URI or just a local path.
The fix changes the initialization logic to only convert the path using file_uri_to_path() if the input string starts with the file:// scheme. Otherwise, the path is preserved …
=> Fix FileFeedStorage handling of Windows paths without file:// scheme

scrapy/core/engine.py, tests/test_engine_loop.py
When the attribute was renamed this code wasn't changed.
(the whole method needs refactoring but that's for later)
=> Fix setting ExecutionEngine._slot to None on close.

docs/conf.py, docs/requirements.txt
Fixes #6786 
> This extension has been deprecated. ([ref](https://github.com/readthedocs/sphinx-hoverxref/blob/main/README.rst))
=> Remove the deprecated sphinx-hoverxref

scrapy/core/engine.py, tests/test_engine.py, tests/test_engine_loop.py
Fixes #6908
As it doesn't look like we can avoid the unhandled CancelledError, change the expectations to exceptions that could be raised when `self._slot` is unexpectedly None.
The test was added in #5440
=> Narrow down TestEngine::test_short_timeout() expectations.

scrapy/core/downloader/__init__.py, scrapy/core/downloader/middleware.py, scrapy/core/scraper.py, scrapy/core/spidermw.py, scrapy/pipelines/files.py, scrapy/pipelines/media.py, scrapy/utils/defer.py, tests/test_pipeline_media.py, tests/test_spidermiddleware.py, tests/test_utils_defer.py
`mustbe_deferred()` calls the wrapped function and 
1. if got a Deferred returns that one directly 
2. if got an exception sleeps for `_DEFER_DELAY` and propagates it
3. if got a normal result sleeps for `_DEFER_DELAY` and returns it.
Thus if we know that the wrapped function always returns a Deferred we add a sleep to the `except` block (it looks like all calls outside `MediaPipeline` are like this) and if we know that the wrapped function can return a normal result we wrap it into a `maybeDeferred()` and add a sleep before calling it (this is only in `MediaPipeline`). I think if `MediaPipeline.media_to_download()` returns a Deferred there is one more sleep than before the change, which I'm fine with. 
Note that all of these sleeps seem to be added empirically and doing more of them …
=> Deprecate mustbe_deferred() and defer_*().

tests/test_engine.py
There is again some coverage-related slowdown on Python 3.12 and 3 seconds is sometimes not enough for the process to finish successfully, bump the timeout.
=> Increase the command timeout in test_short_timeout().

pyproject.toml, scrapy/core/downloader/handlers/ftp.py, scrapy/extensions/telnet.py, tests/test_downloader_handlers.py
This partially rolls back the import changes in #6941 but not all of these were correct before that PR.
=> Ban more imports that import twisted.internet.reactor.

scrapy/pipelines/files.py, scrapy/pipelines/images.py, tests/test_pipeline_files.py, tests/test_pipeline_images.py
**Raise TypeError if `images_urls_field` or `files_urls_field` value is not a list**
* Adds explicit type checking for both `images_urls_field` and `files_urls_field` to ensure they are lists.
* Provides clearer error messages to help users quickly identify and fix misconfigured items.
* Prevents silent bugs caused by accidentally passing a single string or other iterable types instead of a list.
* Adds comprehensive tests for `images_urls_field` and `files_urls_field` to validate the new type enforcement.
=> Add type check in get_media_requests to enforce image / file urls as a list

scrapy/core/downloader/middleware.py, scrapy/core/engine.py, scrapy/core/scraper.py, scrapy/core/spidermw.py, scrapy/middleware.py, scrapy/pipelines/__init__.py, scrapy/utils/defer.py, scrapy/utils/deprecate.py, tests/test_downloadermiddleware_robotstxt.py, tests/test_pipelines.py, tests/test_utils_defer.py
Maybe we should also deprecate `ITEM_PROCESSOR` values that aren't subclasses of `ItemPipelineManager` (considering how much code do you need in even a minimal `ITEM_PROCESSOR` if not subclassing that, it's unlikely that those implementations exist, but I'm not sure if the benefits to us from this deprecation are noticeable).
=> Add ItemPipelineManager.process_item_async() and ensure_awaitable().

scrapy/extensions/statsmailer.py, tests/test_extension_statsmailer.py, tests/test_statsmailer.py
This PR adds unit tests for the StatsMailer extension to improve coverage.
Changes:
- Added `tests/extensions/test_statsmailer.py`
- Verified that `from_crawler` raises NotConfigured when no recipients are configured
- Ensured that an email is sent on spider close when recipients are provided
- Checked that both global stats and spider-specific stats are included in the email body
This increases coverage for `scrapy/extensions/statsmailer.py`.
=> tests: add unit tests for StatsMailer extension

scrapy/core/downloader/__init__.py, scrapy/core/downloader/handlers/__init__.py, scrapy/core/scraper.py, scrapy/pipelines/media.py, scrapy/spidermiddlewares/base.py, scrapy/spidermiddlewares/depth.py, scrapy/spidermiddlewares/httperror.py, scrapy/statscollectors.py, scrapy/utils/decorators.py, tests/test_pipeline_files.py, tests/test_spidermiddleware_base.py
(in preparation for downloader middleware changes, separate PR mostly to check the coverage changes)
It turns out that even simple decorators that support sync and async functions are very unwieldy :-/
=> Extract @_warn_spider_arg.

scrapy/utils/response.py, tests/test_utils_response.py
Fixes #7042 
Problem:
The meta refresh redirect was not working as expected. It was completely ignoring the base URL in the `<base>` HTML tag while resolving the redirect URL for the relative URL in the `<meta>` tag.
Solution:
Replaced usage of `response.url` with `scrapy.utils.response.get_base_url()`, ensuring that the <base> tag is respected when resolving relative URLs in meta refresh redirects.
Testing:
Appropriate testing is added
=> Fix meta refresh redirect issue by respecting <base> tag (#7042)

.github/workflows/tests-ubuntu.yml, pyproject.toml, tox.ini
Discontinued in July: https://pypy.org/posts/2025/07/pypy-v7320-release.html
=> Drop PyPy 3.10 support, restore coverage for subprocesses

docs/conf.py
Today, when someone clicks on View page source in the documentation, they are redirected to raw rst files, _e.g.:_ https://docs.scrapy.org/en/latest/_sources/index.rst.txt.
This PR adds `html_context` so that when someone clicks on **Edit on GitHub**, they are redirected to the correct file in the repository, _e.g.:_ https://github.com/scrapy/scrapy/blob/master/docs/index.rst, making it easier to contribute.
=> docs: Add Edit on GitHub

scrapy/statscollectors.py, scrapy/utils/decorators.py
Merging #7011 significantly increased the test run time, I haven't checked if it translates to a similar increase of long-running spider jobs or not but it should be fixed anyway. I've identified two things that we can fix, it's still not enough though (but it's interesting that handling of specifically `inc_value()` gives most or even all of the performance hit).
=> Improve performance of deprecated spider arg checks.
